### ISSUE TITLE
IdealSystem3clusters

### ISSUE THREAD

**Issue by RicardoUCD** [lbl-srg/modelica-buildings#1021]
I want to model my university district heating, we have three natural gas boilers and one biomass, 10 metered buildings and it is just for heating. Is the example IdealSystem3cluesters a good starting point for those cases? thanks

**Comment by mwetter** [comment]
That can really not be answered without knowing what system you have. I suggest you look into the model and its documentation to see if this is a good starting point. Also, please post questions to unmethours.org as the issue tracker is used to address bugs and add new features and not for general questions.

**Comment by RicardoUCD** [comment]
Sorry about it, i could not find any documentation specifically for this validation example, would you have anything helpful?

**Comment by mwetter** [comment]
Best is if you look at the components of this hypothetical model. It is only used to validate whether the bi-directional flow can correctly be simulated but as you will see when you open the load, the example is very idealized.
