### ISSUE TITLE
Improve econ input signal structure

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#1030]
In the multizone economizer sequence:
* [ ] remove ```uZonSta``` input since implicitly implemented by assigning distinct portions of the control signal to ```uHea```, modulation and ```uCoo```
* [x] fix modulation control diagram image
* [ ] pull TMix tracking out a level (so it becomes a fourth econ subsequence)
* [ ] make block icons gray if they are not present in the G36, but we had to implement them in order to ensure proper control

This and the change in ```OperationMode``` should leave the ```uFreProSta``` unconnected for the case study.

**Comment by milicag** [comment]
This needs further discussion

**Comment by mwetter** [comment]
this is on the master
