### ISSUE TITLE
CDL library - add Sine to sources and make sure to use CLD ramp

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#1036]
* ```Sine``` blocks in C36 validation tests come from ```Modelica.Blocks.Sources```. Implement it in the 
```Buildings.Controls.OBC.CDL.Continuous.Sources``` (although currently this can be done with a ramp and a sine)
* Make sure that all ```Ramp``` blocks in validation tests come from ```Buildings.Controls.OBC.CDL.Continuous.Sources```

**Comment by milicag** [comment]
@mwetter I'll wait on your input of this, just wanted to make a note of the issue.

**Comment by mwetter** [comment]
Yes, please add Sine to CDL together with a validation test and make sure it is used in all validation tests instead of `Modelica.Blocks.Sources`
