### ISSUE TITLE
add validation for AHUs.MultiZone.Controller

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1048]
After https://github.com/lbl-srg/modelica-buildings/pull/1044 is merged, the model `AHUs.MultiZone.Controller` needs more validation tests, in particular one test for every combination of the boolean parameters.
Otherwise, we have no confidence that all parameters are propagated correctly and the right blocks are conditionally removed.

Please also review that I propagated the parameters. There were many parameters that were not propagated in an earlier version of https://github.com/lbl-srg/modelica-buildings/pull/1044

You could already start if you make a new branch based on `issue1030_econ_fix`, but please don't commit to this branch anymore as it is close to being merged to the `master`.

**Comment by milicag** [comment]
@mwetter Does this still need to be addressed?

**Comment by mwetter** [comment]
@milicag Yes, this still need to be addressed (after your refactoring)

**Comment by milicag** [comment]
Well, sorry for the delay, I only noticed this as I was cleaning up the issues the other day.

**Comment by mwetter** [comment]
@milicag : Can you please address this pending issue. Thanks

**Comment by milicag** [comment]
@mwetter I'll still address this now, to use the time when the primary sequences are in queue for review.

**Comment by milicag** [comment]
I'm adding validation cases at a lower level as well, since many of the boolean inputs don't have a test case.
