### ISSUE TITLE
change signal names of economizer to make clear what a position is, and what a signal is

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1052]
The economizer controller uses almost everywhere "DamPos", although in many cases, this is just a signal. This signal could be changed to take into account the non-linearity, and hence "Pos" is not good as it implies a position signal, while the current output is really just a control signal.

**Comment by milicag** [comment]
@mwetter The output signal is an actual position and not a control signal, since the user needs to specify the physical damper position limits, which are propagated parameters. The only case where this is not true is if the TMix frost protection gets activated.

**Comment by mwetter** [comment]
I see. So let's leave it this way, and a feedback linearization would need to be done in the damper.

**Comment by milicag** [comment]
@mwetter A quick fix would be to assign the maximal and minimal physical return and outdoor air damper positions instead of 1 and 0 in the constants if the frost protection gets activated. This is solely to keep consistency with the guideline.

**Comment by milicag** [comment]
@mwetter I now see where you are coming from, I was wondering about the feedback linearisation a while ago and would certainly like to learn about a good way for accounting for it.
