### ISSUE TITLE
Wrong UA value in SolarCollectors.BaseClasses.ASHRAEHeatLoss

### ISSUE THREAD

**Issue by DPatteeuw** [lbl-srg/modelica-buildings#1073]
There is a mistake in the model Buildings.Fluid.SolarCollectors.BaseClasses.ASHRAEHeatLoss 
The UA value is calculated in a wrong way. You can solve this problem by changing:
  -QLosInt[i] * nSeg = UA * (TFlu[i] - TEnv);
to
   -QLosInt[i] * nSeg = -slope*A_c * (TFlu[i] - TEnv);

It is hard to tell the difference in the standard validation file: Buildings.Fluid.SolarCollectors.Validation.FlatPlate
I guess that is why the error was not noticed.

You can clearly see the mistake by following these steps:
- Simulate Buildings.Fluid.SolarCollectors.Validation.FlatPlate
- Plot the heat gain and heat losses of the panel: plot({"solCol.heaGai[1].Q_flow","solCol.rho","solCol.QLos[1].Q_flow"});

- Now in 'SolCol' of this model, change "npanels" to 100
- Plot again the heat gain and heat losses of the panel: plot({"solCol.heaGai[1].Q_flow","solCol.rho","solCol.QLos[1].Q_flow"});

As you can see, the heat gain scales with the number of panels. The heat losses do not.

**Comment by mwetter** [comment]
@DPatteeuw : Thanks for reporting. I am working on a bug fix and a validation case so that this problem will be fixed.

**Comment by mwetter** [comment]
@DPatteeuw  I corrected the bug and added validation tests in `Buildings.Fluid.SolarCollectors.Validation`
