### ISSUE TITLE
control error of primary pumps in a primary-secondary chilled water system with WSE for data center applications

### ISSUE THREAD

**Issue by YangyangFu** [lbl-srg/modelica-buildings#1080]
@mwetter Hi Dr. Wetter, there is an error in the primary-secondary chilled water system with an integrated WSE. In free cooling mode, the primary pumps should be turned off and only the secondary pumps should be used to deliver the chilled water from WSE to AHU.

Can you open a new branch so that I could update the model?

**Comment by mwetter** [comment]
@YangyangFu : Could you please make a pull request against the branch `issue1080_chiller_wse`. Thanks
