### ISSUE TITLE
Translation Error: Error occurred while flattening model Test

### ISSUE THREAD

**Issue by jli113** [lbl-srg/modelica-buildings#1109]
I used OpenModelica v1.13.0-dev-80-gbd7b85c (64-bit) to run [Buildings.Examples.Tutorial.Boiler.System3].
It reported an error:
component boi contains the definition of a partial class Medium.
Please redeclare it to any package compatible with Modelica.Media.Interfaces.PartialMedium.

**Comment by mwetter** [comment]
This is a known bug in OpenModelica and has been reported here:
https://trac.openmodelica.org/OpenModelica/ticket/4235
