### ISSUE TITLE
Fix typos like incomplete brackets

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#1110]
- [ ] `Buildings.Controls.OBC.CDL.Continuous.Sources.TimeTable`:  add “_)_” in “(so the table outputs within an interval are continuous if <code>smoothness = CDL.Types.LinearSegments</code>**)**.”
- [ ] `Buildings.Controls.Predictors.ElectricalLoad`: add “_)_” in “a = min(a<sub>max</sub>, max(a<sub>min</sub>, P<sub>ave</sub> &frasl; P<sub>his</sub>)),”
- [ ] `Buildings.Airflow.Multizone.EffectiveAirLeakageArea`: remove “_)_” in “<code>A=CD/CDRat * L * dpRat^(0.5-m)~~)~~</code> rather than <code>A=CDRat/CD * L * dpRat^(0.5-m)~~)~~</code>.”
- [ ] `Buildings.Electrical.AC.ThreePhasesUnbalanced.Sensors.BaseClasses.GeneralizedProbe`: remove “_)_” in “<a href=\"modelica://Buildings.Electrical.AC.ThreePhasesUnbalanced.Sensors.ProbeDelta\">Buildings.Electrical.AC.ThreePhasesUnbalanced.Sensors.ProbeDelta</a>~~)~~.”
- [ ] `Buildings.Electrical.DC.Loads.Resistor`: add “_)_” in “R(T) = R (1 + &alpha; (T - T<sub>ref</sub>)**)**,”
- [ ] `Buildings.Examples.ChillerPlant.package.mo`: change "_If <i>u &isin; (x, 1]</i> then <i>&Delta;p = &Delta;p<sub>max</sub></i>_” to “_If <i>x &lt; u &le; 1 </i> then <i>&Delta;p = &Delta;p<sub>max</sub></i>_”. ,  change “_If <i> u &isin; [0, x]</i> then” to “If <i>0 &le; u &le; x  </i> then_”. Same for model `Buildings.Examples.ChillerPlant.BaseClasses.Controls.LinearPiecewiseTwo`.
- [ ] Models in `Buildings.HeatTransfer.Sources`: change “Documentation(info="<_HTML_>” to “Documentation(info="<_html_>”
- [ ] `Buildings.HeatTransfer.Windows.Functions.glassPropertyUncoated`: “  n = (1 + sqrt(&rho;(0))**)** &frasl; (1 &minus; sqrt(&rho;(0))).”
- [ ] `Buildings.Media.Specialized.Air.PerfectGas`: add “_)_” in “April 12, 2012, by Michael Wetter:<br/>Added keyword <code>each</code> to <code>Xi(stateSelect=...**)**</code>.”
- [ ] `Buildings.Media.Air`: add “_)_” in “April 12, 2012, by Michael Wetter:<br/> Added keyword <code>each</code> to <code>Xi(stateSelect=...**)**</code>.”
- [ ] `Buildings.Fluid.HeatExchangers.DXCoils.UsersGuide`:  “(Under the assumption that the velocity dependence of <i>UA</i> can be neglected.**)**”
- [ ] `Buildings.Fluid.Interfaces.StaticTwoPortConservationEquation`: “<code>smooth(0, if (port_a.m_flow >= 0) then …**)**</code> declaration,”
- [ ] `Buildings.Fluid.Interfaces.PartialFourPortInterface`: “variables are conditionally enables (because of <code>... if show_T</code>**)**.”
- [ ] `Buildings.Fluid.Interfaces.StaticTwoPortHeatMassExchanger`: “<code>smooth(0, if (port_a.m_flow >= 0) then …**)**</code> declaration,”
- [ ] `Buildings.Fluid.Interfaces.PartialTwoPortInterface`: “are conditionally enables (because of <code>... if show_T</code>**)**.”
- [ ] `Buildings.Fluid.MixingVolumes.Examples.MixingVolumeMoistAir`: “<code>HWat_flow(y=vol1.HWat_flow**)**</code> to”
- [ ] `Buildings.Fluid.Movers.Data.Generic`: “(Dialog(group="Normalized speeds (used in model, default values assigned from speeds in rpm**)**"))”
- [ ] `Buildings.UsersGuide.ReleaseNotes.Version_1_0_build1`: “<code>__Dymola_Commands(file=...**)**</code>”

**Comment by mwetter** [comment]
@JayHuLBL : For these models that are also present in the `IBPSA` library, the issue need also be fixed in the `IBPSA` library. Otherwise, the correction will be overwritten next time we merge the `IBPSA` library.
