### ISSUE TITLE
package.order is missing element "cooling"

### ISSUE THREAD

**Issue by adrpo** [lbl-srg/modelica-buildings#1121]
Please add "cooling" to:
https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Controls/OBC/ASHRAE/G36_PR1/Types/ZoneStates/package.order
as otherwise OpenModelica doesn't want to parse the library.

**Comment by mwetter** [comment]
@adrpo Thanks for reporting. This will be fixed through https://github.com/lbl-srg/modelica-buildings/pull/1120
