### ISSUE TITLE
add state to python API

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1122]
Add a state that is passed between the invocation of the Python functions

**Comment by mwetter** [comment]
Open tasks:
- [ ] Consider returning multiple values without packing them in an array.
- [ ] Regenerate and commit new binaries.

**Comment by mwetter** [comment]
@tsnouidui : Can you please generate the binaries for the OS other than 64 bit linux and review the code. It is ready from my side.

**Comment by tsnouidui** [comment]
@mwetter I improved the documentation and regenerated the binaries.
