### ISSUE TITLE
add model to interface with EnergyPlus thermal zone model

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1129]
This branch is to add the Modelica code to interface with the EnergyPlus thermal zone model.
See https://lbl-srg.github.io/soep/softwareArchitecture.html#coupling-of-energyplus-envelope-and-room-with-modelica-based-hvac-and-control

To connect to HVAC, the model `Buildings.Fluid.FMI.ExportContainers.HVACZone` may be used.

**Comment by tsnouidui** [comment]
Few open issues

- [ ] Pass the simulation start time to the constructor so it can be used to setup the experiment.
This will be needed in https://github.com/lbl-srg/modelica-buildings/tree/issue1129_energyPlus_zone/Buildings/Resources/C-Sources/FMUZoneInitialize.c (after approval of #1177).
- [ ] Expand the number of exchanges variables. Currently, `T` is sent and `QConSen_flow`, `V`, `AFlo`, `mSenFac` are received. 
- [ ] Changed the inputs of FMUZonExchange  to only receive the positive sum of the mass flow rates along with the average inlet temperature. 
- [ ] Sum the positive mass flow rates in Modelica in the when() statement which triggers the data exchange between Modelica and E+. Consider the case where there is no HVAC connected to E+.
- [ ] Compute the avergae inlet temperature in the when() statement which triggers the data exchange between Modelica and E+. Consider the case where there is no HVAC connected to E+.
- [ ] Currently the path to the EnergyPlus library is passed in `Buildings.ThermalZones.EnergyPlus.BaseClasses.FMUZoneAdapter`. The path is required by E+ so it can load the library and have access to the library functions. To support multiple operating systems, this approach requires  to figure the operating system (Win32 or Win64, ...) and pass the path to the correct library to the epLibName. An alternative approach is to have the E+ library in the Library folder. This will cause the tool to load the library in memory so the library can be called directly. It is however not clear how multiple IDFs will need to be handled in such cases as they will all have the same library function names
- [ ] To load the E+ library, the current code use `dlopen`. This function has the constraint multiple calls to the same library will return the same handle (a reference to the same building).  An alternative is to use `dlmopen` (https://www.unix.com/man-page/all/3C/dlmopen/) which might be better to support multiple buildings.

**Comment by mwetter** [comment]
- [ ] In `FMUZoneExchange.c`, the call to `result = zone->ptrBui->fmu->getNextEventTime(&eventInfo, NULL);` jumps one event. Simulating
```
simulateModel("Buildings.Experimental.EnergyPlus.Validation.OneZone", stopTime=3600, method="Cvode", tolerance=1e-06, resultFile="OneZone");
```
produces the following output, where `tNextEP=600` is missing:
```
Start time is set to 0.000000.
Time = 0	 tNextEP = 1200	 tNext = 1200
Time = 1200	 tNextEP = 1800	 tNext = 1800
Time = 1800	 tNextEP = 2400	 tNext = 2400
Time = 2400	 tNextEP = 3000	 tNext = 3000
Time = 3000	 tNextEP = 3600	 tNext = 3600
Time = 3600	 tNextEP = 4200	 tNext = 4200
Integration terminated successfully at T = 3600
```

**Comment by mwetter** [comment]
- [ ] When multiple buildings are supported, enable two buildings in `Buildings.Experimental.EnergyPlus.Validation.ThreeZonesTwoBuildings` by changing the value for `idfName2` to `RefBldgSmallOfficeNew2004_Chicago2.idf`

**Comment by mwetter** [comment]
- [ ] The following command fails in Dymola 2019FD01 with a segmentation fault:
```
simulateModel("Buildings.Experimental.EnergyPlus.Validation.RefBldgSmallOffice", stopTime=604800, method="dassl", tolerance=1e-06, resultFile="RefBldgSmallOffice");
 = false
simulateModel("Buildings.Experimental.EnergyPlus.Validation.OneZone", stopTime=86400, tolerance=1e-06, resultFile="OneZone");
 = false
```
If the solver is changed to CVode, the simulation works:
```
simulateModel("Buildings.Experimental.EnergyPlus.Validation.OneZone", stopTime=86400, method="Cvode", tolerance=1e-06, resultFile="OneZone");
 = true
```

**Comment by AntoineGautier** [comment]
@mwetter Is this the correct branch that I should merge with `issue1442_loadCoupling` for URBANopt Modelica developments?

**Comment by mwetter** [comment]
@AntoineGautier : Please merge `issue1129_energyPlus_zone_fmiSignature` into the URBANopt branch. I already updated `issue1129_energyPlus_zone_fmiSignature` with the `master` this morning.

Once the E+ FMU works, this will be merged into `issue1129_energyPlus_zone` and deleted, but for now, please use `issue1129_energyPlus_zone_fmiSignature`.
