### ISSUE TITLE
Errors when running the validation case 600 and 600FF in Open Modelica

### ISSUE THREAD

**Issue by Ja98** [lbl-srg/modelica-buildings#1131]
When I simulate the validation cases in Open Modelica, I get the following error messages: 

**For Case 600:**

[1] 08:27:52 Translation Error
[Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case600FF: 193:3-201:69]: Variable staRes: In modifier (minT(Min = 254.35), class or component Min), class or component minT not found in <Buildings.ThermalZones.Detailed.Validation.BESTEST.Data.StandardResults$staRes>.

[2] 08:27:52 Translation Error
Error occurred while flattening model Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case600

_For the first error I have looked into the class mentioned, and the variables the error says are missing are present in the class_

**For Case 600FF:**

[1] 08:48:00 Translation Error
[Buildings.HeatTransfer.Data.GlazingSystems: 38:5-42:31]: Dimensions must be parameter or constant expression (in size(glass, 1)).

[2] 08:48:00 Translation Error
[Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case600FF: 96:7-96:25]: Component roo.datConExtWin[1].glaSys of variability PARAM has binding window600 of higher variability VAR.

[3] 08:48:00 Translation Error
Error occurred while flattening model Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case600FF

I have tried to investigate why these errors are occurring but I am new to Modelica and it is not clear why this is occuring. Apologies if this is a trivial issue.

**Comment by mwetter** [comment]
I don't think these models work with OpenModelica as OpenModelica does not
yet parse all models of the Buildings library.
Dymola and JModelica have been tested.

All the best,

Michael

**Comment by thorade** [comment]
Here is th ereport for the testing of OMC latest with Buildings latest:
https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html

The tests with the new OMC parser are here (expected to arrive in 2018):
https://libraries.openmodelica.org/branches/newInst/Buildings_latest/Buildings_latest.html

Also see the Coverage report here:
https://trac.openmodelica.org/OpenModelica/wiki/CoverageIssues#Buildings

**Comment by mwetter** [comment]
Closed as this problem needs to be fixed in OpenModelica. There does not seem to be a reasonable work-around for the Buildings library.
