### ISSUE TITLE
Errors when compiling the FlatPlatewithTank example in JModelica

### ISSUE THREAD

**Issue by Ja98** [lbl-srg/modelica-buildings#1132]
When compiling the Flat Plate with Tank  in JModelica, the following errors are returned: Errors denoted with (....), indicate the error appears multiple times: 

In component pum:
The parameter pum.filter.c0 does not have a binding expression
(.....)

Compliance warning at line 7, column 36, in file
(.....)
String parameters are only partially supported

In components:
    bou
    bou1
  The cardinality() function-like operator is deprecated, and will be removed in a future version of Modelica

In component tan:
  The component energyDynamics is declared multiple times and can not be verified to be identical to other declaration(s) with the same name.

sources/ModelicaInternal_readLine.c: In function 'main':
sources/ModelicaInternal_readLine.c:181:22: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]

Warning at line 1756, column 39, in file 'C:\JModelica.org-2.1\install\ThirdParty\MSL\Modelica\Blocks\Continuous.mo':
  Iteration variable "pum.filter.x[1]" is missing start value!

sources/Buildings_Fluid_SolarCollectors_Examples_FlatPlateWithTank_equ_init.c: In function 'model_ode_initialize_base':
sources/Buildings_Fluid_SolarCollectors_Examples_FlatPlateWithTank_equ_init.c:1706:9: warning: string length '613' is greater than the length '509' ISO C90 compilers are required to support [-Woverlength-strings]

Warning at line 1756, column 39, in file 'C:\JModelica.org-2.1\install\ThirdParty\MSL\Modelica\Blocks\Continuous.mo':
  Iteration variable "pum.filter.x[1]" is missing start value!

warning: string length '613' is greater than the length '509' ISO C90 compilers are required to support [-Woverlength-strings]

Are these errors occurring because I have the wrong set-up with my computer? I am relying on these example cases to understand the interconnections between systems. Thanks

**Comment by mwetter** [comment]
@Ja98 : These are all warnings, not errors. The model should still translate and simulate. Is this not the case for your JModelica installation?

**Comment by Ja98** [comment]
Thanks for your reply, I'm not sure how the error was solved, but the example now compiles fine without generating any error messages or warnings. Apologies if this post was unhelpful.
