### ISSUE TITLE
G36 library variable names consistency, include VAV in the name

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#1137]
Go through the variable names in the G36 primary HVAC control library and check for consistency, e.g. TSupSet vs. TSetSup, etc.

Include a substring 'VAV' in the top AHU sequence controller name.

**Comment by mwetter** [comment]
Please also write a conversion script with all the changes. See `./Resources/Scripts/Dymola/ConvertBuildings_from*.mos`

**Comment by milicag** [comment]
I will. Sorry for the delay, but this is just about to make the top of my list.

**Comment by milicag** [comment]
Include: Fix typo in info section of Buildings.Utilities.IO.Files.CSVWriter: ```The parameter samplePeriod defines every how may seconds the inputs are saved to the file. ```

**Comment by mwetter** [comment]
@milicag This typo needs to be fixed by making a pull request in the IBPSA library https://github.com/ibpsa/modelica-ibpsa  (which will periodically be merged into the Buildings library).

**Comment by milicag** [comment]
@mwetter It looks like I can't push to the IBPSA library: 

```remote: Permission to ibpsa/modelica-ibpsa.git denied to milicag.```

**Comment by mwetter** [comment]
you can make a fork and pull request.

**Comment by milicag** [comment]
Did you mean a branch?

```
mg@w:~/repos/modelica-ibpsa/IBPSA$ git push
Username for 'https://github.com': milicag
Password for 'https://milicag@github.com': 
remote: Permission to ibpsa/modelica-ibpsa.git denied to milicag.
fatal: unable to access 'https://github.com/ibpsa/modelica-ibpsa.git/': The requested URL returned error: 403
mg@w:~/repos/modelica-ibpsa/IBPSA$ git branch
* issue985_fix_typo_in_csvwriter
  master
mg@w:~/repos/modelica-ibpsa/IBPSA$
```

**Comment by mwetter** [comment]
No, I did mean a fork.

**Comment by milicag** [comment]
This is resolved and merged.
