### ISSUE TITLE
Error when converting .epw weather file to .mos 

### ISSUE THREAD

**Issue by Ja98** [lbl-srg/modelica-buildings#1142]
I have been provided with an epw file, I am not sure of the source, but when I run the java script, I get the message: 

`The data at line 9 column 23 in .epw file is missing. You need to fix it before the convert.`

I have manually compared the two files and everything looks identical. Any ideas what could be causing this issue?

**Comment by mwetter** [comment]
Can you try with an original `.epw` file? I have not seen such an error before.

**Comment by Ja98** [comment]
Yes standard .epw files from the EnergyPlus website run fine. 

It seems to be a problem in the weather data rather than the header text. Here are comparisons of the first two lines of the data: 
[Working and Broken File.txt](https://github.com/lbl-srg/modelica-buildings/files/1833495/Working.and.Broken.File.txt)
[Comparing errors.xlsx](https://github.com/lbl-srg/modelica-buildings/files/1833496/Comparing.errors.xlsx)

Looking at the structure of the .mos the it seems to be failing on column 23. Looking at the Excel sheet this 2 for the working file and 99 for the error file. Could this have something to do with it?

**Comment by mwetter** [comment]
The file that is broken has an entry of `99` for the 23rd field, which indicates that this data is missing. You will need to use a valid weather file or fix this entry. Please check the EnergyPlus documentation for the syntax of this file.
