### ISSUE TITLE
JError: GC overhead limit exceeded java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by Ja98** [lbl-srg/modelica-buildings#1146]
When compiling the TwoRoomsWithStorage in JModelica I get the error: 

> JError: GC overhead limit exceeded
> java.lang.OutOfMemoryError: GC overhead limit exceeded

> at org.jmodelica.modelica.compiler.ASTNode.clone(Unknown Source)
> 	at org.jmodelica.modelica.compiler.BaseNode.clone(Unknown Source)
> 	at org.jmodelica.modelica.compiler.FQName.clone(Unknown Source)
> 	at org.jmodelica.modelica.compiler.FQNameString.clone(Unknown Source)
> 	at org.jmodelica.modelica.compiler.FQNameString.copy(Unknown Source)
> 	at org.jmodelica.modelica.compiler.FQNameString.treeCopyNoTransform(Unknown Source)
> 	at org.jmodelica.modelica.compiler.FQNameString.treeCopy(Unknown Source)
> 	at org.jmodelica.modelica.compiler.FQNameString.copyAndAddFas(Unknown Source)
> 	at org.jmodelica.modelica.compiler.InstAssignable.flatten(Unknown Source)
> 	at org.jmodelica.modelica.compiler.ASTNode.flatten(Unknown Source)
> 	at org.jmodelica.modelica.compiler.InstNode.flatten(Unknown Source)

Any idea why this is happening?

**Comment by mwetter** [comment]
Try to increase the memory with
```
pymodelica.environ['JVM_ARGS'] = '-Xmx4096m'
```
