### ISSUE TITLE
OpenModelica compatibility for buildings library

### ISSUE THREAD

**Issue by dgusain** [lbl-srg/modelica-buildings#1168]
Hi,

I am trying to run example cases on OpenModelica, specifically  IdealSystem3Clusters from DistrictHeatingCooling examples, but I just cannot get it up and running. The following is my output from omc:

record SimulationResult
    resultFile = "C:/Users/digvijaygusain/AppData/Local/Temp/OpenModelica/OMEdit/HeatNetwork/Buildings.Experimental.DistrictHeatingCooling.Examples.IdealSystem3Clusters_res.mat",
    simulationOptions = "startTime = 0.0, stopTime = 86400.0, numberOfIntervals = 500, tolerance = 0.1, method = 'dassl', fileNamePrefix = 'Buildings.Experimental.DistrictHeatingCooling.Examples.IdealSystem3Clusters', options = '', outputFormat = 'mat', variableFilter = '.*', cflags = '', simflags = ''",
    messages = "assert            | warning | The following assertion has been violated during initialization at time 0.000000
|                 | |       | hea1.pum.nominalValuesDefineDefaultPressureCurve
assert            | warning | *** Warning: You are using a flow or pressure controlled mover with the
|                 | |       |              default pressure curve.
|                 | |       |              This leads to approximate calculations of the electrical power
|                 | |       |              consumption. Add the correct pressure curve in the record per
|                 | |       |              to obtain an accurate computation.
|                 | |       |              Setting nominalValuesDefineDefaultPressureCurve=true will suppress this warning.
assert            | warning | The following assertion has been violated during initialization at time 0.000000
|                 | |       | hea2.pum.nominalValuesDefineDefaultPressureCurve
assert            | warning | *** Warning: You are using a flow or pressure controlled mover with the
|                 | |       |              default pressure curve.
|                 | |       |              This leads to approximate calculations of the electrical power
|                 | |       |              consumption. Add the correct pressure curve in the record per
|                 | |       |              to obtain an accurate computation.
|                 | |       |              Setting nominalValuesDefineDefaultPressureCurve=true will suppress this warning.
assert            | warning | The following assertion has been violated during initialization at time 0.000000
|                 | |       | coo1.pum.nominalValuesDefineDefaultPressureCurve
assert            | warning | *** Warning: You are using a flow or pressure controlled mover with the
|                 | |       |              default pressure curve.
|                 | |       |              This leads to approximate calculations of the electrical power
|                 | |       |              consumption. Add the correct pressure curve in the record per
|                 | |       |              to obtain an accurate computation.
|                 | |       |              Setting nominalValuesDefineDefaultPressureCurve=true will suppress this warning.
assert            | warning | The following assertion has been violated during initialization at time 0.000000
|                 | |       | coo2.pum.nominalValuesDefineDefaultPressureCurve
assert            | warning | *** Warning: You are using a flow or pressure controlled mover with the
|                 | |       |              default pressure curve.
|                 | |       |              This leads to approximate calculations of the electrical power
|                 | |       |              consumption. Add the correct pressure curve in the record per
|                 | |       |              to obtain an accurate computation.
|                 | |       |              Setting nominalValuesDefineDefaultPressureCurve=true will suppress this warning.
assert            | warning | The following assertion has been violated during initialization at time 0.000000
|                 | |       | hea3.pum.nominalValuesDefineDefaultPressureCurve
assert            | warning | *** Warning: You are using a flow or pressure controlled mover with the
|                 | |       |              default pressure curve.
|                 | |       |              This leads to approximate calculations of the electrical power
|                 | |       |              consumption. Add the correct pressure curve in the record per
|                 | |       |              to obtain an accurate computation.
|                 | |       |              Setting nominalValuesDefineDefaultPressureCurve=true will suppress this warning.
assert            | warning | The following assertion has been violated during initialization at time 0.000000
|                 | |       | hea4.pum.nominalValuesDefineDefaultPressureCurve
assert            | warning | *** Warning: You are using a flow or pressure controlled mover with the
|                 | |       |              default pressure curve.
|                 | |       |              This leads to approximate calculations of the electrical power
|                 | |       |              consumption. Add the correct pressure curve in the record per
|                 | |       |              to obtain an accurate computation.
|                 | |       |              Setting nominalValuesDefineDefaultPressureCurve=true will suppress this warning.
assert            | warning | The following assertion has been violated during initialization at time 0.000000
|                 | |       | coo3.pum.nominalValuesDefineDefaultPressureCurve
assert            | warning | *** Warning: You are using a flow or pressure controlled mover with the
|                 | |       |              default pressure curve.
|                 | |       |              This leads to approximate calculations of the electrical power
|                 | |       |              consumption. Add the correct pressure curve in the record per
|                 | |       |              to obtain an accurate computation.
|                 | |       |              Setting nominalValuesDefineDefaultPressureCurve=true will suppress this warning.
assert            | warning | The following assertion has been violated during initialization at time 0.000000
|                 | |       | coo4.pum.nominalValuesDefineDefaultPressureCurve
assert            | warning | *** Warning: You are using a flow or pressure controlled mover with the
|                 | |       |              default pressure curve.
|                 | |       |              This leads to approximate calculations of the electrical power
|                 | |       |              consumption. Add the correct pressure curve in the record per
|                 | |       |              to obtain an accurate computation.
|                 | |       |              Setting nominalValuesDefineDefaultPressureCurve=true will suppress this warning.
assert            | warning | The following assertion has been violated during initialization at time 0.000000
|                 | |       | hea5.pum.nominalValuesDefineDefaultPressureCurve
assert            | warning | *** Warning: You are using a flow or pressure controlled mover with the
|                 | |       |              default pressure curve.
|                 | |       |              This leads to approximate calculations of the electrical power
|                 | |       |              consumption. Add the correct pressure curve in the record per
|                 | |       |              to obtain an accurate computation.
|                 | |       |              Setting nominalValuesDefineDefaultPressureCurve=true will suppress this warning.
assert            | warning | The following assertion has been violated during initialization at time 0.000000
|                 | |       | hea6.pum.nominalValuesDefineDefaultPressureCurve
assert            | warning | *** Warning: You are using a flow or pressure controlled mover with the
|                 | |       |              default pressure curve.
|                 | |       |              This leads to approximate calculations of the electrical power
|                 | |       |              consumption. Add the correct pressure curve in the record per
|                 | |       |              to obtain an accurate computation.
|                 | |       |              Setting nominalValuesDefineDefaultPressureCurve=true will suppress this warning.
assert            | warning | The following assertion has been violated during initialization at time 0.000000
|                 | |       | hea7.pum.nominalValuesDefineDefaultPressureCurve
assert            | warning | *** Warning: You are using a flow or pressure controlled mover with the
|                 | |       |              default pressure curve.
|                 | |       |              This leads to approximate calculations of the electrical power
|                 | |       |              consumption. Add the correct pressure curve in the record per
|                 | |       |              to obtain an accurate computation.
|                 | |       |              Setting nominalValuesDefineDefaultPressureCurve=true will suppress this warning.
assert            | warning | The following assertion has been violated during initialization at time 0.000000
|                 | |       | coo5.pum.nominalValuesDefineDefaultPressureCurve
assert            | warning | *** Warning: You are using a flow or pressure controlled mover with the
|                 | |       |              default pressure curve.
|                 | |       |              This leads to approximate calculations of the electrical power
|                 | |       |              consumption. Add the correct pressure curve in the record per
|                 | |       |              to obtain an accurate computation.
|                 | |       |              Setting nominalValuesDefineDefaultPressureCurve=true will suppress this warning.
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
assert            | debug   | division by zero at time 0.1728, (a=0) / (b=0), where divisor b expression is: 0.0
assert            | debug   | division by zero at time 0.0432, (a=0) / (b=0), where divisor b expression is: 0.0
assert            | debug   | division by zero at time 0.0108, (a=0) / (b=0), where divisor b expression is: 0.0
assert            | debug   | division by zero at time 0.0027, (a=0) / (b=0), where divisor b expression is: 0.0
assert            | debug   | division by zero at time 0.000675, (a=0) / (b=0), where divisor b expression is: 0.0
assert            | debug   | division by zero at time 0.00016875, (a=0) / (b=0), where divisor b expression is: 0.0
assert            | debug   | division by zero at time 4.21875e-005, (a=0) / (b=0), where divisor b expression is: 0.0
assert            | debug   | division by zero at time 1.0546875e-005, (a=0) / (b=0), where divisor b expression is: 0.0
assert            | debug   | division by zero at time 2.63671875e-006, (a=0) / (b=0), where divisor b expression is: 0.0
assert            | debug   | division by zero at time 6.591796875e-007, (a=0) / (b=0), where divisor b expression is: 0.0
DASKR--  AT T (=R1) AND STEPSIZE H (=R2) THE                                    
      In above,  R1 =  0.0000000000000E+000   R2 =  1.6479492187500E-007
DASKR--  NONLINEAR SYSTEM SOLVER COULD NOT CONVERGE                             
DASKR--  BECAUSE IRES WAS EQUAL TO MINUS ONE                                    
stdout            | warning | A Modelica assert prevents the integrator to continue. For more information use -lv LOG_SOLVER
stdout            | warning | can't continue. time = 0.000000
assert            | debug   | division by zero at time 0, (a=0) / (b=0), where divisor b expression is: 0.0
assert            | debug   | division by zero at time 0, (a=0) / (b=0), where divisor b expression is: 0.0
LOG_SUCCESS       | info    | The simulation finished successfully.
",
    timeFrontend = 57.29827187747517,
    timeBackend = 2.331866912484235,
    timeSimCode = 0.5203689492178714,
    timeTemplates = 1.583034541043606,
    timeCompile = 55.96838202325609,
    timeSimulation = 2.891366777151634,
    timeTotal = 120.5936283124597
end SimulationResult;

It says simulation finished successfully, but I cannot plot anything and the res file seems empty as well. 
I am also facing issues running other examples from Buildings library on OMC (TranslationError in Chiller plant example).
Is the buildings library known to have issues with OpenModelica? If there are compatibility issues with OM and Buildings library, are there any (opensource) workarounds?

Thanks!
Digvijay

**Comment by mwetter** [comment]
I am not aware of the problem that OpenModelica simulates a model but the result file is empty. I suggest you check with the OpenModelica development team.

Note that not all models of the Buildings library work with OpenModelica. If they don't work, then they typically don't translate or don't converge during the simulation, rather than showing the problem that you report.

All models are continuously tested with Dymola and JModelica.
