### ISSUE TITLE
Undeclared function pythonExchangeValuesNoModelica

### ISSUE THREAD

**Issue by sjoelund** [lbl-srg/modelica-buildings#1171]
https://github.com/lbl-srg/modelica-buildings/blob/aa5b566/Buildings/Resources/C-Sources/python27Wrapper.c#L32 contains a call to an undefined function. It exists in the library, but C++ and C99 compilers do not allow calling functions with a declaration.

I believe that the proper fix would be to:
* `#include ".../pythonInterpreter.h"` in `python27Wrapper.c`
* Remove `#include <Python.h>` from that header (since none of the declarations in there use it)
* Possibly add `#include <Python.h>` to some files that got it from this include

Issue taken from: https://openmodelica.org/forum/default-topic/2488-error-with-external-python-function-call-from-buildings-library

**Comment by mwetter** [comment]
@sjoelund Thanks for reporting.
@tsnouidui : Can you please address this, this may also need changes in the SimulatorToFMU program.

**Comment by tsnouidui** [comment]
Yes will do.

**Comment by mwetter** [comment]
This can be closed as the function `pythonExchangeValuesNoModelica` is exported by the library `ModelicaBuildingsPython2.7` which is declared in the annotation of `exchange.mo`.
