### ISSUE TITLE
Weather data: convert weather data file from .epw extension to .mos extension

### ISSUE THREAD

**Issue by LWaal** [lbl-srg/modelica-buildings#1174]
Hello,
I have the same question as #463 

I've followed the instructions to the letter, but using the command returns an error. When I want to change my epw weather file to the mos file, this is the return from the command window: 
`cd Buildings/Resources/weatherdata
C:/Users/sXXXXX/Documents/Dymola/Buildings
 = false
java -jar ../bin/ConvertWeatherData.jar inputFile.epw
Error: ./ (line 1, column 12: <undefined source>)
Error: Expected one of:
DER`

I've tried changing the commands to:
` cd C:/Users/sXXXXX/Documents/Dymola/Buildings/Resources/weatherdata
C:/Users/sXXXXX/Documents/Dymola/Buildings/Resources/weatherdata
 = true
java -jar ../bin/ConvertWeatherData.jar inputFile.epw
Error: ./ (line 1, column 12: <undefined source>)
Error: Expected one of:
DER
`
Which then postivily changes the directory to the right one. But still same error.
And
` cd C:/Users/sXXXXX/Documents/Dymola/Buildings/Resources/weatherdata
C:/Users/sXXXXX/Documents/Dymola/Buildings/Resources/weatherdata
 = true
java -jar ../bin/ConvertWeatherData.jar NLD_Amsterdam.062400_IWEC.epw
Error: ./ (line 1, column 12: <undefined source>)
Error: Expected one of:
DER
`
Which also returns the error. 
Also tried changing the file name to just "test", to see if the problem was in the filename underscore's and dots. Didnt change anything. Reinstalled java too. Can't read the file itself with notepad or the java.exe on my pc.

What am I doing wrong?
Kind regards.

**Comment by mwetter** [comment]
I cannot produce the error. Below is my console output that I run from `Buildings/Resources/weatherdata`
```bash
$ wget https://energyplus.net/weather-download/europe_wmo_region_6/NLD//NLD_Amsterdam.062400_IWEC/NLD_Amsterdam.062400_IWEC.epw
--2018-05-30 09:52:23--  https://energyplus.net/weather-download/europe_wmo_region_6/NLD//NLD_Amsterdam.062400_IWEC/NLD_Amsterdam.062400_IWEC.epw
Resolving energyplus.net (energyplus.net)... 104.27.178.102, 104.27.179.102, 2400:cb00:2048:1::681b:b266, ...
Connecting to energyplus.net (energyplus.net)|104.27.178.102|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘NLD_Amsterdam.062400_IWEC.epw’

NLD_Amsterdam.062400_IWEC.epw                                   [  <=>                                                                                                                                    ]   1.48M  5.88MB/s    in 0.3s    

2018-05-30 09:52:23 (5.88 MB/s) - ‘NLD_Amsterdam.062400_IWEC.epw’ saved [1552242]

$ java -jar ../bin/ConvertWeatherData.jar NLD_Amsterdam.062400_IWEC.epw 
$ head NLD_Amsterdam.062400_IWEC.mos 
#1
double tab1(8760,30)
#LOCATION,AMSTERDAM,-,NLD,IWEC Data,062400,52.30,4.77,1.0,-2.0
#DESIGN CONDITIONS,1,Climate Design Data 2009 ASHRAE Handbook,,Heating,1,-7.3,-4.9,-11.1,1.4,-6.2,-8.4,1.8,-3.7,17.6,9.5,15.7,9.3,4.6,80,Cooling,7,8,27.8,19.7,25.6,19,23.7,18,20.7,25.8,19.7,24.1,18.8,22.6,4.2,50,19,13.7,22.6,18,13,21.4,17.2,12.3,20.5,59.4,26.1,56,24.2,53.2,22.7,1168,Extremes,13.6,11.9,10.4,24.5,-8.7,31.2,3.8,1.8,-11.4,32.5,-13.6,33.6,-15.7,34.6,-18.4,36
#TYPICAL/EXTREME PERIODS,6,Summer - Week Nearest Max Temperature For Period,Extreme,8/ 3,8/ 9,Summer - Week Nearest Average Temperature For Period,Typical,6/ 8,6/14,Winter - Week Nearest Min Temperature For Period,Extreme,2/10,2/16,Winter - Week Nearest Average Temperature For Period,Typical,2/ 3,2/ 9,Autumn - Week Nearest Average Temperature For Period,Typical,10/13,10/19,Spring - Week Nearest Average Temperature For Period,Typical,4/ 5,4/11
#GROUND TEMPERATURES,3,.5,,,,6.55,4.47,3.90,4.39,7.20,10.34,13.30,15.44,16.06,15.06,12.63,9.58,2,,,,8.41,6.47,5.54,5.51,6.99,9.14,11.45,13.43,14.46,14.26,12.90,10.80,4,,,,9.63,8.12,7.19,6.91,7.45,8.71,10.26,11.79,12.81,13.06,12.47,11.24
#HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0
#COMMENTS 1,"IWEC- WMO#062400 - Europe -- Original Source Data (c) 2001 American Society of Heating, Refrigerating and Air-Conditioning Engineers (ASHRAE), Inc., Atlanta, GA, USA.  www.ashrae.org  All rights reserved as noted in the License Agreement and Additional Conditions. DISCLAIMER OF WARRANTIES: The data is provided 'as is' without warranty of any kind, either expressed or implied. The entire risk as to the quality and performance of the data is with you. In no event will ASHRAE or its contractors be liable to you for any damages, including without limitation any lost profits, lost savings, or other incidental or consequential damages arising out of the use or inability to use this data."
#COMMENTS 2, -- Ground temps produced with a standard soil diffusivity of 2.3225760E-03 {m**2/day}
#DATA PERIODS,1,1,Data,Sunday, 1/ 1,12/31
```

**Comment by LWaal** [comment]
While I was typing that it wasn't working, suddenly; it worked! No idea what solved it. 
What does the dollar sign do? Perhaps that is the magic potion.

Thanks!

**Comment by mwetter** [comment]
The dollar sign is only indicating the command line prompt on the bash shell.

**Comment by dqian0130** [comment]
Hello,

I am having the same issue when I was trying to create my own mos file.

By following the instruction, I typed the following command into the console window:

cd **C:/Tools/Dymola_2018_FD01/Modelica/Library/Buildings-v5.1.0/Buildings 5.1.0/Resources/weatherdata**
and get
C:/Tools/Dymola_2018_FD01/Modelica/Library/Buildings-v5.1.0/Buildings 5.1.0/Resources/weatherdata
 = true

then:
java -jar ../bin/ConvertWeatherData.jar **USA_AL_Tuscaloosa.Muni.AP.722286_TMY3**.epw
and get
Error: ./ (line 1, column 12: <undefined source>)
Error: Expected one of:
DER

The directory and epw file are bonded.

I am wondering what is DER? And am I missing something?

Thank you for your help!

**Comment by LWaal** [comment]
Hello Dqian,

Just to be sure, you did place the epw file in the weatherdata folder?
Otherwise, you can see that I had the same problem that miraculously solved itself the next day (after a reboot and reloading of the packages). Perhaps this also is the case for you. 

Otherwise you can try removing the version in the folder line:
C:/Tools/Dymola_2018_FD01/Modelica/Library/Buildings-v5.1.0/Buildings **5.1.0**/Resources/weatherdata
I was once told that modelica/dymola does not like space's in its code and as you can see Michael Wetter doesnt have the package number in his folder name.

If that doesnt help open the console window and copy michael's code given above and see if that works.

If all else fails get back to me :).

Kind regards.

**Comment by dqian0130** [comment]
Dear LWaal,

Thanks for your advice.
I tried to reboot, reloading and removing the version in the directory, unfortunately, I still cannot make it.
I am thinking whether it is because the bin folder was not under "weatherdata", and I made a copy under the "weatherdata".

Thanks

**Comment by mwetter** [comment]
Converting the weather data works for me:
```bash
mbp-2:weatherdata mwetter$ pwd
/Users/mwetter/test/modelica-buildings/Buildings 5.1.0/Resources/weatherdata
mbp-2:weatherdata mwetter$ mv ~/Downloads/USA_AL_Tuscaloosa.Muni.AP.722286_TMY3.zip .
mbp-2:weatherdata mwetter$ unzip USA_AL_Tuscaloosa.Muni.AP.722286_TMY3.zip 
Archive:  USA_AL_Tuscaloosa.Muni.AP.722286_TMY3.zip
  inflating: USA_AL_Tuscaloosa.Muni.AP.722286_TMY3.ddy  
  inflating: USA_AL_Tuscaloosa.Muni.AP.722286_TMY3.epw  
  inflating: USA_AL_Tuscaloosa.Muni.AP.722286_TMY3.stat  
mbp-2:weatherdata mwetter$ java -jar ../bin/ConvertWeatherData.jar USA_AL_Tuscaloosa.Muni.AP.722286_TMY3.epw 
mbp-2:weatherdata mwetter$ head USA_AL_Tuscaloosa.Muni.AP.722286_TMY3.mos 
#1
double tab1(8760,30)
#LOCATION,Tuscaloosa Municipal Ap,AL,USA,TMY3,722286,33.22,-87.62,-6.0,51.0
#DESIGN CONDITIONS,1,Climate Design Data 2009 ASHRAE Handbook,,Heating,1,-6.4,-3.9,-13.8,1.1,-2.5,-10.8,1.5,0.9,8.7,9.9,8.2,9.1,2.1,340,Cooling,7,10.7,35.4,24.7,34.1,24.6,33,24.4,26.5,32.3,25.9,31.6,25.5,31,3.2,250,25.1,20.3,28.7,24.4,19.5,28.3,23.9,19,27.9,82.7,32.2,80.3,31.8,78.2,31,752,Extremes,7.8,6.6,5.8,31.3,-11.1,37.2,3.7,0.9,-13.8,37.8,-15.9,38.3,-18,38.8,-20.7,39.4
#TYPICAL/EXTREME PERIODS,6,Summer - Week Nearest Max Temperature For Period,Extreme,7/15,7/21,Summer - Week Nearest Average Temperature For Period,Typical,7/22,7/28,Winter - Week Nearest Min Temperature For Period,Extreme,1/22,1/28,Winter - Week Nearest Average Temperature For Period,Typical,1/ 1,1/ 7,Autumn - Week Nearest Average Temperature For Period,Typical,11/26,12/ 2,Spring - Week Nearest Average Temperature For Period,Typical,6/10,6/16
#GROUND TEMPERATURES,3,.5,,,,6.97,8.91,12.68,16.24,22.99,26.55,27.53,25.72,21.56,16.37,11.27,7.89,2,,,,9.64,10.11,12.26,14.65,19.84,23.16,24.81,24.44,22.06,18.48,14.45,11.28,4,,,,12.40,12.07,13.00,14.36,17.79,20.36,22.03,22.43,21.39,19.28,16.55,14.08
#HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0
#COMMENTS 1,Custom/User Format -- WMO#722286; NREL TMY Data Set (2008); Period of Record 1973-2005 (Generally)
#COMMENTS 2, -- Ground temps produced with a standard soil diffusivity of 2.3225760E-03 {m**2/day}
#DATA PERIODS,1,1,Data,Sunday, 1/ 1,12/31
mbp-2:weatherdata mwetter$
```
This was on OS X 10.13.5. The same commands also work on Linux Ubuntu 16.04. On both operating systems, I have Java 1.8.0.

**Comment by dqian0130** [comment]
Michael,

Thank you for your response.
Unfortunately, mine is still not working. Is there any other possible reason could cause the error: DER?

The .epw file is under "weatherdata" folder.
Initially, the "bin" folder is locating under "Resources", and I made an copy of the "bin" folder under the "weatherdata" folder. I am not sure whether I suppose to do it, or I should redirect to it?
Like: **java -jar C:/Tools/Dymola_2018_FD01/Modelica/Library/Buildings-v5.1.0/Buildings 5.1.0/Resources/bin/ConvertWeatherData.jar USA_AL_Tuscaloosa.Muni.AP.722286_TMY3.epw**

Thanks!

**Comment by mwetter** [comment]
@dqian0130 : I don't understand your point about "If I did it, there is an error". What is "it"? The error message is from a Modelica model, but running the jar file for the weather conversion does not use any Modelica. Also, there is no need to copy the .jar file around. 

I would test the following:
1. Download the library again and make sure you have a fresh unzipped installation.
2. Make sure USA_AL_Tuscaloosa.Muni.AP.722286_TMY3.epw is in a directory where you have write access. Run the jar file. The generated .mos file will be in the same directory.
3. If it is not working, check your Java version and make sure it is at least 1.8.0, but older versions should work too as this jar file was compiled in 2013 and used by many others.

**Comment by dqian0130** [comment]
@mwetter 
I see what you saying.
I repeated the procedure you suggested, and the problem solved.

Thank you for your help.

**Comment by Gerardocasio1617** [comment]
> Hola, tengo la misma pregunta que [# 463](https://github.com/lbl-srg/modelica-buildings/issues/463)
> 
> He seguido las instrucciones al pie de la letra, pero el uso del comando devuelve un error. Cuando quiero cambiar mi archivo de clima epw al archivo mos, este es el retorno de la ventana de comando: `cd Buildings/Resources/weatherdata C:/Users/sXXXXX/Documents/Dymola/Buildings = false java -jar ../bin/ConvertWeatherData.jar inputFile.epw Error: ./ (line 1, column 12: <undefined source>) Error: Expected one of: DER`
> 
> Intenté cambiar los comandos a: `cd C:/Users/sXXXXX/Documents/Dymola/Buildings/Resources/weatherdata C:/Users/sXXXXX/Documents/Dymola/Buildings/Resources/weatherdata = true java -jar ../bin/ConvertWeatherData.jar inputFile.epw Error: ./ (line 1, column 12: <undefined source>) Error: Expected one of: DER` Que luego cambia el directorio por el correcto. Pero sigue siendo el mismo error. Y `cd C:/Users/sXXXXX/Documents/Dymola/Buildings/Resources/weatherdata C:/Users/sXXXXX/Documents/Dymola/Buildings/Resources/weatherdata = true java -jar ../bin/ConvertWeatherData.jar NLD_Amsterdam.062400_IWEC.epw Error: ./ (line 1, column 12: <undefined source>) Error: Expected one of: DER` que también devuelve el error. También intenté cambiar el nombre del archivo a "prueba", para ver si el problema estaba en los puntos y subrayados del nombre del archivo. No cambió nada. Java reinstalado también. No puedo leer el archivo en sí con el bloc de notas o el java.exe en mi PC.
> 
> ¿Qué estoy haciendo mal? Atentamente.

Podrías ayudarme a convertir el mío 
Lo realicé en meteonorm a formato epw y no puedo convertirlo a mos para cargarlo a esta simulacion

**Comment by Gerardocasio1617** [comment]
![Uploading C19EC140-5F5A-4404-805A-46EA53D97335.jpeg…]()
