### ISSUE TITLE
TMY weather data time stamps

### ISSUE THREAD

**Issue by LWaal** [lbl-srg/modelica-buildings#1201]
Hello,

While using the weather file I've yet to find a way of changing the start and stop time of the weather file. My issue is that I would like to use the most recent year data from my network, which is from 1-5-2017 till 1-5-2018. The TMY data has is from januari till januari. 

I anticipate this means I have to change the java script translating the TMY data to a usable modelica file. However I do not have the expertice to do that. 

Is there a different method I'm unable to think of besides saving the TMY data to a table, change the table and load it as a table in modelica?

Kind regards,
Laurens

**Comment by mwetter** [comment]
@LWaal If you look at the .mos file that is generated by the Java program you see its format. You can use any text editor or program to generate such a file.
Note however that there is currently a bug in reading weather files that span more than a calendar year, see https://github.com/ibpsa/modelica-ibpsa/issues/842
