### ISSUE TITLE
Update CDL.Logical.Timer to reset to zero output

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#1221]
In current setting when parameter `reset = false`, the timer will output accumulated time whenever the input is `true`. However, it should be able to reset to zero when it is necessary.
The issue intends to update the block so to have one additional boolean input `u0` to reset output.

**Comment by mwetter** [comment]
@JayHuLBL : Should this be closed or do you plan to make a pull request? Last update was in October 2019.

**Comment by JayHuLBL** [comment]
This can be closed as the change has been merged to the master.
