### ISSUE TITLE
Inclusion of Buildings 5.1.0 into OpenModelica

### ISSUE THREAD

**Issue by christiankral** [lbl-srg/modelica-buildings#1251]
I was updating the [PhotoVoltaics](https://github.com/christiankral/PhotoVoltaics/issues/31) library to Buildings 5.1.0 as there is a dependency on the Buldings library in the PhotoVoltaics_TGM package. 

I am using the nightly builds of OpenModelica. When looking at the OpenModelica repository I noticed that the 5.1.0 version is not available through the OpenModelica repository. The 5.0.1 and the master version seem the be the two most recent versions. 

![image](https://user-images.githubusercontent.com/4184218/46257634-52b11480-c4bd-11e8-8a46-c90fa7413418.png)

As the PhotoVoltaics library is also a system library in OpenModelica I would very much appreciate if you could add the 5.1.0 version of the Buildings library to the OpenModelica repository. I suspect that the 5.1.0 version is the next version to be included in the upcoming OpenModelica 1.13.0 release. If not, in PhotoVoltaics I would go for the version you are planning to include in OpenModelica 1.13.0.

**Comment by mwetter** [comment]
Thanks for your post. I forwarded it to the OpenModelica development team who is managing which libraries are included.

**Comment by christiankral** [comment]
Any news here? I checked the OM repository a couple times. Even today there is no version 5.1.0 listed yet...

**Comment by christiankral** [comment]
I can confirm that 5.1.0 version is now included in the OM repository.

![image](https://user-images.githubusercontent.com/4184218/48245748-bd267000-e3ec-11e8-94c5-fedec6eb3d44.png)

Thanks!

**Comment by mwetter** [comment]
@christiankral Thank you for the update. I am glad to see that Buildings 5.1.0 is shipped with OpenModelica.
