### ISSUE TITLE
Using WetCoilCounterFlow in OpenModelica

### ISSUE THREAD

**Issue by kinonotofu** [lbl-srg/modelica-buildings#1258]
I know there is closed issue #418 and Buildings library doesn't support OpenModelica.
Can I make some changes to Buildings library for OpenModelica? 
If we change the code as shown below, we can use  WetCoilCounterFlow in OpenModelica.

**Buildings.Fluid.HeatExchangers.DryCoilCounterFlow**
https://github.com/lbl-srg/modelica-buildings/blob/bc727fd06e349f0084b7b0b93b722cb73d791515/Buildings/Fluid/HeatExchangers/DryCoilCounterFlow.mo#L118-L119
Change these lines as below.  
```  
  replaceable model HexElement = BaseClasses.HexElementSensible constrainedby BaseClasses.PartialHexElement;
  HexElement ele[nEle](
```  
  
**Buildings.Fluid.HeatExchangers.WetCoilCounterFlow**
https://github.com/lbl-srg/modelica-buildings/blob/bc727fd06e349f0084b7b0b93b722cb73d791515/Buildings/Fluid/HeatExchangers/WetCoilCounterFlow.mo#L7-L8
Change these lines as below.    
```  
  redeclare final model HexElement =
  Buildings.Fluid.HeatExchangers.BaseClasses.HexElementLatent);
```   
I think we can use redeclare statement for class (such as package, model) in OpenModelica, but not for instance.
Or redeclare statement in the constraining class (such as Medium1,Medium2) may not be good for OpenModelica.

I run some existing Examples listed below in OpenMoelica v1.12.0 and it worked.
- Buildings.Examples.Tutorial.SpaceCooling.System2
- Buildings.Examples.Tutorial.SpaceCooling.System3
- Buildings.Fluid.HeatExchangers.Examples.DryCoilCounterFlowMassFlow
- Buildings.Fluid.HeatExchangers.Examples.DryCoilCounterFlowPControl
- Buildings.Fluid.HeatExchangers.Examples.WetCoilCounterFlowMassFlow
- Buildings.Fluid.HeatExchangers.Examples.WetCoilCounterFlowPControl

**Comment by mwetter** [comment]
@kinonotofu : Thank you for the code changes and the pull request. This change is certainly useful as I see no drawback of the change, and it makes the model work on OpenModelica.

I will test it through the Pull Request https://github.com/lbl-srg/modelica-buildings/pull/1261 and then merge to the master when all tests pass.

Interestingly, `Buildings.Fluid.HeatExchangers.Examples.WetCoilDiscretizedMassFlow` simulates in OpenModelica, although it uses a similar redeclaration.

**Comment by kinonotofu** [comment]
@mwetter
Thank you for the modification according to Dymola.
If you think constrainedby statement is necessary, it' OK to decline this change.
I didn't expect this modification would be necessary, because I don't have Dymola.

As you pointed out, WetCoilDiscretized works on OpenModelica in spite of using that redeclaration.
It is confusing.So we need to find out more detailed condition that makes error on OpenModelica.
I will report if I find out something.

Best regards,

**Comment by mwetter** [comment]
Closed as this is now on the master branch.
