### ISSUE TITLE
Parameter numZon in ModeAndSetPoints minimum

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/modelica-buildings#1263]
Is there a reason why in `Buildings.Controls.OBC.ASHRAE.G36_PR1.TerminalUnits.ModeAndSetPoints` the parameter `numZon` has `(min=2)`?  Could the minimum be removed so that the block could also be used for the Single Zone VAV sequence?

**Comment by mwetter** [comment]
I don't see a reason why it should not also work with `numZon=1`.
@JayHuLBL : Can the `min=2` be changed to `min=1`?

**Comment by dhblum** [comment]
I will implement a copy of this model in that does not utilize vectors in `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.SingleZone.VAV`, with documentation that refers to the multizone version in `Buildings.Controls.OBC.ASHRAE.G36_PR1.TerminalUnits.ModeAndSetPoints`.

**Comment by dhblum** [comment]
This issue is taken care of in https://github.com/lbl-srg/modelica-buildings/issues/1265.

**Comment by JayHuLBL** [comment]
The issue has been addressed.
