### ISSUE TITLE
Add supply fan status output to SZVAV

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/modelica-buildings#1264]
I suggest adding an output for supply fan status in `SingleZone.VAV.SetPoints.Supply` similar to `MultiZone.VAV.SetPoints.SupplyFan`, as single zone VAV atomic sequences also require this as input.

**Comment by mwetter** [comment]
Can you implement the logic for the fan status according to the Guideline 36? It indeed looks like there is no such implementation in the package for single zone VAV.

**Comment by dhblum** [comment]
I will extract the portion of `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.SetPoints.SupplyFan` that calculates the status based on AHU operating mode into its own model as `Buildings.Controls.OBC.ASHRAE.G36_PR1.Generic.FanOnOff.  Then, I will add this model to `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Controller` and the in-development Single Zone controller.

**Comment by dhblum** [comment]
The multizone case requires a flag to indicate if perimeter zones use a VAV with reheat terminal box, as opposed to fan-powered terminal boxes or other heating strategy.  In these cases, the AHU supply fan does not need to be turned on in setback mode.  

Meanwhile. the single zone VAV sequence is more straight-forward, as the fan is on for all operating modes except unoccupied.  This can be checked explicitly in the controller, without the creation of a new block.  Therefore, this issue will be closed.
