### ISSUE TITLE
Wrong results in JMODELICA

### ISSUE THREAD

**Issue by sewtian** [lbl-srg/modelica-buildings#1266]
Dear Michael,

I was trying to use JMODELICA 2.4 to simulate a simple example `Buildings.Fluid.FixedResistances.Examples.PressureDrop`. I only changed the `duration` in `P` from 1 second to 100 seconds.

Here is my code:
```modelica
model test_resistance "test the pressure drop model in Buildings library"
  extends Buildings.Fluid.FixedResistances.Examples.PressureDrop(
    P.duration=100);
end test_resistance;
```
Here is the setting in JMODELICA
```python
...
fmu_model = compile_fmu(model_name,mo_file)
fmu_obj = load_fmu(fmu_model)
res = fmu_obj.simulate(final_time=100)
...
```
Here is the plotting of mass flow rate through the pipe, which is seemingly incorrect:
![image](https://user-images.githubusercontent.com/35269611/47594673-747daa00-d94a-11e8-8cb2-0843c323c14a.png)

Do you have any idea why? or, did you have this problem before?

**Comment by mwetter** [comment]
@sewtian 
Your plot only seems to have 3 data points that are connected by a line, and these 3 data points seem correct. Did you try to number of communication points to increase the resolution of your output? See https://github.com/lbl-srg/docker-ubuntu-jmodelica/blob/master/jmodelica.py#L28

**Comment by sewtian** [comment]
@mwetter Thanks 😃! Your suggestion works .
