### ISSUE TITLE
Failed to run a Fluid Example in JModelica

### ISSUE THREAD

**Issue by sewtian** [lbl-srg/modelica-buildings#1269]
I want to use epsilon-NTU model so I tested running `Buildings.Fluid.HeatExchangers.Examples.DryEffectivenessNTU` in JModelica (JModelica org 2.4) on a Windows machine. The version of Modelica Buildings library is `5.1.0`. It failed.

I also tested `Buildings.Fluid.HeatExchangers.Examples.DryCoilEffectivenessNTUMassFlow` in the Github repository and it gave me the same error.

This is the error message I got:
`pymodelica.compiler_exceptions.JError: Exception caught while scalarizing function'Buildings.Fluid.HeatExchangers.BaseClasses.ntu_epsilonZ`

I basically followed the [script](https://github.com/lbl-srg/docker-ubuntu-jmodelica/blob/master/jmodelica.py#L28) to set up the simulation in JModelica.

Did I possibly miss anything, as I know that you may have tested the whole library in JModelica?
Thanks!

**Comment by mwetter** [comment]
@sewtian : I wasn't aware that this bug slipped into JModelica 2.4 release. You can however use the latest JModelica version, or the docker image at https://hub.docker.com/r/michaelwetter/ubuntu-1604_jmodelica_trunk/ which is the image that we use for compatibility testing.

**Comment by sewtian** [comment]
@mwetter when I searched the error, I found this [post](https://trac.jmodelica.org/ticket/4882). I tested it in my JModelica 2.4 on a Windows machine, no errors were encountered. I am going to try your docker image. Thanks a lot.
