### ISSUE TITLE
SingleZone Occupancy Sensor

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/modelica-buildings#1270]
In `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.SingleZone.VAV.SetPoints.OutsideAirFlow`, the input `nOcc` is not conditional on the parameter `have_occSen`.  If there is not occupancy sensor, how can the number of occupants be input?  Or is this an error, where the fix would be to make `nOcc` conditional on `have_occSen=true`?

**Comment by mwetter** [comment]
The input `nOcc` should be conditionally removed, as it is for the multi zone implementation. I will fix it.
