### ISSUE TITLE
Parameter name in SingleZone VAV Economizer Limits

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/modelica-buildings#1271]
In `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.SingleZone.VAV.Economizers.Subsequences.Limits`, I think the parameter name `minVOutMinFansSpePos` should be changed to `yDam_VOutMin_minSpe` to match the other parameter name conventions.

**Comment by mwetter** [comment]
@dhblum : I think `minVOutMinFansSpePos` is consistent with other parameter names. What should be changed is that the figure in `SingleZone.VAV.Economizers.Subsequences.Limits` uses old parameter names. Do you agree?

**Comment by dhblum** [comment]
@mwetter This can be closed.  The parameter is what I suggest in current master.
