### ISSUE TITLE
MedSpeed calculation different in v2018 than PR1

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/modelica-buildings#1273]
This issue is to point out that the calculation of the MedSpeed for fan control in ASHRAE Guideline 36 Section 5.18.4.3 is different in the v2018 published version than in PR1, which is implemented in `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.SingleZone.VAV.SetPoints.Supply`.

**Comment by JayHuLBL** [comment]
The issue has been addressed.
