### ISSUE TITLE
review parameter name in ingleZone.VAV.Economizers.Subsequences.Limits

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1275]
The model `SingleZone.VAV.Economizers.Subsequences.Limits` has a parameter
`minVOutMinFansSpePos`. Shouldn't this be `minVOutMinFanSpePos` as there is only one fan?

If you agree, please make the change and also update the conversion script and release notes.

**Comment by milicag** [comment]
That looks like a typo, I'll make the changes needed. Let me review the parameter naming and the labeling in the graphical representations for consistency as well.

**Comment by milicag** [comment]
@mwetter and @dhblum: Due to the typo in the previous naming convention, our renaming script has left this variable name behind! The naming is correct on the graphics in the info section. Thus, as Dave suggests, I'll rename 
```minVOutMinFansSpePos``` to ```yDam_VOutMin_minSpe``` and add to conversion script/release notes.
