### ISSUE TITLE
Buildings.Fluid.Humidifiers.SprayAirWasher_X uses undefined Medium.enthalpyOfLiquid

### ISSUE THREAD

**Issue by casella** [lbl-srg/modelica-buildings#1285]
OpenModelica reports this [error](https://libraries.openmodelica.org/branches/newInst/Buildings_latest/files/Buildings_latest_Buildings.Applications.DataCenters.ChillerCooled.Examples.NonIntegratedPrimarySecondaryEconomizer.err). I checked the source code, and indeed the SprayAirWasher_X model calls the function Medium.enthalpyOfLiquid, which is not allowed because the base class PartialTwoPort defines Medium = Modelica.Media.Interfaces.PartialMedium, which does not include that function. 

The fact that this example model redeclares the medium model to a concrete implementation that includes that function doesn't make the model valid anymore - you should redeclare the Medium model of SprayAirWasher_X to belong to a base class that includes that function, otherwised you can't use it.

**Comment by casella** [comment]
Same problem in Buildings.Controls.Predictors.Examples.BESTEST, see [report](https://libraries.openmodelica.org/branches/newInst/Buildings_latest/files/Buildings_latest_Buildings.Controls.Predictors.Examples.BESTEST.err)

**Comment by casella** [comment]
Same problem in Buildings.Examples.HydronicHeating.TwoRoomsWithStorage, see [report](https://libraries.openmodelica.org/branches/newInst/Buildings_latest/files/Buildings_latest_Buildings.Examples.HydronicHeating.TwoRoomsWithStorage.err)

**Comment by casella** [comment]
Same problem in Buildings.ThermalZones.Detailed.Validation.TestConditionalConstructions.SampledModel.OnlyPartition, see [report](https://libraries.openmodelica.org/branches/newInst/Buildings_latest/files/Buildings_latest_Buildings.ThermalZones.Detailed.Validation.TestConditionalConstructions.SampledModel.OnlyPartition.err)

**Comment by mwetter** [comment]
@casella 
The first error (https://libraries.openmodelica.org/branches/newInst/Buildings_latest/files/Buildings_latest_Buildings.Applications.DataCenters.ChillerCooled.Examples.NonIntegratedPrimarySecondaryEconomizer.err) is I believe an error of OpenModelica as the medium is now redeclared as
```modelica
model SprayAirWasher_X
  "Spray air washer with leaving water mass fraction as input"
  extends Buildings.Fluid.HeatExchangers.BaseClasses.PartialPrescribedOutlet(
    redeclare replaceable package Medium =
        Modelica.Media.Interfaces.PartialCondensingGases,
...
```
The other three reported errors shifted now to another problem. If you agree that the problem is on the OpenModelica side, please close the issue. Otherwise I can pick it up after the holidays.

**Comment by casella** [comment]
It is possible that the Buildings library is not sync-ed correctly on our CI system. I'll check and report

**Comment by casella** [comment]
It seems that the Buildings library is updated correctly, so it is probably a lookup error in the redeclared class. I opened [#5279](https://trac.openmodelica.org/OpenModelica/ticket/5279) on this topic.
