### ISSUE TITLE
Argument initialValues in spatialDistribution must be a parameter expression

### ISSUE THREAD

**Issue by casella** [lbl-srg/modelica-buildings#1293]
https://github.com/lbl-srg/modelica-buildings/blob/6f43ccee834b2b5ab95cd5a3d41d03228cd7f3fc/Buildings/Fluid/FixedResistances/BaseClasses/PlugFlowTransportDelay.mo#L55

`time` is not a parameter expression, which is not allowed in the last input of spatial distribution, see [OMC error report](https://libraries.openmodelica.org/branches/newInst/Buildings_latest/files/Buildings_latest_Buildings.Fluid.FixedResistances.Validation.PlugFlowPipes.PlugFlowAIT.err) I'm not sure if you want to use the initial time of the simulation, in which case you could write something like
```
  parameter SI.Time t_init(fixed = false)
initial equation
  when initial() then
    t_init = time;
  end when;

```
and then use `t_init` instead of `time` in the expression

**Comment by mwetter** [comment]
Closed as this is now fixed on the master branch.
