### ISSUE TITLE
Chiller Examples in OpenModelica give errors

### ISSUE THREAD

**Issue by dgusain1** [lbl-srg/modelica-buildings#1341]
Any example from buildings library that contains Chiller model(chi), fails to translate, and gives

> Variable chi: Cyclically dependent constants or parameters found in scope Buildings.Fluid.Chillers.Carnot_TEva$chi: {COP_nominal,etaCarnot_nominal} (ignore with -d=ignoreCycles).

I tried to introduce the flag -d=ignoreCycles in simulation setup but it still does not work.

**Comment by mwetter** [comment]
This is a bug of OpenModelica as far as I can tell.
