### ISSUE TITLE
Develop templates of HVAC systems

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1374]
This issue is to add a template for a multizone VAV model, using as a starting point `VAVReheat`.

**Comment by AntoineGautier** [comment]
The prototype branch is `issue1374_templateVAV`. 

- It only contains some prototypes of the templates that are developed for Linkage.
- It shall be deleted without being merged at the end of Linkage development phase I.

The feature branch `issue1374_templates` will host the final version of the templates and is intended to be merged into the master.

**Comment by AntoineGautier** [comment]
The main feature branch is `issue1374_templates` (`issue1374_templateVAV` is obsolete).

The development branch for the CHW plant template is `issue1374_template_CHW`.

TODO:

- [ ] Add `__Linkage_Template` annotation to filter out classes not to be exposed in Linkage UI (as described in https://lbl-srg.github.io/linkage.js/requirements.html#class-manipulation-and-workflow).

**Comment by AntoineGautier** [comment]
This ticket has been adressed via #2925. The branch `issue1374_templates` can be deleted.
