### ISSUE TITLE
Weather data file

### ISSUE THREAD

**Issue by Ajboor** [lbl-srg/modelica-buildings#1385]
![image](https://user-images.githubusercontent.com/48720179/54608171-d1444300-4a58-11e9-8a9b-f7c91e44e1b7.png)

Dear All,
If you may help me I want to upload weather data of 3 locations in Jordan / Middle east and I don't know how to upload a weatherdata file that is not available on the building systems library, also if I uploaded it from weather websites it is in excel format.
Thank you in advance.

**Comment by mwetter** [comment]
Please use unmethours.com for questions, as this issue tracker is for bug reports and new feature development. 

See the documentation at 
http://simulationresearch.lbl.gov/modelica/releases/latest/help/Buildings_BoundaryConditions_WeatherData.html#Buildings.BoundaryConditions.WeatherData.ReaderTMY3
for how to add new weather data.
