### ISSUE TITLE
Correct img path

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#1396]
In class `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.SetPoints.SupplyTemperature`, the img location is incorrect and the img `Buildings/Resources/Images/Controls/OBC/ASHRAE/G36_PR1/AHUs/VAVMultiZoneSupTempSet.png` can not be shown.

Correct the path to `Buildings/Resources/Images/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAVSupTempSet.png`

**Comment by milicag** [comment]
Let me push this up with the economizer edits, easy fix.
