### ISSUE TITLE
accessing Buildings.Fluid.MixingVolumes.mixingVolume outside the FMU

### ISSUE THREAD

**Issue by lmblanes** [lbl-srg/modelica-buildings#1411]
Dear Michael

We are dealing with a web app that exposes a fmu where we would like to have the parameter "V" (volume) inside:
 ```
Buildings.Fluid.MixingVolumes.mixingVolume
```
as argument that we can pass values to. 
This I guess is similar to #441  . 

Is that component also structural to the fmu so cannot be changed after fmu is generated?
Thanks in advance for your response.

Luis

**Comment by mwetter** [comment]
@lmblanes : Thanks for reporting. We will change this through https://github.com/ibpsa/modelica-ibpsa/issues/1122 and then merge it to the Buildings library.
