### ISSUE TITLE
Create package for district energy system

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#1437]
This issue is to create a working branch for developing models of district energy system. It is in the scope of [URBANopt project](https://github.com/urbanopt/urbanopt-modelica/blob/master/README.md).

**Comment by AntoineGautier** [comment]
@JayHuLBL Better rename the subpackage `Buildings` as we cannot reference a class from the Buildings library by its full path when developing a model inside that package.
Proposed name: `Loads` (Models for computing thermal loads served by the DES)
