### ISSUE TITLE
Create model to couple a building model and an ETS model

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#1442]
This component is designed as a container with a replaceable class corresponding to the model used to compute the building loads. When using a ROM, the component must typically compute a water mass flow rate and delta T based on a heat flow rate and indoor air temperature. The component is structured with:

- a water volume representing the capacity of the distribution and terminal systems,
- a `UA` block representing the steady state heat exchange of the terminal unit.

**Comment by AntoineGautier** [comment]
To implement on [issue1442_loadCoupling](https://github.com/lbl-srg/modelica-buildings/tree/issue1442_loadCoupling):
- [ ] Thermal diode instead of Heavyside on demand signal
- [ ] Computation of heat transfer based on the effectiveness VS LMTD
- [ ] ODE to convert unmet loads into deltaT for time series
- [ ] Vectorized heat ports

**Comment by AntoineGautier** [comment]
@nllong I merged the master and `issue1129_energyPlus_zone_fmiSignature` in the branch [issue1442_loadCoupling](https://github.com/lbl-srg/modelica-buildings/tree/issue1442_loadCoupling) as discussed this morning. 
See `Buildings.Experimental.EnergyPlus.Validation` for the use of EnergyPlus thermal zone model.

**Comment by nllong** [comment]
Great, thanks!

Il giorno ven 13 set 2019 alle 15:19 Antoine Gautier <
notifications@github.com> ha scritto:

**Comment by AntoineGautier** [comment]
- Update UA dependency to mass flow rate and decomposition of nominal values based on [https://www.osti.gov/servlets/purl/7353](https://www.osti.gov/servlets/purl/7353), used in `Buildings.Fluid.HeatExchangers.BaseClasses.HADryCoil`.
This is on hold:
    - There is no consistency in the Buildings library regarding the computation of convective heat transfer coefficients between the different heat exchanger models.
   - [ ] Donghun wet coil model is under development and will be structured so that the UA computation is done in a Modelica block. This can be directly tested in `HeatingOrCooling`. This should be done in priority.
- [ ] Use annotation to hide conditionally non instantiated objects.
- [ ] Improve PI output signal mapping for room air temperature control: currently relies on `Q_flow_nominal`.
- [ ] Update `PartialBuilding` with outputs for heating and cooling demand by building dedicated systems (not connected to district) as well as electric power.
- [ ] Add some examples with 2 buildings models.

**Comment by AntoineGautier** [comment]
The branch now hosts the refactoring discussed with NREL on 12/13/19. 

It includes `Applications.DHC.Loads.BaseClasses.PartialTerminalUnit` which shall be used to develop the models for the building mechanical systems. The requirements for those developments are to be documented by @AntoineGautier.

To do:

- [ ] Include (conditionally) pump model and mixing three-way valve in `Buildings.Applications.DHC.Loads.BaseClasses.FlowDistribution`: this will extend the physical boundaries of the partial building model to the connections to the primary systems (ETS or dedicated plant).

**Comment by AntoineGautier** [comment]
Closed with [PR1791](https://github.com/lbl-srg/modelica-buildings/pull/1791)
