### ISSUE TITLE
Z value in DryEffectivenessNTU is incorrect

### ISSUE THREAD

**Issue by BrendanSulliv** [lbl-srg/modelica-buildings#1470]
The Z value in the counter-flow effectiveness-NTU heat exchanger seems incorrect. In an example where the mass flow rate is 3 kg/s on one side and starts at 0.1 kg/s on the other. The lower mass flow rate increases linearly from 0.1 kg/s to 3 kg/s. Therefore, Z should start close to 0 then increase to 1. However, in simulation Z starts at 3 and **decreases** to 0.17 which seems incorrect.

I noticed from Issue 1328 that it seemed like Z was irrelevant since it is not used in any calculations but doesn't the Z value determine what the a value will be in the epsilon_ntuZ function?

**Comment by mwetter** [comment]
@BrendanSulliv : Do you have a specific test model that illustrates the problem? The function `Buildings.Fluid.HeatExchangers.BaseClasses.epsilon_C` implements
```
Z := CMin_flow/CMaxNZ_flow+1E-10*deltaCMin;
```
which is correct. Did you set reasonable values for `m_flow_nominal`, which is used for regularization of the function?

**Comment by mwetter** [comment]
Closed as it cannot be reproduced.
