### ISSUE TITLE
add steam model for 1st generation DHC system

### ISSUE THREAD

**Issue by YangyangFu** [lbl-srg/modelica-buildings#1500]
The steam-to-water shell&tube heat exchanger needs steam as a medium.  On the primary side, steam goes in, liquid water comes out.

**Comment by JayHuLBL** [comment]
@YangyangFu Please use branch [issue1437_district_heating_cooling](https://github.com/lbl-srg/modelica-buildings/tree/issue1437_district_heating_cooling/Buildings) as your base branch and add your development in [Buildings.Media.Steam](https://github.com/lbl-srg/modelica-buildings/tree/issue1437_district_heating_cooling/Buildings/Media/Steam) package.

**Comment by YangyangFu** [comment]
The development branch is relocated at issue [#1206](https://github.com/ibpsa/modelica-ibpsa/issues/1206).

**Comment by mwetter** [comment]
I will close this because it is replaced by https://github.com/lbl-srg/modelica-buildings/issues/2304
