### ISSUE TITLE
division 0/0 in LMTD for counter flow with same medium and same mass flow

### ISSUE THREAD

**Issue by damienpicard** [lbl-srg/modelica-buildings#1515]
The function `Buildings.Fluid.HeatExchangers.BaseClasses.lmtd` returns 0/0 when dT1 = dT2 which is the case when a counterflow heat exchanger with the same medium at both side and same flow rates is used.

I propose to adapt the implementation to:
```
if dT1 == dT2 then
    lmtd :=dT1;
  else
    lmtd :=(dT2 - dT1)/Modelica.Math.log(dT2/dT1);
  end if;
```

**Comment by mwetter** [comment]
This would not be robust as it makes the function to be discontinuous. We tried similar tricks on another function and it was not good.

Where is this problem occurring? If I recall correctly, this function is only used in an initial equation section, and hence this would indicate wrong parameter values that can be caught with an assertion.

**Comment by AntoineGautier** [comment]
For information, this article provides a regularization function of LMTD when dT1 is close to dT2 (see Equation 9b):
[https://www.modelica.org/publications/papers/ESS97HEX.pdf](https://www.modelica.org/publications/papers/ESS97HEX.pdf)

However:

- I believe that the implementation which is provided (see Listing 2) does not handle correctly the case where dT1 * dT2 == 0 (it should be the first `if` statement, not a `else if` statement),
- it does not handle the case where dT1 * dT2 < 0 (not physical but numerically possible during the solver iterations).

Eventually I favor the Effectiveness-NTU over the LMTD method as the former inherently guards against the violation of the second Law: from my experience, when using the LMTD method (with whatever formulation covering for the case where dT1 * dT2 < 0) it might happen that the solver indeed converge on a solution where dT1 * dT2 < 0.

**Comment by mwetter** [comment]
I will close this unless there is a need and a test model. The current implementation states "Note that the implementation requires the temperature differences to be non-zero. "
