### ISSUE TITLE
Refactor PrimarySystem.ChillerPlant.Economizer.Subsequences.Tunin

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1537]
`Buildings.Controls.OBC.ASHRAE.PrimarySystem.ChillerPlant.Economizer.Subsequences.Tuning` on branch `issue1378_staging_primarySequences` implements a 1 second sampling time. This will lead to excessive simulation times. 
Can this be implemented with a continuous time implementation?

Also, the info section does not really say what the control intent is, and it is not clear why the `pre` blocks are needed.

**Comment by milicag** [comment]
Will look into this and update the documentation.

**Comment by milicag** [comment]
I'm looking at these `pre` blocks and do not remember why I have them, but without them the response is not as expected. I do remember spending quite a bit of time on this to cover all the border cases. I will look into it.

**Comment by milicag** [comment]
I'm using `pre` blocks in order to capture that last moment while the timer is measuring `enable` time, in the moment the WSE gets disabled and the falling edge signals it, otherwise they miss each other for an infinitesimally small amount of time. I'm also looking into alternatives for this, but I'll prioritize the 1s sampling issue.

**Comment by milicag** [comment]
As the comment in of the block says, it `Defines a tuning parameter for the temperature prediction downstream of WSE`. Should I add a more elaborate description? There really isn't that much to it, there is a temperature prediction subsequence, which uses the tuning parameter, and the tuning parameter comes from the `Tuning` sequence. I'm also not sure if we can break an algebraic loop involving real numbers without some sort of sampling, although it does work for boolean values using `pre`. Do you have a suggestion or a similar example?

**Comment by milicag** [comment]
I can use the `UnitDelay`, which we also use in `TrimAndRespond`. Would that be any better than the `ZeroOrderHold`? It does not get rid of the sampling though.

**Comment by milicag** [comment]
merged into chiller plant controller staging branch
