### ISSUE TITLE
Fluid boundaries not working with ideal gas mixtures

### ISSUE THREAD

**Issue by justnielsen** [lbl-srg/modelica-buildings#1543]
I am trying to use Modelica Buildings with MSL mixture gasses. 

In the simples possible case I connect a mass flow source to a pressure sink and use `Modelica.Media.IdealGases.MixtureGases.FlueGasSixComponents`. 

```
model SourceToSink
  package Medium = Modelica.Media.IdealGases.MixtureGases.FlueGasSixComponents;
  Buildings.Fluid.Sources.MassFlowSource_T boundary(redeclare package Medium = Medium, nPorts=1);
  Buildings.Fluid.Sources.Boundary_pT bou(redeclare package Medium = Medium, nPorts=1);
equation 
  connect(boundary.ports[1], bou.ports[1]);
end SourceToSink;
```

This gives a model with 26 equations and 25 unknowns.

Looking into `Buildings.Fluid.Sources.BaseClasses.PartialSource_Xi_C.mo`, I see some problems around the lines

```
if not use_X_in then
  X_in_internal[1:Medium.nXi] = Xi_in_internal[1:Medium.nXi];
  X_in_internal[Medium.nX] = 1-sum(X_in_internal[1:Medium.nXi]);
end if;
```

Since I have chosen not to use an external mass fraction input, I would expect a connection between `X_in_internal` and `X`. If I replace the two lines in the if statement with
`X_in_internal = X` (like in the Modelica.Fluid.Sources) the model works.

Also, if I specify the `X` as an internal input vector in the simple model above, it fails to work.

**Comment by mwetter** [comment]
@justnielsen : Thanks for reporting. I can reproduce this bug and will correct it through https://github.com/ibpsa/modelica-ibpsa/issues/1205

**Comment by justnielsen** [comment]
@mwetter : Thank you for looking into the problem.
