### ISSUE TITLE
Implement latent heat gain to air volume for ReducedOrder.RC

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#1549]
`Buildings.ThermalZones.ReducedOrder.RC` models do not account for latent heat gain from people.
This is to implement that missing part with the same logic as the one used in `Buildings.ThermalZones.Detailed.MixedAir`: water stream input into the air volume.

- Agreement with IDEAS developers is needed regarding the suitable unit: kg/s, W, W/m2
- Consistency of input unit must be ensured within the Buildings library: `Buildings.ThermalZones.Detailed.MixedAir` currently uses W/m2.

**Comment by mlauster** [comment]
This should be modified within the IBPSA library, since this model was developed there

**Comment by KremerMartin** [comment]
@AntoineGautier Maybe you can take a look at the AixLib. We implemented the moisture balance to the ReducedOrder model in issue [695](https://github.com/RWTH-EBC/AixLib/issues/695). We tackled also the issue regarding the latent heat output of people. (see also issue [690](https://github.com/RWTH-EBC/AixLib/issues/690) in Aixlib) 
I have opened an issue in the IBPSA [1209](https://github.com/ibpsa/modelica-ibpsa/issues/1209) concerning the RC-model. If you have suggestions on the solution, let me know there. Maybe we can do a joint attempt.

**Comment by AntoineGautier** [comment]
@mwetter Should we merge the developments from [https://github.com/ibpsa/modelica-ibpsa/issues/1209](https://github.com/ibpsa/modelica-ibpsa/issues/1209) into `Buildings`?

**Comment by mwetter** [comment]
@AntoineGautier : This code is already on the `master` branch of the Buildings library.
I will close this issue.
