### ISSUE TITLE
add epsilon-NTU cooling tower model

### ISSUE THREAD

**Issue by YangyangFu** [lbl-srg/modelica-buildings#1556]
Add a Merkel-theory based cooling tower model to support chiller plant modeling.

@mwetter Dr. Wetter, can you make a new branch for this issue?

**Comment by mwetter** [comment]
I merged the code to `issue1556_ntu_coolTower`.

A quick inspection showed the following:
- [ ] Most `.mo` files have no `info` and `revision` section, these need to be added.
- [ ] https://github.com/lbl-srg/modelica-buildings/blob/issue1556_ntu_coolTower/Buildings/Fluid/HeatExchangers/CoolingTowers/Examples/Merkel.mo has an info and revision section but these are simply a copy of another model and must be updated.
- [ ] Modelica classes must be renamed to comply with the coding convention.
- [ ] A validation model must be added, such as for cross comparison with EnergyPlus.

**Comment by khinkelman** [comment]
@YangyangFu I'm looking into Merkel's theory and it appears the equivalent specific heat is a function of wet-bulb temperature, not dry-bulb temperature, as we have currently implemented in our model. Should this be revised?
[Relevant Function](https://github.com/lbl-srg/modelica-buildings/blob/issue1556_ntu_coolTower/Buildings/Fluid/HeatExchangers/CoolingTowers/BaseClasses/Functions/cpe.mo)
[E+ Reference](https://www.energyplus.net/sites/default/files/docs/site_v8.3.0/EngineeringReference/13c-EncyclopaedicRefs/index.html)

**Comment by YangyangFu** [comment]
Not necessary. It could be any temperature. The function is called `TDry` but you can set the `TDry` to `TWetBul` in cooling towers based on the cooling tower type.
