### ISSUE TITLE
Specifies the initial return water temperature for the secondary loop

### ISSUE THREAD

**Issue by JIEZHUZED** [lbl-srg/modelica-buildings#1569]
There's a small question.

For example ,when I simulation the model:
Buildings.Fluid.HeatExchangers.Examples.DryCoilCounterFlowPControl
hex.sta_b1.T start changing from 20 degrees(Medium1.T_default),

But if I need an initial return water temperature of 12 degrees, I may need to change the underlying model(Fluid.HeatExchangers.BaseClasses.HexElementSensible.T1_start) or initial values in dsin.txt.

It may be  set initialization parameters to be visible in the top-level model.
If there is a better way, please recommend it to me.
Thank you very much!

**Comment by mwetter** [comment]
You could set
```modelica
  Buildings.Fluid.HeatExchangers.WetCoilCounterFlow hex(
    redeclare package Medium1 = Medium1 (T_default=273.15 + 12),
    redeclare package Medium2 = Medium2,
...
```
