### ISSUE TITLE
Remove unnecessary graphics annotations

### ISSUE THREAD

**Issue by justnielsen** [lbl-srg/modelica-buildings#1605]
The entire icon graphics annotion of `Fluid.Actuators.BaseClasses.PartialTwoWayValveKv` and `Fluid.Actuators.Valves.TwoWayPressureIndependent` can be removed since their icons are already drawn in the baseclass `Fluid.Actuators.BaseClasses.PartialTwoWayValve`

**Comment by JayHuLBL** [comment]
@justnielsen Thanks for reporting the issues (#1600, #1601, #1602, #1603, #1604, #1605). They will be addressed through ibpsa library (https://github.com/ibpsa/modelica-ibpsa/issues/1225) and then merge to here.
