### ISSUE TITLE
Add indirect cooling energy transfer station for district energy applications

### ISSUE THREAD

**Issue by khinkelman** [lbl-srg/modelica-buildings#1614]
Add indirect cooling ETS model for district energy 

@mwetter, could you please create a branch for this issue? Also, could you please confirm where you would like to locate the DHC work in the buildings library? (e.g. Applications.DHC.EnergyTransferStations, or Experimental package for now?) 

Thanks

**Comment by mwetter** [comment]
@khinkelman :
I made the branch `issue1614_ets_indirectCooling` based on the master.

 Please put the models into `Buildings/Applications/DHC/EnergyTransferStations` which is then consistent with
https://github.com/lbl-srg/modelica-buildings/tree/issue1437_district_heating_cooling/Buildings/Applications/DHC/EnergyTransferStations

**Comment by khinkelman** [comment]
This ETS model will be refactored based on  #2310. I new issue will be created at a later date for these non-backward compatible changes.
