### ISSUE TITLE
prescribedHeatFlowRate=false in solarcollector if energyDynamics=SteadyState

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/modelica-buildings#1636]
When `energyDynamics=SteadyState`, the solar collector should have `prescribedHeatFlowRate=false` since the mixing volume temperature is computed from an algebraic loop. The heat flow rate is the iteration variable and the following equation becomes a residual equation:
```Modelica
port_b.h_outflow = inStream(port_a.h_outflow) + Q_flow * m_flowInv
```

since `Q_flow` is multiplied by zero for zero flow rate, the residual equation is satisfied for any value of Q, which leads to premature convergence of the solution and:
```
Error: The following error was detected at time: 0
  In EN12975NPanels.solCol.vol[1].steBal:
   The heat flow rate equals -7.28076 W and the mass flow rate equals 0 kg/s,
   which results in a temperature difference 167841 K > dTMax=200 K.
   This may indicate that energy is not conserved for small mass flow rates.
   The implementation may require prescribedHeatFlowRate = false.
  Failed condition: noEvent(abs(solCol.vol[1].heatPort.Q_flow) < 0.008675791775999999)
```

I propose to set `prescribedHeatFlowRate= not energyDynamics==SteadyState` such that the residual equation becomes

```Modelica
0 = solCol.heaLos.QLos[10]+solCol.vol[10].dynBal.ports_H_flow[1]+
      solCol.vol[10].dynBal.ports_H_flow[2]+solCol.solGai.QSol_flow[10];
```

**Comment by mwetter** [comment]
@Mathadon : I don't quite understand why you set
`prescribedHeatFlowRate= not energyDynamics==SteadyState` rather than simply
`prescribedHeatFlowRate=false`, because `prescribedHeatFlowRate` is only used for the steady-state balance. Your assignment sets this `false` for the steady state model, but `true` for the dynamic model.

I suggest to simply use `prescribedHeatFlowRate=false`. Do you agree?

**Comment by Mathadon** [comment]
Indeed. The rationale was that the flow rate is prescribed when temperature is a state, since the heat flow rate is computed explicitly from the temperature state, but I forgot that `prescribedHeatFlowRate` is not used in the `ConservationEquation` so it actually does not matter.
