### ISSUE TITLE
Initial temperatures of stratified tanks

### ISSUE THREAD

**Issue by justnielsen** [lbl-srg/modelica-buildings#1644]
### Feature request
In district heating simulation it is often useful to specify an initial charge of a heat storage tank (`Buildings.Fluid.Storage.Stratified*`) — that is individual temperatures for the `nSeg` tank segments to form a temperature profile. However, in `Buildings.Fluid.Storage.BaseClasses.PartialStratified` the same initial temperature `T_start` is assigned to all `nSeg` volumes.

To be able to assign different initial temperatures to the individual segments, `T_start` must be a an array of `nSeg` temperatures. This could give some problems with backward compatibility unless

- a new parameter is introduced, e.g. `parameter Modelica.SIunits.Temperature[nSeg] T_start_profile = T_start*ones(nSeg)` or
- the existing `T_start` scalar parameter can be automatically replaced with `T_start*ones(nSeg)` in a  conversion script

**Comment by mwetter** [comment]
@JayHuLBL : Can you please implement 
`parameter Modelica.SIunits.Temperature[nSeg] TFlu_start = T_start*ones(nSeg)`
This would be backward compatible. Please do so on the `IBPSA` library as the model is from there.

**Comment by JayHuLBL** [comment]
@justnielsen It will be addressed in IBPSA library [#1246](https://github.com/ibpsa/modelica-ibpsa/issues/1246) and then merge to here.

**Comment by mwetter** [comment]
This is now on the master branch of the Buildings library.
