### ISSUE TITLE
Update of DynamicSelect() annotation

### ISSUE THREAD

**Issue by justnielsen** [lbl-srg/modelica-buildings#1647]
It is often nice to show values of selected variables in the diagram view rather than plotting them.
However, when I add a component using DynamicSelect() annotation to display the value of a variable it only displays the value at time=0 s and not the final value. 

For example, I do the following

1. Add a `Modelica.Blocks.Interaction.Show.RealValue` to `Buldings.Fluid.Actuators.Valves.Examples.TwoWayValves`
2. connect it to `valLin.y_actual` 
3. run the simulation

When i plot the valve position i the 'Simulation' window in Dymola 2020 it shows a ramp ending in 1.0. The value shown on the `RealValue` component is 0 in the diagram view.

I've only encountered the problem in Modelica Buildings. Adding `RealValue` components to (copies of) models from MSL works as expected.

![TwoWayValves](https://user-images.githubusercontent.com/5364451/68849675-cb2f6080-06d2-11ea-932b-c07f35373579.png)

### Edit
Apparently, the problem solved itself. Now, the graphical readouts work as expected and I have no clue why. Is there anyway the update frequency of the `DynamicSelect()` can be controlled in Dymola 🤔

**Comment by mwetter** [comment]
I don't think you can update the frequency of `DynamicSelect()`, but this would be a question to the Dymola developers.
