### ISSUE TITLE
District Energy - Direct Cooling Energy Transfer Station

### ISSUE THREAD

**Issue by khinkelman** [lbl-srg/modelica-buildings#1662]
Add new models for direct cooling energy transfer stations based on standard ASHRAE defined configurations. 

Hi @JayHuLBL, could you please create a new branch for this issue from the staging branch `issue1437_district_heating_cooling`?

**Comment by khinkelman** [comment]
Two new models proposed: 
- [ ] CoolingDirect - with in-building pumping
- [ ] CoolingDirect - without in-building pumping

**Comment by JayHuLBL** [comment]
@khinkelman 
The branch `issue1437_1662_ets_directCooling` was created based on urbanOpt staging branch `issue1437_district_heating_cooling`. Please work on your developments based on the new branch.

**Comment by khinkelman** [comment]
This ETS model will be refactored based on  #2310. I new issue will be created at a later date for these non-backward compatible changes.
