### ISSUE TITLE
Incompatible sizes for variables and its definition equations in the reduced order thermal zone model

### ISSUE THREAD

**Issue by LXUtue** [lbl-srg/modelica-buildings#1667]
I receive an error when using `Buildings.ThermalZones.ReducedOrder.RC.ThreeElements` and `Buildings.ThermalZones.ReducedOrder.RC.FourElements` model. If I assign different values for the number of RC-elements of floor, roof and external wall, I'll receive an error message saying 'Incompatible sizes for variables and its definition equations'. I believe there's a typo in the code below. It should be `nFloor` and `nRoof` for floor and roof respectively, instead of `nExt`.
`parameter Modelica.SIunits.ThermalResistance RFloor[nExt]`
`parameter Modelica.SIunits.HeatCapacity CFloor[nExt]`
`parameter Modelica.SIunits.ThermalResistance RRoof[nExt]`
`parameter Modelica.SIunits.HeatCapacity CRoof[nExt]`

Please kindly confirm if this is correct.

**Comment by mlauster** [comment]
@LXUtue, thanks for identifying this, most definitely an error! Need to be solved in IBPSA lib, I will open an issue!

**Comment by mwetter** [comment]
This has been fixed on the master branch.
