### ISSUE TITLE
Tutorial Examples do not work on OMEdit

### ISSUE THREAD

**Issue by sohertz** [lbl-srg/modelica-buildings#1676]
I load the latest "Buildings" library available in OMEdit (v6.0.0) and load Tutorial.Boiler.System1. No problem to check or simulate the system. The simulation provides the expected results. 

But I have problems with Tutorial.Boiler.System2 (and above). No problem to open the system but I get following error message when I click on "Simulate" button. Do you have any clue what I could do to solve this?

From the warning window:
> [1] 15:18:38 Skripting Meldung
> Check of Buildings.Examples.Tutorial.Boiler.System2 completed successfully.
> 
> [1] 15:18:49 Symbolisch Warnung
> The model contains alias variables with conflicting start and/or nominal values. It is recommended to resolve the conflicts, because otherwise the system could be hard to solve. To print the conflicting alias sets and the chosen candidates please use -d=aliasConflicts.

From the Compiling Window:

> C:/Program Files/OpenModelica1.14.0-64bit//share/omc/scripts/Compile.bat Buildings.Examples.Tutorial.Boiler.System2 gcc mingw64 parallel 2 0
> PATH = "C:\PROGRA~ 1\OpenModelica1.14.0-64bit\tools\msys\mingw64\bin;C:\PROGRA~1\OpenModelica1.14.0-64bit\tools\msys\mingw64\bin\..\..\usr\bin;"
> mingw32-make: Entering directory 'C:/Users/admin/AppData/Local/Temp/OpenModelica/OMEdit/Buildings.Examples.Tutorial.Boiler.System2'
> gcc  -Os -falign-functions -fno-ipa-pure-const -mstackrealign -msse2 -mfpmath=sse     -I"C:/Program Files/OpenModelica1.14.0-64bit//include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=Buildings_Examples_Tutorial_Boiler_System2 -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=8 -DOMC_NUM_NONLINEAR_SYSTEMS=2 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0  -c -o Buildings.Examples.Tutorial.Boiler.System2.o Buildings.Examples.Tutorial.Boiler.System2.c
> gcc  -Os -falign-functions -fno-ipa-pure-const -mstackrealign -msse2 -mfpmath=sse     -I"C:/Program Files/OpenModelica1.14.0-64bit//include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=Buildings_Examples_Tutorial_Boiler_System2 -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=8 -DOMC_NUM_NONLINEAR_SYSTEMS=2 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0  -c -o Buildings.Examples.Tutorial.Boiler.System2_functions.o Buildings.Examples.Tutorial.Boiler.System2_functions.c
> In file included from Buildings.Examples.Tutorial.Boiler.System2_model.h:24:0,
>                  from Buildings.Examples.Tutorial.Boiler.System2.c:7:
> Buildings.Examples.Tutorial.Boiler.System2.c: In function 'Buildings_Examples_Tutorial_Boiler_System2_eqFunction_1272':
> Buildings.Examples.Tutorial.Boiler.System2_functions.h:32:100: error: too few arguments to function 'Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars_p'
>  #define Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)
>                                                                                                     ^
> Buildings.Examples.Tutorial.Boiler.System2.c:390:3: note: in expansion of macro 'Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars'
>    Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars(tmp1, &(data->localData[0]->realVars[34] /* $cse13.p variable */), &(data->localData[0]->realVars[33] /* $cse13.T variable */));;
>    ^
> Buildings.Examples.Tutorial.Boiler.System2_functions.h:31:6: note: declared here
>  void Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T, real_array* in_X);
>       ^
> Buildings.Examples.Tutorial.Boiler.System2.c: In function 'Buildings_Examples_Tutorial_Boiler_System2_eqFunction_1273':
> Buildings.Examples.Tutorial.Boiler.System2.c:402:157: error: too few arguments to function 'omc_Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState'
>    data->localData[0]->realVars[204] /* temSup.T_b_inflow variable */ = omc_Buildings_Examples_Tutorial_Boiler_System2_temSup_Medium_temperature(threadData, omc_Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState(threadData, data->localData[0]->realVars[34] /* $cse13.p variable */, data->localData[0]->realVars[33] /* $cse13.T variable */));
>                                                                                                                                                              ^
> In file included from Buildings.Examples.Tutorial.Boiler.System2_model.h:24:0,
>                  from Buildings.Examples.Tutorial.Boiler.System2.c:7:
> Buildings.Examples.Tutorial.Boiler.System2_functions.h:200:70: note: declared here
>  Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState omc_Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T, real_array omc_X);
>                                                                       ^
> In file included from Buildings.Examples.Tutorial.Boiler.System2_model.h:24:0,
>                  from Buildings.Examples.Tutorial.Boiler.System2.c:7:
> Buildings.Examples.Tutorial.Boiler.System2.c: In function 'Buildings_Examples_Tutorial_Boiler_System2_eqFunction_1306':
> Buildings.Examples.Tutorial.Boiler.System2_functions.h:32:100: error: too few arguments to function 'Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars_p'
>  #define Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)
>                                                                                                     ^
> Buildings.Examples.Tutorial.Boiler.System2.c:868:3: note: in expansion of macro 'Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars'
>    Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars(tmp21, &(data->localData[0]->realVars[36] /* $cse14.p variable */), &(data->localData[0]->realVars[35] /* $cse14.T variable */));;
>    ^
> Buildings.Examples.Tutorial.Boiler.System2_functions.h:31:6: note: declared here
>  void Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T, real_array* in_X);
>       ^
> Buildings.Examples.Tutorial.Boiler.System2.c: In function 'Buildings_Examples_Tutorial_Boiler_System2_eqFunction_1307':
> Buildings.Examples.Tutorial.Boiler.System2.c:880:157: error: too few arguments to function 'omc_Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState'
>    data->localData[0]->realVars[203] /* temSup.T_a_inflow variable */ = omc_Buildings_Examples_Tutorial_Boiler_System2_temSup_Medium_temperature(threadData, omc_Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState(threadData, data->localData[0]->realVars[36] /* $cse14.p variable */, data->localData[0]->realVars[35] /* $cse14.T variable */));
>                                                                                                                                                              ^
> In file included from Buildings.Examples.Tutorial.Boiler.System2_model.h:24:0,
>                  from Buildings.Examples.Tutorial.Boiler.System2.c:7:
> Buildings.Examples.Tutorial.Boiler.System2_functions.h:200:70: note: declared here
>  Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState omc_Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T, real_array omc_X);
>                                                                       ^
> In file included from Buildings.Examples.Tutorial.Boiler.System2_model.h:24:0,
>                  from Buildings.Examples.Tutorial.Boiler.System2.c:7:
> Buildings.Examples.Tutorial.Boiler.System2.c: In function 'Buildings_Examples_Tutorial_Boiler_System2_eqFunction_1331':
> Buildings.Examples.Tutorial.Boiler.System2_functions.h:32:100: error: too few arguments to function 'Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars_p'
>  #define Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)
>                                                                                                     ^
> Buildings.Examples.Tutorial.Boiler.System2.c:1180:3: note: in expansion of macro 'Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars'
>    Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars(tmp26, &(data->localData[0]->realVars[45] /* $cse7.p variable */), &(data->localData[0]->realVars[44] /* $cse7.T variable */));;
>    ^
> Buildings.Examples.Tutorial.Boiler.System2_functions.h:31:6: note: declared here
>  void Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T, real_array* in_X);
>       ^
> Buildings.Examples.Tutorial.Boiler.System2.c: In function 'Buildings_Examples_Tutorial_Boiler_System2_eqFunction_1332':
> Buildings.Examples.Tutorial.Boiler.System2.c:1192:164: error: too few arguments to function 'omc_Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState'
>    data->localData[0]->realVars[196] /* sin.ports[1].h_outflow variable */ = omc_Buildings_Examples_Tutorial_Boiler_System2_sin_Medium_specificEnthalpy(threadData, omc_Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState(threadData, data->localData[0]->realVars[45] /* $cse7.p variable */, data->localData[0]->realVars[44] /* $cse7.T variable */));
>                                                                                                                                                                     ^
> In file included from Buildings.Examples.Tutorial.Boiler.System2_model.h:24:0,
>                  from Buildings.Examples.Tutorial.Boiler.System2.c:7:
> Buildings.Examples.Tutorial.Boiler.System2_functions.h:200:70: note: declared here
>  Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState omc_Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T, real_array omc_X);
>                                                                       ^
> In file included from Buildings.Examples.Tutorial.Boiler.System2_model.h:24:0,
>                  from Buildings.Examples.Tutorial.Boiler.System2.c:7:
> Buildings.Examples.Tutorial.Boiler.System2.c: In function 'Buildings_Examples_Tutorial_Boiler_System2_eqFunction_1336':
> Buildings.Examples.Tutorial.Boiler.System2_functions.h:32:100: error: too few arguments to function 'Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars_p'
>  #define Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)
>                                                                                                     ^
> Buildings.Examples.Tutorial.Boiler.System2.c:1247:3: note: in expansion of macro 'Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars'
>    Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars(tmp29, &(data->localData[0]->realVars[29] /* $cse1.p variable */), &(data->localData[0]->realVars[28] /* $cse1.T variable */));;
>    ^
> Buildings.Examples.Tutorial.Boiler.System2_functions.h:31:6: note: declared here
>  void Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T, real_array* in_X);
>       ^
> Buildings.Examples.Tutorial.Boiler.System2.c: In function 'Buildings_Examples_Tutorial_Boiler_System2_eqFunction_1337':
> Buildings.Examples.Tutorial.Boiler.System2.c:1259:164: error: too few arguments to function 'omc_Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState'
>    data->localData[0]->realVars[200] /* sou.ports[1].h_outflow variable */ = omc_Buildings_Examples_Tutorial_Boiler_System2_sou_Medium_specificEnthalpy(threadData, omc_Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState(threadData, data->localData[0]->realVars[29] /* $cse1.p variable */, data->localData[0]->realVars[28] /* $cse1.T variable */));
>                                                                                                                                                                     ^
> In file included from Buildings.Examples.Tutorial.Boiler.System2_model.h:24:0,
>                  from Buildings.Examples.Tutorial.Boiler.System2.c:7:
> Buildings.Examples.Tutorial.Boiler.System2_functions.h:200:70: note: declared here
>  Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState omc_Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T, real_array omc_X);
>                                                                       ^
> <builtin>: recipe for target 'Buildings.Examples.Tutorial.Boiler.System2.o' failed
> mingw32-make: *** [Buildings.Examples.Tutorial.Boiler.System2.o] Error 1
> mingw32-make: *** Waiting for unfinished jobs....
> mingw32-make: Leaving directory 'C:/Users/admin/AppData/Local/Temp/OpenModelica/OMEdit/Buildings.Examples.Tutorial.Boiler.System2'
> Compilation process failed. Exited with code 2.

**Comment by mwetter** [comment]
This is due to OpenModelica not completely supporting the Buildings library yet. The OpenModelica team is working on getting coverage and are testing their development with the Buildings library.

I will close the issue.
