### ISSUE TITLE
Update EnergyPlus to write UnitDefinitions in modelDescription.xml, then activate unit conversion

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1680]
Activate unit conversion after Kyle implements `UnitDefinitions` in modelDescription.xml. To activate unit conversion, search EnergyPlusUtil.c for "fixme"

**Comment by kbenne** [comment]
@mwetter here are the unit definitions that I have defined based on the table located in the documentation, https://lbl-srg.github.io/soep/softwareArchitecture.html#unit-system All of the variables will be associated with one of these unit definitions in the spawn modelDescription.xml. If you think I have made an error then here would be a good place to discuss before I commit to code. There are a number of dimensionless quantities in the table, and for those variables I expect them to use the unit name "1". 

  <UnitDefinitions>
    <Unit name="1"/>
    <Unit name="rad">
      <BaseUnit/>
      <DisplayUnit name="rad"/>
      <DisplayUnit name="deg" factor="57.29577951308232"/>
    </Unit>
    <Unit name="J">
      <BaseUnit kg="1" m="2" s="-2"/>   
    </Unit>                                
    <Unit name="lm/m2">                      
      <BaseUnit cd="1" m="-2"/>       
      <DisplayUnit name="lm/m2"/>
      <DisplayUnit name="lux"/>                           
    </Unit>
    <Unit name="cd.sr">
      <BaseUnit cd="1"/>       
      <DisplayUnit name="cd.sr"/>
      <DisplayUnit name="lum"/>
    </Unit>
    <Unit name="kg/s"> 
      <BaseUnit kg="1" s="-1"/>
    </Unit>
    <Unit name="W">
      <BaseUnit kg="1" m="2" s="-3"/>
    </Unit>
    <Unit name="Pa">
      <BaseUnit kg="1" m="-1" s="-2"/>
    </Unit>
    <Unit name="K"> 
      <BaseUnit K="1"/>               
      <DisplayUnit name="K"/>  
      <DisplayUnit name="degC" offset="-273.15"/>
    </Unit>
    <Unit name="s">
      <BaseUnit s="1"/>
    </Unit>                  
    <Unit name="m3/s">                           
      <BaseUnit m="3" s="-1"/> 
    </Unit>        
  </UnitDefinitions>

**Comment by kbenne** [comment]
Also. I need to add a unit m2 unit to support area, and I don't believe that is in the documentation table.

**Comment by mwetter** [comment]
@kbenne :  These look good to me, and please add `m2`. On that note, please check if `W/m2` need to be added for some EnergyPlus output variables.

**Comment by kbenne** [comment]
I found a few more we could support after implementing an algorithmic search for all output variables and their units. If you want to document these you can.

"Environmental Impact Electricity Water Consumption Volume","L"
"Zone Thermal Comfort Clothing Value","clo" 
"Environmental Impact Electricity Nuclear Low Level Waste Volume","m3"

The full set of units related to output variables are these.

"C", "kgWater/kgDryAir", "%", "Pa", "m/s", "deg", "W/m2", "m", "J/kg", "kg/m3", "lux", "lum/W", "W", "J", "m2", "rad", "W/m2-K", "clo", "hr", "kg", "L", "m3"

**Comment by kbenne** [comment]
Some of these should perhaps be culled. I would have no problem just removing them from the support list of output variables.

**Comment by mwetter** [comment]
On the Modelica side, we want to convert hr to s and l to m3

**Comment by kbenne** [comment]
Addressed in https://github.com/NREL/Spawn/commit/93bc067239f01c70433820b71964383e4f47a3a2
