### ISSUE TITLE
Support in EnergyPlus reading output variable "Zone Mean Air Temperature"

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1681]
Support reading output variable "Zone Mean Air Temperature". This need to be supported on the EnergyPlus side. Modelica currently issues an assertion to guard against reading this output. This was added in commit d6669ad

**Comment by kbenne** [comment]
I made a correction to address this here: https://github.com/NREL/Spawn/commit/1c30973de2eca5a73980614e7f923413d88cbf6c

There appears to be a lag of two timesteps though, so I am not ready to close this issue.

**Comment by kbenne** [comment]
I made a second correction to addressing lagging here https://github.com/NREL/Spawn/commit/a61f2b305731caa6831a6eefaa5ea156b3ce6c1a

As the commit message describes, the "zone mean air temperature" output variable will still only be updated when time crosses a zone timestep. @mwetter I'm guessing that what you want is for the output variables to be update immediately given the current inputs, is that correct? I can make another commit to definitively make that happen for "zone mean air temperature" but there might be a whack a mole situation as I go down this road as there is not one centralized function or method call to update all report variables.

**Comment by mwetter** [comment]
@kbenne : Yes, the output should be updated for the current input variables.

**Comment by kbenne** [comment]
https://github.com/NREL/Spawn/commit/e443d634ab4f15d5d69e487fcc206c7d4f403353
