### ISSUE TITLE
Jmodelica no longer open-source, is there a plan to support other open-source Modelica compilers?

### ISSUE THREAD

**Issue by zhangzhizza** [lbl-srg/modelica-buildings#1686]
As published in https://jmodelica.org/ website, Modelon no longer makes the Jmodelica compilers open-source. It is a big loss for open-source community. Is there a plan for modelica-buildings library to support other open-source Modelica compilers?

**Comment by mwetter** [comment]
@zhangzhizza Please see https://simulationresearch.lbl.gov/modelica/environments.html regarding simulation environments.
