### ISSUE TITLE
wrong computation of activePower?

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#171]
PowerSystems.PhaseSystems.ThreePhase_dq and the District library implement the following:
```
  redeclare function phasePowers_vi "Return phase powers"
    extends Modelica.Icons.Function;
    input SI.Voltage v[n] "phase voltages";
    input SI.Current i[n] "phase currents";
    output SI.Power p[n] "phase powers";
  algorithm 
    p := {v*i, -j(v)*i};
  end phasePowers_vi;

  redeclare function activePower 
    "Return total power as function of phase powers"
    extends Modelica.Icons.Function;
    input SI.Voltage v[n] "phase voltages";
    input SI.Current i[n] "phase currents";
    output SI.ActivePower P "active system power";
  algorithm 
    P := v[1]*i[1];
  end activePower;
```
Shouldn't activePower compute `P := v*i`? This applies to
`Districts/Electrical/PhaseSystems/ThreePhase_dq/package.mo`,
`Districts/Electrical/PhaseSystems/ThreePhase_dqo/package.mo` and to the 
PowerSystems library.

See also http://www.openelectrical.org/wiki/index.php?title=Dq0_Transform

**Comment by mbonvini** [comment]
These implementation come from the PowerSystem library and is related to the fact that the components of the voltage vectors are in the dq or dq0 representation (not the usual phasors).
The models in the Buildings.Electrical package use the OnePhase package and in this package the power is computed as you said

ActivePower
P := v*i (= v[1]*i[1] + v[2]*i[2])

ComplexPower
p := {v[1]*i[1] + v[2]*i[2], v[2]*i[1] - v[1]*i[2]};
