### ISSUE TITLE
Correct positive maximum cooling

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#1712]
In model `Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case640`, 
```
peakCoo(Min= -5.892*1000, Max = 6.776*1000, Mean= -6.410 * 1000)));
```
The peak cooling maximum value should be negative as well, so `Max = 6.776*1000,` should be `Max = -6.776*1000,`.

**Comment by mwetter** [comment]
Closed as this is now on the master.
