### ISSUE TITLE
Error with  european weather data in TMY3 reader 

### ISSUE THREAD

**Issue by PhilippZofer** [lbl-srg/modelica-buildings#1735]
Dear Buildings-Team,

the block _Buildings.BoundaryConditions.WeatherData.ReaderTMY3_ raises an error if converted european weather data from energyplus.net are used.

**Setup**:

- Dymola 2020x
- Buildings Library version 7.0.0

**Steps to reproduce:**

1. Following the instruction "Adding new weather data" from the documentation of the ReaderTMY3 model
    1.  Downloaded the weather data file with the epw extension from http://energyplus.net/weather
    1. Convert via command window the epw file to mos `java -jar ../bin/ConvertWeatherData.jar inputFile.epw`
1. use the .mos file as input file for the block _Buildings.BoundaryConditions.WeatherData.ReaderTMY3_ 
1. simulate the model

**Error message:**

![2020-02-03 11_14_32-WeatherReaderTestGER - WeatherDataCheck WeatherReaderTestGER  -  Diagram](https://user-images.githubusercontent.com/51989887/73646041-de6e1e80-4678-11ea-87da-23f8d299185f.png)

**Locations raising this error:**

- FRA_Strasbourg
- DEU_Munich
- AUT_Innsbruck

**Locations working just fine:**

- USA_WY_Laramie
- MAR_Casablanca
- NZL_Wellington
- RUS_Yakutsk

Strange enough, after a few times trying to simulate a model with european weather data it suddenly works and the mentioned .mat file for the error message was produced...

Is this an already known issue and are there any known workarounds?

Thank you already in advance.
Best regards,
Philipp

**Comment by mwetter** [comment]
Philipp

I tested it with
https://energyplus.net/weather-download/europe_wmo_region_6/DEU//DEU_Munich.108660_IWEC/DEU_Munich.108660_IWEC.epw
and
the model Buildings.BoundaryConditions.WeatherData.Examples.ReaderTMY3
works fine with this weather file with Dymola, OPTIMICA and JModelica.

If the problem persists, please let me know what Modelica environment you
use and share a model and weather file that reproduces the problem.

All the best,

Michael

**Comment by PhilippZofer** [comment]
Hi Michael,

thank you for testing the issue and providing a feedback. Unfortunately the error cannot be reproduced deterministically. 
Nonetheless you can find my testing package here: [WeatherDataCheck.zip](https://github.com/lbl-srg/modelica-buildings/files/4190810/WeatherDataCheck.zip) - it includes Modelica test models and the used weather data. The models should work if you add the unziped folder to the standard Dymola workdir (C:\Users\<UserName>\Documents\Dymola).

The model using the .mos file provided by your link (`WeatherDataCheck.WeatherReaderTestGER_mwetter`) did not fail once, even the content of the .mos file is the same as the one I used in `WeatherDataCheck.WeatherReaderTestGER`, which failed before.

Most of the time the erorr occured if I used the following steps:

1. starting a new Dymola instance 
1. loading the _Buildings_ package.mo
1. loading my _WeatherDataCheck_ package.mo, loacated in the standard Dymola workdir 
1. Using the standard Dymola workdir as actual workdir
1. simulate one of the models using the above mention weather data e.g. `WeatherDataCheck.WeatherReaderTestFRA` or `WeatherDataCheck.WeatherReaderTestGER`

Setup:

- Dymola 2020x with the this [ListOfVariables.txt](https://github.com/lbl-srg/modelica-buildings/files/4190861/ListOfVariables.txt)
- MSL 3.2.3
- Buildings Library 7.0.0
- Compiler

Maybe you could give the models a try? If the error does not occure would it be possible for you to share your Dymola setup so I could give this setup a try at my machine?

Thank you already in advance!

Best regards,
Philipp

**Comment by mwetter** [comment]
Hi Philipp

It is unlikely that it is related to the Dymola setup, because your model
runs once and the setup is not changing. More likely could be some timing
issues when opening/closing files on Windows, or problems with getting the
Dymola license. I suggest you try to run a test case a few thousand times
with a script in a loop. If this fails, make a test case that does not use
the weather data reader. This way you may be able to isolate it, in
particular if you catch any error messages. As the model runs once, I would
think our model code is correct and the problem lies either with Dymola,
Windows, or network resources that you may use when running the model.
Because your error is at runtime, another test would be to translate the
model once and run dymosim.exe in a loop to see if this reproduces the
issue and help you isolate the cause.

Best,

Michael

**Comment by PhilippZofer** [comment]
Hi Michael,

thank you very much for your tips. I'm trying to narrow down the error with them.
Because the issue is not reproduceable on your end, nor deterministically reproducable at my end, I will close this issue.

Thanks again for your help,
best regards,

Philipp

**Comment by efjerb** [comment]
I experience the same error when using weather data for Copenhagen, Denmark. However, I also get the following error message in the simulation log, which indicates that the problem may be caused by the getTimeSpanTMY3 function.

> Error: The following error was detected at time: 0
Received unexpected EOF in getTimeSpan.c when searching for first time stamp in C:/Users/s190190/OneDrive - Danmarks Tekniske Universitet/Dokumenter/Dymola/Library/Buildings 7.0.0/Resources/weatherdata/EP_Copenhagen.mos.
The stack of functions is:
Buildings.BoundaryConditions.WeatherData.BaseClasses.getTimeSpanTMY3
Buildings.BoundaryConditions.WeatherData.BaseClasses.getTimeSpanTMY3(weaDat.filNam, "tab1")
Error: Integrator failed to start model.

**Comment by mwetter** [comment]
@efjerb : Can you please try with https://github.com/lbl-srg/modelica-buildings/tree/maint_7.0.x. I just merged
https://github.com/lbl-srg/modelica-buildings/pull/2375 which prevents a possible memory violation in `getTimeSpanTMY3` that may be the reason. (This is also fixed on the master branch.)

**Comment by efjerb** [comment]
Thank you, this resolved the issue!

**Comment by GeorgeDawes** [comment]
Hi @mwetter, sorry to re-raise this issue but I have the same problem as @efjerb (error message below) when running any weather file as a path - I do not get the error when using the examples which use "Modelica.Utilities.Files.loadResource()" function...

**********
dymosim started
... "Unnamed1" simulating
... "dsin.txt" loading (dymosim input file)
Error: The following error was detected at time: 0
Failed to open file C:Dymola2022xBirminghamWeather.mos
The stack of functions is:
Buildings.BoundaryConditions.WeatherData.BaseClasses.getTimeSpanTMY3
Buildings.BoundaryConditions.WeatherData.BaseClasses.getTimeSpanTMY3(building.weaDat.filNam, "tab1")

Error: Integrator failed to start model.
**********

I am using Buildings 9.0.0 & Dymola 2022x and I have attached a .ZIP of files which recreates the error on my machine.

[Unnamed1_test.zip](https://github.com/lbl-srg/modelica-buildings/files/9971852/Unnamed1_test.zip)

**Comment by mwetter** [comment]
@GeorgeDawes : The .mo file that you sent has declarations such as
```
weaName="C:\Dymola2022x\BirminghamWeather.mos"
```
The proper entry would be
```
weaName=Modelica.Utilities.Files.loadResource(
      "modelica://NameOfYourLibrary/Resources/BirminghamWeather.mos")
```
where `NameOfYourLibrary` is for example the name of the top-level package of your library, and I assumed the file will be under this folder in a folder named `Resources` (you can call it any name).

This way it should work on any operating system. Based on your log, it looks like the C code mangled up the backward slash, which is not uncommon on Windows unless one uses `\\`. The form above with the `loadResources` is the one that complies with the Modelica standard, works across operating systems, and hence I recommend that form.
