### ISSUE TITLE
Buildings.ThermalZones.Detailed.Constructions examples with invalid modifiers

### ISSUE THREAD

**Issue by perost** [lbl-srg/modelica-buildings#1766]
Two of the examples in Buildings.ThermalZones.Detailed.Constructions have modifiers that references a non-existent variable `linearize`:

https://github.com/lbl-srg/modelica-buildings/blob/dafe2f4d49658dc61c0f349ed5bed922f9a10301/Buildings/ThermalZones/Detailed/Constructions/Examples/ExteriorWallWithWindow.mo#L102

https://github.com/lbl-srg/modelica-buildings/blob/dafe2f4d49658dc61c0f349ed5bed922f9a10301/Buildings/ThermalZones/Detailed/Constructions/Examples/ExteriorWallTwoWindows.mo#L112

Both models do contain a declaration for a variable `linearizeRadiation` which is used in modifiers for other components, so it might simply be that the variable was renamed without changing the modifiers.

Some tools might ignore these modifiers since the modified components are conditional and disabled, and it's not clear how valid a modifier on a disabled component must be. But in this case it looks more like a mistake than something intentional.

**Comment by mwetter** [comment]
@perost Thanks for reporting. This is indeed a mistake which will be closed through https://github.com/lbl-srg/modelica-buildings/pull/1771
