### ISSUE TITLE
Add Steam Boiler model for 1st Generation District Heating

### ISSUE THREAD

**Issue by khinkelman** [lbl-srg/modelica-buildings#1767]
Hi @JayHuLBL, could you please create a new issue for the BoilerSteam component model? This will be used in the 1st generation district heating systems. 

This model is to be located: Buildings.Fluid.Boilers.BoilerSteam

Thanks

**Comment by JayHuLBL** [comment]
@khinkelman Please use branch [issue1437_1767_steBoi](https://github.com/lbl-srg/modelica-buildings/tree/issue1437_1767_steBoi) as your working branch for this issue.

**Comment by khinkelman** [comment]
Hi @JayHuLBL, I hope you are doing well. The steam boiler and steam heat exchanger ended up having shared base classes; thus, I developed both on the same issue branch rather than separate branches. The steam boiler development will be on branch [issue1437_1768_steHex](https://github.com/lbl-srg/modelica-buildings/tree/issue1437_1768_steHex). 

Thus, this [issue1437_1767_steBoi](https://github.com/lbl-srg/modelica-buildings/tree/issue1437_1767_steBoi) branch can be deleted and the issue closed.

**Comment by JayHuLBL** [comment]
Close this issue as it will be addressed in #1768.
