### ISSUE TITLE
Add Steam Heat Exchanger for 1st Generation District Heating Systems

### ISSUE THREAD

**Issue by khinkelman** [lbl-srg/modelica-buildings#1768]
Hi @JayHuLBL, could you please create a new issue for the SteamHeatExchanger component model? This will be used in the 1st generation district heating systems. 

This model is to be located: Buildings.Fluid.HeatExchangers.SteamHeatExchanger

Thanks

**Comment by JayHuLBL** [comment]
@khinkelman Please use branch [issue1437_1768_steHex](https://github.com/lbl-srg/modelica-buildings/tree/issue1437_1768_steHex) as your working branch for this issue.

**Comment by khinkelman** [comment]
Hi @dhblum. This issue should be closed. Your interpretation is correct; the modeling approach changed, and this development is no longer active. Thanks for checking and cleaning these up!

**Comment by mwetter** [comment]
Yes, I will close it, and deleted the branch `issue1437_1768_steHex` which has nothing that is not on the master.

**Comment by dhblum** [comment]
Great, thank you @khinkelman and @mwetter!
