### ISSUE TITLE
enable CDL conformance check

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1779]
This issue is to check
- whether all models in `Buildings.Controls.OBC` conform to the CDL language,
- whether all models have comments on all parameters, inputs etc and have an `info` section.

To test, we should be able to run the parser of the form
```
node app.js -f ../modelica-buildings/Buildings/Controls/OBC/CDL/Continuous -o json -m cdl -d out
```
and get an non-zero exit value if there are warnings. Maybe the parser should have a `--strict` flag that interprets warnings as errors.

**Comment by mwetter** [comment]
This should now work on the `OBC` package.

**Comment by JayHuLBL** [comment]
@mwetter In `modelica` parsing mode, it should work, but not yet in `cdl` mode. This will work
```
node app.js -f ../modelica-buildings/Buildings/Controls/OBC -o json -m modelica -d out
```

**Comment by JayHuLBL** [comment]
@mwetter In `modelica` parsing mode, we can parse the OBC package and the modelica schema is now current. It takes 3 minutes to run:
```
node app.js -f ../modelica-buildings/Buildings/Controls/OBC -o json -m modelica -d out
```
This captures a  list of warnings shown in issue #1944.

**Comment by mwetter** [comment]
@JayHuLBL : It looks like modelica-json is still broken. See the output at https://travis-ci.com/github/lbl-srg/modelica-buildings/builds/166815928#L1552

You should be able to reproduce locally using something like
```
cd modelica-buildings
export TRAVIS_BUILD_DIR=`pwd`
export MODELICA_JSON_HOME=../lbl-srg/modelica-json
( cd Buildings/Resources/Scripts/travis && make test-cdl-conformance)
```
Then, when you fix modelica-json, change the commit at
https://github.com/lbl-srg/modelica-buildings/blob/issue1779_cdl_conformanceCheck/.travis.yml#L22

Once you enabled all targets again and verified that missing comments etc lead to a failed test, please make a pull request against the master.

**Comment by JayHuLBL** [comment]
@mwetter The modelica-json tool has been fixed and updated the commit for the tool. See the output at https://travis-ci.com/github/lbl-srg/modelica-buildings/builds/166984765. The test can successfully capture the missing comment (which I removed on purpose for the test.) and the CI test would be fail due to it.

**Comment by JayHuLBL** [comment]
@mwetter The tool has been fixed now and new version has been added for the travis test. See the output at https://travis-ci.com/github/lbl-srg/modelica-buildings/builds/167032943.

**Comment by mwetter** [comment]
@JayHuLBL 
Once you enabled all targets again, please make a pull request against the master.
