### ISSUE TITLE
Update CDL tutorial

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#1781]
This is to update the CDL tutorial:

- I propose to systematically use the word "command" for a control output signal and reserve "status" to the control input signal (return status from the plant). This is also consistent with RP1711.
- I added an explanation of the reverse action configuration for the PI controller in `Buildings.Examples.Tutorial.CDL.System3`.
- I bounded the upper value used in `dynamicSelect` for the radiator model.
- I fixed a few typos.

**Comment by mwetter** [comment]
This is now on the master, and also the radiator changes have been moved upstream to the IBPSA Library.
