### ISSUE TITLE
Fan power model

### ISSUE THREAD

**Issue by tamandri** [lbl-srg/modelica-buildings#1812]
Hello,

I tried to use the component SpeedControlled_Nrpm with addPowerToMedium=true.
I notice that the thermal power added to the air is Pele instead of PEle - Wflo. 
In the model, prePow.Q_flow = heatDis.Q_flow + eff.WFlo. Instead of just prePow.Q_flow = heatDis.Q_flow.

I am not sure to fully understand why, if you could help me?

Thank you.

**Comment by mwetter** [comment]
I a real fan, the energy input is PEle, while the heat input is as you write PEle-WFlo. However, in a real system the flow work will dissipate to heat wherever there is flow friction, and this would turn WFlo to heat eventually. In our library, we don't model this conversion from flow work to heat in flow resistances, and therefore we add the flow work as heat in the fan.

**Comment by tamandri** [comment]
Pele is the input. The part Wflo of it contributes to accelerate the air and the other part contributes heating the air. In the case I have a volume (conditioned space) after the fan, I have an energy balance in it to define the volume temperature. So the kinetic energy of the fluid is transformed into heat in it as it is there that my fluid is not in motion anymore and dissipates the flow work. In that case, in the fan, if I add as thermal energy the whole Pele to the air, wouldn't Wflo be considered twice in my energy balance in volume ? Thank you.
