### ISSUE TITLE
Add default value to conditional connectors of CDL sequences

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#1854]
This is to add default value to conditional connectors of CDL sequences.
```
CDL.Interfaces.IntegerInput nOcc if have_occSen
  "Number of occupants"
    annotation (__cdl(default = 0));
```

**Comment by mwetter** [comment]
@JayHuLBL : Looking at all the changes from the PR, I wonder if we should rather assume a default values if not specified. The convention could be:

For connectors that can conditionally be removed, a default value can be specified with the syntax `__cdl(default=value)`. If no such annotation is present, programs that require a value must use the following default values:
- For RealInput, the default values are:
  - If `unit=K`, the default is 293.15 K.
  - If `quantity="Pressure"`, the default is 101325 Pa.
  - If `quantity="PressureDifference"`, the default is 0 Pa.
  - For all other units, the default value is 0.
- For `IntegerInput`, the default value is `0`.
- For `BooleanInput`, the default value is `false`.
- For `DayTypeInput`, the default value is `WorkingDay`.

With this convention, the modelica to json translator can set most values to reasonable settings and users only need to specify special cases.

**Comment by JayHuLBL** [comment]
Close this issue as the default value will be assigned in translation process.
