### ISSUE TITLE
Update base models for Loads

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#1858]
Models in `Buildings.Applications.DHC.Networks.BaseClasses` shall be updated.

- [x] Rename parameter `have_heaFloOut` as `show_Q`.
- [x] Keep a state in the temperature sensor model to avoid algebraic coupling.
- [x] Modify `mDis_flow_nominal` as the nominal mass flow rate in the distribution line before **the first** connection 
- [x] Compute `mEnd_flow_nominal` from `mDis_flow_nominal` and `mCon_flow_nominal`
- Package the computation of `Q_flow` from temperature measurements in a reusable block: this is moved to #1769.
- Double check that replaceable types cannot be propagated and document the redeclare logic: this is moved to #1769.

In `Buildings.Applications.DHC.Loads.Examples.CouplingTimeSeries`

- [x] Update `mLoaHea_flow_nominal` and `mLoaCoo_flow_nominal` to representative values for FCU and use the scaling factor to size for the design load.

In `Buildings.Applications.DHC.Loads.BaseClasses.PartialTerminalUnit`

- [x] Check if `MassFlowRateMultiplier` could not be useful on the load side as well, in case of large thermal zones covering several rooms.
- [x] Add `HeatFlowRateMultiplier` for heat ports.

In `Buildings.Applications.DHC.Controls.MixingValveControl`

- [x] Correct description string of `toBoo` in `Buildings.Applications.DHC.Controls.MixingValveControl`.

In `Buildings.Applications.DHC.Loads.BaseClasses.PartialBuilding`

- [x] Refactor with `ports_aHeaWat` and `ports_aChiWat`, both conditional.

In `Buildings.Applications.DHC.Loads.BaseClasses.PartialBuilding` 

- [x] Update schematic to include distributor / collector line in `PartialBuilding`
- [x] Check the image size (too big on standard dpi).

In `Buildings.Applications.DHC.Loads.Examples.BaseClasses.BuildingSpawnZ6`

- [x] Let the `Attic` zone unconditioned.

In `Buildings.Applications.DHC.Loads.Examples.CouplingTimeSeries` 

- [x] Check the mismatch between `QReqHea_flow` and `QActHea_flow`, see plot.
- [x] Add integrator of heat flow rate for validation in energy.

<img width="352" alt="Buildings Applications DHC Loads Examples CouplingTimeSeries_plot" src="https://user-images.githubusercontent.com/10965994/80772995-62fffa00-8b0d-11ea-9f88-57d57053d5b3.png">

@amyeallen1 to review PR.

Updates to handle steam distribution will be addressed in a specific issue by @khinkelman.

**Comment by AntoineGautier** [comment]
For the computation of the supply temperature in `Applications.DHC.Loads.BaseClasses.FlowDistribution`, using a state or not, with 1s time constant leads to the following statistics.

For `Applications.DHC.Loads.Examples.CouplingRCZ1Valve` with cvode

- With a state

```
Integration terminated successfully at T = 604800
   CPU-time for integration                  : 0.451454 seconds
   CPU-time for initialization               : 0.0387611 seconds
   Number of result points                   : 822
   Number of grid points                     : 501
   Number of accepted steps                  : 17890
   Number of rejected steps                  : 1045
   Number of f-evaluations (dynamics)        : 24221
   Number of non-linear iteration            : 23819
   Number of non-linear convergence failures : 33
   Number of Jacobian-evaluations            : 499
```

- Without

```
Integration terminated successfully at T = 604800
   CPU-time for integration                  : 0.257215 seconds
   CPU-time for initialization               : 0.0325241 seconds
   Number of result points                   : 822
   Number of grid points                     : 501
   Number of accepted steps                  : 11159
   Number of rejected steps                  : 740
   Number of f-evaluations (dynamics)        : 16000
   Number of non-linear iteration            : 15598
   Number of non-linear convergence failures : 34
   Number of Jacobian-evaluations            : 374
```
This is unexpected as the number of non linear iterations (and integration time) increases significantly despite the algebraic decoupling due to the additional state variable. 
This model instantiates a three-way valve model modulated by a PI controller tracking the supply temperature. Conversely, for the other example models with no three-way valve and where the supply temperature is only used to compute the inlet temperature of the terminal HX, the sensitivity is as expected, but the impact is not significant.

Example for `Applications.DHC.Loads.Examples.CouplingSpawnZ6` with cvode

- With a state

```
Integration terminated successfully at T = 604800
   CPU-time for integration                  : 3.70014 seconds
   CPU-time for initialization               : 3.56516 seconds
   Number of result points                   : 2516
   Number of grid points                     : 501
   Number of accepted steps                  : 56074
   Number of rejected steps                  : 564
   Number of f-evaluations (dynamics)        : 69279
   Number of non-linear iteration            : 66761
   Number of non-linear convergence failures : 18
   Number of Jacobian-evaluations            : 1609
```

- Without

```
Integration terminated successfully at T = 604800
   CPU-time for integration                  : 3.69725 seconds
   CPU-time for initialization               : 1.10321 seconds
   Number of result points                   : 2516
   Number of grid points                     : 501
   Number of accepted steps                  : 56465
   Number of rejected steps                  : 574
   Number of f-evaluations (dynamics)        : 69719
   Number of non-linear iteration            : 67201
   Number of non-linear convergence failures : 23
   Number of Jacobian-evaluations            : 1626
```

Therefore, and only for this model, it is decided to use `tau=if allowFlowReversal then 1 else 0` in the instance of `Fluid.Sensors.TemperatureTwoPort` which allows reintroducing a state in case convergence issues appear.

**Comment by AntoineGautier** [comment]
The mismatch between `QReqHea_flow` and `QActHea_flow` is due to the fan dynamics.
I added the time integral of these variable in the simulation script. It shows that the relative error on energy is lower than 1E-6. Nevertheless there are some issues to fix.

The model in the current version of `issue1437_district_heating_cooling` has the following parameters setting.

- For what relates to the model structure

```
energyDynamics=Modelica.Fluid.Types.Dynamics.FixedInitial
use_inputFilter=true
```

- For what relates to the control parameters and time constants 

```
k=1
Ti=10
tau=1
riseTime=30
```
The simulation statistics are
```
Integration terminated successfully at T = 3.1536e+07
   CPU-time for integration                  : 7.66343 seconds
   CPU-time for initialization               : 0.00542283 seconds
   Number of result points                   : 8770
   Number of grid points                     : 8761
   Number of accepted steps                  : 210931
   Number of rejected steps                  : 21407
   Number of f-evaluations (dynamics)        : 330287
   Number of non-linear iteration            : 330265
   Number of non-linear convergence failures : 1862
   Number of Jacobian-evaluations            : 8882
   Number of crossing function evaluations   : 219747
   Number of model time events               : 1
   Number of state events                    : 4
   Number of step events                     : 0
```
Also note that we have the following error (one occurrence).
```
Error: The following error was detected at time: 21385258.82627517
  In CouplingTimeSeries.bui.terUniCoo.hex.bal1.vol:
   The heat flow rate equals 298233 W and the mass flow rate equals 0.0455495 kg/s,
   which results in a temperature difference 1564.88 K > dTMax=200 K.
   This may indicate that energy is not conserved for small mass flow rates.
   The implementation may require prescribedHeatFlowRate = false.
  Failed condition: noEvent(abs(bui.terUniCoo.hex.Q1_flow) < 836800.0*max(1.7562141491395795E-08, abs(bui.terUniCoo.hex.port_a1.m_flow)))
```
By changing to
```
energyDynamics=Modelica.Fluid.Types.Dynamics.SteadyState
use_inputFilter=false
```
We nearly eliminate the mismatch and get
```
Integration terminated successfully at T = 3.1536e+07
   CPU-time for integration                  : 9.3172 seconds
   CPU-time for initialization               : 0.00982118 seconds
   Number of result points                   : 8770
   Number of grid points                     : 8761
   Number of accepted steps                  : 169410
   Number of rejected steps                  : 21112
   Number of f-evaluations (dynamics)        : 267152
   Number of non-linear iteration            : 267127
   Number of non-linear convergence failures : 934
   Number of Jacobian-evaluations            : 5762
   Number of crossing function evaluations   : 178228
   Number of model time events               : 1
   Number of state events                    : 4
   Number of step events                     : 0
```
However we now get non convergence of the Newton solver, which is yielded by the steady-state coupling. 13 error messages are output but they all correspond to the same time value (22425536s).
Also we cannot set the start value of the new iteration variables which are protected, see warning
```
Some variables are iteration variables of the initialization problem:
but they are not given any explicit start values. Zero will be used.

Iteration variables:
bui.terUniCoo.fan.heaDis.WHyd
bui.terUniHea.fan.heaDis.WHyd
```

**Comment by mwetter** [comment]
@AntoineGautier : Regarding "we cannot set the start value of the new iteration variables which are protected": If it helps, you can set the start values of other variables in this iteration loop. Then a tool is more likely to use these as break variables.

**Comment by AntoineGautier** [comment]
Another issue appears when simulating `DHC.Loads.Examples.CouplingTimeSeries` with Optimica.
The simulation over a whole year takes about 200s, so 20 times more than with Dymola. Three modeling options for the fan have been tested without significant impact on simulation time.

1.
```
energyDynamics=Modelica.Fluid.Types.Dynamics.SteadyState
use_inputFilter=false
```
Gives
```
 Number of steps                                 : 168357
 Number of function evaluations                  : 267338
 Number of Jacobian evaluations                  : 6196
 Number of function eval. due to Jacobian eval.  : 0
 Number of error test failures                   : 21149
 Number of nonlinear iterations                  : 264193
 Number of nonlinear convergence failures        : 888
 Number of state function evaluations            : 180961
 Number of state events                          : 698
 Number of time events                           : 1

Solver options:

 Solver                   : CVode
 Linear multistep method  : BDF
 Nonlinear solver         : Newton
 Linear solver type       : DENSE
 Maximal order            : 5
 Tolerances (absolute)    : [1.e-06 1.e-06 1.e-01 1.e-01 1.e-06 1.e-06 1.e-06 1.e-06 1.e-06 1.e-06]
 Tolerances (relative)    : 1e-06

Simulation interval    : 0.0 - 31536000.0 seconds.
Elapsed simulation time: 200.5334931439993 seconds.
```
2.
```
energyDynamics=Modelica.Fluid.Types.Dynamics.FixedInitial
use_inputFilter=false
```
Gives
```
 Number of steps                                 : 200275
 Number of function evaluations                  : 324722
 Number of Jacobian evaluations                  : 7916
 Number of function eval. due to Jacobian eval.  : 0
 Number of error test failures                   : 21595
 Number of nonlinear iterations                  : 321511
 Number of nonlinear convergence failures        : 851
 Number of state function evaluations            : 213021
 Number of state events                          : 712
 Number of time events                           : 1

Simulation interval    : 0.0 - 31536000.0 seconds.
Elapsed simulation time: 205.7573771089992 seconds.
```
3.
```
energyDynamics=Modelica.Fluid.Types.Dynamics.FixedInitial
use_inputFilter=true
```
Gives 
```
 Number of steps                                 : 232331
 Number of function evaluations                  : 355251
 Number of Jacobian evaluations                  : 9227
 Number of function eval. due to Jacobian eval.  : 0
 Number of error test failures                   : 21565
 Number of nonlinear iterations                  : 352399
 Number of nonlinear convergence failures        : 1732
 Number of state function evaluations            : 245423
 Number of state events                          : 708
 Number of time events                           : 1

Simulation interval    : 0.0 - 31536000.0 seconds.
Elapsed simulation time: 199.04034140199838 seconds.
```
Adding a state in the temperature sensor in `DHC.Loads.BaseClasses.FlowDistribution` does not change the simulation statistics significantly.

**Comment by AntoineGautier** [comment]
@mwetter Does the fact that the number of steps, Jacobian evaluations and non linear iterations is similar between Dymola and Optimica whereas the simulation time is 20 times higher for the latter indicate a potential performance gap rather due to the software stack?

**Comment by mwetter** [comment]
@AntoineGautier The model `Buildings.Applications.DHC.Loads.Examples.CouplingTimeSeries` in latest commit e2493ad7dacbf964bd55964c35f8df0d4e0a3376 fails to translate in Optimica with `Cannot find component declaration for use_reset` so I can't reproduce. If you simulate it with the attached script, debug information will be shown, including the CPU time vs model time which should help seeing if there are specific points that explain the 20x increase in simulation time, which is unexpected. 
[jmodelica.zip](https://github.com/lbl-srg/modelica-buildings/files/4662278/jmodelica.zip)

**Comment by AntoineGautier** [comment]
Closed by https://github.com/lbl-srg/modelica-buildings/pull/1960
