### ISSUE TITLE
address simulation that start not at midnight

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1861]
For Spawn, test that the EnergyPlus envelope either works for any start time, including negative and not coinciding with a minute (or midnight), or else add an assertion plus documentation to inform the user about requirements for the start time.

Also, add test cases that pass the New Year.

@kbenne : Before I start testing, do you know of any limitations of your side of the code?

**Comment by kbenne** [comment]
I know that negative start time will not work the way you expect it to. I haven't tested this scenario, but I expect EnergyPlus to essentially stand still until you get to time zero. I don't think it will cause an error or exception though. 

You should be able to spawn multiple years.

**Comment by mwetter** [comment]
See https://github.com/lbl-srg/modelica-buildings/issues/1870 for a failed test that starts at midnight but not on January 1.

**Comment by mwetter** [comment]
Replaced by https://github.com/lbl-srg/modelica-buildings/issues/1938
