### ISSUE TITLE
DC/AC conversion losses bug in electrical battery model

### ISSUE THREAD

**Issue by mike280512** [lbl-srg/modelica-buildings#1865]
The battery model in Buildings.Electrical.AC.OnePhase.Storage does not correctly account for DC/AC conversion. The output from the splice block, 'spl', is connected to both the charge block and the resistive load 'bat', the latter connection via a gain block, 'gain'. 
This means that the absolute values determined for change in SOC (before applying other conversion efficiencies) and power transferred at the terminal are equal. Furthermore, the power transfer defined at 'P' differs from what is actually transferred at the terminal. 
Issue can be resolved by deleting the connection between 'spl' and 'gain', then connecting 'P' to 'gain' directly.
Detail on the issue:
Currently when all eta values, apart from eta_DCAC, are set = 1, simulation of the battery will determine a change in SOC per second that is equal to bat.Pow/EMax. Therefore the DC/AC conversion efficiency is not applied; the correct change in SOC per second should be eta_DCAC*bat.Pow/EMax for charging or (2-eta_DCAC)*bat.Pow/EMax for discharging (in the particular case with other etas = 1).

**Comment by mwetter** [comment]
@mike280512 : Thanks for reporting, this is indeed incorrect. This will be addressed through https://github.com/lbl-srg/modelica-buildings/pull/1868

**Comment by mike280512** [comment]
You are most welcome. Thanks for maintaining such a useful resource!
