### ISSUE TITLE
reimplement CDL.Continuous.LimPID

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1878]
This issue is to try to reimplement `LimPID` using only CDL constructs. This will allow composing this block from other elementary block.

However, some parameter evaluation will be needed following the conventions on http://obc.lbl.gov/specification/cdl.html#instantiation.

The development branch is `issue1878_CDL_limPID`

**Comment by JayHuLBL** [comment]
@mwetter Issue #1700 intended to do the same thing and I have done some development in branch `issue1700_reimpPID`. Please check if the development there is helpful. 
However, in branch `issue1700_reimpPID`, `D` controller was not included.

**Comment by mwetter** [comment]
@JayHuLBL : Thanks. Can you please review https://github.com/lbl-srg/modelica-buildings/pull/1879 which is a complete implementation. There are only minor changes in some large models, likely due to changes in the numeric.

**Comment by JayHuLBL** [comment]
@mwetter I have left comments to the PR. It's quite minor.

**Comment by mwetter** [comment]
This revision also simpifies the implementation by removing the parameters `strict`, `initType`, `y_start` and `xd_start`. It introduces the parameter `yd_start` for the initial output of the derivative term which is easier to understand than the initial state used in the derivative term. The parameter `y_start` has been removed because using it with only CDL does not work because its use would require to know the inputs of the controller in order to set the initial condition.
