### ISSUE TITLE
Package for standard hydronic configurations

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#1884]
Note: The feature branch is `issue1884_hydronics`.

This is to develop a package where we collect different hydronic configurations for heating or cooling systems. 

- For these it would also be nice to have CDL control sequence. 
- The configurations either have a differential pressure or not at their supply, and have either no valve, a two-way or three-way valve, optionally with a bypass if the primary supply temperature is higher than the secondary heating design supply temperature (or cooler for cooling systems). 
- These are the repetitive elements that can then be used in a variety of projects. As such, this is a shared task between OBC, URBANopt and Spawn.

See figure for some examples of such standard configurations.

![Screen Shot 2020-04-07 at 5 11 27 PM](https://user-images.githubusercontent.com/10965994/78730875-ef464500-78f2-11ea-94de-7683459f2585.png)

**Comment by mwetter** [comment]
See also the classification in http://herzmediaserver.com/data/01_product_data/06_broschure/eng/hkls_anlagen_en.pdf
