### ISSUE TITLE
Add template model for 4GDHC energy transfer station

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#1885]
The model should be structured with high-level boolean parameters allowing to chose between typical hydraulic configurations (presence or not of bridge piping, check valve, heat exchanger, three-way valve, etc.) and controls.
Depending on the complexity, one model could even be developed for both heating and cooling systems.
This development has a dependency to #1884.
See also the related [PR1838](https://github.com/lbl-srg/modelica-buildings/pull/1838) which is currently on hold.

**Comment by dhblum** [comment]
Looking to clean up issues.  Direct and indirect ETS's have been added for heating and cooling here: https://github.com/lbl-srg/modelica-buildings/tree/master/Buildings/Experimental/DHC/EnergyTransferStations.  I think this could be closed based on those additions?  And any further updates, like incorporating the hydronic configurations suggested in #1884, suggested in new dedicated issues.
