### ISSUE TITLE
CDL.Continuous.LimPID change of default values

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1888]
This issue is to change the default values for `LimPID` as follows:

1. Set a default value of `yMax=1`.
2. Change the default value for `yMin=-yMax` to `yMin=0`.

Also, the conversion script needs to be updated to change existing models to set the value of `yMax` if they did not change the default setting.

The rational for this change is that almost all controllers in the library have outputs from `0` to `1` because this is the control input used by valves, dampers, pumps and fans.

This change should be done after https://github.com/lbl-srg/modelica-buildings/pull/1879 is merged.

**Comment by mwetter** [comment]
Note that `Buildings.Controls.Continuous.LimPID` is also using `yMin=0` and `yMax=1`, and the same gains as `CDL.Continuous.LimPID`.

**Comment by mwetter** [comment]
The conversion script was tested with
```modelica
within ;
model TestPID
  Buildings.Controls.OBC.CDL.Continuous.LimPID conPIDPlus10Minus10(
    yMax=10,
    yMin=-10);
  Buildings.Controls.OBC.CDL.Continuous.LimPID conPIDPlus10(
    yMax=10);
  Buildings.Controls.OBC.CDL.Continuous.LimPID conPIDMinus10(
    yMin=-10);
  Buildings.Controls.OBC.CDL.Continuous.LimPID conPIDstrict(
    strict=true);
  Buildings.Controls.OBC.CDL.Continuous.LimPID conPIDInitType(
    initType=Buildings.Controls.OBC.CDL.Types.InitType.NoInit,
    y_start=99,
    xd_start=99)
    annotation (Placement(transformation(extent={{60,0},{80,20}})));
  annotation (
    Icon(coordinateSystem(preserveAspectRatio=false)),
    Diagram(coordinateSystem(preserveAspectRatio=false)),
    uses(Buildings(version="6.0.0")));
end TestPID;
```
The message from Dymola is
```
Warning: Complex conversion failed for yMin in TestPID.conPIDPlus10Minus10.
Warning: Complex conversion failed for yMin in TestPID.conPIDMinus10.
Warning: Complex conversion failed for yMin in TestPID.conPIDPlus10Minus10.
Warning: Complex conversion failed for yMin in TestPID.conPIDMinus10.
Conversion removed modifier strict in TestPID.
Conversion removed modifier initType in TestPID.
Conversion removed modifier y_start in TestPID.
Conversion removed modifier xd_start in TestPID.
```
so it does not manage to set `yMin` if it were previously unassigned, but at least it issues a warning in these cases.

**Comment by AntoineGautier** [comment]
I believe the warning you get when running the conversion script is because the parameter you reference in the modified vector (here `yMax`) must be in the origin vector, with a default value that will only be used in case the parameter has no previous binding.
Does the following syntax gives you what you need?

```
convertModifiers("Buildings.Controls.OBC.CDL.Continuous.LimPID", {"yMin=fill(\"\",0)", "yMax=1"}, {"yMin=-%yMax%", "yMax=%yMax%"}, true);
```

**Comment by mwetter** [comment]
@AntoineGautier : Thanks, the command below works (note that `yMax=yMax` to retain the old value.
```
convertModifiers("Buildings.Controls.OBC.CDL.Continuous.LimPID", {"yMin=fill(\"\",0)", "yMax=yMax"}, {"yMin=-%yMax%", "yMax=%yMax%"}, true);
```

**Comment by AntoineGautier** [comment]
I see. `yMax=1` is used only if the parameter has no assigned value, otherwise this value is used. In your case you also change the default value of `yMax` right? Which indeed requires what you mention.

**Comment by mwetter** [comment]
@AntoineGautier The default value of `yMax` has been changed from unspecified to `1`.
