### ISSUE TITLE
Warm up and cool down modes are not activated in the operation mode 

### ISSUE THREAD

**Issue by kuzha** [lbl-srg/modelica-buildings#1893]
The block Buildings.Controls.OBC.ASHRAE.G36_PR1.Generic.SetPoints.OperationMode has 7 operation modes. 

Two of the seven modes, warm up and cool down modes, are never activated.

Another issue is: TZonMax and TZonMin are used as inputs for these two modes; but using TZon is enough according to the G36 description. This can slightly simplify the implementation.

- [ ] Needs to set the warm up and cool down time to 1800s in the VAV reheat G36 model so that it is consistent to that in the ASHRAE 2006 model

**Comment by JayHuLBL** [comment]
@kuzha How to reproduce the plot shown here?

**Comment by kuzha** [comment]
@JayHuLBL 
We had this issue when simulating SZVAV system. The plots were from SZVAV models.
I will fix this issue. Please assign the task to me.

**Comment by JayHuLBL** [comment]
@kuzha you may request me to review it when making PR.
