### ISSUE TITLE
Generic 1st Generation District Heating & Cooling System

### ISSUE THREAD

**Issue by khinkelman** [lbl-srg/modelica-buildings#1910]
Hi @JayHuLBL, could you please create a new branch for us to assemble an example 1st generation district heating & cooling system? 

This will be located in: Buildings.Applications.DHC.Examples

Several DHC component models will be used in this example, including:
- [Steam Boiler](https://github.com/lbl-srg/modelica-buildings/tree/issue1437_1768_steHex)
- [Steam Heat Exchanger](https://github.com/lbl-srg/modelica-buildings/tree/issue1437_1768_steHex)
- Steam Medium
- [Direct Cooling ETS](https://github.com/lbl-srg/modelica-buildings/tree/issue1437_1662_ets_directCooling)

**Comment by JayHuLBL** [comment]
@khinkelman Please use branch `issue1437_1910_1stDHC` as the development branch.

**Comment by dhblum** [comment]
@khinkelman Can this be closed with PRs #3093 (District Cooling) and #2961 (Steam)?

**Comment by khinkelman** [comment]
@dhblum Yes, this may be closed with the PRs you mentioned above.

**Comment by dhblum** [comment]
Thanks @khinkelman, will close when those are closed.

**Comment by dhblum** [comment]
Noting that https://github.com/lbl-srg/modelica-buildings/pull/3093 is closed.

**Comment by dhblum** [comment]
Noting that https://github.com/lbl-srg/modelica-buildings/pull/2961 is now closed.  Closing this issue.
