### ISSUE TITLE
WetCoilCounterFlow with condensate removal

### ISSUE THREAD

**Issue by justnielsen** [lbl-srg/modelica-buildings#1920]
I'm using `Fluid.HeatExchangers.WetCoilCounterFlow` as a flue gas condenser for a district heating system. The setup is identical to the example `Fluid.HeatExchangers.Examples.WetCoilCounterFlowMassFlow` where I remove water/condensate from moist air (flue gas) (~70 °C, 100 % RH) by cooling it with 7 °C water on the 'other side'. So the flow of condensate is always small compared to the flow of air. 

I would like to simulate the removal of condensate  from the moist air stream, to se that `port_b2.m_flow` < `port_a2.m_flow` by setting the constant `simplify_mWat_flow` to `false`. However, due to the following restrictions I am not allowed to modify `simplify_mWat_flow` when I instantiate `WetCoilCounterFlow`.

1. in `Fluid.HeatExchangers.BaseClasses.HexElementLatent` the redeclaration of `vol2` is `final`.
2. in `Fluid.HeatExchangers.DryCoilCounterFlow` the replaceable model `ele` is `protected` (which just gives me a warning)

## Reproduction of problem

- In `Fluid.HeatExchangers.Examples.WetCoilCounterFlowMassFlow` insert the modifier `ele(each vol2(simplify_mWat_flow=false))` in the instantiation of `hex` (line 11).
- Simulation/Check gives error

## Fixing of problem
- in `Fluid.HeatExchangers.BaseClasses.HexElementLatent` remove `final` from the line `redeclare  Buildings.Fluid.MixingVolumes.BaseClasses.MixingVolumeHeatMoisturePort vol2(` (line 8)
-  in `Fluid.HeatExchangers.DryCoilCounterFlow` make `ele` public (line 119)

**Comment by mwetter** [comment]
@justnielsen Please let me know if https://github.com/lbl-srg/modelica-buildings/commit/d8f08525237e17169355d3a98c3aefb274b3e444 allows you to use the model in the intended way by setting the constant `simplify_mWat_flow`. If your experiments show that you need this feature permanently, e.g., setting `simplify_mWat_flow=false` is indeed needed, we could merge it to the master.

**Comment by justnielsen** [comment]
@mwetter The solution in [`d8f0852`](https://github.com/lbl-srg/modelica-buildings/commit/d8f08525237e17169355d3a98c3aefb274b3e444) works perfectly fine! It would be great to have it merged into the master branch since I'll be using the feature often.

Thanks very much.
