### ISSUE TITLE
forced-convection heat transfer coefficient is not zero though wind speed is zero

### ISSUE THREAD

**Issue by jpsautEurobios** [lbl-srg/modelica-buildings#1923]
The issue is related to the behavior of model **Buildings.HeatTransfer.Convection.Exterior**.
Even if there is no wind (wind speed = 0), the heat flow depends on surface orientation (azimuth angle).
The simple example below shows the problem:

```modelica
model TestExteriorConv
  Buildings.HeatTransfer.Convection.Exterior conv1(
    A=5,
    azi=0,
    conMod=Buildings.HeatTransfer.Types.ExteriorConvection.TemperatureWind,
    til=1.5707963267949) annotation (Placement(transformation(extent={{0,-10},{20,10}})));
  Buildings.HeatTransfer.Convection.Exterior conv2(
    A=5,
    conMod=Buildings.HeatTransfer.Types.ExteriorConvection.TemperatureWind,
    azi=3.1415926535898,
    til=1.5707963267949) annotation (Placement(transformation(extent={{0,-52},{20,-32}})));
  Modelica.Thermal.HeatTransfer.Sources.FixedTemperature fixedTemp1(T=288.15)
    annotation (Placement(transformation(extent={{-50,-10},{-30,10}})));
  Modelica.Thermal.HeatTransfer.Sources.FixedTemperature fixedTemp2(T=278.15)
    annotation (Placement(transformation(extent={{90,-10},{70,10}})));
  Modelica.Blocks.Sources.Constant windSpeed(k=0) annotation (Placement(transformation(extent={{-90,10},{-70,30}})));
  Modelica.Blocks.Sources.Constant windDir(k=0) annotation (Placement(transformation(extent={{-90,-40},{-70,-20}})));
equation 
  connect(fixedTemp1.port, conv1.solid) annotation (Line(points={{-30,0},{0,0}}));
  connect(conv1.fluid, fixedTemp2.port) annotation (Line(points={{20,0},{70,0}}));
  connect(fixedTemp1.port, conv2.solid) annotation (Line(points={{-30,0},{-26,0},{-26,-42},{0,-42}}));
  connect(conv2.fluid, fixedTemp2.port) annotation (Line(points={{20,-42},{50,-42},{50,0},{70,0}}));
  connect(windSpeed.y, conv1.v) annotation (Line(points={{-69,20},{-10,20},{-10,10},{-2,10}}));
  connect(windSpeed.y, conv2.v) annotation (Line(points={{-69,20},{-10,20},{-10,-32},{-2,-32}}));
  connect(windDir.y, conv1.dir) annotation (Line(points={{-69,-30},{-18,-30},{-18,5},{-2,5}}));
  connect(windDir.y, conv2.dir) annotation (Line(points={{-69,-30},{-18,-30},{-18,-37},{-2,-37}}));
  annotation (
    Icon(coordinateSystem(preserveAspectRatio=false)),
    Diagram(coordinateSystem(preserveAspectRatio=false)),
    experiment(StopTime=86400, __Dymola_NumberOfIntervals=5000));
end TestExteriorConv;
````

The value of Q_flow is not the same in the two Convection.Exterior blocks, though they are identical, apart from their orientation. The orientation should normally have no effect since there is no wind.
The issue is due to how the "Convective heat transfer coefficient due to forced convection" hF is computed.
The formula in the model documentation is hf = 2.537 * W * R * sqrt( P * v ⁄ A ), with v the wind speed and W=1 for windward surfaces and W=0.5 for leeward surfaces.
A regularization function is used around v = 0. This function (Buildings.Utilities.Math.Functions.regNonZeroPower) is non-zero in v = 0.
Therefore hf is non-zero when v = 0, and it depends on azimuth.
Why not using a regularization function that is zero at v = 0 ?
The following regularization polynomial can be used instead of the one used in Buildings.Utilities.Math.Functions.regNonZeroPower:
  p(x) = a6 * x^6 + a4 * x^4 + a2 * x^2
The coefficients are computed with the following formulas:
   a6 := (1 + (n^2)/8 - (3 * n)/4) * delta^(n - 6);
   a4 := (n * (n - 2)/8) * delta^(n - 4) - 3 * a6 * delta^2;
   a2 := (1/2) * n * (n - 1) * delta^(n - 2) - 15 * a6 * delta^4 - 6 * a4 * delta^2;

The derivatives (to replace computations in der_regNonZeroPower and der_2_regNonZeroPower, in Utilities.Math.Functions.BaseClasses) are
  der_y := (6 * a6 * x^5 + 4 * a4 * x^3 + 2 * a2 * x)  * der_x;
  der_2_y := (6 * a6*x^5 + 4 * a4*x^3 + 2 * a2 * x) * der_2_x + (30 * a6 * x^4 + 12 * a4 * x^2 + 2  * a2) * der_x^2;

I have code for all these functions if needed.
Best regards

**Comment by mwetter** [comment]
Thanks for reporting. This will be fixed through 7d44a3e5d.
There is also a new validation test `Buildings.HeatTransfer.Convection.Validation.ZeroWindSpeed` that shows that with this fix, `hF` is independent of the wind direction for zero wind speed.

Updating `Buildings.Utilities.Math.Functions.regNonZeroPower` is not preferred here as these functions are used in various models that expect a non-zero value.
