### ISSUE TITLE
Support negative start time in EnergyPlus

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1938]
The following command
```
simulateModel("Buildings.ThermalZones.EnergyPlus.Validation.OneZone", startTime=-864000, stopTime=864000, method="Cvode", tolerance=1e-06, resultFile="OneZone");
```
produces
![image](https://user-images.githubusercontent.com/1329080/81738527-b0099780-944e-11ea-91a1-5defead0b4e6.png)

**Comment by kbenne** [comment]
What are the outside conditions when a simulation is started in a scenario like this with a negative start time? I need to correlate with a time in the weather file.

**Comment by mwetter** [comment]
If the E+ weather file is from t=0 to t=365 days, then you can look up the outside conditions at t-365 days.

**Comment by kbenne** [comment]
Yikes!

**Comment by mwetter** [comment]
In FY21 AOP for NREL.

**Comment by mwetter** [comment]
Todo for the release:
- [ ] On the Modelica side, issue an error if the simulation time is negative.

**Comment by mwetter** [comment]
@kbenne : This issue is not yet fixed in the latest build that is merged through https://github.com/lbl-srg/modelica-buildings/pull/2984

Commit 06cc58dc25 on branch `issue1938_spawn_negative_startTime` adds the validation case `Buildings/Resources/Scripts/Dymola/ThermalZones/EnergyPlus_9_6_0/Validation/RunPeriod/NegativeStartTime.mos` which produces the following output:
![image](https://user-images.githubusercontent.com/1329080/166289474-26fb33c9-ffa3-4d6d-9520-5517e19f5331.png)

**Comment by kbenne** [comment]
Hmm. That's interesting. I can't perceive why it is doing this, although the testing I'm doing at my level doesn't attempt actual simulation. Take a look at the unit test in [this](https://github.com/NREL/Spawn/commit/17e04fe450ab3adf926612426538c936c5c5c79e) commit.

I'll have to dig a bit deeper.

**Comment by mwetter** [comment]
You may need to check if E+ does internally the right thing, for example by verifying that it picks the same weather data for t=-1 days as it does for t=364 days; or whether the simulations for these two day specifications produce the same indoor temperatures.

**Comment by kbenne** [comment]
Yeah I certainly have some investigation to do. But the whole point of the strategy was that EnergyPlus would never actually see a negative time. I probably need to rig up a test that actually does simulation for day 364 and day -1, which will be a bit more involved. 

Note how this so closely relates to https://github.com/lbl-srg/modelica-buildings/issues/2453 because simulating day 364 actually requires EnergyPlus to simulate through the first 363 days to arrive at the start time.

**Comment by mwetter** [comment]
Delay for later, not part of release 9.0
