### ISSUE TITLE
Boiler example does not work

### ISSUE THREAD

**Issue by ohmsweetohm1** [lbl-srg/modelica-buildings#1955]
Hi,

I have a fresh installation of OpenModelica:
```
Connected to OpenModelica v1.14.1 (64-bit)
Connected to OMSimulator v2.1.0-dev-147-g36ec2c7-mingw
```

and tried `Buildings.Examples.Tutorial.Boiler.System2` but I get errors.

The first one:
> In file included from Buildings.Examples.Tutorial.Boiler.System2_model.h:24:0,
                 from Buildings.Examples.Tutorial.Boiler.System2.c:7:
Buildings.Examples.Tutorial.Boiler.System2.c: In function 'Buildings_Examples_Tutorial_Boiler_System2_eqFunction_1268':
Buildings.Examples.Tutorial.Boiler.System2_functions.h:32:100: error: too few arguments to function 'Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars_p'
 #define Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Examples_Tutorial_Boiler_System2_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)
                                                                                                    ^

However, `Buildings.Examples.Tutorial.Boiler.System1` works but I think it does not use any classes from `Buildings`.
I did not follow the instructions on https://simulationresearch.lbl.gov/modelica/installLibrary.html to install the library but loaded the library via SystemLibraries > Buildings.

Thanks in advance!

**Comment by mwetter** [comment]
@ohmsweetohm1 : Not all models work with OpenModelica, please also see the note at https://simulationresearch.lbl.gov/modelica/environments.html
