### ISSUE TITLE
Compatibility of Buildings Lib. with Modelica 3.2.3

### ISSUE THREAD

**Issue by amirjodeiri** [lbl-srg/modelica-buildings#1961]
Hi, 
I have recently reinstall OpenModelica and I think its version has been changed from 3.2.2 to 3.2.3. When I work with storage model in fluid package, in initialization section of the storage model, I am not able to input the T-start with an array of more than 1. It means it accepts only one initial temperature even if the tank has more than 1 segment. I suppose this issue is related to the fact that I am using newer version of Modelica. Would you please advise me with this regard.

**Comment by mwetter** [comment]
That seem to be a wrong setting of the parameter or a problem in OpenModelica. The following command works in Dymola 2020x which also uses MSL 3.2.3:
```
simulateModel("Buildings.Fluid.Storage.Examples.Stratified(tanEnh(T_start=303.15))", stopTime=10800, tolerance=1e-08, resultFile="Stratified");
```

**Comment by amirj1984** [comment]
Dear @mwetter , 
Thanks for your reply. The 1st attached file shows the input temperature and 2nd file shows the error I received. I used to do the same with 3.2.2 without any error.
![1](https://user-images.githubusercontent.com/51123927/82563095-b3033700-9b76-11ea-846e-a68d1beb3cd0.png)
![2](https://user-images.githubusercontent.com/51123927/82563105-b7c7eb00-9b76-11ea-8c67-ac4ce7fb80d5.png)

**Comment by amirjodeiri** [comment]
I think I was not able to convey my message properly. In initialization of Stratified tank model, the user is able to give each tank segment with different temperature (T_start). To do so, the user must give a vector with dimension equal to the number of segments (nSeg). But with this input from user, the error that I mentioned above is received which means model requires a scalar, but not a vector. I have tried with one number instead of vector and it works; however, it imposes limitation on the model in such a way that initial temperature is uniform for the whole tank. I hope I was able to clarify it.
Note: I have tried it with Dymola and it was identical to what explained at above.

**Comment by amirjodeiri** [comment]
Dear @JayHuLBL  I would appreciate if you could help me with this regard.

**Comment by JayHuLBL** [comment]
@amirjodeiri By setting `T_start` to an array should not be allowed by Modelica standard itself. As in the base class `Buildings.Fluid.Storage.BaseClasses.PartialStratified` from which the class `Buildings.Fluid.Storage.Stratified` extends, parameter `T_start` is specified as:
```
  parameter Medium.Temperature T_start=Medium.T_default
    "Start value of temperature"
    annotation(Dialog(tab = "Initialization"));
```
`T_start` is a scalar not an array. The tank initial temperature is specified by `TFlu_start` as
```
  parameter Modelica.SIunits.Temperature TFlu_start[nSeg]=T_start*ones(nSeg)
    "Initial temperature of the tank segments, with TFlu_start[1] being the top segment"
    annotation(Dialog(tab = "Initialization"));
```
To customize your own initial temperature profile, you should set it through `TFlu_start`
![image](https://user-images.githubusercontent.com/23491921/82934247-0e9b3f00-9f40-11ea-9320-67efd6baf75e.png)
