### ISSUE TITLE
correct large whitespace in ASHRAE sequences

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1975]
Some sequences such as in
https://simulationresearch.lbl.gov/modelica/releases/latest/help/Buildings_Controls_OBC_ASHRAE_G36_PR1_TerminalUnits_SetPoints.html#Buildings.Controls.OBC.ASHRAE.G36_PR1.TerminalUnits.SetPoints
and 
https://simulationresearch.lbl.gov/modelica/releases/latest/help/Buildings_Controls_OBC_ASHRAE_G36_PR1_TerminalUnits_Reheat.html#Buildings.Controls.OBC.ASHRAE.G36_PR1.TerminalUnits.Reheat
have very large white spaces. 

This issue is to check and correct what causes this, maybe a wrong diagram annotation?

**Comment by JayHuLBL** [comment]
@mwetter This issue could be closed as it has been addressed by Dassault for Dymola 2021x.
<img width="722" alt="image" src="https://user-images.githubusercontent.com/23491921/89673085-9f748c00-d89a-11ea-9856-f5d6be73be9d.png">
