### ISSUE TITLE
Wrong warning for steady state hypothesis in radiant slab model

### ISSUE THREAD

**Issue by EttoreZ** [lbl-srg/modelica-buildings#2009]
The model SingleCircuitSlab contains the function component AverageResistance. In the component AverageResistance the value of alpha = k/d for the insulant layer (layer below the active layer, see picture below) should be < 1.212 according to the TRNSYS active floor model of the Type56 (from which the Buildings model was derived). 

![image](https://user-images.githubusercontent.com/46685675/84702746-6af9e900-af57-11ea-81cf-ca320d7a5366.png)
_source TRNSYS18 type 56 manual pag 197-201_

The if alpha >= 1.212 is properly computed in the Buildings model, however the warning message is not coherent with the requirement since it is shown as: 

_Warning: In RadiantAverageResistance, require alpha = kIns/dIns ">=" 1.212 W/(m2.K).
   Obtained alpha = 8 W/(m2.K)
            kIns = 0.4 W/(m.K)
            dIns = 0.05 m
            For these values, the radiant slab model is outside its valid range._
is should simply be:

_Warning: In RadiantAverageResistance, require alpha = kIns/dIns "**<=**" 1.212 W/(m2.K).
   Obtained alpha = 8 W/(m2.K)
            kIns = 0.4 W/(m.K)
            dIns = 0.05 m
            For these values, the radiant slab model is outside its valid range._

Attached a simple zip file containing the model. [BugRadiantSlabTotal.zip](https://github.com/lbl-srg/modelica-buildings/files/4782796/BugRadiantSlabTotal.zip).

A further modification I would propose is in the documentation of the AvarageResistance function. Currently the introduction is:
"This function computes a fictitious thermal resistance between the pipe outer wall and a fictitious, average temperature of the plane that contains the pipes. The equation is the same as is implemented in TRNSYS 17. etc... "
I would specify that it implements the model from TRNSYS 17 type 56 active layer component, because TRNSYS has also the types 653 and 993, so it could generate a bit of confusion.

**Comment by mwetter** [comment]
@EttoreZ : Thanks for the 2 suggestions. It would be great if you can make a pull request against the branch `issue2009_radiantSlab`.

**Comment by EttoreZ** [comment]
No problem. I will do it tomorrow morning.
