### ISSUE TITLE
Minimum outdoor air flow control in Examples.VAVReheat 

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#2019]
Issues with a checked box below are addressed in the branch `issue2019_VAV_MinOA`.

- [x] One issue is related to the default values of the gain (0.05) and integral time (1200s) for the minimum outdoor air flow control in `Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Controller`, `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Economizers.Controller`,
`Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Economizers.Subsequences.Limits`.
This leads to losing the set point tracking as illustrated below (from simulation of `Buildings.Examples.VAVReheat.Guideline36`).
![Guideline36](https://user-images.githubusercontent.com/10965994/85868787-9f537d80-b77f-11ea-89a0-d3c8f7817a63.png)

- [x] Another issue is related to the values of `yMin` and `yMax` in the same set of controllers. According to G36-5.16.5.3 the output of the control loop should be between 0 and 1 whereas the defaults in `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Economizers.Subsequences.Limits` are -1 and +1 and the parameters `yMinDamLim=0` and `yMaxDamLim=1` in `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Controller` are not propagated (these parameters are not used at all).

- [x] Another issue is related to the value of `VOut_flow_min` in `ASHRAE2006` which is set to 0.3*m_flow_nominal/1.2 = 1.7 m3/s. A proper sizing with ASHRAE 62.1 leads to the following values, with a total of 0.9 m3/s, so nearly 50% less.
![Screen Shot 2020-07-02 at 7 36 44 PM](https://user-images.githubusercontent.com/10965994/86392227-65143f80-bc9b-11ea-96e4-c01ad1a17b66.png)
This makes the comparison with  `Guideline36` unfair as illustrated below.  

![Guideline36_1](https://user-images.githubusercontent.com/10965994/85869288-56e88f80-b780-11ea-8777-631c3547585e.png)

- [x] `Buildings.Controls.OBC.ASHRAE.G36_PR1.TerminalUnits.Reheat.SetPoints.ActiveAirFlow` does not take into account the zone air distribution effectiveness Ez to compute Voz, which is not consistent with G36-5.2.1.3, and with the airflow set point computation for the AHU. 

> There is no inconsistency as Vmin is the only parameter used by the terminal control block and it can be given a fixed value, independent from the actual zone air distribution effectiveness.

- [x] In `Buildings.Examples.VAVReheat.ThermalZones.VAVBranch` the sizing of the heating coil is incorrect as it uses the nominal air flow rate (cooling design conditions) instead of the air flow rate at heating design conditions. Also `T_a2_nominal` is set to 82.2 degC and is not an exposed parameter whereas `souTer` supplies water at 50 degC (not exposed) and  `Guideline36` and `ASHRAE2006` model the AHU heating coil with a constant HHW temperature of 45 degC. Eventually, best would be to use ports `*1` for water and ports `*2` for air.

  - Addressed by #2059.

- [x] In `Buildings.Examples.VAVReheat.Guideline36` the peak system population for the AHU controller is `final peaSysPop=1.2*sum({0.05*AFlo[i] for i in 1:numZon}))` whereas the zone design occupation in `zonOutAirSet[]` is `{0.05*AFlo[i] for i in 1:numZon}`. This seems inconsistent as the system peak should always be lower or equal to the sum of zone peaks. @JayHuLBL What do you think?

- [x] @JayHuLBL In `Buildings.Examples.VAVReheat.Guideline36`, `minZonPriFlo` (Minimum expected zone primary flow rate) is set to `{ mCor_flow_nominal,mSou_flow_nominal,mEas_flow_nominal,mNor_flow_nominal,mWes_flow_nominal}/1.2`. Why is not bound to `VDisSetMin_flow` from the terminal unit controllers?

**Comment by AntoineGautier** [comment]
@JayHuLBL In `Buildings.Examples.VAVReheat.Guideline36`, `minZonPriFlo` (Minimum expected zone primary flow rate) is set to `{ mCor_flow_nominal,mSou_flow_nominal,mEas_flow_nominal,mNor_flow_nominal,mWes_flow_nominal}/1.2`. Why is not bound to `VDisSetMin_flow` from the terminal unit controllers?

**Comment by AntoineGautier** [comment]
The impact of the above changes (commit d32b474) have been assessed with annual simulations of the models in `Buildings.Examples.VAVReheat`.

**Branch `issue2019_VAV_MinOA`**

```
.. table:: Heating, cooling, fan and total site HVAC energy, and savings of guideline 36 case versus base case.

   ===================================== ===================================== ====================================== ====================================== =====
   :math:`E_{h} \quad [kWh/(m^2\,a)]`    :math:`E_{c} \quad [kWh/(m^2\,a)]`    :math:`E_{f} \quad [kWh/(m^2\,a)]`     :math:`E_{tot} \quad [kWh/(m^2\,a)]`     [%]
   ===================================== ===================================== ====================================== ====================================== =====
                                   6.147                                 18.04                                  2.385                                  26.57   
                                   3.643                                 14.67                                  1.877                                  20.19  24.0 
   ===================================== ===================================== ====================================== ====================================== =====
  
  
CPUtime, base 52'
CPUtime, G36  95'
```

![plt](https://user-images.githubusercontent.com/10965994/87042843-807bcf00-c1f4-11ea-8c16-c14f21d7635f.png)

**Branch `master`**

**Comment by AntoineGautier** [comment]
@mwetter Following our discussion yesterday, see [here](https://github.com/lbl-srg/modelica-buildings/pull/2022#issuecomment-651892938) for the description of the non convergence issues after implementing the above changes.
I just noticed that simulating `VAVReheat.Guideline36` from the master branch also yielded one occurrence of the same error (the updated models in PR #2030 give 2 occurrences). The variables are the same in all occurrences, namely the NL iteration variables `amb.ports[2].m_flow`, `dpRetDuc.port_a.m_flow`,  `amb.ports[1].m_flow`. The number of occurrence seems to increase when decreasing the integral time for the OA control, until we reach the non-recoverable error `Unexpected CVode value`.

**Comment by mwetter** [comment]
@AntoineGautier 
On branch `issue2019_VAV_MinOA`, using the current version which is commit 97ab605fe4a4d33d900a886751eb819083610d37 and running
```
simulateModel("Buildings.Examples.VAVReheat.Guideline36", stopTime=172800, method="cvode", tolerance=1e-06, resultFile="Guideline36");
```
does not give any warnings or errors.

**Comment by mwetter** [comment]
This is now on the master. Simulating c609370eb8dfe8c66414c3deb11048b5c2e01a0b (on the `master`) as
```
simulateModel("Buildings.Examples.VAVReheat.Guideline36", stopTime=8985600, method="Cvode", tolerance=1e-06, resultFile="Guideline36");
```
works without any error. I will close the issue. Please open a new issue with a `simulateModel` command if the problem persists.
