### ISSUE TITLE
ASHRAE2006: Economizer controlled in sequence with the heating and cooling coils

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#2024]
Currently in `Buildings.Examples.VAVReheat.ASHRAE2006` the control of the economizer is based on `TMix` and the control of the heating and cooling coils is based on `TSup` (with 2 independent control loops). These 3 different control loops use 3 different set points, namely 10 degC for the heating coil, 12 degC for the cooling coil and the average (11 degC) for the economizer.
This is not as described in the documentation of the control sequence 2A2-21232 which is cited as a reference in the model information section.

> The heating coil valve, mixed air dampers, and cooling coil valve shall modulate in sequence to maintain supply air temperature setpoint of 55°F (adjustable). Provide deadband between heating and economizer cooling.

This issue is to implement this exact control logic, using one single controller and a mapping function to sequence the 3 control actions.

[EDIT 1] During the implementation comes the question of set point scheduling. The current model in the master uses

- a constant supply set point for the heating coil (10 degC), independent from the operation mode,
- a scheduled supply set point for the cooling coil, namely
    - `max(TSetHea+1, TCooOn)` with `TCooOn=12` degC in occupied, unoccupiedPreCool and safety modes
    - `TCooOff=30` degC in unoccupiedOff, unoccupiedNightSetBack and unoccupiedWarmUp modes

This cannot be used anymore when implementing the control sequence 2A2-21232 since the heating coil and cooling coil share the same supply temperature set point (so using `TCooOff` would increase the load on the heating coil in unoccupied mode). Therefore, the set point scheduling for the cooling coil will not be used anymore. No impact is expected as 

- The fan is off in unoccupiedOff mode.
- The unoccupiedNightSetBack and unoccupiedWarmUp modes are activated based on a test for a heating demand in the rooms. So no load on the cooling coil is expected in this case.

[EDIT 2] There is another issue in the master related to the operation modes and corresponding set points. Currently:

- In `Buildings.Examples.VAVReheat.Controls.Economizer` `connect(max.y, extractor.u[Integer(OperationModes.unoccupiedWarmUp)])` whereas the ASHRAE VAV 2A2-21232 states
  > Morning Warm-up: The optimum start program shall start the unit at the latest possible
time to reach the desired occupied space temperature setpoint at occupancy time. If the
average space temperature is below the occupied space temperature setpoint, the supply
and return fans shall energize, the maximum and minimum outside and exhaust dampers
shall remain closed, and return damper open

- In `Buildings.Examples.VAVReheat.Controls.ModeSelector` the condition `TRooAve.y < TRooSetCooOcc` is used to transition towards warm-up mode whereas the ASHRAE VAV 2A2-21232 states
  > If the average space temperature is below the occupied space temperature setpoint...

- In `Buildings.Examples.VAVReheat.ASHRAE2006` the heating coil air outlet temperature set point is constant (10 degC) whereas the ASHRAE VAV 2A2-21232 states
  > The heating coil valve shall modulate to maintain supply air temperature setpoint of 95°F (adjustable) until the average space temperature equals the occupied space temperature setpoint. 

  The current setting where the set point in warm-up is lower than the room set point (and thus the return temperature), raises an issue when transitioning to a control in sequence of the supply temperature. In warm-up mode (with full air recirculation) the controller yields a cooling demand but gets "incorrect feedback" from the system as the economizer is disabled. So when the mode changes to "occupied" the economizer starts will fully open OA dampers (due to the saturated control signal yielded by the supply temperature controller) and the time it takes for the control output to desaturate and activate the heating coil, freezing conditions are reached in the cooling coil.

**Comment by AntoineGautier** [comment]
This is addressed in `issue1502_replaceable_thermal_zone_sequence`.

**Comment by kuzha** [comment]
@AntoineGautier 
Please also have a check at the ASHRAE2006 model documentation when you push changes.
The [heating control logic](https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Examples/VAVReheat/ASHRAE2006.mo#L381) still describes the old control implementation.

**Comment by AntoineGautier** [comment]
For future reference I report the impact on HVAC site energy evaluated for the models in `Buildings.Examples.VAVReheat`.
Simulation options
```
simulateModel(modelInstance, startTime=0, stopTime=31536000, method="CVode", tolerance=1e-06, resultFile="ASHRAE2006", numberOfIntervals=500);
simulateModel(modelInstance, startTime=0, stopTime=31536000, method="CVode", tolerance=1e-06, resultFile="Guideline36", numberOfIntervals=500);
```
Results 
```
branch=issue2024_ASHRAE2006_sequence
commit=c21ecd4bc6cf144ae0f38df0cab0c35cf2976081
```
```
.. table:: Heating, cooling, fan and total site HVAC energy, and savings of guideline 36 case versus base case.

   ===================================== ===================================== ====================================== ====================================== =====
   :math:`E_{h} \quad [kWh/(m^2\,a)]`    :math:`E_{c} \quad [kWh/(m^2\,a)]`    :math:`E_{f} \quad [kWh/(m^2\,a)]`     :math:`E_{tot} \quad [kWh/(m^2\,a)]`     [%]
   ===================================== ===================================== ====================================== ====================================== =====
                                    5.06                                 16.08                                  2.369                                  23.51   
                                   3.639                                 14.72                                  1.839                                   20.2  14.1 
   ===================================== ===================================== ====================================== ====================================== =====
  
  
CPUtime, base 56'
CPUtime, G36  93'
```
```
branch=master
commit=8195ac05dd420728f6a04f536ac5d2e155456270
```
```
.. table:: Heating, cooling, fan and total site HVAC energy, and savings of guideline 36 case versus base case.

   ===================================== ===================================== ====================================== ====================================== =====
   :math:`E_{h} \quad [kWh/(m^2\,a)]`    :math:`E_{c} \quad [kWh/(m^2\,a)]`    :math:`E_{f} \quad [kWh/(m^2\,a)]`     :math:`E_{tot} \quad [kWh/(m^2\,a)]`     [%]
   ===================================== ===================================== ====================================== ====================================== =====
                                   5.581                                 16.47                                  2.299                                  24.35   
                                   3.639                                 14.72                                  1.839                                   20.2  17.0 
   ===================================== ===================================== ====================================== ====================================== =====
  
  
CPUtime, base 52'
CPUtime, G36  93'
```
