### ISSUE TITLE
Refactor G36_PR1 blocks that use nOcc with a Boolean signal instead of Integer

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#2029]
`Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.SetPoints.OutdoorAirFlow.Zone` and `Buildings.Controls.OBC.ASHRAE.G36_PR1.TerminalUnits.Controller` use `nOcc` as an AI point in case of occupancy sensor in the zone. This should rather be a DI (see G36 §4.2 VAV Terminal Unit with Reheat, where the optional occupancy sensor is listed as DI), and the current occupancy in the zone computed from the design occupancy of the zone `Pz` as `Pz* = if isOcc then Pz else 0`.

**Comment by AntoineGautier** [comment]
I am adding `Linkage` label also to this issue (and reactivate it): the VAV box template will not provide `nOcc` but rather a Boolean signal indicating whether the room is occupied or not.

**Comment by JayHuLBL** [comment]
This has been addressed through issue #1913.
