### ISSUE TITLE
Spawn simulation directory is disorganized 

### ISSUE THREAD

**Issue by kbenne** [lbl-srg/modelica-buildings#2053]
After running a simulation from within an empty directory the file structure is the following.

```
kbenne@Darth-Vader:~/Development/spawn/build/runtest$ ls -l
total 108956
drwxr-xr-x 2 kbenne kbenne      4096 Jul 28 20:32 7904aee5cf80e4c390084a983b3f5e1d
-rw-rw-r-- 1 kbenne kbenne   1401315 Jul 28 20:32 Buildings_ThermalZones_EnergyPlus_Validation_Actuator_LightsControl_debug.txt
-rw-rw-r-- 1 kbenne kbenne   1613444 Jul 28 20:32 Buildings_ThermalZones_EnergyPlus_Validation_Actuator_LightsControl.fmu
-rw-rw-r-- 1 kbenne kbenne 104846559 Jul 28 20:32 Buildings_ThermalZones_EnergyPlus_Validation_Actuator_LightsControl_log.txt
-rw-rw-r-- 1 kbenne kbenne   3693707 Jul 28 20:32 Buildings_ThermalZones_EnergyPlus_Validation_Actuator_LightsControl_result.mat
drwx------ 5 kbenne kbenne      4096 Jul 28 20:32 tmp-simulation-LightsControl.building
```

The directory `7904aee5cf80e4c390084a983b3f5e1d` is the energyplus working directory and the name comes from the FMU instancename provided to fmi2Instantiate. All energyplus output files end up here. Consider removing this sub directory and simply allow the eplusout to go into the cwd. 

The directory `temp-simulation-LightControl.building` is generated by the function `getSimulationTemporaryDirectory` https://github.com/lbl-srg/modelica-buildings/blob/19a997dabf44ff709525bc6402060d3eac5baff3/Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusUtil.h#L53 The EnergyPlus FMU is generated within this directory. Currently the contents of the staged FMU before it is zipped by spawn.exe are left in this location, however it would be better to remove the staged files.

It appears that the EnergyPlus FMU is extracted to the temp-simulation-LightControl.building directory. The result is two copies of the FMU contents. 1. The staged files before the FMU is zipped. 2. The extracted files. The result is messy.

```
kbenne@Darth-Vader:~/Development/spawn/build/runtest$ ls -l tmp-simulation-LightsControl.building/
total 444624
drwxrwxr-x 3 kbenne kbenne      4096 Jul 28 20:32 binaries
drwxrwxr-x 4 kbenne kbenne      4096 Jul 28 20:32 LightsControl.building
-rw-rw-r-- 1 kbenne kbenne 455259926 Jul 28 20:32 LightsControl.building.fmu
-rw-rw-r-- 1 kbenne kbenne      5632 Jul 28 20:32 modelDescription.xml
-rw-rw-r-- 1 kbenne kbenne      1156 Jul 28 20:32 ModelicaBuildingsEnergyPlus.json
-rw-rw-r-- 1 kbenne kbenne      1090 Jul 28 20:32 model.spawn
drwxrwxr-x 2 kbenne kbenne      4096 Jul 28 20:32 resources
```

**Comment by kbenne** [comment]
After the previous two commits the simulation directory looks like this

```
kbenne@Darth-Vader:~/Development/spawn/build/runtest$ find .
.
./eplusout.mdd
./Buildings_ThermalZones_EnergyPlus_Validation_Actuator_LightsControl_log.txt
./eplusout.dxf
./eplusout.bnd
./eplusout.audit
./eplusout.eio
./sqlite.err
./eplusout.mtd
./eplusout.shd
./tmp-simulation-LightsControl.building
./tmp-simulation-LightsControl.building/resources
./tmp-simulation-LightsControl.building/resources/Energy+.idd
./tmp-simulation-LightsControl.building/resources/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw
./tmp-simulation-LightsControl.building/resources/SingleFamilyHouse_TwoSpeed_ZoneAirBalance.idf
./tmp-simulation-LightsControl.building/binaries
./tmp-simulation-LightsControl.building/binaries/linux64
./tmp-simulation-LightsControl.building/binaries/linux64/epfmi.so
./tmp-simulation-LightsControl.building/modelDescription.xml
./tmp-simulation-LightsControl.building/model.spawn
./tmp-simulation-LightsControl.building/LightsControl.building.fmu
./tmp-simulation-LightsControl.building/ModelicaBuildingsEnergyPlus.json
./eplusout.err
./Buildings_ThermalZones_EnergyPlus_Validation_Actuator_LightsControl_debug.txt
./Buildings_ThermalZones_EnergyPlus_Validation_Actuator_LightsControl_result.mat
./eplusout.rdd
./eplusout.end
./eplustbl.htm
./Buildings_ThermalZones_EnergyPlus_Validation_Actuator_LightsControl.fmu
./eplusout.eso
```

**Comment by mwetter** [comment]
@kbenne : That won't work for a model with 2 FMUs. Can you use `tmp-simulation-LightsControl.building/eplusout` (or similar subdirectory within `tmp-simulation-LightsControl.building` as the working directory).

**Comment by kbenne** [comment]
Actually when we discussed this morning I said `bui->fmu` sounds ok, but I was wrong. You might be thinking that `bui` is an instance of FMUBuilding https://github.com/lbl-srg/modelica-buildings/blob/issue2012_spawn_logging/Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusTypes.h#L42, but it is not. Rather `bui` is a pointer to an instance of a C++ class named `Spawn` https://github.com/NREL/Spawn/blob/develop/lib/spawn.hpp#L68. It is this way because that is the type I return from fmi2Instantiate https://github.com/NREL/Spawn/blob/develop/epfmi/EPFMI.cpp#L135. 

Anyway, I think I have a different solution that will achieve the same goal. It looks like I can use `fmuResourceURI` https://github.com/NREL/Spawn/blob/develop/epfmi/EPFMI.cpp#L94 given to fmi2Instantiate to locate the path we want.

**Comment by kbenne** [comment]
This will take care of it https://github.com/NREL/Spawn/commit/19b0c41f0e59c5e5e39d755ee332cd2c2b57c7ad

**Comment by mwetter** [comment]
@kbenne : Thanks, I close it as it is fixed on `issue1633_schedulesActuators`.

If it is easy, it would be cleaner to put all E+ outputs to `tmp-simulation-LightsControl.building/eplusout` (or similar directory within `tmp-simulation-LightsControl.building`) so they are grouped together.

**Comment by kbenne** [comment]
Honestly I was tempted to add this directory in my first cut, but decided to stick to what we discussed. Here is is with eplusout appended. https://github.com/NREL/Spawn/commit/5c8974afafb564d6d3c9b81517edbc7ba9b9e477

**Comment by mwetter** [comment]
Thanks, looks much less cluttered.
