### ISSUE TITLE
write error message if Spawn is compiled on non-supported OS

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#2067]
Compilation support for Spawn in the Buildings library for OS other than Linux will take some time. In order to give a reasonable error message, this issue is to add a compile time warning of the form:
```diff
$ git diff
diff --git a/Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusFMU.h b/Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusFMU.h
index 403fc465a..1650cb08f 100644
--- a/Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusFMU.h
+++ b/Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusFMU.h
@@ -5,6 +5,10 @@
 #ifndef Buildings_EnergyPlusFMU_h /* Not needed since it is only a typedef; added for safety */
 #define Buildings_EnergyPlusFMU_h
 
+#ifndef __linux__
+#error Modelica Spawn coupling is in this development phase only supported for Linux. Windows and OS X will be supported later.
+#endif
+
```
@kbenne : This will break your OS X and Windows builds. Is there an environment variable from your compilation toolchain that we can check for to bypass this `#error` directive?

**Comment by kbenne** [comment]
This won't actually impact me. I don't (yet) have tests that include the Modelica part. These seems like a good addition to me until there is support for non linux.

**Comment by kbenne** [comment]
Links to EnergyPlus FMU for all platforms are here https://github.com/NREL/Spawn#nightly-builds

**Comment by mwetter** [comment]
This will be address in https://github.com/lbl-srg/modelica-buildings/issues/2132 which contains https://github.com/lbl-srg/modelica-buildings/commit/6dfd383803d1dfb6fb9bbf0bb363fac70c97d8a5.
