### ISSUE TITLE
3 Way Valve missing components res1,2,3 in OMEditor

### ISSUE THREAD

**Issue by bvadrian** [lbl-srg/modelica-buildings#2080]
I was trying to use the Buildings Library with OMeditor. The three way valve under Fluid>actuators is missing components and all connectors are gone when class is opened.

Opening the same library in Dymola does not cause these problems

Example of error message when class is opened:
Unable to find component res3.y while parsing connection {inv.y,res3.y,}.

![image](https://user-images.githubusercontent.com/32707549/89635406-3a736300-d8a7-11ea-9766-ad66add3cfa9.png)

Is there a fix to this?

**Comment by mwetter** [comment]
There is no fix for this. It looks like OMEdit is not correctly parsing this model.
I suggest you issue a ticket on the OpenModelica issue tracker.
