### ISSUE TITLE
Remove parameter evaluation for applicable parameters after Modelon fix

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#2086]
Optimica has a bug that causes test to fail for vector parameters.

To temporarily deal with the issue we replaced parameter definitions such as:
```
  parameter Real LIFT_min[nChi](
    final unit=fill("K",nChi),
    final quantity=fill("TemperatureDifference",nChi),
    displayUnit=fill("degC", nChi))={12, 12}
      "Minimum LIFT of each chiller";
```
With the CDL compliant version:
```
  parameter Real LIFT_min[nChi](
    final unit=fill("K",nChi),
    final quantity=fill("TemperatureDifference",nChi),
    displayUnit=fill("degC", nChi))={12, 12}
      "Minimum LIFT of each chiller"
    annotation (Evaluate=true);
```
As `Evaluate=true` imposes undesired limitations for the translator, this issue is to remove  `annotation (Evaluate=true);` for all applicable parameter instances after Modelon fixes the error.

**Comment by milicag** [comment]
@JayHuLBL Thanks for clarifications.

**Comment by JayHuLBL** [comment]
@milicag 
With new OCT version `OCT-r17595_JM-r14295`, model `PrimarySystem.ChillerPlant.Tower.Validation.Controller` in branch `issue1378_staging_primarySequences` runs well after removing `Evaluate=true` from the annotation of the parameter `LIFT_min`, `TConWatSup_nominal`, `TConWatRet_nominal`, `TChiWatSupMin` of model `PrimarySystem.ChillerPlant.Tower.Controller`.

In OBC package, we could remove all the `Evaluate=true` annotation now.

**Comment by milicag** [comment]
This is addressed on branch `issue2293_chiller_plant_seq` that is in a [PR](https://github.com/lbl-srg/modelica-buildings/pull/2299).
