### ISSUE TITLE
Spawn crashes when the Output:Variable,*,Zone Mean Air Temperature,timestep; is commented on the IDF.

### ISSUE THREAD

**Issue by Helarga** [lbl-srg/modelica-buildings#2088]

**Comment by mwetter** [comment]
I cannot reproduce this. The model `Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput` outputs the `Zone Mean Air Temperature` which is not listed as an output in the IDF file.

**Comment by Helarga** [comment]
@mwetter Thank you for checking it, if i remember correctly, we faced this problem last year with an IDF generated from OS and it did the trick to uncomment Zone Mean Air Temperature variable. Maybe Kyle's latest updates on the radiant air temperature evaluation took care of it.

For the IDF in general, we need at least one "Output:Variable,*, Zone  ;" to be listed on the file in order to initialize Spawn, correct?

**Comment by kbenne** [comment]
> For the IDF in general, we need at least one "Output:Variable,*, Zone ;" to be listed on the file in order to initialize Spawn, correct?

@Helarga have not known that to be true, although I don't have a model to present as evidence in support or not. I suggest that we leave this one closed, and reopen if we have an example model to demonstrate the issue. In which case attach the model here.

**Comment by Helarga** [comment]
@kbenne thank you for your reply, I have tried it yesterday actually with an idf not included in the MBL and today again as a double check. It seems that an output variable has to be listed on the idf.
___
With "SingleFamilyHouse_TwoSpeed_ZoneAirBalance.idf" and the model of Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZone 

I removed all the outputs  except for commented one as in 
![image](https://user-images.githubusercontent.com/47648835/106294001-e0c37400-620b-11eb-8fb3-6702c78bb7e8.png)

 run the model and it failed as in 
![image](https://user-images.githubusercontent.com/47648835/106294103-fc2e7f00-620b-11eb-84e8-e59bfba2b0a3.png)

when i uncommented this output as in 

![image](https://user-images.githubusercontent.com/47648835/106294331-44e63800-620c-11eb-8204-77ec07bf728e.png)

the model run successfully but with these EP warnings
![image](https://user-images.githubusercontent.com/47648835/106294261-326bfe80-620c-11eb-86b2-44cc8f84a084.png)
