### ISSUE TITLE
Fix missing semicolons

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#2098]
Here referenced spot and the command below are missing a semicolon:

https://github.com/lbl-srg/modelica-buildings/blob/ce6344ec3174a2a6eb0daeaa26e22ffe6efb877f/Buildings/Resources/Scripts/Dymola/ConvertBuildings_from_7_to_8.0.0.mos#L19

@mwetter Would you like me to address this?

**Comment by mwetter** [comment]
@milicag : Yes, it would be great if you can correct this. Thanks.
