### ISSUE TITLE
Correct BooleanPulse block to avoid wrong result

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#2110]
Block `Modelica.Blocks.Sources.BooleanPulse` and `Buildings.Controls.OBC.CDL.Logical.Sources.Pulse` would give wrong results. 

For example, by setting its parameters as `width=0.5, period=4, startTime=-11`, 

1. run simulation with settings as: `experiment(StartTime=-3, StopTime=5, Tolerance=1e-06, __Dymola_Algorithm="Dassl")`, gives output:
![image](https://user-images.githubusercontent.com/23491921/91745300-9b711c80-eb6f-11ea-8dbb-9fce5c9895eb.png)

2. run simulation with settings as: `experiment(StartTime=-2, StopTime=5, Tolerance=1e-06, __Dymola_Algorithm="Dassl")`, gives output:
![image](https://user-images.githubusercontent.com/23491921/91745233-7b415d80-eb6f-11ea-86b0-92e2ca631362.png)

The simulation results should not shift along with the different simulation start times, in which, the second one is not correct.

**Comment by milicag** [comment]
Added an if condition to the initial equation to obtain the correct expected behavior:
![Capture](https://user-images.githubusercontent.com/5322943/91776416-2cf98200-eba2-11ea-89de-c55799df15b6.PNG)
