### ISSUE TITLE
Test Dymola 2021x beta

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#2122]
This issue is to test Dymola 2021x beta.
Note that it uses MSL 4.0.0

**Comment by beutlich** [comment]
Will Buildings be upgraded to MSL 4.0.0?

**Comment by mwetter** [comment]
I expect that the Buildings and IBPSA Libraries will be updated to MSL 4.0.0 this fall (when OCT also ships MSL 4.0.0).
