### ISSUE TITLE
move CDL.Continuous.NumberOfRequests to Obsolete

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#2124]
This block is not used in any sequence. Also, it would need to be refactored to add hysteresis and drop the strict inequality, similar to how we refactored the `Less` block in https://github.com/lbl-srg/modelica-buildings/issues/2076.

As this block seems not useful, I suggest it be moved to `Buildings.Obsolete`.

@JayHuLBL @milicag @karthikeyad-pnnl: Do you agree or do you see a need to keep it, in which case it would need to be refactored?

**Comment by karthikeyad-pnnl** [comment]
@mwetter: I agree. We don't see the need for this block in any of the boiler plant control sequences.

**Comment by milicag** [comment]
@mwetter I did not make use of it ever, so `Buildings.Obsolete` works for me.

**Comment by JayHuLBL** [comment]
@mwetter I agree to move it to Obsolete. Never used it before.
