### ISSUE TITLE
add blocks to CDL.*.Sources

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#2125]
This issue is to make the package `CDL.*.Sources` more uniform. Blocks that are applicable for all data types should be available for all these data types, and have the same parameters.

Specifically, the following blocks should be present (x means they are already present)
```
Continuous         Logical   Integer   Block
   x                 x           x     Constant
   x                 x                 Pulse (with a parameter nPeriod,
 rename nperiod                         renamed from nperiod to use camel case)
   x                                  TimeTable
```
Note that for `Logical.Pulse` the parameter `nPeriod` should be added.

**Comment by milicag** [comment]
`Pulse` related tasks are:

* [ ] rename `nperiod` to `nPeriod` in `Continuous.Sources.Pulse`
* [ ] add `nPeriod` to `Logical.Sources.Pulse` 
* [ ] create `Integer.Sources.Pulse` , also include  `nPeriod`

**Comment by milicag** [comment]
I added the `TimeTable` to logical and integer sources.
