### ISSUE TITLE
Add optimal start example models

### ISSUE THREAD

**Issue by kuzha** [lbl-srg/modelica-buildings#2126]
This issue is to add example models for the the block OptimalStart.

**Comment by mwetter** [comment]
@kuzha : I merged your PR and made minor edits. Can you please do the following:
- [ ] add examples that validate the correct calculation for optimal cooling (summer) and for the shoulder seasons if there is neither precooling nor preheating needed. For these, you could use extend the current examples, change the simulation time, update the documentation and provide the `.mos` file with the new simulation period.
- [ ] In the plots, also add the `optCoo.tOpt` (even for heating) as this will validate that it is indeed zero.
