### ISSUE TITLE
Propagate maximum and minimum airflow setpoints of the VAV terminal unit controller

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#2172]
In class `Buildings.Controls.OBC.ASHRAE.G36_PR1.TerminalUnits.Controller`, the parameter `V_flow_nominal` is only used for set default values of the design airflow setpoints `VDisCooSetMax_flow`, `VDisSetMin_flow`, `VDisHeaSetMax_flow` and `VDisConMin_flow`. These setpoints should not have default values and the parameter `V_flow_nominal` is not needed.

This issue is to
- [ ] delete `V_flow_nominal`,
- [ ] remove default values of the airflow setpoints,
- [ ] update parameter values of terminal controller in class `Buildings.Examples.VAVReheat.Guideline36`, so the `VDisCooSetMax_flow` is zone nominal flow, `VDisHeaSetMax_flow` will be 0.3 of zone nominal flow.

**Comment by AntoineGautier** [comment]
I would rather set `VDisHeaSetMax_flow` to `0.3 * V_flow_nominal` for consistency with `Buildings.Examples.VAVReheat.ASHRAE2006`.

**Comment by JayHuLBL** [comment]
PR #2173 which closes this issue:

- [x] did not remove `V_flow_nominal,
- [x] changed the default heating maximum flow to `0.3*V_flow_nominal`,
- [x] no change to the model `Buildings.Examples.VAVReheat.Guideline36`.

The todo that shows above will be done after upgrading to G36 official release,
- the `V_flow_nominal` will be removed,
- there will be no default value to these setpoints,
- the setpoints values of terminal controller in class `Buildings.Examples.VAVReheat.Guideline36` will need to be specified.
