### ISSUE TITLE
UrbanOpt_TimeSeries terminal Unit: heating and chilled water deltaT is very low comparing to the nominal value

### ISSUE THREAD

**Issue by Helarga** [lbl-srg/modelica-buildings#2202]
For the time series model at Buildings.Applications.DHC.Loads.Examples.CouplingTimeSeries
which lives in the staging branch of issue1437_district_heating_cooling

the heating and chilled water temperature difference across the terminal unit heat exchanger is very low "0.5degC in case of heating and 0.2degC in case of cooling" comparing to the nominal deltaT of 5 degC.

for heating terminal unit:

![image](https://user-images.githubusercontent.com/47648835/97606829-d8be2300-19d5-11eb-8718-88284fbc2c42.png)

for cooling terminal unit:

![image](https://user-images.githubusercontent.com/47648835/97606762-c512bc80-19d5-11eb-8d19-8cee0c63eeb0.png)

**Comment by AntoineGautier** [comment]
Nice catch, thanks.
That is indeed a bug. The nominal HHW and CHW mass flow rate in the FCU components of `Buildings.Applications.DHC.Loads.Examples.BaseClasses.BuildingTimeSeries` should be scaled by `1 / facSca` as it is done in `Buildings.Applications.DHC.Loads.Validation.TerminalUnitScaling`.

**Comment by AntoineGautier** [comment]
This will be addressed through https://github.com/lbl-srg/modelica-buildings/issues/2302.
