### ISSUE TITLE
Interface with geojson-modelica-translator

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#2204]
Note: This issue should stay open for reference, as long as `issue2204_gmt_mbl` is alive.

This issue is to create 

- an interface branch with the GMT according to the [new git workflow](https://docs.google.com/document/d/1EfFXuyeXJ0E5eLWKOT7GBdEhNJvWmOtbsvBeqzqEMmo/edit) adopted for URBANopt-Modelica: the corresponding branch is `issue2204_gmt_mbl`, it will be used to merge developments that are still in beta version,
- a frozen branch that include empty packages to be used as placeholders for URBANopt developments:  the corresponding branch is `issue2204_gmt_mbl_master`, empty packages needed to host new developments shall be checked out manually from this branch, according to the `Experimental` package structure:

```
(base) ~/gitrepo/modelica-buildings[issue2204_gmt_mbl_master]$ tree -L 3 Buildings/Experimental/
Buildings/Experimental/
├── CoolingPlants
│   ├── AirCooled
│   │   ├── package.mo
│   │   └── package.order
│   ├── BaseClasses
│   │   ├── package.mo
│   │   └── package.order
│   ├── Controls
│   │   ├── package.mo
│   │   └── package.order
│   ├── Examples
│   │   ├── package.mo
│   │   └── package.order
│   ├── package.mo
│   ├── package.order
│   └── WaterCooled
│       ├── package.mo
│       └── package.order
├── DHC
│   ├── CentralPlants
│   │   ├── BaseClasses
│   │   ├── Combined
│   │   ├── Cooling
│   │   ├── Heating
│   │   ├── package.mo
│   │   └── package.order
│   ├── Controls
│   │   ├── package.mo
│   │   ├── package.order
│   │   ├── Subsequences
│   │   └── Validation
│   ├── EnergyTransferStations
│   │   ├── BaseClasses
│   │   ├── Combined
│   │   ├── Cooling
│   │   ├── Heating
│   │   ├── package.mo
│   │   └── package.order
│   ├── Examples
│   │   ├── Combined
│   │   ├── Cooling
│   │   ├── Heating
│   │   ├── package.mo
│   │   └── package.order
│   ├── Loads
│   │   ├── BaseClasses
│   │   ├── Controls
│   │   ├── Examples
│   │   ├── FlowDistribution.mo
│   │   ├── Loads
│   │   ├── package.mo
│   │   ├── package.order
│   │   ├── SimpleRoomODE.mo
│   │   ├── Types.mo
│   │   └── Validation
│   ├── Networks
│   │   ├── BaseClasses
│   │   ├── package.mo
│   │   └── package.order
│   ├── package.mo
│   ├── package.order
│   └── ThermalStorages
│       ├── BaseClasses
│       ├── package.mo
│       └── package.order
├── DomesticHotWater
│   ├── BaseClasses
│   │   ├── package.mo
│   │   └── package.order
│   ├── Controls
│   │   ├── package.mo
│   │   └── package.order
│   ├── Examples
│   │   ├── package.mo
│   │   └── package.order
│   ├── package.mo
│   └── package.order
├── package.mo
└── package.order
```

Note that

- `issue2204_gmt_mbl` SHOULD accept pull requests with a "lighter" review process that can be carried out outside of LBL.
- `issue2204_gmt_mbl` SHALL NOT be merged into MBL `master`.
- `issue2204_gmt_mbl` will be deleted ultimately, the GMT stable release having only MBL `master` for dependency.

The existing staging branch for URBANopt-Modelica `issue1437_district_heating_cooling` will be retired.

**Comment by AntoineGautier** [comment]
The branch is created from https://github.com/lbl-srg/modelica-buildings/pull/2213/commits/abb6c296deaaf62a1988074a5395ef5d39aa76ce

It contains empty packages such as `Buildings.Experimental.CoolingPlants` that are placeholders for URBANopt future developments.

The branch `issue2203_moveDHC` that is merged into the master is generated by running the python script below which iteratively removes any empty packages under `Buildings.Experimental`. 

- URBANopt developments ready to be merged into MBL master SHALL apply this script.
- URBANopt developments only ready to be merged into `issue2204_gmt_mbl` SHALL NOT apply this script.

**Comment by AntoineGautier** [comment]
```
clean_experimental.py
```
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Run the script from ~/**/modelica-buildings/.
# Will iteratively remove any empty packages under `Buildings.Experimental`.

import glob
import os
import pathlib
import re
import shutil
from buildingspy.development import refactor


pkg_lib_path = 'Buildings.Experimental'
pkg_dir_path = re.sub(r'\.', os.path.sep, pkg_lib_path)

# Find deepest level of the directory tree.
pkg_ord_list = glob.glob(pkg_dir_path + '/**/package.order', recursive=True)
idx_deep = 0
for el in pkg_ord_list:
    idx_deep = max(
        idx_deep,
        len(el.split(os.path.sep)) - len(pkg_dir_path.split(os.path.sep))
    )

# Iteratively remove directory and update package order files.
for i in range(idx_deep):
    toclean = []
    for el in glob.glob(pkg_dir_path + '/**/package.order', recursive=True):
        with open(el) as fh:
            if len(list(fh)) == 0:
                toclean.append(pathlib.Path(el).parent)
    for dir_path in toclean:
        print(f'{i + 1}th pass: removing {dir_path}')
        shutil.rmtree(dir_path)
    refactor.write_package_order(directory=pkg_dir_path, recursive=True)
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Run the script from ~/**/modelica-buildings/.
# Will iteratively remove any empty packages under `Buildings.Experimental`.

import glob
import os
import pathlib
import re
import shutil
from buildingspy.development import refactor


pkg_lib_path = 'Buildings.Experimental'
pkg_dir_path = re.sub(r'\.', os.path.sep, pkg_lib_path)

# Find deepest level of the directory tree.
pkg_ord_list = glob.glob(pkg_dir_path + '/**/package.order', recursive=True)
idx_deep = 0
for el in pkg_ord_list:
    idx_deep = max(
        idx_deep,
        len(el.split(os.path.sep)) - len(pkg_dir_path.split(os.path.sep))
    )

# Iteratively remove directory and update package order files.
for i in range(idx_deep):
    toclean = []
    for el in glob.glob(pkg_dir_path + '/**/package.order', recursive=True):
        with open(el) as fh:
            if len(list(fh)) == 0:
                toclean.append(pathlib.Path(el).parent)
    for dir_path in toclean:
        print(f'{i + 1}th pass: removing {dir_path}')
        shutil.rmtree(dir_path)
    refactor.write_package_order(directory=pkg_dir_path, recursive=True)
```

**Comment by AntoineGautier** [comment]
> ```
> clean_experimental.py
> ```
> 
> ```
> #!/usr/bin/env python
> # -*- coding: utf-8 -*-
> 
> # Run the script from ~/**/modelica-buildings/.
> # Will iteratively remove any empty packages under `Buildings.Experimental`.
> 
> import glob
> import os
> import pathlib
> import re
> import shutil
> from buildingspy.development import refactor
> 
> 
> pkg_lib_path = 'Buildings.Experimental'
> pkg_dir_path = re.sub(r'\.', os.path.sep, pkg_lib_path)
> 
> # Find deepest level of the directory tree.
> pkg_ord_list = glob.glob(pkg_dir_path + '/**/package.order', recursive=True)
> idx_deep = 0
> for el in pkg_ord_list:
>     idx_deep = max(
>         idx_deep,
>         len(el.split(os.path.sep)) - len(pkg_dir_path.split(os.path.sep))
>     )
> 
> # Iteratively remove directory and update package order files.
> for i in range(idx_deep):
>     toclean = []
>     for el in glob.glob(pkg_dir_path + '/**/package.order', recursive=True):
>         with open(el) as fh:
>             if len(list(fh)) == 0:
>                 toclean.append(pathlib.Path(el).parent)
>     for dir_path in toclean:
>         print(f'{i + 1}th pass: removing {dir_path}')
>         shutil.rmtree(dir_path)
>     refactor.write_package_order(directory=pkg_dir_path, recursive=True)
> #!/usr/bin/env python
> # -*- coding: utf-8 -*-
> 
> # Run the script from ~/**/modelica-buildings/.
> # Will iteratively remove any empty packages under `Buildings.Experimental`.
> 
> import glob
> import os
> import pathlib
> import re
> import shutil
> from buildingspy.development import refactor
> 
> 
> pkg_lib_path = 'Buildings.Experimental'
> pkg_dir_path = re.sub(r'\.', os.path.sep, pkg_lib_path)
> 
> # Find deepest level of the directory tree.
> pkg_ord_list = glob.glob(pkg_dir_path + '/**/package.order', recursive=True)
> idx_deep = 0
> for el in pkg_ord_list:
>     idx_deep = max(
>         idx_deep,
>         len(el.split(os.path.sep)) - len(pkg_dir_path.split(os.path.sep))
>     )
> 
> # Iteratively remove directory and update package order files.
> for i in range(idx_deep):
>     toclean = []
>     for el in glob.glob(pkg_dir_path + '/**/package.order', recursive=True):
>         with open(el) as fh:
>             if len(list(fh)) == 0:
>                 toclean.append(pathlib.Path(el).parent)
>     for dir_path in toclean:
>         print(f'{i + 1}th pass: removing {dir_path}')
>         shutil.rmtree(dir_path)
>     refactor.write_package_order(directory=pkg_dir_path, recursive=True)
> ```

**Comment by dhblum** [comment]
@AntoineGautier According to the latest GMT docs at https://github.com/urbanopt/geojson-modelica-translator/blob/develop/docs/getting_started.rst, the GMT works with Building v9.0.0.

@nllong Does GMT plan to continue to use development branches starting with ``issue2204`` anymore?

**Comment by nllong** [comment]
We are on 9.1 now actually (latest main/master). From my perspective you can remove athe issue2204.* branches. Thanks for confirming!

Nicholas

Da: David Blum ***@***.***>
Data: venerdì, 18 novembre 2022, 09:25
A: lbl-srg/modelica-buildings ***@***.***>
Cc: Long, Nicholas ***@***.***>, Mention ***@***.***>
Oggetto: Re: [lbl-srg/modelica-buildings] Interface with geojson-modelica-translator (#2204)

CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@AntoineGautier<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAntoineGautier&data=05%7C01%7Cnicholas.long%40nrel.gov%7C504cd92afa894e6f5edb08dac98175c1%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C638043855129515592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eYp%2F0jpzWyxADES%2FzOHCuKl5OtwU77%2BVUkpvcVbx7vc%3D&reserved=0> According to the latest GMT docs at https://github.com/urbanopt/geojson-modelica-translator/blob/develop/docs/getting_started.rst<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Furbanopt%2Fgeojson-modelica-translator%2Fblob%2Fdevelop%2Fdocs%2Fgetting_started.rst&data=05%7C01%7Cnicholas.long%40nrel.gov%7C504cd92afa894e6f5edb08dac98175c1%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C638043855129515592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2B2kgfYzlgHdZy0Ii%2Fjn793BP6839bcMlM0jyjJkNulA%3D&reserved=0>, the GMT works with Building v9.0.0.

@nllong<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnllong&data=05%7C01%7Cnicholas.long%40nrel.gov%7C504cd92afa894e6f5edb08dac98175c1%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C638043855129515592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KDfuA1JEh6ArI7b35gaTQPQFnqmIajJUpyEtzbzIGuQ%3D&reserved=0> Does GMT plan to continue to use development branches starting with issue2204 anymore?

**Comment by mwetter** [comment]
Just for clarification: The next release will be 9.1 in December, based on the `maint_9.1.x` branch. Code freeze is on Nov 30. (https://github.com/lbl-srg/modelica-buildings/milestones)

The master is for the 10.0.0 release in 2023. 

The `maint_9.1.x` and `master` branch forked last week, the changes are mainly on the controls side that won't impact URBANopt.

**Comment by vtnate** [comment]
Urbanopt is using released versions of the MBL. This is my (Nate's) confirmation that this issue is no longer needed and can be closed. Thank you!

**Comment by dhblum** [comment]
Thanks @vtnate for confirming! Closing this issue.
