### ISSUE TITLE
Harmonize the spelling of set point in the library

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#2225]
Currently different spellings are used: setpoint, set-point or set point.
This issue is to adopt set point everywhere. This choice is consistent with several ASHRAE publications, namely Guideline 36 and [@dhblum could you please edit and provide the other reference you mentioned].

**Comment by milicag** [comment]
Maybe set-point will make everyone happy?

**Comment by mwetter** [comment]
Guideline 36 used for the public review draft setpoint, and for the official release set point. Hence I suggest we use set point as well.

**Comment by milicag** [comment]
We could take the opportunity in the Wednesday 231P Call to ask if there is any preference for the sequence library.

**Comment by mwetter** [comment]
I would go with what the G36 committee already selected. I don't see a
rationale for trying to go another way.

**Comment by milicag** [comment]
Sounds reasonable to me.
