### ISSUE TITLE
Html  and annotation errors

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#2248]
This issue is to correct following errors:
- [ ] in class `Buildings.BoundaryConditions.WeatherData.BaseClasses.PartialLimiter`, following section misses `)`: `<i>y_internal=min(uMax, max(uMin, u)</i>`;
- [ ] in class `Buildings.Fluid.HeatPumps.EquationFitReversible`, in info, following section misses `)`:
```
<p align=\"center\" style=\"font-style:italic;\">
  P=
  ( &beta;<sub>1</sub>
  + &beta;<sub>2</sub> T<sub>loa,ent</sub>/T<sub>RefHeaLoa</sub>
  + &beta;<sub>3</sub> T<sub>sou,ent</sub>/T<sub>RefHeaSou</sub>
  + &beta;<sub>4</sub> m&#775;<sub>loa,ent</sub>/(m&#775;<sub>loa,0</sub> &nbsp; s)
  + &beta;<sub>5</sub> m&#775;<sub>sou,ent</sub>/(m&#775;<sub>sou,0</sub> &nbsp; s) &nbsp; P<sub>0</sub> &nbsp; s,
</p>
```
- [ ]  also in class `Buildings.Fluid.HeatPumps.EquationFitReversible`, in icon layer graphic has following:
```
        Rectangle(
          extent={{-44,50},{-40,10}},
          lineColor={ERROR,
                          0,0},
          fillColor={135,135,135},
          fillPattern=FillPattern.Solid),
```

- [ ] in class `Buildings.Utilities.Plotters.Examples.Scatter`, following section missing `)`:
```
that plots <i>(sin(t), cos(t)</i>, which will be a circle
with radius <i>1</i>,
and <i>(sin(t), cos<sup>2</sup>(t)</i>, which will be an arc
```
- [ ] in class `Buildings.Utilities.Plotters.Examples.TimeSeries`, following section missing `)`:
```
This example demonstrates the use of a plotter
that plots <i>(t, sin(t), cos(t), sin(t)*cos(t)</i> in
one plot, and
<i>(t, sin(t), cos(t)</i> 
in another plot.
```
---
- [ ] in calss `Buildings.Examples.VAVCO2.BaseClasses.Suite`, the lines in icon layer are specified as, for example, 
```
Line(points=[-136,180; 190,180; 252,180]),
Line(points=[192,180; 192,40; 222,20]),
```
Suggest to change it as:
```
Line(points={{-136,180}, {190,180}, {252,180}}),
Line(points={{192,180}, {192,40}, {222,20}}),
```
---

**Comment by mwetter** [comment]
@JayHuLBL : `PartialLimiter` comes from the IBPSA library, so please fix it there. It then will be merged next time we merge the IBPSA library to Buildings.

The `Line` annotations violate the Modelica language. `Scatter` and `TimeSeries` are errors in the documentation. Can you please fix them on the branch `maint_7.0.x` (maintenance branch), and then make a PR from that branch to the master. We use `maint_7.0.x` to fix bugs where the Modelica language is violated. This branch will be used to test OpenModelica.
