### ISSUE TITLE
Refactor VAVReheat models with replaceable AHU model conforming with Linkage template structure

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#2260]
What needs to be done:

- [ ] Create an AHU model with the system configuration currently implemented in `Buildings.Examples.VAVReheat.Guideline36` and conforming with Linkage template structure illustrated in `Buildings.Experimental.Templates.Commercial.VAV.AHUs.AHULayout` of branch `issue1374_templateVAV`
- [ ] Refactor the models in `Buildings.Examples.VAVReheat` with a replaceable AHU model defaulting to the above one

**Comment by JayHuLBL** [comment]
@AntoineGautier I am cleaning-up OBC related issues and see this is still open. Have it been addressed?

**Comment by AntoineGautier** [comment]
I think we can close this as not addressed. @mwetter please confirm.
Now the plan is rather to develop a template model of a complete VAV system (AHU and terminal units serving several rooms), including
- Equipment model development and testing
- Integration with EnergyPlus model
- Routing component to specify flow paths between zones and systems, see `Buildings.Electrical.Transmission.Grids.PartialGrid`
- Script for sizing based on peak loads (generalized version of LDRD work)
- Integration into ctrl-flow: schedule page to configure the zone-system relationships

We were tentative to include this in Solamen subcontract for FY23 but we had to postpone due to limited resources (time and budget).

**Comment by mwetter** [comment]
Yes, this is superseded with the new templating.
