### ISSUE TITLE
URBANopt generic cooling plant model development

### ISSUE THREAD

**Issue by JingWang-CUB** [lbl-srg/modelica-buildings#2264]
This issue addresses the development of a cooling plant model to be used in the URBANopt GMT workflow.

**Comment by JingWang-CUB** [comment]
Hi @AntoineGautier , can we repurpose this issue for merging the generic cooling plant models into the `master` branch? If so, could you please create a new branch called `issue2264_generic_cooling` based on the `master`? Otherwise, please feel free to close this issue and I will create a new dedicated issue. Thanks!

**Comment by AntoineGautier** [comment]
Hi @JingWang-CUB
It's here: https://github.com/lbl-srg/modelica-buildings/tree/issue2264_generic_cooling
Please consider extending from `Buildings.Experimental.DHC.CentralPlants.BaseClasses.PartialPlant` to build the generic plant model.

**Comment by JingWang-CUB** [comment]
Thanks @AntoineGautier , I will check it out.

**Comment by AntoineGautier** [comment]
@JingWang-CUB Please check out manually the empty packages you need from `issue2204_gmt_mbl_master`, see `Experimental` package structure below.
This branch is frozen and not in sync with the master. This is because empty packages were removed from the master. So if you merge the master into `issue2204_gmt_mbl_master` (or the other way around) git will detect that this removal was ulterior and will only keep the packages currently on the master.

```
(base) ~/gitrepo/modelica-buildings[issue2204_gmt_mbl_master]$ tree -L 3 Buildings/Experimental/
Buildings/Experimental/
├── CoolingPlants
│   ├── AirCooled
│   │   ├── package.mo
│   │   └── package.order
│   ├── BaseClasses
│   │   ├── package.mo
│   │   └── package.order
│   ├── Controls
│   │   ├── package.mo
│   │   └── package.order
│   ├── Examples
│   │   ├── package.mo
│   │   └── package.order
│   ├── package.mo
│   ├── package.order
│   └── WaterCooled
│       ├── package.mo
│       └── package.order
├── DHC
│   ├── CentralPlants
│   │   ├── BaseClasses
│   │   ├── Combined
│   │   ├── Cooling
│   │   ├── Heating
│   │   ├── package.mo
│   │   └── package.order
│   ├── Controls
│   │   ├── package.mo
│   │   ├── package.order
│   │   ├── Subsequences
│   │   └── Validation
│   ├── EnergyTransferStations
│   │   ├── BaseClasses
│   │   ├── Combined
│   │   ├── Cooling
│   │   ├── Heating
│   │   ├── package.mo
│   │   └── package.order
│   ├── Examples
│   │   ├── Combined
│   │   ├── Cooling
│   │   ├── Heating
│   │   ├── package.mo
│   │   └── package.order
│   ├── Loads
│   │   ├── BaseClasses
│   │   ├── Controls
│   │   ├── Examples
│   │   ├── FlowDistribution.mo
│   │   ├── Loads
│   │   ├── package.mo
│   │   ├── package.order
│   │   ├── SimpleRoomODE.mo
│   │   ├── Types.mo
│   │   └── Validation
│   ├── Networks
│   │   ├── BaseClasses
│   │   ├── package.mo
│   │   └── package.order
│   ├── package.mo
│   ├── package.order
│   └── ThermalStorages
│       ├── BaseClasses
│       ├── package.mo
│       └── package.order
├── DomesticHotWater
│   ├── BaseClasses
│   │   ├── package.mo
│   │   └── package.order
│   ├── Controls
│   │   ├── package.mo
│   │   └── package.order
│   ├── Examples
│   │   ├── package.mo
│   │   └── package.order
│   ├── package.mo
│   └── package.order
├── package.mo
└── package.order
```

**Comment by JingWang-CUB** [comment]
@AntoineGautier Thanks for your update. It makes sense to me. Will do as instructed.
