### ISSUE TITLE
Single Zone VAV Conventional Controller Not Cooling in Setup

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/modelica-buildings#2265]
I believe there is a bug in ``Buildings.Air.Systems.SingleZone.VAV.ChillerDXHeatingEconomizerController`` where the controller does not turn on the fan if cooling is needed in setup (that is, during unoccupied hours but the room temperature still goes above the higher zone air temperature cooling setpoint).

In addition, I believe:
- the controller component model should be located in ``Buildings.Air.Systems.SingleZone.VAV.BaseClasses`` with the other controllers
- it's name changed to ``ControllerChillerDXHeatingEconomizer`` to be more consistent with the other controllers
- validation example added to ``Buildings.Air.Systems.SingleZone.VAV.BaseClasses.Validation`` to check for the above condition and make sure it is fixed

A validation model has been made to reproduce the bug.  It can be seen in the screenshot below at the time indicated.  Here, the fan should turn on to cool the space, but does not (as seen in the second plot).

<img width="1305" alt="Screen Shot 2020-11-20 at 5 04 11 PM" src="https://user-images.githubusercontent.com/19480999/99854327-990cd600-2b52-11eb-9fbc-9b2df21f4a1d.png">

The proposed fix is to add a connection between ``orFan`` and ``chOnTRoo`` as shown in the figure below.  Note that the existing description of ``orFan`` is ``"Switch fan on if heating, cooling, or occupied"`` so I believe this issue address the already intended operation.

<img width="633" alt="Screen Shot 2020-11-20 at 5 06 11 PM" src="https://user-images.githubusercontent.com/19480999/99854381-b9d52b80-2b52-11eb-8a3a-ec7dba033be6.png">

Then, the validation model shows the desired behavior in the Figure below.

<img width="1299" alt="Screen Shot 2020-11-20 at 5 07 51 PM" src="https://user-images.githubusercontent.com/19480999/99854509-f2750500-2b52-11eb-8ce8-6a049d3b05d1.png">

**Comment by dhblum** [comment]
My above comments are addressed in https://github.com/lbl-srg/modelica-buildings/pull/2266.

**Comment by mwetter** [comment]
Merged on the master.
