### ISSUE TITLE
LMTD computation does not support equal temperature differences

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/modelica-buildings#2268]
When the flow rates at both sides of a heat exchanger are balanced, the temperature differences between both streams are identical and consequently the temperature differences between the inlets/outlets are also equal. In this case `dT1=dT2` in `Buildings.Fluid.HeatExchangers.BaseClasses.lmtd`, which causes `0/0` in `lmtd :=(dT2 - dT1)/Modelica.Math.log(dT2/dT1);`. 

I propose to reformulate

```
lmtd := if abs(dT1-dT2)< Modelica.Constants.small then dT1 else (dT2 - dT1)/Modelica.Math.log(dT2/dT1);
```
since the 'logarithmic mean temperature' difference for constant temperature difference simply equals the constant temperature difference.

**Comment by AntoineGautier** [comment]
@Mathadon See also https://github.com/lbl-srg/modelica-buildings/issues/1515

**Comment by Mathadon** [comment]
aha. Thanks for that link.

> I will close this unless there is a need and a test model. The current implementation states "Note that the implementation requires the temperature differences to be non-zero. "

I saw that line but I figured it does not apply to what I was doing. More accurate would be "Note that the implementation requires the temperature differences to be not equal."

Note that the limit of`(dT2 - dT1)/Modelica.Math.log(dT2/dT1)` function is `dT1`, so there should be no discontinuity unless there is numerical noise in the evaluation of `(dT2 - dT1)/Modelica.Math.log(dT2/dT1)`as `dT1` approaches `dT2`, in which case there's not much point to avoid a discontinuity. 

See
https://www.wolframalpha.com/input/?i=limit+%28a-x%29%2Flog%28a%2Fx%29%2C+x-%3Ea

**Comment by AntoineGautier** [comment]
@Mathadon Thanks for the precision. 
Reconsidering all this, my best guess is that `Fluid.HeatExchangers.BaseClasses.lmtd` was initially developed as a simple means to compute parameter values (which is the only use case in the library where it is used to compute UA nominal values). Perhaps the important admonition missing in the function's documentation is that it is not intended to be used with continuous time variables. To support this use case, we need to guard against `dT1 = dT2`, but also against `dT1 = 0`, `dT2 = 0 ` and `dT1 / dT2 < 0`. And eventually I am not sure that we can guarantee that the models using this function in the equation section would not yield solutions violating the second Law.
On the other hand we have the eps-NTU implementation that is numerically robust, covers various HX configurations, and inherently yields solutions consistent with the second Law.

**Comment by mwetter** [comment]
I will update the documentation to make it clearer.

**Comment by Mathadon** [comment]
Ok, thanks!
