### ISSUE TITLE
URBANopt Steam Boiler Model Development

### ISSUE THREAD

**Issue by khinkelman** [lbl-srg/modelica-buildings#2290]
This issue addresses the new steam boiler models that were developed as part of the URBANopt-Modelica project.

**Comment by khinkelman** [comment]
@AntoineGautier, could you please create a branch `issue2290_steam_boilers` from `master` for these developments? Thanks

**Comment by AntoineGautier** [comment]
@khinkelman Here: https://github.com/lbl-srg/modelica-buildings/tree/issue2290_steam_boilers

**Comment by khinkelman** [comment]
Hi @AntoineGautier, I believe we should be able to use this old branch still for the steam boiler models. If you agree, could you please pull the changes from the master to this branch so that it is up-to-date?
Thanks!

@SaranyaAnbarasu: just copying you here as well so that you are aware of the status.

**Comment by AntoineGautier** [comment]
@khinkelman Correct, you can start from this branch that is now identical to the master.
```
(base) ~/gitrepo/modelica-buildings[issue2290_steam_boilers]$ git diff origin/master
(base) ~/gitrepo/modelica-buildings[issue2290_steam_boilers]$ 
```

**Comment by khinkelman** [comment]
- [ ] Note: a lower bound should be set for the fuel to air ratio to avoid division by zero error. 

See below as an example:
   ```
 // To compute the electrical power, we set a lower bound for eta to avoid
    // a division by zero.
    PEle = WFlo / Buildings.Utilities.Math.Functions.smoothMax(x1=eta, x2=1E-5, deltaX=1E-6);
    eta = etaHyd * etaMot;
```

**Comment by khinkelman** [comment]
Many thanks @dhblum for your time and efforts to complete these tasks! All work for outstanding steam district heating issues is complete from my end. Thanks for closing the related issues.
