### ISSUE TITLE
Avoid initial rising edge of Change block outputs

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#2294]
In block `Buildings.Controls.OBC.CDL.Integers.Change`, 
```
protected
  Integer u_start = 0 "Initial value of input";

initial equation
   pre(y) = y_start;
   pre(u) = u_start;

equation
  y = change(u);
  up = u > pre(u);
  down = u < pre(u);
```

If the input `u` has initial value that is greater than 0, `up` output will have a initial rising edge. The same is also applicable to the output `down`.

This issue is to correct the implementation to ensure that there is no initial rising edge to the outputs `y`, `up`, and `down`.

**Comment by milicag** [comment]
Nice catch.

**Comment by mwetter** [comment]
This block assigns
```modelica
protected 
  Integer u_start = 0 "Initial value of input";
```
which is not good. It should not assign an arbitrary initial value that cannot be changed.
