### ISSUE TITLE
Add Steam model

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#2304]
This issue is to add the steam model from https://github.com/ibpsa/modelica-ibpsa/pull/1395 for further testing and component development.

**Comment by mwetter** [comment]
@khinkelman : I merged the steam models from the `IBPSA library` to the new branch `issue2304_steam`.

**Comment by khinkelman** [comment]
@dhblum My understanding is yes. The steam medium has been merged with the master and there are no ongoing developments at this time.

**Comment by mwetter** [comment]
Yes, this can be closed.

**Comment by dhblum** [comment]
Thank you both!
