### ISSUE TITLE
About occupant latent heat gain in Buildings.ThermalZones.Detailed.BaseClasses.MixedAirHeatMassBalance

### ISSUE THREAD

**Issue by JamesCheng21** [lbl-srg/modelica-buildings#2312]
When using the library, I noticed that the `QLat_flow` is both modeled as (sensible?) heat gain to the air and converted to the amount of water vapor. I thought it should be only counted as water vapor, which is later dealt with in the cooling coil. Is there any specific reason for a treatment like this?

![image](https://user-images.githubusercontent.com/23103678/102380739-3f89b100-4003-11eb-9f0f-5799b198bb30.png)

P.S. thank you for developing this useful library!

**Comment by mwetter** [comment]
This implementation is correct. See also the info section of `Buildings.Fluid.MixingVolumes.MixingVolume` which states:
The variable Q_flow is used to add sensible and latent heat to the fluid.
Also, the implementation in `ConservationEquation` that is used in this model is
```modelica
der(U) = Hb_flow + Q_flow;
```
