### ISSUE TITLE
Wrong mode in ASHRAE2006 with OPTIMICA

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#2369]
The plot below shows the room set point temperature for cooling, with the top line from OPTIMICA and the bottom from Dymola.
![image](https://user-images.githubusercontent.com/1329080/108437402-1acbd880-7202-11eb-8127-9cc328379b4c.png)

OPTIMICA seems to be one cycle of in the state transition.
This was observed with commit abdc9f5e9925724500e1ba54ee020adcc20bbc71.
On the master, OPTIMICA produces the correct results.

**Comment by AntoineGautier** [comment]
@mwetter OPTIMICA seems correct (not Dymola) as the cooling set point gets reset *down* on operating hours.
![newplot](https://user-images.githubusercontent.com/10965994/108442684-51a6ec00-720c-11eb-92f0-8d8cf8e3ba0c.png)

**Comment by mwetter** [comment]
Commit https://github.com/lbl-srg/modelica-buildings/commit/fece53cd6fad3652a52463bdaf5e62e015c99b07 (on branch `issue2369_ASHRAE2006_Optimica_occupied`) reproduces the problem.

If run with Optimica (OCT-stable-r19089_JM-r14295 on Linux Ubuntu 18.04), the following log file is produced:
```
$ cat Buildings_ThermalZones_EnergyPlus_Examples_SmallOffice_ASHRAE2006Spring_log.txt
FMIL: module = FMILIB, log level = 4: Loading 'linux64' binary with 'default' platform types
FMIL: module = Model, log level = 4: [INFO][FMU status:OK] <JMIRuntime><value name="build_date">"Nov  2 2020"</value> <value name="build_time">"07:56:27"</value></JMIRuntime>
FMIL: module = Model, log level = 4: [INFO][FMU status:OK] <JMIRuntime>Using mathematical functions with domain checks.</JMIRuntime>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <ModelicaMessage category="warning"><value name="msg">"*** fixme: Compared tNonOcc &lt; tOcc = 7.4124e+06 &lt; 7.3656e+06 to give occupied = false&#10;"</value></ModelicaMessage>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <ModelicaMessage category="warning"><value name="msg">"*** fixme: End of initial algorithm: occupied = false&#10;"</value></ModelicaMessage>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning]   <ModelicaMessage category="warning"><value name="msg">"7344000.000 ASHRAE2006Spring.flo.building: Warning from EnergyPlus: ManageSizing: For a zone sizing run, there must be at least 1 Sizing:Zone input object. SimulationControl Zone Sizing option ignored.&#10;"</value></ModelicaMessage>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning]   <ModelicaMessage category="warning"><value name="msg">"7344000.000 ASHRAE2006Spring.flo.building: Warning from EnergyPlus: ManageSizing: For a plant sizing run, there must be at least 1 Sizing:Plant object input. SimulationControl Plant Sizing option ignored.&#10;"</value></ModelicaMessage>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning]   <ModelicaMessage category="warning"><value name="msg">"7344000.000 ASHRAE2006Spring.flo.building: Warning from EnergyPlus: ProcessScheduleInput: Schedule:Constant=""SPAWN-RADIANTGAINS-SCHEDULE"", Blank Schedule Type Limits Name input -- will not be validated.&#10;"</value></ModelicaMessage>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <AssertionError category="warning"><value name="msg">"*** fixme: Expected occupied = false, but received occupied = true"</value></AssertionError>
FMIL: module = Model, log level = 2: [INFO][FMU status:Error] Initialization failed.
```
E.g., Optimica computes `occupied = false` in the initial algorithm section, but then the assertion in the equation section (https://github.com/lbl-srg/modelica-buildings/blob/fece53cd6fad3652a52463bdaf5e62e015c99b07/Buildings/Controls/SetPoints/OccupancySchedule.mo#L119) triggers because `occupied == true`. The `when` condition has been altered so that the `when` clause does not trigger (which would give another assertion if it were triggered).

The simulation was done with this file:
[jmodelica.txt](https://github.com/lbl-srg/modelica-buildings/files/6013063/jmodelica.txt) (rename it to `.py` as github does not accept python files to be uploaded).

The figure below shows the outputs of Optimica (top) and Dymola (bottom):
![image](https://user-images.githubusercontent.com/1329080/108565190-229a8400-72b9-11eb-8880-62ab03eddee4.png)

**Comment by mwetter** [comment]
Modelon ticket is Modelon #2021022039000016
