### ISSUE TITLE
PipeAutosize fails to translate with OCT

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#2435]
The model `Buildings.Experimental.DHC.Examples.Combined.Generation5.Networks.BaseClasses.PipeAutosize` fails to translate with OCT.
Modelon ticket is 2021022539000525, see attached email.
[Modelon.2021022539000525.pdf](https://github.com/lbl-srg/modelica-buildings/files/6274300/Modelon.2021022539000525.pdf)
This can be reproduced with the minimum example below.
```
model MinimumExample1

  model PipeAutosize
    parameter Modelica.SIunits.Length dh(
      fixed=false,
      start=0.2,
      min=0.01)
      "Hydraulic diameter (assuming a round cross section area)";
    parameter Modelica.SIunits.PressureDifference dpStraightPipe_nominal(
      displayUnit="Pa")=
        Modelica.Fluid.Pipes.BaseClasses.WallFriction.Detailed.pressureLoss_m_flow(
          m_flow=1,
          rho_a=1.2,
          rho_b=1.2,
          mu_a=0.001,
          mu_b=0.001,
          length=1,
          diameter=dh,
          roughness=2.5e-5,
          m_flow_small=1e-4)
    "Pressure loss of a straight pipe at m_flow_nominal";
    initial equation
      dpStraightPipe_nominal = 200;
  end PipeAutosize;

  PipeAutosize pip;

initial equation

  Modelica.Utilities.Streams.print("pip.dh=" + String(pip.dh));

  annotation (uses(Modelica(version="3.2.3")));
end MinimumExample1;
```

**Comment by mwetter** [comment]
@AntoineGautier  : I mentioned this yesterday in my Modelon meeting and Christian will follow up to see if this is fixed in the next release.

**Comment by mwetter** [comment]
@AntoineGautier This should be fixed in OCT next week, at which time we should update the OCT binaries.
