### ISSUE TITLE
Models in DHC.Examples.Combined.Generation5.Examples fail to compile with OCT

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#2436]
Models in `Buildings.Experimental.DHC.Examples.Combined.Generation5.Examples` fail to compile with OCT.
This issue is independent from #2435: it appears when replacing the pipe model `Buildings.Experimental.DHC.Examples.Combined.Generation5.Networks.BaseClasses.PipeAutosize` (which causes the error reported in #2435) with `Buildings.Experimental.DHC.Examples.Combined.Generation5.Networks.BaseClasses.PipeStandard`.
Modelon ticket is 2021022539000651, see attached email (which provides a link to my private fork of MBL using the  `PipeStandard` model.)
[Modelon.2021022539000651.pdf](https://github.com/lbl-srg/modelica-buildings/files/6274335/Modelon.2021022539000651.pdf)

**Comment by mwetter** [comment]
@AntoineGautier This is fixed in the stable OCT release from last week, which we should get soon.
