### ISSUE TITLE
Variability issues in multiple example models

### ISSUE THREAD

**Issue by perost** [lbl-srg/modelica-buildings#2438]
Many examples in the library contains the pattern:
```Modelica
model M
  parameter SomeDataRecord dat;
end M;

model Example
  SomeDataRecord dat;
  M m(dat = dat);
end Example;
```
There's been some confusion in the past whether a record that only contains parameters is itself a parameter, but [#1832](https://github.com/modelica/ModelicaSpecification/issues/1832) makes it clear that this is not the case. Record instances used to modify parameters must therefore be declared as parameters themselves.

OpenModelica ticket: https://trac.openmodelica.org/OpenModelica/ticket/6206

**Comment by mwetter** [comment]
This has been corrected on the master and maintenance branches.
