### ISSUE TITLE
Output variable from Spawn is not updated in the first few hours of simulation (LightsControl)

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#2450]
From the master (commit a55e89c4c38025d296d17a716ffcffb92a042bbe), the command
```
simulateModel("Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.LightsControl", stopTime=172800, method="Cvode", tolerance=1e-06, resultFile="LightsControl");
```
retrieves the correct output of the lighting power ("Lights Electricity Rate"):

![image](https://user-images.githubusercontent.com/1329080/114770595-79a06080-9d20-11eb-851f-6819c1b65e01.png)

From commit b00169b7fc53fd0d8776c3d6556cc22be549a43c which is from branch `issue2358_spawn_surface`, the output `ligPow.y` is 50 rather than 0 until the actuator first overrides the value.

The command
```
simulateModel("Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.LightsControl(PLig(realFalse=0))", stopTime=172800, method="Cvode", tolerance=1e-06, resultFile="LightsControl");
```
produces this result:
![image](https://user-images.githubusercontent.com/1329080/114771008-f2072180-9d20-11eb-8561-88b98b6ddc06.png)

However, the command
```
simulateModel("Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.LightsControl(PLig(realFalse=500))", stopTime=172800, method="Cvode", tolerance=1e-06, resultFile="LightsControl");
```
produces the correct result:

![image](https://user-images.githubusercontent.com/1329080/114771629-a5701600-9d21-11eb-9af5-9fa6fc108e90.png)

It looks like setting the value to zero is being ignored, while setting it to 500 is not ignored.

**Comment by kbenne** [comment]
Fixed in https://github.com/NREL/Spawn/commit/9b1d5e0243cee95439709f782c8071d8d79b2b0d and new test added to show the fix.

**Comment by mwetter** [comment]
@kbenne : Can you please publish the binaries for https://gitlab.com/kylebenne/spawn/-/jobs/1187384151
The fail for me with 
![image](https://user-images.githubusercontent.com/1329080/115072382-61f5e300-9eac-11eb-94ab-ef6a0f0b7344.png)

**Comment by kbenne** [comment]
It is just a dumb kink in the process. The artifacts timeout and then gitlab removes them, so they aren't available to publish. And I can't preemptively schedule a build to publish. I have to wait until the tests pass. I need to figure out a solution.
