### ISSUE TITLE
Spawn does Updating Shadowing Calculations starting in January even if simulation starts in summer

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#2453]
On branch `scale_eplus_floor`, commit cf98372053afccc447a5c5987acc1f5e5a62fd1d 
the command:
```
OutputCPUtime = true;
Advanced.ParallelizeCode = false;
Advanced.SparseActivate = true;
modelInstance="Buildings.Examples.ScalableBenchmarks.ZoneScaling.EnergyPlus.Large4Floors()";
simulateModel(modelInstance, startTime=16848000, stopTime=17280000, method="CVode", tolerance=1e-05, resultFile="Large4Floors", numberOfIntervals=500);
```
Takes about 60 seconds to initialize the model. Running dymosim from the bash console shows that EnergyPlus updates the shading calculations from the start of the year to the actually requested simulation period first:
```
Updating Shadowing Calculations, Start Date=01/08/2017
Continuing Simulation at 01/08/2017 for SPAWN-RUNPERIOD
Updating Shadowing Calculations, Start Date=01/15/2017
Continuing Simulation at 01/15/2017 for SPAWN-RUNPERIOD
Updating Shadowing Calculations, Start Date=01/22/2017
...
Updating Shadowing Calculations, Start Date=06/25/2017
Continuing Simulation at 06/25/2017 for SPAWN-RUNPERIOD
Updating Shadowing Calculations, Start Date=07/02/2017
Continuing Simulation at 07/02/2017 for SPAWN-RUNPERIOD
Updating Shadowing Calculations, Start Date=07/09/2017
Continuing Simulation at 07/09/2017 for SPAWN-RUNPERIOD
```
This takes considerable time (about a minute). This issue is to see if EnergyPlus can be changed so it only computes the shading calculations that are needed for the simulation.

**Comment by kbenne** [comment]
This has been at the top of @nllong 's list for a while. Happy to get this in the queue. The solution is to look at the given fmu start time and then modify the idf file run period appropriately.

**Comment by kbenne** [comment]
@mwetter correct me if I'm wrong, but I think we are going to table this for 9.0 release.

**Comment by mwetter** [comment]
@kbenne : Correct, that's for past 9.0.

**Comment by mwetter** [comment]
This should be fixed on the master. LBL to check.

**Comment by mwetter** [comment]
This is now corrected on the master branch (as tested by running the above model on the console with OpenModelica with start time of 300 days.
