### ISSUE TITLE
Spawn should reject other side surface to be the front surface if the other side surface temperature is set

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#2457]
The following command produces non-physical results:
```
simulateModel("Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.RadiantHeatingCooling(building(idfName=Modelica.Utilities.Files.loadResource(\"modelica://Buildings/Resources/Data/ThermalZones/EnergyPlus/Examples/SingleFamilyHouse_TwoSpeed_ZoneAirBalance/SingleFamilyHouse_TwoSpeed_ZoneAirBalance.idf\")))", stopTime=432000, method="Cvode", tolerance=1e-06, resultFile="RadiantHeatingCooling");
```
Note that `Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.RadiantHeatingCooling` works for the idf file `SingleFamilyHouse_TwoSpeed_ZoneAirBalance_aboveSoil.spawn.idf`, but for the idf file that couples the other surface to the ground. The diff is
```
$ diff --horizon-lines=10 ./Resources/Data/ThermalZones/EnergyPlus/Examples/SingleFamilyHouse_TwoSpeed_ZoneAirBalance/SingleFamilyHouse_TwoSpeed_ZoneAirBalance_aboveSoil.idf ./Resources/Data/ThermalZones/EnergyPlus/Examples/SingleFamilyHouse_TwoSpeed_ZoneAirBalance/SingleFamilyHouse_TwoSpeed_ZoneAirBalance.idf
1,10d0
< !----------------------------------------------------------------------------------------------------------
< ! Spawn idf file.
< !
< ! This file is identical to SingleFamilyHouse_TwoSpeed_ZoneAirBalance.idf, except that
< !   BuildingSurface:Detailed,
< !    Living:Floor,            !- Name
< ! is above ground. In the original file, this surface boundary conditions is set to the front surface,
< ! but this would not be correct for the radiant floor.
< !
< !----------------------------------------------------------------------------------------------------------
589,590c579,580
<     Ground,                  !- Outside Boundary Condition
<     ,                        !- Outside Boundary Condition Object
---
>     Surface,                 !- Outside Boundary Condition
>     Living:Floor,            !- Outside Boundary Condition Object
```
The result with the idf file that uses the `Living:Floor` also as the outside boundary condition, the above `simulate` command yields:

![image](https://user-images.githubusercontent.com/1329080/115547865-a215e680-a25b-11eb-94cc-c158fa1da354.png)

I don't see a use case where setting the back surface condition to the front surface condition in EnergyPlus is meaningful if the back surface temperature is set from Modelica. EnergyPlus should therefore reject such models with an error.

This is with commit 9220a9fe7763db01ab7923aa93fb9b3d6e53683c

**Comment by mwetter** [comment]
EnergyPlus to reject the model after the logging is set up.

**Comment by kbenne** [comment]
@mwetter See https://github.com/NREL/Spawn/commit/a2a9e1041c796c5ba7b3ee91470cc9d3de85d132 

The error is going to show up when EnergyPlus first begins to simulate, which is later than when the log function is established and I think later than you were hoping. Still early though. getReal and fmi2ExitInitializationMode will both trigger the EnergyPlus simulation to begin.

**Comment by kbenne** [comment]
See this test https://github.com/NREL/Spawn/blob/bda0024ded093b5589337d5c1a7abf44e0f92829/test/test_mbl_idf.cpp#L207 for details. Upon returning an error code, there will be a log message that looks like this, "Attempt to control surface named LIVING:FLOOR that has a self referencing exterior boundary condition. This is not supported by Spawn."

**Comment by mwetter** [comment]
This will be fixed through https://github.com/lbl-srg/modelica-buildings/pull/2483

The message is
```
0.000 RadiantHeatingCooling.building: Error from EnergyPlus: Attempt to control surface named LIVING:FLOOR that has a self referencing exterior boundary condition. This is not supported by Spawn
Error: The following error was detected at time: 0
Failed to get variables for RadiantHeatingCooling.livFlo

The stack of functions is:
Buildings.ThermalZones.EnergyPlus.BaseClasses.initialize
Buildings.ThermalZones.EnergyPlus.BaseClasses.initialize(
livFlo.adapter, 
building.isSynchronized)

FixInitials:Init: Integrator failed to start model.0.000 RadiantHeatingCooling.building: Fatal from EnergyPlus: EnergyPlus is not running
```
