### ISSUE TITLE
Spawn binaries have wrong version and hash code in README.md

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#2481]
The `README.md` files of the Spawn binary distribution have the wrong version and has code:
Version `Spawn-0.1.0-3ec0a1fa6e-Linux.tar.gz` contains in the README.md files the entries

```
_Version: 0.0.1_

_Build: 316d0c8c19_
```
I distribute these files, but my code does not read these values. They should nevertheless be either removed or corrected to avoid inconsistent information.

**Comment by kbenne** [comment]
The executable reports the version and build. I think remove is the best option. If they are ever re-introduced 1) I would consider a dedicated VERSION file 2) avoid hard coding and configure these values as it is done here https://github.com/NREL/Spawn/blob/develop/cli/config.hpp.in.

**Comment by mwetter** [comment]
For release, take out incorrect build and version number, in the future these two lines will no longer be part of the readme file.

**Comment by mwetter** [comment]
@kbenne : The wrong version number and hash code is still present in the latest Spawn distribution. Can you remove these or keep them current so I don't have to delete them manually:
```
$ head ./Buildings/Resources/bin/spawn-linux64/README.md
# Spawn 

_Version: 0.0.1_

_Build: 316d0c8c19_


This is the spawn executable. 
There are currently two capabilities provided by this program.
1. Create an FMU given an EnergyPlus idf file
$ head ./Buildings/Resources/bin/spawn-win64/README.md
# Spawn 

_Version: 0.0.1_

_Build: 316d0c8c19_


This is the spawn executable. 
There are currently two capabilities provided by this program.
1. Create an FMU given an EnergyPlus idf file

$ grep commit Buildings/Resources/src/ThermalZones/EnergyPlus/install.py 
    # The setup below lead to a specific commit being pulled.
    commit = "09f8cff897fac3aa6054e69f4c6d4b9bc923d2db"
    name_version = f"Spawn-0.1.0-{commit[0:10]}"

```

**Comment by kbenne** [comment]
The fix has been merged into the develop branch, it just didn't make the release tag. 

The tag moved and will move again due to the infiltration thing we are working on, but I hadn't back ported any other commits from develop during this process. Trying to make the infiltration change as minimal and surgical as possible. Having said this, the readme change is about as benign as it gets so now that the tag is moving anyway I can cherry pick it.
