### ISSUE TITLE
Missing experiment StopTime annotations

### ISSUE THREAD

**Issue by sjoelund** [lbl-srg/modelica-buildings#250]
OpenModelica now generates a conservative coverage report on (for example):
https://test.openmodelica.org/libraries/Buildings/Coverage.txt
https://test.openmodelica.org/libraries/Annex60/Coverage.txt

In it, you can see that for example Buildings.Examples.ChillerPlant.DataCenterContinuousTimeControl would not be tested when only looking for experiments with StopTime annotation (although I can see why the mos-script would be convenient; StartTime/StopTime does not allow multiplications to be used, only literal values).

You can also see which classes are unused (UsersGuide and Icons I guess are expected to be untested).

**Comment by mwetter** [comment]
This is fixed on the master branch and hence will be closed.
