### ISSUE TITLE
Invalid uses of commercialCable

### ISSUE THREAD

**Issue by perost** [lbl-srg/modelica-buildings#2503]
`commercialCable` is used in several places like this:
https://github.com/lbl-srg/modelica-buildings/blob/34b4bb945edc7b76a5e527145177da131c87515c/Buildings/Electrical/AC/OnePhase/Lines/Network.mo#L8
https://github.com/lbl-srg/modelica-buildings/blob/34b4bb945edc7b76a5e527145177da131c87515c/Buildings/Electrical/AC/ThreePhasesBalanced/Lines/Network.mo#L9
https://github.com/lbl-srg/modelica-buildings/blob/34b4bb945edc7b76a5e527145177da131c87515c/Buildings/Electrical/AC/ThreePhasesBalanced/Lines/Examples/ACSimpleGridMedium.mo#L8
https://github.com/lbl-srg/modelica-buildings/blob/34b4bb945edc7b76a5e527145177da131c87515c/Buildings/Electrical/AC/ThreePhasesBalanced/Lines/Examples/ACSimpleGridMedium.mo#L98
https://github.com/lbl-srg/modelica-buildings/blob/34b4bb945edc7b76a5e527145177da131c87515c/Buildings/Electrical/AC/ThreePhasesUnbalanced/Lines/Network_N.mo#L8
https://github.com/lbl-srg/modelica-buildings/blob/34b4bb945edc7b76a5e527145177da131c87515c/Buildings/Electrical/AC/ThreePhasesUnbalanced/Lines/Network.mo#L7

This does not seem to be correct though, since `commercialCable` is a scalar while `grid.cables` is an array.

**Comment by casella** [comment]
@perost, but isn't `lines `an array, perhaps?

**Comment by perost** [comment]
> @perost, but isn't `lines `an array, perhaps?

Yes, I missed that. Then it's probably correct.
