### ISSUE TITLE
HideResult annotation with string value in ThermalZones.Detailed.BaseClasses.RadiationTemperature

### ISSUE THREAD

**Issue by perost** [lbl-srg/modelica-buildings#2550]
RadiationTemperature contains the follow definition:
https://github.com/lbl-srg/modelica-buildings/blob/de057991f414851897aa1c2df0141a470356eb3c/Buildings/ThermalZones/Detailed/BaseClasses/RadiationTemperature.mo#L18-L19

The value in the HideResult annotations should just be `true` and not `"true"`.

**Comment by mwetter** [comment]
@perost : Thanks, I will correct it on the maintenance and master branches.
