### ISSUE TITLE
Missing parameter prefixes in ThermalZones.Detailed

### ISSUE THREAD

**Issue by perost** [lbl-srg/modelica-buildings#2555]
The following components are used as parameters but are not declared as such:
https://github.com/lbl-srg/modelica-buildings/blob/dd3df91c9bf47c13721c6f529f6f15e1fe9c703e/Buildings/ThermalZones/Detailed/Validation/BESTEST/Cases6xx/Case600FF.mo#L151-L155

https://github.com/lbl-srg/modelica-buildings/blob/dd3df91c9bf47c13721c6f529f6f15e1fe9c703e/Buildings/ThermalZones/Detailed/FLEXLAB/Rooms/X3B/Electrical.mo#L28-L31

**Comment by casella** [comment]
@JayHuLBL, @mwetter, please cherry-pick this commit into maint/7.0.x and maint/8.0.x branches, otherwise it won't be possible to use the library with OpenModelica.

**Comment by perost** [comment]
> @JayHuLBL, @mwetter, please cherry-pick this commit into maint/7.0.x and maint/8.0.x branches, otherwise it won't be possible to use the library with OpenModelica.

It's already done. It seems we also now test maint/7.0.x, see [this report](https://libraries.openmodelica.org/branches/master/Buildings_maint.7.0.x/Buildings_maint.7.0.x.html).

**Comment by casella** [comment]
I had checked[ the commits of the maint/7.0.x](https://github.com/lbl-srg/modelica-buildings/commits/maint_7.0.x) but I could not identify it. Now I see it on 29 June, I just had to search for the right commit SHA...

Case600FF now passes the frontend, see [maint report](https://libraries.openmodelica.org/branches/master/Buildings_maint.7.0.x/files/Buildings_maint.7.0.x_Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case600FF.err), so I confirm all's fine.

Case closed 😄
