### ISSUE TITLE
Some examples in ThermalZones.Detailed.Constructions.Examples uses undeclared variable

### ISSUE THREAD

**Issue by perost** [lbl-srg/modelica-buildings#2556]
The variable AGla is used in the following locations, but no such variable is declared in the models:
https://github.com/lbl-srg/modelica-buildings/blob/dd3df91c9bf47c13721c6f529f6f15e1fe9c703e/Buildings/ThermalZones/Detailed/Constructions/Examples/ExteriorWallWithWindow.mo#L108

https://github.com/lbl-srg/modelica-buildings/blob/dd3df91c9bf47c13721c6f529f6f15e1fe9c703e/Buildings/ThermalZones/Detailed/Constructions/Examples/ExteriorWallTwoWindows.mo#L118

**Comment by mwetter** [comment]
This is fixed on the`master` and `main_8.0.x` and `maint_7.0.x` branches.
