### ISSUE TITLE
Errors in example  "DataCenterContinuousTimeControl" within Building Libraries8.0 

### ISSUE THREAD

**Issue by ELINT599X** [lbl-srg/modelica-buildings#2574]
Dear Developers

I tested an example called "DataCenterContinuousTimeControl" in Building Libraries 8.0 but never run due to the following errors.
I appreciate if you can share some advice to run this example.

[7] 10:14:53 Symbol  Error
Too many equations, over-determined system. The model has 741 equation(s) and 739 variable(s).

[8] 10:14:53 Symbol  Error
$cse74 = Buildings.Fluid.Movers.BaseClasses.IdealSource$pumCHW$preSou.Medium.setState_phX(TCHWLeaCoi.port_b.p, TCHWLeaCoi.port_a.h_outflow, {}) has size 2 but 1 variables (roo.TRooAir)

[9] 10:14:53  Error
Internal error Transformation Module PFPlusExt index Reduction Method Pantelides failed!

[10] 10:14:53 Error
post-optimization module wrapFunctionCalls (simulation) failed.

**Version**
 - Modelica Buildings Library: 8.0
 - Modelica simulation 3.2.3
 - Operating system Windows 10

Best regard,

**Comment by mwetter** [comment]
Which simulation environment did you use? See also https://simulationresearch.lbl.gov/modelica/environments.html for supported tools.

**Comment by ELINT599X** [comment]
Thank your reply sir.

I use OpenModelica1.17.0-64bit.
I expected open source based OpenModelica can run your library.
Do we really need commercial based Dymola, OPTIMICA or JModelica ?

Best reagrds,

**Comment by mwetter** [comment]
OpenModelica does not yet work with all models as shown in the link above.
