### ISSUE TITLE
documentation: supported compilers for Spawn

### ISSUE THREAD

**Issue by thorade** [lbl-srg/modelica-buildings#2597]
I started looking into the EnergyPlus examples:
https://github.com/lbl-srg/modelica-buildings/tree/master/Buildings/ThermalZones/EnergyPlus/Examples
and at first try they did not compile for me because I was using an unsupported compiler. After switching to a different compiler version or compiler it works without any problems.

Does a list of supported or tested compilers/tools/operating systems exist somewhere? How much effort is it to add more supported combinations?

**Comment by thorade** [comment]
In this case, it failed with CentOS/RedHat and gcc 4.8.5, so I just wanted to know whether that would be expected to work, and we just had some library missing or wrong setting. It worked well on another computer with Ubuntu and a newer gcc.

**Comment by mwetter** [comment]
@thorade : We have not tested it on CentOS/RedHat, only on Ubuntu 18.04 and 20.04.
