### ISSUE TITLE
SpawnExternalObject.mo external C include *.c ?

### ISSUE THREAD

**Issue by kbenne** [lbl-srg/modelica-buildings#2606]
The SpawnExternalObject depends on an external C object, which is defined by the annotation:

```
    annotation (
      Include="#include <EnergyPlusWrapper.c>",
      IncludeDirectory="modelica://Buildings/Resources/C-Sources",
      Library={"ModelicaBuildingsEnergyPlus","fmilib_shared"});
```

https://github.com/lbl-srg/modelica-buildings/blob/v8.0.0/Buildings/ThermalZones/EnergyPlus/BaseClasses/SpawnExternalObject.mo#L96

 In this annotation it might be better to include the EnergyPlusWrapper.h file.

**Comment by mwetter** [comment]
Leave as is unless there is a problem on the integration side. 
C function are used to include the `ModelicaError` function.
