### ISSUE TITLE
cryptographicsHash.h definitions

### ISSUE THREAD

**Issue by kbenne** [lbl-srg/modelica-buildings#2607]
cryptographicsHash.h declares some functions that are conventionally declared by openssl. For example `SHA1`. 

https://github.com/lbl-srg/modelica-buildings/blob/v8.0.0/Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/cryptographicsHash.h#L40

I've wrestled with this causing a linker error due to duplicate symbols. I think it would be best to declare these functions static. ie.

```
-void SHA1(
+static void SHA1(
     char *hash_out,
     const char *str,
     int len);
```

I can PR this change if there is consensus.

**Comment by mwetter** [comment]
Please make a PR to make them static.

**Comment by mwetter** [comment]
This is on the master (4a6285f84726e0bfaa712d76a8e3ef1c7b418584)
