### ISSUE TITLE
Missing declaration of ModelicaFormatError in pythonWrapper.c

### ISSUE THREAD

**Issue by casella** [lbl-srg/modelica-buildings#2617]
The following identifier:
https://github.com/lbl-srg/modelica-buildings/blob/89bf74035bdea926701edef2c3dbf35f48b32680/Buildings/Resources/C-Sources/pythonWrapper.c#L42
is not defined in function pythonWrapper.c, hence OMC [fails](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Utilities.IO.Python36.Examples.KalmanFilter.err) reporting
```
Buildings 9.0.0-master/Resources/C-Sources/pythonWrapper.c:42:4: error: use of undeclared identifier "ModelicaFormatError"
```
please add the `ModelicaUtilities.h` file to the resources and `#include` it appropriately in the .c file.

Please also port this to `maint/7.0.x` and `maint/8.0.x` to ensure compatibility of versions 7 and 8 with OpenModelica.

**Comment by mwetter** [comment]
@JayHuLBL : Can you please make a pull request with these changes for the 3 branches.

**Comment by casella** [comment]
P.S. I guess Dymola includes this header automatically. Although this may be sensible, it is not mandated by the language specification, so I think it's best to add it explicitly, so there is no magic involved.

**Comment by mwetter** [comment]
I agree, relying on magic is never advisable, and risks portability.

**Comment by casella** [comment]
Great. We should see the improvement in the next [library test report](https://libraries.openmodelica.org/branches/master/Buildings_maint.7.0.x/Buildings_maint.7.0.x.html). Will reopen if something went wrong.

**Comment by casella** [comment]
Still pending, see #2627. Will close once the three branches are updated.

**Comment by mwetter** [comment]
This has been corrected on the master and on `maint_7.0.x` and `maint_8.0.x`.
