### ISSUE TITLE
Correct bug in `Experimental.DHC.CentralPlants.BaseClasses.PartialPlant`, refactor “if” statements used in fluid ports. 

### ISSUE THREAD

**Issue by mingzhe37** [lbl-srg/modelica-buildings#2639]
Hi Dr. Hu @JayHuLBL , could you please open a new branch for me to fix this bug? Please let me know if you have any questions. Thanks!

**Describe the bug**
The partial model `Experimental.DHC.CentralPlants.BaseClasses.PartialPlant` has a bug with the fluid ports. This model should enable and disable fluid ports functionally and graphically according to the `typ` value, but this function has been found to be invalid.

**To Reproduce**
1. Open model `Buildings.Experimental.DHC.CentralPlants.Cooling.Examples.Plant`
2. Set parameter `typ=Buildings.Experimental.DHC.Types.DistrictSystemType.Cooling`
3. As seen in image below, only fluid ports `port_aSerCoo` and `port_bSerCoo` (the pair of fluid ports on the bottom) should be enabled, and only the line showing connection between them (the pair of red and dark blue line on the bottom) should be enabled as well. However, the results shows that all fluid ports and lines are enabled. 

**Expected behavior**
Only fluid ports `port_aSerCoo` and `port_bSerCoo` (the pair of fluid ports on the bottom) should be enabled, and only the line showing connection between them (the pair of red and dark blue line on the bottom) should be enabled. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46808578/134255963-1614ab4c-eada-4a30-af13-e936b884c07b.png)

**Version**
 - Modelica Buildings Library: current master branch (update to commit 806aa91); this bug is related to commit 03be483
 - Modelica simulation environment: Dymola 2021/2021X/2022, OpenModelica 1.18.0
 - Operating system: Ubuntu 18.04.5 LTS (used with Dymola 2021), Windows 10 Pro (used with Dymola 2021/2021X/2022, OpenModelica 1.18.0)

**Additional context**
This error happens to all fluid ports. The error is caused by improper expression of the value assignment in the "if" statement, which located in `Experimental.DHC.CentralPlants.BaseClasses.PartialPlant` as follows:

![partial_model_1](https://user-images.githubusercontent.com/46808578/134255782-37171357-1686-4c53-a0a5-802c3daec416.png)

![partial_model_2](https://user-images.githubusercontent.com/46808578/134253321-fe67e740-cfc9-45df-976b-087c6595945c.png)

As shown above, the original implementation uses imported alias `TypDisSys` for the value assignment to `typ` in the “if” statements. However, the result shows this implementation doesn’t work, a full path `Buildings.Experimental.DHC.Types.DistrictSystemType` must be used instead of alias `TypDisSys`. 
This issue will refactor the expression of value assignment of `typ` in “if” statements to make this model enable and disable fluid ports correctly. Specifically, the full path is used in value assignment, and the multiple conditions for “if” statement would be combined into a single parameter with `protected` and `final` attributes. This approach is constant with other implementations in MBL like `Controls.OBC.CDL.Continuous.PID`, this will make it easier to further revise and maintain the code. 

I’ve also attached a simple example showing why using the single parameter is better when there are multiple conditions for “if” statements. The attachments include:
- `IfTest_ExampleDocumentation.docx`: Documentation on the simple example
- `IfTestNotDesired.txt`: Modelica model indicating the performance we do not want. As it is not allowed to attach a .mo file, please change the suffix to .mo to run the model.
- `IfTestDesired.txt`: Modelica model indicating the desired performance. As it is not allowed to attach a .mo file, please change the suffix to .mo to run the model.

[IfTestNotDesired.txt](https://github.com/lbl-srg/modelica-buildings/files/7206682/IfTestNotDesired.txt)
[IfTestDesired.txt](https://github.com/lbl-srg/modelica-buildings/files/7206683/IfTestDesired.txt)
[IfTest_ExampleDocumentation.docx](https://github.com/lbl-srg/modelica-buildings/files/7206684/IfTest_ExampleDocumentation.docx)

**Comment by JayHuLBL** [comment]
@mingzhe37 Please make the change through branch issue2639_ifExpressions.

**Comment by mingzhe37** [comment]
As this issue has been solved through https://github.com/lbl-srg/modelica-buildings/pull/2643, I closed this issue.
