### ISSUE TITLE
It does not allow me to simulate with the meteorological data obtained in meteonorm in epw format

### ISSUE THREAD

**Issue by Gerardocasio1617** [lbl-srg/modelica-buildings#2658]
It does not let me perform the simulation with the data obtained in meteornom with epw format.I have tried to change it to mos but I can not.
I need to simulate it with a specific date (example: simulate the day February 25-2021)
The data obtained in energy plus I do not know what date I made the meteorological data

the package is this
from the Buildings 7.00 library
[El_Paso_TX-hour-.csv](https://github.com/lbl-srg/modelica-buildings/files/7295562/El_Paso_TX-hour-.csv)

![image](https://user-images.githubusercontent.com/91864274/136240984-37991241-2ae2-44f5-b73b-bf03b881847d.png)

**Comment by mwetter** [comment]
See the info section of `ReaderTMY3`. The conversion supports .epw file to .mos file. CSV files are not supported, but you can write the .mos file manually as long as you keep the same structure.
