### ISSUE TITLE
Example model for Conventional AHU

### ISSUE THREAD

**Issue by Kanchan-Aggarwal** [lbl-srg/modelica-buildings#2662]
Hi, I am looking for a conventional AHU model (chiller based cooling) in Modelica. 
@mwetter 
It would be really helpful if you can guide me to some example model that can be used directly or after modifications. 
Thanks and regards,
Kanchan

**Comment by YashwanthVellala** [comment]
@mwetter sorry to comment on an issue that is closed. 
Could you please help pick an example model that represents a conventional RTU model as well in Modelica (buildings library)
