### ISSUE TITLE
AHU Model in Energy plus and controls strategy

### ISSUE THREAD

**Issue by Harsha17101992** [lbl-srg/modelica-buildings#2679]
@mwetter Hello good morning,
I want to build an AHU model with 5 zones in energy plus software. Can you please suggest a suitable example model for the same? Also, is PID/PI Control strategies supported in energy plus tool?
Request your reply.

**Comment by mwetter** [comment]
Please see https://simulationresearch.lbl.gov/modelica/userGuide/help.html for how to submit general questions (and I am not sure if your question is about EnergyPlus or Modelica.)
