### ISSUE TITLE
Correct structure of weather bus connections in Applications.DataCenters.ChillerCooled.Examples

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#2706]
This issue is to correct the connections of the weather bus in `Applications.DataCenters.ChillerCooled.Examples`.

The connections are of the form `connect(weaBus.TWetBul.TWetBul, cooModCon.TWetBul)` which looks incorrect and does not work with OpenModelica (it does work with OCT and Dymola).

**Comment by casella** [comment]
@mwetter, this was actually the [last remaining front-end issue](https://github.com/OpenModelica/OpenModelica/issues/7833) with Buildings 7.0.x in OpenModelica. Let's see if this PR actually solves it.

Thanks!

**Comment by perost** [comment]
I was wondering why a variable called `TWetBul` was being used as an expandable connector. The issue in OpenModelica is that we don't yet support adding new expandable connectors to expandable connectors through connections, which is not forbidden by the specification but does raise some questions.

**Comment by casella** [comment]
Yeah, expandable connectors within expandable connectors makes me a bit dizzy... 😄

**Comment by mwetter** [comment]
@perost : `TWetBul` should not have been used as an expandable connector. Not sure how it got in there and passed the review.

@casella : I think OMEdit still has an error with
`Buildings.Applications.DataCenters.ChillerCooled.Examples.IntegratedPrimaryLoadSideEconomizer`

When opening this model, I get
```
[4] 08:59:05 Scripting Error
Unable to find component chiWSE.yPum while parsing connection {pumSpeSig.y,chiWSE.yPum,}.

[5] 08:59:05 Scripting Error
Unable to find component chiWSE.yVal5 while parsing connection {yVal5.y,chiWSE.yVal5,}.

[6] 08:59:05 Scripting Error
Unable to find component chiWSE.yVal6 while parsing connection {yVal6.y,chiWSE.yVal6,}.
```

The model contains the statement
```modelica
extends
    Buildings.Applications.DataCenters.ChillerCooled.Examples.BaseClasses.PartialDataCenter(
    redeclare Buildings.Applications.DataCenters.ChillerCooled.Equipment.IntegratedPrimaryLoadSide chiWSE(
      addPowerToMedium=false,
      perPum=perPumPri)
  ...
```
and this new model contains the connectors `yPum`, `yVal5` and `yVal6`. The model however simulates with OMEdit.

This is with Buildings, `maint_7.0.x` (commit db3342c3e43a1624b7bb38d5f293edd171c62273) and OMEdit from OpenModelica 1.19.0~dev-330-ga25f5f3

**Comment by casella** [comment]
This is the [OMC Jenkins report](https://libraries.openmodelica.org/branches/history/master/2021-11-03%2003:08:30..2021-11-04%2003:47:24.html) following this commit. As expected the chiller models now work fine.

@mwetter, we still have issues with the FFD models in there, but I understand they somehow involve some external code, does it make sense that we actually test them with OMC?

**Comment by mwetter** [comment]
@casella : It makes sense to test them with OMC. Of the 7 cases with FFD, only two fail, both have a window (as opposed to only opaque constructions), none of the others have a window. They both fail with
```
Error: Internal error function createSimCode failed [Transformation from optimised DAE to simulation code structure failed]
```
I don't have a handle yet on what triggers this failure, but I don't think the root cause is the external code

**Comment by casella** [comment]
It could be #7999, let's see when that is fixed, hopefully soon.
