### ISSUE TITLE
Revise `Experimental.DHC.CentralPlants.Example.Plant.mo` for GMT extension

### ISSUE THREAD

**Issue by ChengnanShi-Work** [lbl-srg/modelica-buildings#2749]
Hi Dr.Hu @JayHuLBL , for the extension usage of GMT, I have made two minor changes for an existing example model `Experimental.DHC.CentralPlants.Example.Plant.mo` in MBL:

1. Add "replaceable" prefix for two parameters ("perChi", "pla") for new type redeclaring.
2. Add two more parameters ("dTApp" and "PFan_nominal") because they are also important parameters of the cooling plant which we wish to replace value for.

Here is the screenshots of what have been changed:

![image](https://user-images.githubusercontent.com/82961137/141206321-f557de73-3fdf-47be-90b3-d858cf9b4d45.png)

Could you please open a new branch for me to update these revision? Please let me know if you have any questions. Thanks!

**Comment by JayHuLBL** [comment]
@ChengnanShi-Work Please work on the issue in branch `issue2749_refactorParameters`.

**Comment by ChengnanShi-Work** [comment]
As this issue has been solved through #2769 , I closed this issue.
