### ISSUE TITLE
Edit CO2 generation calculation

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/modelica-buildings#2781]
This issue is just to update the calculation of CO2 generation in ``Buildings.Examples.VAVReheat.Validation.BaseClasses.Floor`` so as to directly use the output from internal gain schedule and assumed 0.05 ppl/m^2 population density, rather than a latent load per person assumption.  This should not change unit test results significantly, if at all, for ``Buildings.Examples.VAVReheat.Validation.TraceSubstances``.

**Comment by mwetter** [comment]
This is now on the master.
