### ISSUE TITLE
Spawn to handle idf files with Multiplier

### ISSUE THREAD

**Issue by SenHuang19** [lbl-srg/modelica-buildings#2852]
The output <code>QCon_flow</code> of the model <code>Buildings.ThermalZones.EnergyPlus.BaseClasses.ThermalZoneAdapter</code> seems to ignore the <code>Zone multiplier</code> in the input idf file

```EnergyPlus
Zone,
    Core_bottom,             !- Name
    0.0000,                  !- Direction of Relative North {deg}
    0.0000, 0.0000, 0.0000,             !- X,Y,Z  {m}
    1,                       !- Type
    10,                       !- Multiplier
    ,                        !- Ceiling Height {m}
    ,                        !- Volume {m3}
    autocalculate,           !- Floor Area {m2}
    ,                        !- Zone Inside Convection Algorithm
    ,                        !- Zone Outside Convection Algorithm
    Yes;                     !- Part of Total Floor Area
```

![image](https://user-images.githubusercontent.com/6975889/149238018-ebe3acfc-62ae-4030-b756-4060f845f5d4.png)
(w/o means Multiplier =1 and w/ means Multiplier =10)

We expect that the <code>QCon_flow</code> will be equal to the calculated convection load times the zone multiplier

 - Modelica Buildings Library: 8.0.0
 - Modelica simulation environment: Dymola 2021x
 - Operating system: Windows 10

**Comment by mwetter** [comment]
As first step, @kbenne to reject the idf file with an error, and then we can devise a solution.
File rejection for Buildings 9 release.

**Comment by mwetter** [comment]
@SenHuang19 Let's start with rejecting the file, and then device a robust way to handle it. There are various questions, such as what does it mean to connect to the heatPort of such a zone, what flow rate should it be given, should this be multiplied in Modelica or should Modelica only have the volume of one zone etc. Hence, I rather reject it first to make sure users don't get wrong results, and then implement something that covers all corner cases.

**Comment by SenHuang19** [comment]
> Let's start with rejecting the file, and then device a robust way to handle it. There are various questions, such as what does it mean to connect to the heatPort of such a zone, what flow rate should it be given, should this be multiplied in Modelica or should Modelica only have the volume of one zone etc. Hence, I rather reject it first to make sure users don't get wrong results, and then implement something that covers all corner cases.

Thanks for your detailed explanations!  In EnergyPlus, besides Zone Multiplier, there is also a floor Multiplier (Zone List Multiplier).  Since we will find a long-term solution, should we include the floor Multiplier as well?

**Comment by mwetter** [comment]
@kbenne : Is there already a build available that rejects such idf files? I plan to make the 9.0.0 release the coming week.

**Comment by kbenne** [comment]
I'm working on it now.

**Comment by kbenne** [comment]
Here is the build https://gitlab.com/kylebenne/spawn/-/pipelines/542554616 

This also contains the changes to address https://github.com/lbl-srg/modelica-buildings/issues/2863
