### ISSUE TITLE
Translation of FMU with Spawn model fails on Windows

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#2854]
With Dymola 2022x, the following commands work on Linux Ubuntu 20.04, but fail on Windows:
```
translateModelFMU("Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.AirHeating");
importFMU("Buildings_ThermalZones_EnergyPlus_Examples_SingleFamilyHouse_AirHeating.fmu", true, false, false, "");
```
The error message is "Translation aborted."
Other models such as `Buildings.Controls.Continuous.Examples.LimPID` work.

Tested with master, commit 89fe3cb871d453ad2064b5221f4793ea265a71fc

**Comment by mwetter** [comment]
This may be related to Windows missing permissions to execute spawn when building the fmu, as the following shows that running a system command works, but invoking spawn fails:
```
Modelica.Utilities.System.command("dir");
 = 0
Modelica.Utilities.System.command("Resources\bin\spawn-win64\bin\spawn-0.3.0-d6204d26f6.exe -h");
 = 1
```

**Comment by mwetter** [comment]
@kbenne : I tested again with the current master (3f9b735a50877972f18c141e860826a9a38c99c7), Dymola 2022x and now the import works. I still get the `-1` as the output of `spawn-0.3.0-d6204d26f6.exe -h` but this is no longer an issue as I thought that is the root cause.

**Comment by kbenne** [comment]
A non zero return value still might qualify as a (less severe) bug. I'll take a look.
