### ISSUE TITLE
Cooling tower sta_a.T and sta_b.T swap due to flow reversal in computation

### ISSUE THREAD

**Issue by hcasperfu** [lbl-srg/modelica-buildings#2866]
First reported in comments of PR #2693.
When simulating `Buildings.Fluid.HeatExchangers.CoolingTowers.Examples.Merkel` and other models that use a cooling tower, the temperatures of the two ports of the cooling tower `sta_a.T` and `sta_b.T` may swap at times. This occurs when the flow rate of the tower is supposed to be zero, but its actual value is a very small negative number (see figures below for a snapshot of a few time steps).
![image](https://user-images.githubusercontent.com/91219266/151455026-aebd7b52-2fbc-4164-a608-c84d5a6e5e7c.png)
![image](https://user-images.githubusercontent.com/91219266/151455032-94002c85-18cc-4f7a-8f1e-9d43202e5bcf.png)

This could be solved by adding the modifier `final allowFlowReversal=false` when `Buildings.Fluid.HeatExchangers.CoolingTowers.BaseClasses.CoolingTower` extends `Buildings.Fluid.Interfaces.TwoPortHeatMassExchanger`.

`Buildings.Fluid.HeatExchangers.CoolingTowers.Examples.Merkel`
Before:
<img width="685" alt="Screen Shot 2022-01-27 at 16 46 52" src="https://user-images.githubusercontent.com/91219266/151455941-9c24e1d9-f48c-4f4d-a63c-1b1b792d3d23.png">

After:
<img width="683" alt="Screen Shot 2022-01-27 at 16 44 50" src="https://user-images.githubusercontent.com/91219266/151455763-80077fdf-0b7d-47b7-8b38-c74f1e03cc5f.png">

This will change the results of quite a few models.

**Comment by hcasperfu** [comment]
This has changed the results for `Buildings.Fluid.HeatExchangers.CoolingTowers.Examples.YorkCalc` rather drastically. The two port temperatures are now much closer to `TAir`, which is similar to what is seen in the results of `.Merkel`.

<img width="890" alt="Screen Shot 2022-01-27 at 17 20 29" src="https://user-images.githubusercontent.com/91219266/151459545-6282a7f3-c8cb-4275-bf44-299aa0acd62b.png">

**Comment by hcasperfu** [comment]
This didn't help with the results for models in `Buildings.Experimental.DHC.Plants.Cooling.Subsystems.Examples`. Although the unit test results changed, negative flow still occurred. Further investigation is needed.

**Comment by mwetter** [comment]
For example models, if you can guarantee `m_flow > 0`, then `allowFlowReversal` could be set to false.
In the actual component model, this should however not be done as we don't have a guarantee that this condition holds.

The temperatures reported in `sta_a.T` are indeed flipping if `m_flow` crosses zero. This is done efficiently without generating an event. If there is near zero flow rate (just numerical noise) then these quantities are not useful, but also the component performance is not useful as it has no or almost no flow rate. The quantity `sta_a` is implemented conditionally, this prevents any user to use this as an input into other model, e.g., they can only be used for reporting. If they were used in a model, the translation would stop with an error or warning.

**Comment by hcasperfu** [comment]
@mwetter 
Thank you for the explanation. I will make the change in each example model instead. 

The reported flipping behaviour is causing trouble for me with #2668 because when the mover models were adjusted, the numerical noise would behave slightly differently. The two temperatures then flipped at different places which then generated very different result files even though they were virtually the same if the flipping was ignored. 
I believe nailing those two temperatures to where they belong in these example models would save the time of anyone who adjusts the component models in the future.

**Comment by hcasperfu** [comment]
@mwetter 
Greetings!
As we discussed in the meeting this morning, now I changed where the water entering and leaving temperatures are taken in `Buildings.Fluid.HeatExchangers.CoolingTowers.Examples.BaseClasses.PartialStaticTwoPortCoolingTower` and `Buildings.Experimental.DHC.Plants.Cooling.Subsystems.Examples.BaseClasses.PartialCoolingTowersSubsystem` to resolve this issue.
