### ISSUE TITLE
ModelicaBuildingsEnergyPlus.json paths to idf and weather file include "\" - spawn FMU generation fails.

### ISSUE THREAD

**Issue by borlum** [lbl-srg/modelica-buildings#2900]
**Describe the bug**
I am attempting to run an FMU of a building model, that relies on spawn to interface with E+. The whole workflow works fine on Linux, where I use FMPy to simulate my FMU.

However, now I am attempting to also make it work on Windows where I would like to simulate the FMU in Simulink.
I can successfully generate the FMU in Dymola and import it in Simulink, however when I run the Simulink model, it fails with:

```
Log from FMU: [category:Log, status:fmi2Error] Error: The following error was detected at time: 0
Log from FMU: [category:Log, status:fmi2Error] 0.000 SeminarcenterComplete.building: Executing '""C:/Users/borlum/repos/CBS/simulation/matlab/slprj/_fmu/fed1dd2c994cb333b08c01f61fc2e9a4/seminarcenter/resources/Resources/bin/spawn-win64/bin/spawn.exe" --no-compress  --output-path "C:/Users/borlum/repos/CBS/simulation/matlab/EnergyPlus-simulation-SeminarcenterComplete.building/SeminarcenterComplete.building.fmu" --create "C:/Users/borlum/repos/CBS/simulation/matlab/EnergyPlus-simulation-SeminarcenterComplete.building/ModelicaBuildingsEnergyPlus.json""' failed to generate fmu 'C:/Users/borlum/repos/CBSsimulations/simulation/matlab/EnergyPlus-simulation-SeminarcenterComplete.building/SeminarcenterComplete.building.fmu'.
Log from FMU: [category:Log, status:fmi2Error] The stack of functions is:
Log from FMU: [category:Log, status:fmi2Error] Buildings.ThermalZones.EnergyPlus.BaseClasses.initialize
Log from FMU: [category:Log, status:fmi2Error] Buildings.ThermalZones.EnergyPlus.BaseClasses.initialize(
TZ9.zone.fmuZon.adapter, 
building.isSynchronized)
Log from FMU: [category:Log, status:fmi2Error]
Log from FMU: [category:Log, status:fmi2Error] Initialization Failed
Log from FMU: [category:Log, status:fmi2OK]
```

I checked the generated ModelicaBuildingsEnergyPlus.json file, and I believe that the issue is, that the paths inserted here, are using '\\' and not '/'. If I fix the paths (replace '\\' with '/'), I can successfully call spawn with the .json file. This is however not a viable quick-fix, as the file is overwritten whenever I run the Simulink model.

**To Reproduce**
1. Generate a co-simulation FMU including a building model that references E+ using spawn on Windows (using Dymola).
2. Import the FMU in Simulink using Simulinks own 'FMU Import'-block.
3. Run the Simulink model.
4. See error.

**Expected behavior**
That the generated ModelicaBuildingsEnergyPlus.json is formatted with '/' on Windows, making spawn accept the file and generate the appropriate E+ FMU. That Simulink will then simulate the FMU.

**Version**
 - Modelica Buildings Library: 8.1.0
 - Dymola 2021x, Simulink (MATLAB 2021b)
 - Windows 10

**Comment by borlum** [comment]
So, I fiddled around with making a quick-fix for this and did a quick 'String.replace' in the ThermalZoneAdapter on the idf file and weather file paths. This works - but maybe not the correct place for a permanent solution:

```
Buildings.ThermalZones.EnergyPlus.BaseClasses.SpawnExternalObject adapter=Buildings.ThermalZones.EnergyPlus.BaseClasses.SpawnExternalObject(
    objectType=1,
    startTime=startTime,
    modelicaNameBuilding=modelicaNameBuilding,
    modelicaInstanceName=modelicaInstanceName,
    idfName=Modelica.Utilities.Strings.replace(idfName, "\\", "/", replaceAll=true), // Do string replacement here
    weaName=Modelica.Utilities.Strings.replace(weaName, "\\", "/", replaceAll=true), // And here
```

**Comment by mwetter** [comment]
@borlum : I try to understand where the `\\` slashes come from in your situation. When writing the `ModelicaBuildingsEnergyPlus.json` file in the C layer between Modelica and EnergyPlus, we simply write the string that is obtained from Modelica without changing the slashes.

I suspect that when you run the FMU from Simulink, a call to loadResource is made and this returns `\\` rather than `/`.

If I understand correctly, the situation where you have `\\` rather than `/` as path separators in `ModelicaBuildingsEnergyPlus.json` is only when you import the Dymola-generated FMU in Simulink, and then simulate it? 
Does a simulation work if you implement the FMU in Dymola?
If you unzip the Dymola generated FMU and open `modelDescription.xml`, do you have any entry for `idfName`? (There may be no entry if it is compiled into the FMU.)

**Comment by borlum** [comment]
Correct. Only when I import the Dymola-generated FMU in Simulink and simulate it, the paths are made up with \ instead of /.

I have not attempted to import and simulate the FMU in Dymola. There is no entry for `idfName` in the `modelDescription.xml`.

I saw in the C layer between Modelica and EnergyPlus that you do some protection on `\` vs `/` in regards to the path to the generated E+ FMU, as it is made up by a call to `_getcwd` (or equivalent), and that on Windows, this path may be returned with `\`. Maybe it is not the worst fix, to do the same protection against the paths for the idf and the weatherfile? Just a suggestion.

Thanks for following up :-)

**Comment by mwetter** [comment]
@borlum : Can you please post the faulty `ModelicaBuildingsEnergyPlus.json` file, and let me know if you get any error message on the screen when you execute from a dos console the command below, assuming
`C:/Users/borlum/repos/CBS/simulation/matlab/slprj/_fmu/fed1dd2c994cb333b08c01f61fc2e9a4/seminarcenter/resources/Resources/bin/spawn-win64/bin/spawn.exe` exists as this would otherwise trigger a different error:
```
"C:/Users/borlum/repos/CBS/simulation/matlab/slprj/_fmu/fed1dd2c994cb333b08c01f61fc2e9a4/seminarcenter/resources/Resources/bin/spawn-win64/bin/spawn.exe" --no-compress  --output-path "C:/Users/borlum/repos/CBS/simulation/matlab/EnergyPlus-simulation-SeminarcenterComplete.building/SeminarcenterComplete.building.fmu" --create "C:/Users/borlum/repos/CBS/simulation/matlab/EnergyPlus-simulation-SeminarcenterComplete.building/ModelicaBuildingsEnergyPlus.json"
```

I don't think we do a protection of `\` vs `/` in the C code, or did you see one? What file and line number would that be?

**Comment by borlum** [comment]
@mwetter : I am out of office, but will post the faulty .json when I get the chance.

You do protect against \, but this is in the context of generating the path of the E+ FMU - see:

https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/SpawnUtil.c#L566

My point was simply, to "copy" this strategy and use it on the paths provided for the IDF file and the weather file as-well.

**Comment by mwetter** [comment]
This is addressed through https://github.com/lbl-srg/modelica-buildings/pull/2935 on the 8.1.x maintenance branch, and through https://github.com/lbl-srg/modelica-buildings/pull/2933 for the 9.0.0 release.
