### ISSUE TITLE
Steam District Heating - Complete System

### ISSUE THREAD

**Issue by khinkelman** [lbl-srg/modelica-buildings#2905]
@bravache and @JayHuLBL: Please do not create the branch for this issue until PRs for Issues #2701 and #2904 have (at a minimum) been merged. A PR for Issue #2848 will be opened ASAP if @SaranyaAnbarasu and I can complete the model improvements requested by Michael in time; however, it is not required. With that said, I wanted to open this "system-level" issue prematurely so that you are aware of this final requirement for the OSMSES Conference paper. This is the last time-sensitive issue for the steam district heating models. These models need to be merged to `lbl-srg/issue2905_steamsystem` before the paper submission deadline of **Thursday, March 10, 2022 (time zone CET, GMT+1, Aachen, Germany)**. (Our **internal deadline** should be **end-of-business PT on Wed. March 9**.)

This issue is to to add the subsystem (Steam Plant) and system-level example (complete steam district heating system) to the `Experimental.DHC` package. In addition to the complete system example (`Steam` model to be located in `DHC.Examples`), the below subsystem model will be contributed (highlighted in green). This work is part of the URBANopt project.

![image](https://user-images.githubusercontent.com/44682485/156400402-576fd801-942c-46a9-8358-682bbb091377.png)

This subsystem and system models use components from previously opened issues (mentioned above). Once the component branches have been merged from fork to lbl-srg, they need to be pulled into this system-level branch before the new developments can be added. Here is a graphical representation of the current status and requirements:

[Updated 3/2/22 with dependency with Network models]
[Updated 3/4/22 with PRV PR]
[Updated 3/9/22 with Networks PR]
[Updated 4/4/22 with components/subsystems merged with development branches]
[Updated 4/12/22 PR for complete system opened.]
![image](https://user-images.githubusercontent.com/44682485/163014169-fd15de0d-7a33-49b3-92cb-de1b50bbcd5a.png)
I am fully available to work on these developments until the March 10th deadline. If you have any questions or if I can help in any way, please let me know. My sincerest thanks!

**Comment by khinkelman** [comment]
Note to self: 
- [ ] BuildingTimeSeries - Change data file from `.csv` to `tab`/`.txt` per [Issue 1572](https://github.com/ibpsa/modelica-ibpsa/issues/1572)

**Comment by khinkelman** [comment]
Update: Per [2904#issuecomment-1057080973](https://github.com/lbl-srg/modelica-buildings/issues/2904#issuecomment-1057080973), the network models in Issue #2904 depend on the models involving phase change, which are included in Issue #2290. Thus, I revised the diagrams above to reflect the dependencies. 

The model developments are the same, but the distribution of models on the involved issues above are changing slightly.

**Comment by khinkelman** [comment]
Hi @bravache and @JayHuLBL: When you have a chance, could either of you please create the branch for this issue (from the master) so that I can add the developments? 

I was trying to avoid dependencies between issues by dividing the issues like I had; but it turns out that the network issue had unavoidable dependencies. Thus, there is no longer an incentive to wait to create this branch.

Please let me know if you have any questions. If it works for you, let's please plan to touch base before the end of this week to reassess our plan.
Many thanks!

**Comment by JayHuLBL** [comment]
@khinkelman @bravache I just created branch `issue2905_steamDHS_fullSys` for this.

**Comment by khinkelman** [comment]
Hi @bravache, thanks for your help reviewing and merging the component/subsystem branches (PR #2701, PR #2908, PR #2914). 
Before continuing with this full system branch (`issue2905_steamDHS_fullSys`) we wanted to ask: 
Would you like to review/process/merge the previous development branches with the master first? Or should we continue with developments and open a new PR for this system branch before merging any to the master? 
Many thanks!

**Comment by bravache** [comment]
@khinkelman Can you take a look at the lbl-srg branch:
https://github.com/lbl-srg/modelica-buildings/tree/issue2905_steamDHS_fullSys

This has all of the latest development from #2290 , #2848 and #2904 and is up to date with `master`. I've also committed a commit to fix a few lines that prevented the full system example from working, so you might want to check that this commit is correct:
https://github.com/lbl-srg/modelica-buildings/commit/3f2132f71efbcaf80e25f830525e0012146ba6d1

Please also take a few minutes to go over the whole branch and verify that everything is in order. If so, I can just create a pull request to merge it to master, and I'll discuss with the team who would be taking a final review before merge.

**Comment by khinkelman** [comment]
Many thanks @bravache! We will look over this branch, clean up the developments, perform our internal review, and open a PR for you to review when its ready (anticipating towards the end of next week). Hope you have a nice weekend!
