### ISSUE TITLE
Dymola simulates EnergyPlus case in Building library 8.0.0  will report an error

### ISSUE THREAD

**Issue by Magicpanda1985** [lbl-srg/modelica-buildings#2923]
**Describe the bug**
When I use dymola 2020X or dymola 2021X simulates EnergyPlus case in Building library 8.0.0, dymola will report an error. However, for models without EnergyPlus, they run successfully.

**To Reproduce**
1. Open model 'Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.Unconditioned or other examples in Buildings.ThermalZones.EnergyPlus.Examples'
2. Run script 'using dymola 2021X run this case directly'
3. See error 
![image](https://user-images.githubusercontent.com/101372560/158492627-d80921da-5970-4322-abf1-56280f588db1.png)

**Expected behavior**
My European colleagues can run the EnergyPlus models without any problems. However, my Asian colleagues in Shanghai get the same error as shown before when they run EnergyPlus models. I expect my Asian colleagues and I should run all the EnergyPlus models successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/101372560/158493261-531e03c7-7a6d-446d-be79-d4efd6e04f6e.png)
![image](https://user-images.githubusercontent.com/101372560/158493282-190b590e-32ac-4d71-aee8-491f80da981c.png)

**Version**
 - Modelica Buildings Library: 8.0.0
 - Modelica simulation environment: dymola 2021X or 2020X， compiler VS 2013.
 - Operating system: Windows 10 Enterprise, 64-bit operating system, x64-based processor

**Additional context**
log file generated by dymola is empty

**Comment by mwetter** [comment]
@Magicpanda1985 : can you please first check if you have the right binaries: In `Resources/bin/spawn-win64/bin`, you should have epfmi.dll that is about 41MB large and spawn.exe that is about 9.9 MB. If these are much smaller, it looks like git-lfs is not set up right (assuming you checked out the code from github).

If these files have the right size, set in the top-level model, instance `building`, the parameter
`logLevel=Buildings.ThermalZones.EnergyPlus.Types.LogLevels.Debug`. This will give log information to see where the issue occurs. If invoking spawn.exe fails, it shows the command used, which you could run from a dos shell which may give additional information on the console output.

**Comment by Magicpanda1985** [comment]
Hi, mwetter:
I checked the size of epfmi.dll & spawn.exe , and they are 41MB and 10MB respectively. I think they are set up right.
I also set logLevel=Buildings.ThermalZones.EnergyPlus.Types.LogLevels.Debug in Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.Unconditioned:
![image](https://user-images.githubusercontent.com/101372560/158923468-2258409c-a482-4dde-95fb-247fe02f899a.png)
The result log files are listed:
![image](https://user-images.githubusercontent.com/101372560/158923626-3fe7a54d-6c18-442d-bb5a-574d93226396.png)
dslog.txt is empty; 
buildlog.txt content:
![image](https://user-images.githubusercontent.com/101372560/158923774-307d8030-1ed4-4f68-9b40-4fc98cfb567d.png)
I also run dymosim.exe, and the output:
![image](https://user-images.githubusercontent.com/101372560/158923918-9092131f-1bc0-4c82-9e2d-b8cdf7f36f2c.png)
I still cannot get extra information from the error message. Waiting your suggestions, and thank you very much.

**Comment by mwetter** [comment]
Can you try with Buildings 8.1.0, a more recent version of Dymola, and use VS 2019 rather than 2013.
My guess is it is related to the compiler.

Also, can you search for the file `ModelicaBuildingsEnergyPlus.json` below your working directory. This file is written by the already compiled C code before spawn.exe that generates the FMU is invoked.

**Comment by Magicpanda1985** [comment]
I run Building 8.0.0 successfully when I change my compiler to VS2019. Thank you very much for your kindly help.

**Comment by mwetter** [comment]
Thanks for reporting. I just added this compiler information at https://simulationresearch.lbl.gov/modelica/download.html
