### ISSUE TITLE
Spawn with OpenModelica: failed to generate fmu

### ISSUE THREAD

**Issue by davidefop** [lbl-srg/modelica-buildings#2924]
I am trying to use spawn of EnergyPlus with the following software setup: 

-   Connected to OpenModelica v1.19.0-dev-682-gd30cc419c5 (64-bit) 
-   master branch of the Buildings library 
-   windows 10 

The example I’m trying to run is:

    ` modelica-buildings-master\Buildings\ThermalZones\EnergyPlus\Validation\ThermalZone\OneZoneCompareZoneTemperatureOutput `

I have encountered the following obstacles: 

-  When the example is run from OpenModelica, the compilation appears to succeed but the simulation fails. The log message is: 

     

   ` Executing '""C:/Users/.../modelica-buildings-master/modelica-buildings-master/Buildings/Resources/bin/spawn-win64/bin/spawn-0.3.0-d6204d26f6.exe" --no-compress  --output-path "C:/Users/.../AppData/Local/Temp/OpenModelica/OMEdit/EnergyPlus-simulation-Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building/Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building.fmu" --create "C:/Users/.../AppData/Local/Temp/OpenModelica/OMEdit/EnergyPlus-simulation-Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building/ModelicaBuildingsEnergyPlus.json""' failed to generate fmu 'C:/Users/.../AppData/Local/Temp/OpenModelica/OMEdit/EnergyPlus-simulation-Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building/Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building.fmu'.`
`

-  When the above command is run from a terminal spawn encounteres an error: 

`[json.exception.parse_error.101] parse error at line 4, column 16: syntax error while parsing value-invalid string: forbidden character after backslash; last read: ‘“C:\U’” `

Converting the backslash into a forwardslash in the forementioned .json file, there seems to be an error in the location of the working directories: 
`
Spawn encountered an error: "create_directories: Error The system cannot find the path specified: "C:/Users/.../AppData/Local/Temp/OpenModelica/OMEdit/EnergyPlus-simulation-Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building\Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building"" `

Indeed the above path is wrong, in that folder (`EnergyPlus-simulation-Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building`) is not parent to folder (`Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building`) but rather they are at the same hierarchy level (they are both located in the OpenModelica Temporary Directory)

**Comment by davidefop** [comment]
**Update**: when correcting the path in the command that calls spawn to generate the fmu, so that spawn points directly to `Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building`, an fmu file is generated in the OpenModelica Temporary Directory.

**Comment by mwetter** [comment]
There seems to be something wrong with file system access:
With the current master branch of the Buildings library (d538de534a6f6c19311d70efb664ffdf6f5ca6a6) the model `OneZoneCompareZoneTemperatureOutput` works with Dymola 2022x on Windows, run from the F: drive which is exported from the Linux host.

With OMEdit nightly build (1.19.0-dev-682-gd30cc419c5), compilation fails in the first trial (header files where not found), if translated again, the translation was successful. This looks like Windows was not able to access the files on the shared drive.
Translating again with debug mode enabled in the `buildings` instance works up to the point where spawn.exe is searched. The log shows that the
`Buildings library root is at F:\modelica-buildings\Buildings\legal.html`
If run on with Dymola, on Windows and on Linux, this message is 
`Buildings library root is at F:\modelica-buildings\Buildings`, which is the expected behavior.

It looks like this is the reason why the spawn executable was not found. This error marks the one reported above.

**Comment by davidefop** [comment]
I tried previously to run the example, and at first I got the log showing:
`Buildings library root is at F:\modelica-buildings\Buildings\legal.html`
In order to overcome this problem, I deleted the `legal.html` file from the `Buildings` folder. By doing this, I was able to get to the previous error (as indicated in the first message of this thread).
Is the `legal.html` file necessary for any process, or can it safely be removed from the folder?

Moreover, by adjusting the fmu extraction command in the prompt (see second comment), an fmu was actually created. Is that sufficient to run the simulation, perhaps from a master? I tried to run it with PyFMI, and the EnergyPlus simulation appeard to start up the warming up stage, only to stop at the first simulation step.

**Comment by mwetter** [comment]
@davidefop : Don't delete legal.html, this is a file that we use to figure out where the Buildings library is installed, which then is used to search for spawn.exe. A first fix to this is in https://github.com/lbl-srg/modelica-buildings/pull/2928, but more changes are needed in the C code which I try to implement on branch `issue2924_spawnOpenModelicaWindows` as loadResources does not uniformly handle forward and backward slashes on Windows.

**Comment by davidefop** [comment]
I have reintroduced legal.html in the `Buildings` folder, both in the `master` and the `issue2924_spawnOpenModelicaWindows`. Still the example crashes after compilation.  
I got the following log file (last lines):

```
**0.000 Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.zon: Entered EnergyPlusSpawnInitialize.

0.000 Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building: Entered EnergyPlusSpawnAllocateAndInstantiateBuilding.

0.000 Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building: Entered findSpawnExe.

0.000 Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building: In findSpawnExe, trying to to use buildingsLibraryRoot to find spawn.

0.000 Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building: Entered findSpawnExe.

0.000 Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.OneZoneCompareZoneTemperatureOutput.building: Found executable 'spawn-0.3.0-d6204d26f6' in 'C:\Users\...\Downloads\modelica-buildings-issue2924_spawnOpenModelicaWindows\Buildings/Resources/bin/spawn-win64/bin'.

Process crashed**
```
The process seems to be crashing when spawn is called

**Comment by mwetter** [comment]
@davidefop : I can reproduce this process crash. As written yesterday, more changes are needed. I try to implement them over the next days.
