### ISSUE TITLE
Incorrect hydronics in Experimental.DHC.Examples.Combined.ParallelConstantFlow

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#2967]
Simulating the model yields a negative ETS pump power due to incorrect hydronic principles.
The model is indeed a blunt adaptation of `SeriesConstantFlow` to a two-pipe network, developed primarily to illustrate the use of `Experimental.DHC.Networks.Combined.UnidirectionalParallel`. 
However, the hydronic layout of the ETS (as presented in Sommer 2020) is suited for "passive networks" where the ETS is not exposed to a high differential pressure.
For active networks (as it is the case here) a control valve should be used instead of a pump for the heat pump source circuits.
In addition, as an ideal pump model is used (that takes mass flow rate as an input) the model logically computes a negative flow work and a negative power.
I suggest removing that model from the library (as it may also be confused with the bidirectional network presented in Sommer 2020).
Maybe an assert statement would also be useful in `Fluid.Movers.FlowControlled_m_flow` to generate a warning in case of a negative flow work.

**Comment by mwetter** [comment]
I agree that this is wrong and should be removed.

Adding an assertion to the pump would be good. We had a similar problem a few years ago where a pump ended up acting as a turbine because of a wrong hydraulic configuration.

**Comment by mwetter** [comment]
Todo:
- [ ] Apply to `maint_8.1.x` branch.

**Comment by AntoineGautier** [comment]
Closed by PR #2974 and #2968.
