### ISSUE TITLE
add hysteresis to blocks in CDL.Integer package

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#2978]
This issue is to add hysteresis to blocks in `CDL.Integer` so the blocks have identical parameters as the ones in `CDL.Continuous` package. Following blocks will be updated:
- [x] `Buildings.Controls.OBC.CDL.Integers.Greater`
- [x] `Buildings.Controls.OBC.CDL.Integers.GreaterThreshold`
- [x] `Buildings.Controls.OBC.CDL.Integers.Less`
- [x] `Buildings.Controls.OBC.CDL.Integers.LessThreshold`

**Comment by mwetter** [comment]
@JayHuLBL : I thought a bit more about the (lack of?) use cases to add hysteresis to Integer blocks, and the complexity this feature adds to users for little (to no?) useful additional functionality. The main rationale of some on the 231 Committee to add hysteresis was easier documentation and translation from `Analog.Greater` to `Integer.Greater` for the case of `h > 0`.

I think the need for concise documentation should not worsen usability, and for translation, we can always address the rare situation that someone uses `Analog.Greater` for `Integer` with `h > 0` by generating a composite block on the fly when translating CXF to CDL. This is similar to what we actually did for CXF to WebCTRL for some corner cases where WebCTRL does not have an equivalent.

In view of this, I suggest to wait with merging this. But please correct the edits we discussed yesterday, and make the changes (if needed) for the `Continuous` versions of these blocks on a separate branch so we can merge these corrections independently of the changes for the `Integer` versions.

**Comment by mwetter** [comment]
This won't be merged as it adds non-needed complexity. The development branch was `issue2978_integerHys`, last commit https://github.com/lbl-srg/modelica-buildings/pull/2979/commits/fab253f53b0661a6350f649608f3a5e8c6a59d52
