### ISSUE TITLE
Computation of Qcon_flow

### ISSUE THREAD

**Issue by Magicpanda1985** [lbl-srg/modelica-buildings#2983]
Hi:
In Buildings.ThermalZones.EnergyPlus.ThermalZone, two heatflux outputs of fmuZon are provided. The first one is Qlat_flow, which is very clear the latent heat flux. However, for the second one, Qcon_flow(Convective sensible heat to be added to zone air), I don't know how it computed based on energyplus outputs. Could you tell me about it? Thank you very much.

**Comment by mwetter** [comment]
The sensible heat gain is computed in EnergyPlus, and consists of all sensible heat flow to the zone air heat balance (surface convection and sensible convective internal heat load).
