### ISSUE TITLE
Removed protected record definition inside a record (Fluid.HeatPumps.Data.EquationFitReversible.Generic)

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#3009]
This issue is to remove the `protected` statement in `Fluid.HeatPumps.Data.EquationFitReversible.Generic` as this is not allowed in Modelica. See https://github.com/OpenModelica/OpenModelica/issues/8959

**Comment by casella** [comment]
@mwetter I see you did not port this change to the 7.0.x maintenance version, which got worse success ratio as a consequence. Are you still maintaining it actively, or should we stop bothering about it and focus on 8.1.x and 9.0.0 only?

Thanks!

**Comment by mwetter** [comment]
@casella Please drop the 7.0.x maintenance branch. I see more value in focusing our time on the 8.1.x and 9.0.0 branches.

**Comment by casella** [comment]
Will do, thanks!
