### ISSUE TITLE
Add duty cycle blocks in CDL.Logical

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#3042]
This issue is to add duty cycle blocks as discussed in ASHRAE231p meeting:
- [x] `CDL.Logical.ConstantDutyCycle`: produces an output that cycles on and off according to the specified length of time for the cycle, and the specified percentage of the time that the output should be on. It only cycles the output when the go input is on; if the go input is off, the output remains on.
- [x] `CDL.Logical.VariableDutyCycle`: produces an output that cycles on and off according to the specified length of time for the cycle and the value of the input, which indicates the percentage of the cycle time the output should be on. It only cycles the output when the input value is greater than zero. If the input is zero, the output ~~remains off~~ remains on.

For the `VariableDutyCycle`, if for example the cycle time is 10 minutes and the cycle on percentage is 50%, then at first 5 minutes the output will be `True` and the next 5 minutes will be `False`. If in the middle of one cycle (say 10 minutes cycle time), the cycle percentage changes from 50% to 25%, the output will become `True` immediately (a new timing period is established) for 2.5 minutes and remain `False` for 7.5 minutes.

**Comment by mwetter** [comment]
How do you establish a new timing period? This would require monitoring the continuous-valued input signal for a change, and then trigger events, which can be very costly. Do you know of an efficient implementation for this?
