### ISSUE TITLE
the BoundaryConditions.Weatherdata.Bus cannot properly used for connection with other component in Openmodelica

### ISSUE THREAD

**Issue by gustave4u** [lbl-srg/modelica-buildings#3053]
Hi,there!
there is a confusing problems that i actually cannot select any variable in Weatherdata.Bus for further connect with other component, such as Fluid.Sources.Outside. I found this issue is common in Openmodelica since i tried the Official Release, Stable Development, and Nightly Build.

**Screenshots**

<img width="551" alt="微信截图_20220528151106" src="https://user-images.githubusercontent.com/33016873/170814830-4b17d6be-0df6-40fe-a42f-44eb4195ef63.png">

**Comment by mwetter** [comment]
I think this happens with any bus connector in OpenModelica, not just the Buildings library, and graphical support for bus connectors are still ongoing by the OpenModelica development team. I will therefore close this issue. Please reopen if it only occurs with the bus from the `Buildings` library.

**Comment by gustave4u** [comment]
thanks for your reply
