### ISSUE TITLE
Error while running Spawn of EnergyPlus

### ISSUE THREAD

**Issue by sunitajha406** [lbl-srg/modelica-buildings#3057]
When I am running Spawn using Impact modelon, by executing Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.AirHeating, I am getting the following error!
"Compilation of generated C code failed".

Can you help me in understanding if I am missing out anything because what I understand from the document is that the spawn totally resides inside impact and generates EnergyPlus FMU/executables for simulation.

@mwetter

**Comment by mwetter** [comment]
Please see 
https://simulationresearch.lbl.gov/modelica/releases/v9.0.0/help/Buildings_ThermalZones_EnergyPlus_9_6_0_UsersGuide.html#Buildings.ThermalZones.EnergyPlus_9_6_0.UsersGuide.Installation
to make sure you used the right installation. E.g., if you cloned the repository, you need to download the binaries. If you used the zip file from https://simulationresearch.lbl.gov/modelica/download.html you should have all that is needed.
