### ISSUE TITLE
Compilation error while running Spawn in Impact modelon

### ISSUE THREAD

**Issue by sunitajha406** [lbl-srg/modelica-buildings#3058]
I am not able to run Spawn of EnergyPlus example file in Impact using windows. It is giving compilation error of C code generated. The latest default Impact version uses GCC compiler. I saw in the website it says that "Requirements: This library uses Modelica 4.0.0. On Windows, the models in [Buildings.ThermalZones.EnergyPlus_9_6_0](https://simulationresearch.lbl.gov/modelica/releases/v9.0.0/help/Buildings_ThermalZones_EnergyPlus_9_6_0.html) have been tested using the **Microsoft VS 2019 compiler**." 

So do we have to install this Microsoft VS 2019 compiler for running spawn in Impact using windows operating system or is there some other way ? @mwetter

**Comment by mwetter** [comment]
@sunitajha406 . You will need to install Microsoft VS 2019 if gcc is not compatible.
