### ISSUE TITLE
Wrong value set in the component "TOutSwi" in example "TwoRoomsWithStorage"

### ISSUE THREAD

**Issue by adahash** [lbl-srg/modelica-buildings#3059]
Hi @mwetter,

I was going to use the model "Buildings.Examples.HydronicHeating.TwoRoomsWithStorage" as a base model for a simulation case study with some modifications. I went through the model and all components incoporated and found that the component "TOutSwi" has the value of 16 + 293.15 instead of 16+ 273.15 since it is used as a reference outside temperature to switch off the heating system as shown in comment "Outside air temperature to switch heating on or off".

Is there any reason for having 36°C or it's just a typo? 

Thanks in advance.
Regards,
Abdul

**Comment by mwetter** [comment]
@adahash : Thanks, this is indeed a typo that will be corrected for the next release.
