### ISSUE TITLE
Spawn generated FMU

### ISSUE THREAD

**Issue by davidefop** [lbl-srg/modelica-buildings#3064]
I'd like to run a Spawn example from my own master Python code using pyFMI. What FMU (FMUs?) do I need to import in my code?
When I run an example, (e.g. `Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.AirHeating`) from OpenModelica, I see it generates automatically an FMU only for the EnergyPlus model. On the other hand, if I ask OpenModelica to extract an FMU from the model, as:

`model = load_fmu("AirHeating.fmu")`

such FMU will not work on Python, yielding this error message:

`pyfmi.fmi.InvalidBinaryException: The FMU could not be loaded. Error loading the binary. Could not load the FMU binary:The specified module could not be found`

**Is it possible to run a spawn cosimulation (Modelica + EnergyPlus) from a pyFMI master code?** That would allow me to interact at desired timesteps, thus sending my own control signals generated in Python.

Details on software and setup:
• OS: Windows 10
• OpenModelica v1.19.0-dev.beta1 (64-bit)
• FMI version: 2.0
• Python 3.8

**Comment by mwetter** [comment]
I think that should work. The CI tests on Linux also generate an FMU with OPTIMICA and load it with `load_fmu`, see https://github.com/lbl-srg/BuildingsPy/blob/bcc47ca8cba6d908bb05bcb942227ac3a1199482/buildingspy/development/optimica_run.template#L118

I wonder if the error message indicates a mismatch in the compiler. See https://simulationresearch.lbl.gov/modelica/download.html for the MS compiler that we used to generate the binaries.

**Comment by davidefop** [comment]
I'm not sure about the compiler; I have Microsoft VS 2022 instead of the 2019 version, are they supposed to conflict? 

Regarding the FMU, I noticed that when a spawn example is run from OpenModelica, in the temporary directory I only find an fmu called EnergyPlus.fmu. When unzipped, it contains in the Model Description json file the sole variables relative to the Thermal Zone, whereas in the resources folder are:

- the Energy+.idd file;
- the model.spawn executable;
- the idf and the epw weather files.

On the other hand, when I generate the fmu of the spawn example myself, using OpenModelica, such FMU contains all the model variables except for the zone related variables in its model description. In the resources folder, neither spawn, the idf nor the climate file are to be found. 

Is spawn supposed to work with two different FMUs (one for Modelica and one for EnergyPlus), so that a single FMU is not enough to run from a pyfmi master code? Or can a single FMU call for the spawn executable to then manage the coupling of Modelica and E+? 

Thanks

**Comment by mwetter** [comment]
We haven't tested with the MS VS 2022, so they may conflict.

To run from pyfmi as a master, you would have one FMU for the Modelica code, and this should generate on the fly (during the initialization) another FMU that contains the EnergyPlus binary and configuration.
See
https://simulationresearch.lbl.gov/modelica/releases/v9.0.0/help/Buildings_ThermalZones_EnergyPlus_9_6_0_UsersGuide.html#Buildings.ThermalZones.EnergyPlus_9_6_0.UsersGuide.Installation
for the proper installation so that the Modelica code can find the software that generates the EnergyPlus FMU.

**Comment by davidefop** [comment]
I would assume that the problem lies in using OpenModelica to extract the FMU. Indeed, spawn examples from the buildings library work fine, meaning OpenModelica per se has no problems finding the spawn exe in my local path.  

I tried inspecting an FMU from the MODRLC-actb project that uses spawn:

https://github.com/henze-research-group/MODRLC/tree/actb/testcases/spawnrefsmalloffice/models

and I noticed that the modelDescription file includes explicit references to the spawn exe, namely:

```
<ScalarVariable name="mod.building.spawnExe" valueReference="805306368" description="Name of the spawn executable, without extension, such as spawn-0.2.0-d7f1e095f3" causality="local" variability="constant" initial="exact">
			<String start="spawn-0.2.0-d7f1e095f3" />
```
which are absent in the FMU that I extracted with OpenModelica. Besides, there are differences in the `binaries` and `resouces` folders between the forementioned example and my own, OpenModelica generated FMU. 

May this be relevant?

**Comment by davidefop** [comment]
I think I isolated a possible issue. It seems that the .dll file included in the generated FMU requires the following dependecies:

- KERNEL32.dll
- msvcrt.dll
- ModelicaBuildingsEnergyPlus_9_6_0 (which I found mentioned in Buildings\ThermalZones\EnergyPlus_9_6_0\BaseClasses\SpawnExternalObject)

I'm guessing that the last dependency cannot be found by the Python master. This problem seems related to the issue of spawn FMUs lack of portability (see issue https://github.com/lbl-srg/modelica-buildings/issues/2443) that should have already been addressed in the latest Buildings Library release.

**Comment by davidefop** [comment]
Thanks for the reply. Apparently OpenModelica has known issues when it comes to including .dll libraries into exported FMUs. A number of workarounds are suggested around the internet; basically I see two options:

- manually modify the FMU by unzipping it and compress it back or
- modify the SpawnExternalObject.mo. 

I'd like to try some possible solutions, but I'm not able to determine if the missing dependency is the `EnergyPlus_9_6_0_Wrapper.c` or the `spawn.exe` itself; in the latter case, I couldn't find where it is explicitly called in the Modelica model. 

I guess this whole issue is not strictly related to Spawn/BuildingsLibrary itself; however, as far as I know right now compilation of FMUs relies on pymodelica which is no longer available outside dockers. I noticed @dhblum opened an issue on this topic (https://github.com/ibpsa/project1-boptest/issues/422) where boptest testcases are being compiled with OpenModelica so I hope this could somehow help.

**Comment by dhblum** [comment]
Just a correction here that boptest test cases are not yet being compiled with OpenModelica, but the issue in reference aims to move to OpenModelica.  

Also, a note that may or may not help the problem reported here originally.  When providing Spawn support for BOPTEST in https://github.com/ibpsa/project1-boptest/issues/406, it was noted by @kbenne that the same version of Spawn used to compile the FMU needed to be on the system path to simulate the fmu.
