### ISSUE TITLE
Change nominal flow rate in Buildings.Examples.ScalableBenchmarks

### ISSUE THREAD

**Issue by hcasperfu** [lbl-srg/modelica-buildings#3067]
This is to address a problem of `Buildings.Examples.ScalableBenchmarks.BuildingVAV.Examples.{OneFloor_OneZone,TwoFloor_TwoZone}` which was exposed by upcoming changes to the movers model.
The new method will be able to account for variable efficiency values at different flow rates and pressure rises instead of using a constant efficiency. The new efficiency computation relies on the peak operation point of the mover. In the case of the models in question, this peak point is guessed from nominal values.
Because the nominal flow rate of `Buildings.Examples.ScalableBenchmarks.BuildingVAV.Examples.OneFloor_OneZone` is set too high, it lead to the estimated fan efficiency being 0.068 when the fan operates normally. This resulted in significant heat generation and a temperature rise across the fan of 7 degC. This in turn changed the economiser behaviour as well.

(1 = bbb23fece0faf13502f5cf178f64a9c69eecd24d; 2 = a4bf2006b2f8a7620e90e736e8dc5c2e13e9b21d)
![image](https://user-images.githubusercontent.com/91219266/174857908-e9d0f06a-af70-442d-b763-9a2b184f5ba3.png)

(bbb23fece0faf13502f5cf178f64a9c69eecd24d)
![image](https://user-images.githubusercontent.com/91219266/174858184-bb14ccea-5f6f-43d9-a4d9-21dcca570f8b.png)

After changing `fan[].m_flow_nominal` from 10 to 0.1, the new method produces largely unchanged results.

**Comment by dhblum** [comment]
Closed by https://github.com/lbl-srg/modelica-buildings/pull/3068.
