### ISSUE TITLE
Add CDL.Continuous.FirstOrder

### ISSUE THREAD

**Issue by SenHuang19** [lbl-srg/modelica-buildings#3072]
PID controller with autotuning(#2884) requires a <code>FirstOrder</code> block to validate its performance. Since this block uses the <code>der()</code> operator and cannot be implemented as a composite block.

This issue is to implement this block in <code>CDL.Continuous.FirstOrder</code>. The implementation will be similar to <code>CDL.Continuous.Derivative</code>

**Comment by SenHuang19** [comment]
@mwetter:
Please let me know if this makes sense to you.

**Comment by mwetter** [comment]
@SenHuang19 : This is no longer needed as the master has now the "Derivative" block.

**Comment by SenHuang19** [comment]
@mwetter : I am sorry but I don't quite follow you. I am looking for a "FirstOrder" block, not a "Derivative" block.

**Comment by mwetter** [comment]
@SenHuang19 : The `FirstOrder` block can be composed using the `Derivative` block, e.g, you can implement it as a composite block.

**Comment by SenHuang19** [comment]
@mwetter Ah, I see. Thank you. Should we use the same method to compose the <code>SecondOrder</code> block. Do we want to include the <code>FirstOrder</code> block as a part of #2884  or create a dedicated issue for it?

**Comment by mwetter** [comment]
I think best is to do it within #2884.
Yes, the 2nd order block should also be a composite block (if it is needed for your work).
