### ISSUE TITLE
Potential typo in description field

### ISSUE THREAD

**Issue by vtnate** [lbl-srg/modelica-buildings#3077]
https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Experimental/DHC/Loads/BaseClasses/Examples/BaseClasses/BuildingTimeSeries.mo#L16-L17

What does SHW mean? Is this a typo? Should `SHW` instead be `DHW`?

**Comment by JayHuLBL** [comment]
`SHW` means `service hot water`. Check https://github.com/lbl-srg/modelica-buildings/blob/a0b13bd2905603c1acbe525e8d8998d5b2b86439/Buildings/Experimental/DHC/EnergyTransferStations/Combined/HeatPumpHeatExchanger.mo#L148

**Comment by vtnate** [comment]
Excellent, thank you for that explanation. I'll close this issue.
