### ISSUE TITLE
Warmup/initialization of zone temperatures with Spawn vs EnergyPlus

### ISSUE THREAD

**Issue by bresait** [lbl-srg/modelica-buildings#3079]
Hello,
I am struggling with comparability of behaviour between EnergyPlus and Spawn models.
More specifically, I am looking at free-floating temperatures during the first days of simulation.
As an example, the unconditioned example in the Buildings library V9.0.0:
* Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.Unconditioned (with modified m_flow_nominal to match the 0.01 m³/s infiltration in the EnergyPlus model)
* Which I compared with the corresponding EnergyPlus model after removing the HVAC objects (see attached IDF).

While EnergyPlus temperatures oscillate rather smoothly from an initial temperature at about 5 °C, the Spawn temperatures have a strong initial peak at 20 °C. When setting zon.T_start to 5 °C, the temperature does start at 5 °C but has a fast increase to about 15 °C in 10 minutes (see plots attached). Somehow the zone thermal mass seems to start significantly higher.
After this difference in the first days, the temperatures in both models do seem to converge.

Is there any way to achieve initial conditions in the zone that are more similar to EnergyPlus?

EnergyPlus:
![EnergyPlus_SingleFamilyHouse_TwoSpeed_ZoneAirBalance_FreeRunning_five_days](https://user-images.githubusercontent.com/78547759/181485273-6bfb48c4-6dd3-4261-bd47-0c70e073e1c2.svg)

Spawn with T_start 5 °C:
<img width="292" alt="Spawn_SingleFamilyHouse_TwoSpeed_ZoneAirBalance_FreeRunning_five_days_init_5C" src="https://user-images.githubusercontent.com/78547759/181485278-498cf565-2862-4d1c-8291-47169e89fe6f.png">

Spawn with T_start 20 °C:
<img width="292" alt="Spawn_SingleFamilyHouse_TwoSpeed_ZoneAirBalance_FreeRunning_five_days_init_20C" src="https://user-images.githubusercontent.com/78547759/181485281-76fb5b39-e7ad-4107-bbb2-c7fe39c3b4ee.png">

**Comment by mwetter** [comment]
@bresait : This is caused by the warm-up procedure that EnergyPlus is doing prior to the start of the simulation. Please see https://simulationresearch.lbl.gov/modelica/releases/v9.0.0/help/Buildings_ThermalZones_EnergyPlus_9_6_0_UsersGuide.html#Buildings.ThermalZones.EnergyPlus_9_6_0.UsersGuide.EnergyPlusWarmUp for the explanation.

@kbenne FYI.

**Comment by bresait** [comment]
Thank you very much for your answer! I am sorry I missed that section in the users guide.
