### ISSUE TITLE
Outdated code for .EPW weather conversion

### ISSUE THREAD

**Issue by GeorgeDawes** [lbl-srg/modelica-buildings#3080]
**Describe the bug**
After running the command prompt and changing the directory, I received an error when running the "-jar ../bin/ConvertWeatherData.jar NottinghamWeather.epw" code (see screenshot). From what I understand, the version of JAVA I am using is too new and does not support this command type - therefore, I am unable to convert the .EPW file

**To Reproduce**
Steps to reproduce the behaviour:
1.  Install latest JAVA verion
2. Open command prompt
3. Run script '**cd "C:\Program Files\Dymola 2021x\Modelica\Buildings 9.0.0\Resources\weatherdata"**' 
          where <C:\Program Files\Dymola 2021x\Modelica\Buildings 9.0.0\Resources\weatherdata> is the location of the weather file data
5. See error

**Expected behavior**
As described by M. Wetter, this should create a file of the same name only with the .MOS filetype and in that format for use in Modelica modelling.

**Screenshots**
![image](https://user-images.githubusercontent.com/107847981/182827426-4ed2b48e-c1b3-437c-97f3-eaadac25f394.png)

**Version**
 - Modelica Buildings Library: V 9.0.0
 - Modelica simulation environment Dymola - though not used to create this error
 - Operating system - Windows 11 Home (64-bit)

**Additional context**
I require a .MOS file to run either the TMY3 weather data function or the SOE functionality (though I get a separate error regarding my lack of Linux 64-bit OS for compilation.)

**Comment by mwetter** [comment]
@GeorgeDawes : It looks like your Java Runtime Environment needs to be updated. Your system seems to use Java 8 and the jar file was compiled with Java 11. See also the explanation at https://www.baeldung.com/java-lang-unsupportedclassversion

**Comment by GeorgeDawes** [comment]
I have since updated my java using JDK and changed the read/write permissions on the folder (as I thought this was the next error) but I still receive the error below stating "error in read and write data."

I have looked online to see what this type of error could be, but nothing of much use... Is this error coming from the converter program? 

I have also tried using a different .epw file to see if there was an error in the original file - but as you can see, there is no change.

![image](https://user-images.githubusercontent.com/107847981/184326376-04545f62-e1da-4892-96cb-65de2eeb0be9.png)

**Comment by mwetter** [comment]
@GeorgeDawes : This error comes from the weather data conversion program, whose source is in `src/convertEPW/src`. I tested it for the file `USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw` (on Linux) with spaces in the name, but the spaces are no problem. 
Does it work on your end if you convert the San Francisco weather data that are provided with the library?

**Comment by GeorgeDawes** [comment]
It does not work with that weather file either. I placed the filename in "" to make sure but no change. 

I could try reinstalling Dymola with the necessary libraries and see if that works. As I mentioned in my first post, it may be the installation as I cannot run Spawn due to an error raised due to my lack of Linux operating system.

**Comment by GeorgeDawes** [comment]
Hi, @mwetter any updated thoughts on this?

I'm not sure there is any issue with the .EPW file but I have attached it for reference.
[GBR_Birmingham.035340_IWEC.zip](https://github.com/lbl-srg/modelica-buildings/files/9635201/GBR_Birmingham.035340_IWEC.zip)

**Comment by mwetter** [comment]
@GeorgeDawes : That file works for me, please see below:
```bash
mwetter@srg-mw:~/Downloads$ wget -q https://github.com/lbl-srg/modelica-buildings/releases/download/v9.0.0/Buildings-v9.0.0.zip
mwetter@srg-mw:~/Downloads$ wget -q https://github.com/lbl-srg/modelica-buildings/files/9635201/GBR_Birmingham.035340_IWEC.zip
mwetter@srg-mw:~/Downloads$ unzip -q Buildings-v9.0.0.zip 
mwetter@srg-mw:~/Downloads$ unzip -q GBR_Birmingham.035340_IWEC.zip 
mwetter@srg-mw:~/Downloads$ java -jar "Buildings 9.0.0/Resources/bin/ConvertWeatherData.jar" GBR_Birmingham.035340_IWEC.epw 
mwetter@srg-mw:~/Downloads$ java --version
openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
mwetter@srg-mw:~/Downloads$ md5sum GBR_Birmingham.035340_IWEC.mos 
3ac0cf10f6c7a8d748ab60edd52b723a  GBR_Birmingham.035340_IWEC.mos
```

**Comment by GeorgeDawes** [comment]
Not sure what i did differently other than have the 2022x version of Dymola in the highest level. This may be a similar issue with having spaces in the folder names, as found when trying to run Spawn if Dymola is not at the highest-level folder/drive.

Many thanks for you help @mwetter 
![image](https://user-images.githubusercontent.com/107847981/196408440-efee37e7-768d-431a-8c4a-8792476669e7.png)
