### ISSUE TITLE
Representation of outputs in Buildings.Electrical.Examples.ACLineMedium

### ISSUE THREAD

**Issue by amyeallen1** [lbl-srg/modelica-buildings#3094]
Phase angle: The phase angle at the terminals of each line seem to be reported cumulatively--perhaps this could be clarified in the output descriptions. 

"P" (power of the load): This variable does not appear to be used for the lines in this model, and instead, the active and reactive powers S report the dissipated power. Perhaps this output should be disabled. 

Thanks, Mingzhe, for clarifying about the variable outputs. @mingzhe37

**Comment by mwetter** [comment]
@amyeallen1 : The underlying issue seems to be that depending on the parameter `mode`, power is not used and then set to zero in `Electrical.Interfaces.Load`:
```modelica
  // If the power is fixed, inner connector value is equal to 1
  if mode==Buildings.Electrical.Types.Load.FixedZ_steady_state or 
     mode==Buildings.Electrical.Types.Load.FixedZ_dynamic then
    y_internal   = 1;
    P_internal = 0;
  elseif mode==Buildings.Electrical.Types.Load.VariableZ_y_input then
    P_internal = 0;
  elseif mode==Buildings.Electrical.Types.Load.VariableZ_P_input then
    y_internal = 1;
  end if;

  // Value of the load, depending on the type: fixed or variable
  if mode==Buildings.Electrical.Types.Load.VariableZ_y_input then
    load = eps + oneEps*y_internal;
  else
    load = 1;
  end if;

  // Power consumption
  if mode==Buildings.Electrical.Types.Load.FixedZ_steady_state or 
     mode==Buildings.Electrical.Types.Load.FixedZ_dynamic then
    P = P_nominal;
  elseif mode==Buildings.Electrical.Types.Load.VariableZ_P_input then
    P = P_internal;
  else
    P = P_nominal*load;
  end if;
```
An output cannot be "disabled" in Modelica.

**Comment by amyeallen1** [comment]
Hi Michael---thanks for clarifying about that. 
@mwetter

**Comment by mwetter** [comment]
@amyeallen1 : I will close this. Please reopen it if you have a suggestions for how to clarify or improve the model.
