### ISSUE TITLE
Spawn contained FMU running in Simulink issue

### ISSUE THREAD

**Issue by LiangSHI430** [lbl-srg/modelica-buildings#3097]
Hi all,

I am trying to do a co-simulation between Simulink (for HVAC control design) and Modelica (for building envelope from Spawn) in the Simulink environment. For a simple test, I exported a fmu file containing the Spawn module (Buildings Library v9.0.0) using Dymola 2021x, and imported it to Simulink (MATLAB R2018a) through FMIKit-Simulink-2.9. I tried to run the simulation but it came with the following error:

Error: The following error was detected at time: 0
Failed to find spawn executable in Buildings Library installation, on SPAWNPATH and on PATH. See installation instructions at Buildings.ThermalZones.EnergyPlus_9_6_0.UsersGuide.Installation
The stack of functions is:
Buildings.ThermalZones.EnergyPlus_9_6_0.BaseClasses.initialize
Buildings.ThermalZones.EnergyPlus_9_6_0.BaseClasses.initialize(
zon.fmuZon.adapter, 
building.isSynchronized)
fmiInitialize: dsblock_ failed, QiErr = 1
Unless otherwise indicated by error messages, possible errors are (non-exhaustive):
The model references external data that is not present on the target machine, at least not with the same location.
Failed to enter initialization mode
Failed to enter initialization mode. The FMU crashed (exception code: UNKOWN_EXEPTION_CODE).

I am wondering if anyone can help me with this problem, thank you in advance and I am looking forward to your reply.

Regards,
Liang from Purdue

**Comment by mwetter** [comment]
@LiangSHI430 : The error message is
> Failed to find spawn executable in Buildings Library installation, on SPAWNPATH and on PATH. See installation instructions at Buildings.ThermalZones.EnergyPlus_9_6_0.UsersGuide.Installation

Did you set these environment variables as explained in the referenced user guide?

**Comment by LiangSHI430** [comment]
@mwetter Hi Michael, I am new and not familiar with how to set environment variables, is there any tutorial on this? Thank you so much!

**Comment by mwetter** [comment]
@LiangSHI430 Please work with your IT support for how to set environment variables, or check the documentation of your operating system.
