### ISSUE TITLE
Drybulb temperature change after adding water

### ISSUE THREAD

**Issue by fuxinniu** [lbl-srg/modelica-buildings#3102]
Hi Michael, 

I am confused on the indoor dry bulb temperature after adding water into room. Why the dry bulb decreased after adding water. 

Through the energy and mass balance equation, it should be decoupled between water inject and Qflow. Could you help explain this?

Thanks a lot. 

Frank

// Energy and mass balances
  if energyDynamics == Modelica.Fluid.Types.Dynamics.SteadyState then
    0 = Hb_flow + Q_flow;
  else
    der(U) = Hb_flow + Q_flow;
  end if;

  if massDynamics == Modelica.Fluid.Types.Dynamics.SteadyState then
    0 = mb_flow + (if simplify_mWat_flow then 0 else mWat_flow_internal);
  else
    der(m) = mb_flow + (if simplify_mWat_flow then 0 else mWat_flow_internal);
  end if;

![image](https://user-images.githubusercontent.com/58092272/189232681-f292f632-95ba-4061-94eb-fa073e974d78.png)

![image](https://user-images.githubusercontent.com/58092272/189232607-64a7e5e1-3621-41d0-bf31-8bdec20dc89e.png)

**Comment by mwetter** [comment]
@fuxinniu: This behavior is expected as adding liquid water causes isenthalpic cooling of the air. The leaving moisture content of the air is higher than the moisture content of the air that enters the volume. To keep enthalpy constant between inlet and outlet, the leaving air temperature needs to be lower.
If you want to add water vapor, you also need to add the corresponding energy at the heat port of the volume.
