### ISSUE TITLE
Port update of Guideline 36 ventilation effectiveness (guard against division by zero)

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#3108]
This issue is to port the updates from https://github.com/lbl-srg/modelica-buildings/pull/3107 to the updated implementation of Guideline 36 because the corrections in https://github.com/lbl-srg/modelica-buildings/pull/3107 have only been done for the public release draft 1.

**Comment by mwetter** [comment]
@JayHuLBL : Can you please port these changes. Note that the official G36 version is now on the `master` and soon on `maint_9.1.x`. It will be merged via https://github.com/lbl-srg/modelica-buildings/pull/3161, so best is to use the branch `maint_9.1.x_G36` as the base, and make a new PR to `maint_9.1.x`. Once https://github.com/lbl-srg/modelica-buildings/pull/3161 is merged, the new PR will only show the updated files.

This fix needs to be part of the 9.1 release.

**Comment by JayHuLBL** [comment]
@mwetter The correction in #3107 has been implemented in the official version in the master branch.
This issue can be closed.
