### ISSUE TITLE
Unable to compile fmu with single layer glazing systems

### ISSUE THREAD

**Issue by JamesCheng21** [lbl-srg/modelica-buildings#3117]
**Describe the bug**

Any model with a single-layer glazing system cannot be compiled into FMU using OpenModelica (or JModelica)

**To Reproduce**
1. Open any room model, say 'Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case600FF'
2. Replace the glazing system with a single layer one, say 'Buildings.HeatTransfer.Data.GlazingSystems.SingleClear3'
3. export FMU in OpenModelica

**Error messages**
`[5] 14:46:12 Translation Error: Internal error Instantiation of BCAA.BaseClasses.testbedFF failed with no error message.`

`Array size mismatch in modification of gas, expected size is [0] and size of binding expression is [1]` (generated by pymodelica)

**Version**
 - Modelica Buildings Library: 7.0/8.0/9.0
 - Modelica simulation environment: OpenModelica/JModelica
 - Operating system: win10 64bit

**Additional context**
We've faced the same issue since one year ago using JModelica with older version Buildings and Modelica libraries. Now again with OpenModelica 1.19.0 and the Buildings library 9.0.0. The reason for going back to pymodelica is to get the specific error message.

**Comment by JayHuLBL** [comment]
@JamesCheng21 See the closed issue #3026. It has been addressed. This is fixed on the `master` and `maint_8.1.x` branches.
