### ISSUE TITLE
G36 VAV MZ controller

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#3139]
This issue is to track the changes related to 
- the comments at https://github.com/lbl-srg/modelica-buildings/issues/1913 that were disregarded:
  - [x] See comment on `uRelFan`: this input should be removed.
  - [x] See comment on `uSupFanSpe_actual`: this input should be removed.
  - [x] See comment on `u1SupFan` and `u1RelFan`: the description string should be corrected.
- some recent comments that further need to be considered:
  - [x] In `Buildings.Controls.OBC.ASHRAE.G36.Types.OutdoorAirSection` the `NoEconomizer` choice is not mapped to any control logic: it should be removed as the corresponding control sequence is not specified in G36.
  - [x] In `Buildings.Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.Controller` the option `Buildings.Controls.OBC.ASHRAE.G36.Types.BuildingPressureControlTypes.ReturnFanCalculatedAir` should be deleted as suggested by Hwakong on Fri, Oct 21, 2022. (Please note that the current implementation of this option yields an algebraic loop if the controller has a proportional term as the fan speed has direct feedback.)
  - [x] In `Buildings.Controls.OBC.ASHRAE.G36.Types.FreezeStat` for `Connected_to_BAS_NO` and `Connected_to_BAS_NC`: The choice of polarity should be removed as it is nowhere else present (for occupancy or window switches for instance). It is recommended to choose a NC polarity by default and to make it explicit in the documentation (for all other Boolean switches as well, such as occupancy or window switches).  In addition, the implementation should be validated as the description string for `u1FreSta` is incorrect (confusion between NC and NO): see comment on `u1FreSta` at https://github.com/lbl-srg/modelica-buildings/issues/1913. Eventually, Reece mentioned on Wed, Nov 2, 2022 that a freeze stat connected to the BAS only has an impact on the 3rd stage of freeze protection (5.16.12.3): the first 2 stages based on SAT should remain unchanged.
  - [x] FER: Add option to completely disable freeze protection (for climates that don't need it): this should be close to the actual implementation for `Hardwired_to_equipment` but an additional Boolean parameter is needed.
  - [x] The G36 VAV box controller should only output the commanded damper position and not expose any choices related to the VAV damper type. This is because standalone pressure independent dampers (that take a mass flow rate setpoint as an input, see for instance the description in ASHRAE 825-RP) are not commonly used in North America. There is rather a pressure independent *control logic* that is implemented in the terminal unit controller with all the additional logic for occupancy modes and requests.
  - [x] The example model `Buildings.Examples.VAVReheat.Guideline36` should use an instance of `Buildings.Fluid.Actuators.Dampers.Exponential` as opposed to `Buildings.Fluid.Actuators.Dampers.PressureIndependent` which is used currently.

**Comment by JayHuLBL** [comment]
@AntoineGautier 
For the comment `There is rather a pressure independent control logic that is implemented in the terminal unit controller with all the additional logic for occupancy modes and requests.`, do you mean to create a new subsequence in, for instance, `TerminalUnits.Reheat.Subsequences`, so one `DamperValvesPressureIndependent`?
I am addressing the comments in branch issue3139_MZController.

**Comment by AntoineGautier** [comment]
@JayHuLBL My comment about the pressure independent *control logic* is for reference only. This logic is already implemented: see for instance the component `conPID` within `Controls.OBC.ASHRAE.G36.TerminalUnits.CoolingOnly.Subsequences.Dampers`. 
What should be removed is the output connector `VSet_flow` and the parameter `have_preIndDam` (within the scope of G36 application, VAV box dampers always receive a commanded position, not a flow setpoint). 
Those modifications should be applied to all terminal unit subsequences.
With those modifications the example model `Examples.VAVReheat.Guideline36` becomes invalid as it uses a pressure independent damper model that requires a flow setpoint as input. So this should be refactored with an exponential damper model.
