### ISSUE TITLE
Bugs for the models in cooling capacity calculator model

### ISSUE THREAD

**Issue by lambtt** [lbl-srg/modelica-buildings#3146]
**Describe the bug**
Model 1. Buildings.Fluid.HeatExchangers.DXCoils.BaseClasses.CoolingCapacityWaterCooled
Model 2. Buildings.Fluid.HeatExchangers.DXCoils.BaseClasses.PartialCoolingCapacity
Some codes for these two models seem to have problems.
**Screenshots**
For Model 1, it seems the water mass flow, ffCon should have been used in Cooling capacity modification factor as a function of water flow fraction at the condenser, but it didn't. And it seems the ffConMin should be replaced with ffConMax.

![Snipaste_2022-11-08_10-26-41](https://user-images.githubusercontent.com/91109801/200620784-746cdb93-32da-40d1-8f60-6b94f0b62530.png)

For Model 2, it seems there is the same issue as Model 1.

![Snipaste_2022-11-08_10-30-01](https://user-images.githubusercontent.com/91109801/200621454-fd1f9f12-b709-49cc-9ea8-2f9c1deeaab1.png)
![Snipaste_2022-11-08_10-30-41](https://user-images.githubusercontent.com/91109801/200621600-c1713fed-3939-4265-a030-1e4d5dbbd359.png)

**Version**
 - Modelica Buildings Library: [9.0.0]
 - Modelica simulation environment: Dymola 2023
 - Operating system: Windows 10

**Additional context**
I did the curve fitting (different temperatures and different flow rates) for the heat pump in our lab and found the results could not be matched. I copied Models 1 and 2 and modified the codes. Finally, the results could be matched.

The performance curve (Buildings.Fluid.HeatExchangers.DXCoils.WaterCooled.Examples.PerformanceCurves.Curve_I) in Example (Buildings.Fluid.HeatExchangers.DXCoils.WaterCooled.Examples.VariableSpeed) uses a constant modification factor for capFunFF, capFunFFCon, EIRFunFF, and EIRFunFFCon. I'm wondering if maybe that's the reason the bugs above didn't come up in the Example.

![Snipaste_2022-11-08_10-32-40](https://user-images.githubusercontent.com/91109801/200622040-38e217a9-606f-4256-9ac4-c49691c1e608.png)

**Comment by mwetter** [comment]
Thanks for reporting. I will correct it on branch `issue3065_dxCoilsPerformance`

**Comment by mwetter** [comment]
@lambtt : Can you please check if https://github.com/lbl-srg/modelica-buildings/pull/3147 addresses the issue.
Thanks.
