### ISSUE TITLE
Fluid.HeatExchangers.BaseClasses.PartialEffectivenessNTU has wrongly designed sta2_default

### ISSUE THREAD

**Issue by RouvenZ** [lbl-srg/modelica-buildings#3151]
Dear all,

within the file [PartialEffectivenessNTU](https://github.com/lbl-srg/modelica-buildings/blob/5994b610d9a149a0bad847e16c2605251445b5ed/Buildings/Fluid/HeatExchangers/BaseClasses/PartialEffectivenessNTU.mo) in the Fluid Package there seems to be an error in [line 57](https://github.com/lbl-srg/modelica-buildings/blob/5994b610d9a149a0bad847e16c2605251445b5ed/Buildings/Fluid/HeatExchangers/BaseClasses/PartialEffectivenessNTU.mo#L57), where it defines the default state for medium 2 `sta2_default` with the default temperature of medium 1 which (as not mentioned in the docu) I assume to be a typo:

`final parameter Medium2.ThermodynamicState sta2_default = Medium2.setState_pTX(`
`T=Medium1.T_default,`
`p=Medium2.p_default,`
`X=Medium2.X_default[1:Medium2.nXi]) "Default state for medium 2";`

As most default temperatures are defined at 20°C, I assume this has never had an impact. However, for compatibility reasons and designing new media, I assume this might cause problems. 

Thanks for caring, have a nice weekend!

Cheers
Rouven

**Comment by mwetter** [comment]
Thanks for reporting. I will correct it.
For `Media.Air` and `Media.Water` the temperature does not affect the thermodynamic properties, but it is nevertheless good to correct.
