### ISSUE TITLE
Highlight version requirement for Python functions package

### ISSUE THREAD

**Issue by piliadis** [lbl-srg/modelica-buildings#3156]
Hi there,
From our experiments, we concluded that for Python IO package to work in Windows, it needs specifically Python version 3.8.0. If this is indeed the case, we suggest highlighting it in the UsersGuide.
Best regards

**Comment by JayHuLBL** [comment]
Hi @piliadis,

We indeed have package named as `Python_3_8` and in the UserGuide, we have highlighted it as `To use classes from this package, a Python 3.8 runtime environment must be installed.`

**Comment by JayHuLBL** [comment]
@piliadis I tested the example models in `Buildings.Utilities.IO.Python_3_8` with Python 3.8.10 and they work well. Please make sure the `Advanced.CompileWith64 = 2;` being set as  shown in the `UserGuide`.

I will highlight the minor version in the `UserGuide` through PR #3162.
