### ISSUE TITLE
Spawn FMU cannot be reset and initialized

### ISSUE THREAD

**Issue by lambtt** [lbl-srg/modelica-buildings#3172]
**Describe the bug**
Model: The model with Spawn.
I exported the model by Dymola 2023 to FMU (Co-simulation, 64-bit).
I could run this FMU in Python for a whole day.
I could also run this FMU in a timestep and then continue it for another.
But I could not run this FMU at the same timestep by reset () and initialize ().
The console will report "Writing tabular output file results using HTML format.", and then no reaction anymore.

I test the model without Spawn in the same framework. The FMU could be simulated in the same timestep by reset () and initialize().
I'm wondering if that's because EnergyPlus's FMU doesn't be initialized even though I give commands "FMU.reset ()" and "FMU. initialize()" to the total FMU for the model with Spawn.

I tried to manually load the EnergyPlus's FMU generated by Spawn.exe in this process and initialize it. But it doesn't work.
Maybe they are two different instances from the same EnergyPlus FMU.

**Expected behavior**
The expected behavior is the model could be run again during the same timestep for optimization control like MPC.

**Screenshots**
The FMU setting.

![Snipaste_2022-11-29_18-38-21](https://user-images.githubusercontent.com/91109801/204679357-b2917008-0c7f-46f0-b14f-d29ba888193c.png)

The model with Spawn can not be reset and initialized by initialize() or enter_initialization_mode() and exit_initialization_mode().

![image](https://user-images.githubusercontent.com/91109801/204678989-a6caa7c8-e390-4ce1-82cd-1d0fc9df2bd0.png)
![image](https://user-images.githubusercontent.com/91109801/204678952-114588a7-b28f-4475-bfaa-5ca10e97bb44.png)
The model without Spawn can be reset and initialized by initialize().

![Snipaste_2022-11-29_18-36-17](https://user-images.githubusercontent.com/91109801/204679081-26075059-08bd-41de-a70f-506f4a0a3f0e.png)

**Version**
 - Modelica Buildings Library: [9.0.0]
 - Modelica simulation environment: Dymola 2023
 - Operating system: Windows 10

**Additional context**

**Comment by mwetter** [comment]
Because the EnergyPlus binaries do not allow saving and reinitializing the state, Modelica models with the Spawn coupling can't be used in such a workflow. If you need this capability, you will need to model the envelope in Modelica.
