### ISSUE TITLE
Instructions in ExpansionVessel Example Documentation Lead to Error

### ISSUE THREAD

**Issue by hcasperfu** [lbl-srg/modelica-buildings#3198]
The documentation of `Buildings.Fluid.Storage.Examples.ExpansionVessel` has the following language:

> To see the effect of the expansion vessel, delete the connecting line between the volume and the expansion vessel and check how much more the pressure increases as the fluid is heated.

Doing so, however, will make the model structurally singular. 
The documentation of this example model also does not have revision log.

**Comment by mwetter** [comment]
That is a very old comment from the times when the media was modeled as compressible. Can you please correct it an make a pull request for the master and `maint_9.1.x` branch.

**Comment by hcasperfu** [comment]
@mwetter 
Thank you for the clarification! This makes sense now.
Do I just change the comment (and say something like "to see the effect use a compressible medium model") or should I replace the medium model to a compressible one?

**Comment by mwetter** [comment]
I suggest to delete this part of the comment, and also the statement that the example uses a density that is dependent on temperature. This was in an earlier version of this example but is no longer true.
Note that this would also need to be corrected in the IBPSA library.
