### ISSUE TITLE
Buildings.Utilities.Time.CalendarTime is not numerically robust

### ISSUE THREAD

**Issue by casella** [lbl-srg/modelica-buildings#3199]
**Describe the bug**
The test model [Buildings.Utilities.Time.Examples.CalendarTime](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Utilities.Time.Examples.CalendarTime.diff.calendarTime2016.day.html), when ran by OMC, shows an issue with the computation of the day of the month: following Jan 31, Jan 32 is output before turning to Feb 1.

The cause of this issue is that `epochLastMonth` is updated by this when statement
```modelica
  when unixTimeStampLocal >= pre(epochLastMonth) +
      (if pre(month)==2 and isLeapYear[yearIndex]
        then 1 + dayInMonth[pre(month)] else dayInMonth[pre(month)])*3600*24 then
    month = if pre(month) == 12 then 1 else pre(month) + 1;
    epochLastMonth = pre(epochLastMonth) +
      (if pre(month)==2 and isLeapYear[yearIndex]
        then 1 + dayInMonth[pre(month)] else dayInMonth[pre(month)])*3600*24;
  end when;
```
while the day of the month is computed by this other when statement
```modelica
  daySampleTrigger =sample(daySampleStart, 86400);
  when daySampleTrigger then
    if pre(firstDaySampling) then
      daysSinceEpoch = integer(floor(unixTimeStampLocal/3600/24));
      weekDay=integer(rem(4+daysSinceEpoch-1,7)+1);
    else
      daysSinceEpoch = pre(daysSinceEpoch) + 1;
      weekDay = if (pre(weekDay) == 7) then 1 else (pre(weekDay) + 1);
    end if;
    day = integer(1+floor((unixTimeStampLocal-epochLastMonth)/3600/24));

    firstDaySampling = false;
  end when;
```
In principle, the two statements should be triggered exactly at the same time. However, there is no explicit synchronization mechanism between the to, and in fact `epochLastMonth` tends to accumulate small numerical errors, so that there could be a small time shift between the two events. So, when the end of the month comes, there is no guarantee that when `daySampleTrigger` fires, `epochLastMonth` has just been updated to the new value. In fact, this is precisely why OMC goes to Jan 32, see the event log:
```
check for discrete changes at time=2678400
discrete var changed: calTim.daySampleTrigger from 0 to 1
...
state event at time=2678400.14543
[2] calTim.unixTimeStampLocal >= pre(calTim.epochLastMonth) + /*Real*/((if pre(calTim.month) == 2 and {false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false}[calTim.yearIndex] then 1 + {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31}[pre(calTim.month)] else {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31}[pre(calTim.month)]) * 3600 * 24)
```
In this case, the number of the day is updated 0.14 s before epochLastMonth is updated, so January gets an extra leap day. The same happens for the following months.

My suggestions is that the logic of CalendarTime should be changed so that all the daily, monthly and yearly updates are all made _with the proper order_ within the `when daySampleTrigger` statement. Statements such as  
```modelica
when unixTimeStampLocal >= timeStampsNewYear[pre(yearIndex)+1] then
```
should be moved inside the `when daySampleTrigger` and turned into
```modelica
if abs(unixTimeStampLocal - timeStampsNewYear[pre(yearIndex)+1]) < eps_time then
```
where `eps_time` should be much smaller than one day, but large enough to accommodate for accumulated errors in the time stamps and epoch times.

In this way, it will be guaranteed by construction that events won't be missed because of rounding errors.

**Comment by mwetter** [comment]
@casella : Thanks for reporting. We will fix it upstream in the `IBPSA` library.

**Comment by casella** [comment]
Great, thanks!
