### ISSUE TITLE
HDirNor or HDirHor?

### ISSUE THREAD

**Issue by JackHsueh** [lbl-srg/modelica-buildings#3217]
**Describe the bug**
In the block ShyClearness (buildings9.1--Boundary Conditions--SolarIrradiation--BaseClasses)，"Modelica.Blocks.Interfaces.RealInput  
 HDirHor" is declared, but in the equation "skyCle = Buildings.Utilities.Math.Functions.smoothLimit(
        x = ((HDirNor+HDifHorBou)...." HDirNor is used. Whiche one is right?

**Comment by EttoreZ** [comment]
@JackHsueh  I checked the block `SkyClearness`. I did not find the variable `HDirHor` in the equations, could you write a code snippet of the block? I found two typos one in the release notes mentioning `HDirHor` and one in Icon view misnaming `HDirNor`. For the @mwetter I can open a pull request on the the IBPSA library.

**Comment by mwetter** [comment]
@EttoreZ : Can you please open the PR in `IBPSA` so that the typos are fixed, thanks.

**Comment by mwetter** [comment]
This is fixed through https://github.com/ibpsa/modelica-ibpsa/issues/1713
