### ISSUE TITLE
Buildings.Fluid.HeatPumps.Carnot_TCon error with default value of parameter etaCarnot_nominal

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/modelica-buildings#3226]
## Problem
When using ``Buildings.Fluid.HeatPumps.Carnot_TCon`` if I set ``use_eta_Carnot_nominal=true`` and let ``etaCarnot_nominal`` be the default value (``COP_nominal/(TUseAct_nominal/(TCon_nominal + TAppCon_nominal - (TEva_nominal -
  TAppEva_nominal)))``), I get an error when trying to compile and simulate the example ``Buildings.Fluid.HeatPumps.Examples.Carnot_TCon``:

```
The parameter bindings 
heaPum.etaCarnot_nominal = heaPum.COP_nominal*(heaPum.TCon_nominal+ heaPum.TAppCon_nominal-heaPum.TEva_nominal+heaPum.TAppEva_nominal)/ heaPum.TUseAct_nominal;
heaPum.COP_nominal = heaPum.etaCarnot_nominal*heaPum.TUseAct_nominal/( heaPum.TCon_nominal+heaPum.TAppCon_nominal-heaPum.TEva_nominal+ heaPum.TAppEva_nominal);
are cyclic, that is only allowed if evaluating other parameters with Evaluate=true breaks the loop.
```

In the example ``Buildings.Fluid.HeatPumps.Examples.Carnot_TCon``, the value of ``etaCarnot_nominal`` is set ``=0.3``, and the model compiles and simulates ok.

I think the default value of ``etaCarnot_nominal``  should be set such that the model can compile and simulate ok.

## Possible solutions
1. Set by default ``etaCarnot_nominal=0.3``
2. Determine what is wrong with the current default expression and make a different fix.

## Environment
Ubuntu 20.04
Dymola 2023x
Buildings latest master commit (67a5063).

**Comment by mwetter** [comment]
The current implementation leads indeed to a circular assignment. Solution 1 is what I think is the best. I will suggest the fix in the `IBPSA` library.
