### ISSUE TITLE
Guideline36Winter example slow simulation advancement 

### ISSUE THREAD

**Issue by GiuseppeR96** [lbl-srg/modelica-buildings#3259]
Hello, I am try to run the example Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.Guideline36Winter. The simulation seems to get stuck at 0%. During the simulation the following  message appears in output window: 

`Matrix singular! 
under-determined linear system not solvable!
The initialization finished successfully with 3 homotopy steps.`

I wonder if  this is releted to a poor performance of openModelica as a solver.

I am using:

- Windows 10 
- OpenModelica v1.20.0 (64-bit) and v1.19.0 dev.beta1 (64 bit) (same behavior with both versions)
- Buildings library 9.1.0

**Comment by mwetter** [comment]
This is a known problem and the file is currently on the exclude list:
https://github.com/lbl-srg/modelica-buildings/blob/2d91fc74f52294b58aea2e2f4eefd8cc7d931360/Buildings/Resources/Scripts/BuildingsPy/conf.yml#L374

We are working with the OpenModelica team on simulation support.
