### ISSUE TITLE
Buildings.Experimental.DHC.EnergyTransferStations.Cooling.Indirect controls building supply temperature incorrectly

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/modelica-buildings#3299]
In the example model ``Buildings.Experimental.DHC.EnergyTransferStations.Cooling.Examples.Indirect``, the building chilled water supply temperature set point is 7 C (``TSetCHWS.k = 273.15+7``).  However, when looking at the example simulation results, the building chilled water supply temperature measurement does not meet the set point, and the control valve is always at 1.  See below screenshot.

<img width="828" alt="wrong" src="https://user-images.githubusercontent.com/19480999/225758857-e7a439be-6db3-4dd1-8692-b38dce132768.png">

I think the component ``Buildings.Experimental.DHC.EnergyTransferStations.Cooling.Indirect.con`` has the wrong parameter setting for ``reverseActing``.  It is equal to ``true`` but should be ``false``.  Changing it to ``false`` produces the expected result for building chilled water supply temperature.  See below screenshot.

<img width="817" alt="Screen Shot 2023-03-16 at 5 37 02 PM" src="https://user-images.githubusercontent.com/19480999/225758878-d37f1a6c-a051-479c-9f9a-8ab11b4a87f7.png">

@JayHuLBL Can you double check and let me know what you think?  If this is indeed an issue, I can make the correction, etc. and make a PR.

**Comment by JayHuLBL** [comment]
@dhblum

I think it indeeds is a bug. The `reverseActing` should be `false`. 

The expected behavior is that when the reading from `senTBuiSup` increases, the control valve `conVal` should open wider to cool down the building supply temperature. Thus, the PID should not be `reverseActing`.

**Comment by dhblum** [comment]
Thank you!  Making a PR now.

**Comment by dhblum** [comment]
This was closed by https://github.com/lbl-srg/modelica-buildings/pull/3300.
