### ISSUE TITLE
reference external data not found

### ISSUE THREAD

**Issue by lambtt** [lbl-srg/modelica-buildings#3307]
**Describe the bug**
Any input related to the function "Buildings.Utilities.Psychrometrics.TWetBul_TDryBulXi" would introduce an error when I use PyFMI to simulate the FMU.

I tried different variables as inputs for the FMU and found if I set any variable related to this function as input, an error would stop the simulation at the beginning, which is shown below.

**Screenshots**
![image](https://user-images.githubusercontent.com/91109801/226069789-43138294-eacc-40e5-a536-cf31735220b1.png)

**Version**

 - Modelica Buildings Library: 9.0.0
 - PyFMI: 2.9.7
 - Modelica 4.0.0. Dymola 2023
 - Windows 10

**Comment by mwetter** [comment]
The expression `r1` is `Real r1=TSat/TTriple` where `TSet` is an input that is obtained from
```modelica
  Modelica.Blocks.Interfaces.RealInput TDryBul(
    start=303,
    final quantity="ThermodynamicTemperature",
    final unit="K",
    min=0) "Dry bulb temperature"
    annotation (Placement(transformation(extent={{-120,70},{-100,90}})));
```
As this has a start value, and you seem to also provide a value when calling the FMU, this seems to be a bug in PyFMI which appears to evaluate the equations before the start value or the input is set. I suggest you post it on the PyFMI support site.
