### ISSUE TITLE
Clean Buildings.Experimental.DHC.Networks

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/modelica-buildings#3357]
This issue is to clean up the ``Buildings.Experimental.DHC.Networks`` package.  In particular, things like:

- [x] Differentiate icon for ``Combined.BaseClasses.PipeAutosize`` and ``Combined.BaseClasses.PipeStandard`` and also move them out of ``BaseClasses`` since would be good to show them as available to use by users.
- [x] Move ``Combined.BaseClasses``, ``Combined.UnidirectionalSeries``, and ``Combined.UnidirectionalParallel`` out of ``Combined`` since meant to be used with any network type.
- [x] Implement distribution network models that utilize the autosizing pipes, as this would be useful.
- [ ] Clean up the network models so as to not have unconnected ports, which are confusing, especially to new users.
- [x] Fill out network options as needed.
- [x] Add example and validation models.
- [x] Improve documentation

**Comment by EttoreZ** [comment]
I leave this comment to keep track with an issue found with model`Buildings.Experimental.DHC.Networks.Connections.Connection2PipePlugFlow`. Where supply plugflow pipe `pipDisSup` and return plugflow pipe `pipDisRet` are connected to the same heat port.

**Comment by dhblum** [comment]
This is being addressed now together with https://github.com/lbl-srg/modelica-buildings/issues/3431.

**Comment by dhblum** [comment]
Closed by https://github.com/lbl-srg/modelica-buildings/pull/3642.
