### ISSUE TITLE
update to optimica 1.43.4

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#3360]
This issue is to update the ci testing to oct 1.43.4

**Comment by mwetter** [comment]
With this version of optimica, `Buildings.Air.Systems.SingleZone.VAV.Examples.OptimalStart.Guideline36Summer` fails to simulate. The reason is that in the cooling coil, `C1_flow` has no nominal value set. It is an iteration variable with magnitude 25000. Setting it fixes the problem.

**Comment by mwetter** [comment]
Setting a nominal value gives in Dymola the error "Incompatible number of dimensions for variable and its definition equation":
https://app.travis-ci.com/github/lbl-srg/modelica-buildings/jobs/601041107#L9942

**Comment by hcasperfu** [comment]
@mwetter -
I had a quick look at this and I am fairly certain it's a bug of Dymola. Both OMC and OCT can simulate this model with no problem. What's funny is that Dymola has no problem with the extended model with two floors and two zones.
I couldn't figure out a quick workaround for this.

**Comment by mwetter** [comment]
It looks like our work crossed. I think it is a bug in Dymola, with the work-around being [d15928d](https://github.com/lbl-srg/modelica-buildings/commit/d15928d5bcf663e453b5cc7257e2c8d599e47294).

I updated the PRs on Buildings (master and maint_9.1.x) and also made a new PR on IBPSA to avoid a warning about nominal values being non-literal (https://github.com/ibpsa/modelica-ibpsa/pull/1734).
