### ISSUE TITLE
Add type casts to malloc and realloc in C-Sources

### ISSUE THREAD

**Issue by hcasperfu** [lbl-srg/modelica-buildings#3382]
This issue is to assign an issue number and branch number for PR #3378 which was created from a fork.

**Comment by rfranke** [comment]
Tonight we got actual numbers for "Numerous" in #3378:
Compile/Simulate/Verify improved from
```
 1233/1171/1029
```
[to](https://libraries.openmodelica.org/branches/overview-c++.html)
```
 1410/1330/1148
```
Not yet the level of the default C runtime for Buildings (1555/1503/1341), but not bad either for one PR :)

May 5:
<img width="590" alt="Screenshot 2023-05-06 at 05 33 29" src="https://user-images.githubusercontent.com/4224368/236596779-dc921534-da6f-4062-ac04-67202d5ff37b.png">

May 3:
<img width="586" alt="Screenshot 2023-05-06 at 05 32 03" src="https://user-images.githubusercontent.com/4224368/236596739-7db0ffc5-080c-4985-b4d3-05531f429597.png">

**Comment by rfranke** [comment]
Here are some examples motivating the C++ runtime, as sheer coverage statistics looks worse than C. The major use is for FMI export, if models get compiled once and then run frequently. Stricter typing and deterministic memory management lead to some additional issues and longer compilation times. In return the compiler does more code optimization. Generally this pays off at runtime. [See coverage testing](https://github.com/OpenModelica/OpenModelica/wiki/Library-Coverage-Testing).

Two good examples:
`Buildings.Fluid.Geothermal.Borefields.Examples.Borefields`
`Buildings.Fluid.Geothermal.Borefields.Examples.RectangularBorefield`
```
           Simulation | Compile Time C++      Simulation | Compile Time C
                 1.92 | 308.49                      4.29 | 60.25
                10.31 | 76.49                      27.59 | 16.69
```

Two extreme cases deviating upwards and downwards:
`Buildings.Fluid.Geothermal.Borefields.Validation.ConstantHeatInjection_100Boreholes`
`Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.CylindricalHeatSource`
```
           Simulation | Compile Time C++      Simulation | Compile Time C
                82.00 | 90.53                      58.12 | 20.78
                42.99 | 5.86                      254.37 | 2.41
```
The extreme cases are as quite some (maybe too many) things are different between the two runtimes, beyond target language. Like the treatment of events, see also https://github.com/OpenModelica/OpenModelica/issues/10580

**Comment by rfranke** [comment]
@mwetter: I just discovered a remaining thing: PR #3378 changed `Buildings/Resources/C-Sources/jsonWriterInit.c` line 38 from:
```C
   ID-> varKeys[i] = malloc((strlen(varKeys[i])+1) * sizeof(char*));
```
to
```C
    ID-> varKeys[i] = (char **)malloc((strlen(varKeys[i])+1) * sizeof(char*));
```
It should be:
```C
    ID-> varKeys[i] = (char *)malloc((strlen(varKeys[i])+1) * sizeof(char));
```
See https://libraries.openmodelica.org/branches/cpp/Buildings_latest/files/Buildings_latest_Buildings.Utilities.IO.Files.Examples.JSONWriter.err
```
Buildings 10.0.0-master/Resources/C-Sources/jsonWriterInit.c:38:23:
error: incompatible pointer types assigning to 'char *' from 'char **'; dereference with *
    ID-> varKeys[i] = (char **)malloc((strlen(varKeys[i])+1) * sizeof(char*));
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by mwetter** [comment]
@rfranke : Thanks, I will make the changes in `Buildings` and `IBPSA`.

**Comment by mwetter** [comment]
This is corrected since a while already.
