### ISSUE TITLE
The default binding of a function input depends on itself.

### ISSUE THREAD

**Issue by qlambert-pro** [lbl-srg/modelica-buildings#3384]
**Describe the bug**
The default binding of a function argument depends on itself.

**To Reproduce**
1. Open `Buildings.Media.Examples.BaseClasses.PartialProperties.checkState`
2. Validate the function with Wolfram SystemModeler
3. See error:
> Error: Buildings.Media.Examples.BaseClasses.PartialProperties.checkState [5:5-5:5] Invalid declaration equation. Cyclical dependency involving: errAbs.

**Expected behavior**
The function validates because the name of the function input and the name of the constant used to initialise it are different.

**Version**
 - Modelica Buildings Library: 368f3a3
 - Wolfram SystemModeler
 - Operating system: NA

**Comment by hcasperfu** [comment]
@mwetter -

I have made PR's for `Buildings` on `master` (#3387) and on `maint_9.1.x` (#3388), as well as for `IBPSA` (https://github.com/ibpsa/modelica-ibpsa/pull/1743). This does not apply to `Buildings` on `maint_8.1.x` because the line in question doesn't exit on that branch.

**Comment by mwetter** [comment]
@mwetter Thanks for the fixes, I put it on auto-merge in the Buildings library.
