### ISSUE TITLE
Incorrect result for FMU when contains Stategraph waitTime component

### ISSUE THREAD

**Issue by bin-doge** [lbl-srg/modelica-buildings#3412]
Hi, when I simulate with Buildings.Examples.Tutorial.Boiler.System7, everything is fine when it is simulated with Dymola.

When I export this example as FMU and simulate with Pyfmi, the result is correct when the communication step is set to 30s, as shown below.

![step_30](https://github.com/lbl-srg/modelica-buildings/assets/90144264/f121233d-46e9-4250-be43-f37362cb31b0)

However, when the communication step increases to 300s, the result is totally wrong, as shown below.

![step_300](https://github.com/lbl-srg/modelica-buildings/assets/90144264/d61f1580-f630-4585-9ec8-c8cb2e9d1bd9)

In principle, the size of communication step will not affect the result of standalone FMU. 

I did some tests, and I found that this inconsistent was attributed to the waitTime of transition of Stategraph library. When I disable the waitTime, as shown below, the result is correct no matter how I increase the communication step.

![image](https://github.com/lbl-srg/modelica-buildings/assets/90144264/70b2157b-35ef-4bc5-89f9-1d195cd7db44)

Any insights for this problem? Does it mean we have to use a small communication step when the FMU contains waitTime component? And how we determine the communication step for building simulation, since most applications in Building library contain the Stategraph waitTime component?

**Comment by bin-doge** [comment]
The codes and FMU to reproduce the experiment are as follows.
[Boiler_waitTime_test.zip](https://github.com/lbl-srg/modelica-buildings/files/11583587/Boiler_waitTime_test.zip)

**Comment by mwetter** [comment]
It looks like (a) either the FMU does not report that there is a time event, or (b) that PyFMI does not properly handle that time event. I suggest you contact the developers of the tool that exports the FMU, or the PyFMI developers, as the model looks fine to me.
