### ISSUE TITLE
chiller power consumption calculation

### ISSUE THREAD

**Issue by chenjuncheng00** [lbl-srg/modelica-buildings#3425]
I'm not sure if this is a bug or a calculated feature that I don't understand.
Buildings.Fluid.Chillers.BaseClasses.PartialElectric, line144, buildings library version=9.1.0
// Compressor power.
P = - QEva_flow_ava / COP_nominal * EIRFunT * EIRFunPLR * CR;
EIRFunT: proportion of cooling COP as a function of chilled water outlet temperature and cooling water return temperature;
EIRFunPLR: proportion of cooling COP as a function of partial load factor;
I think that if the chiller's rated chilled water discharge temperature is 7 degrees Celsius and the setting at this point is 9 degrees Celsius, assuming that the COP at this point is 1.1 times the rated COP, then EIRFunT=1.1;
At this point the formula should be  P = - QEva_flow_ava / (COP_nominal * EIRFunT * EIRFunPLR) * CR;
Am I understanding you correctly?

**Comment by mwetter** [comment]
I don't see an error in the implementation. See for example the EnergyPlus Engineering Reference, or the source code of EnergyPlus at 
https://github.com/NREL/EnergyPlus/blob/d5cec9178bd6a7abc8399f1df2de7a7980dda697/src/EnergyPlus/ChillerElectricEIR.cc#L2235
which is the same equation as is used in
https://github.com/lbl-srg/modelica-buildings/blob/cf11ed882851670684cf615f4adb440edef8f73f/Buildings/Fluid/Chillers/BaseClasses/PartialElectric.mo#L187

**Comment by chenjuncheng00** [comment]
In Building Library, should the parameter EIRFunT be increased if the chilled water discharge temperature of the chiller increases? Or should it be reduced.

**Comment by hcasperfu** [comment]
@chenjuncheng00 -
Greetings! I know this doesn't directly answer your question. This formula is implemented in the library as-is from DOE-2.1 and EnergyPlus. These formulae can be found in [EnergyPlus Engineering Reference](https://energyplus.net/assets/nrel_custom/pdfs/pdfs_v22.1.0/EngineeringReference.pdf) section 14.3.9.2. And especially see equation 14.240.

<img width="689" alt="Screenshot 2023-06-15 at 16 18 51" src="https://github.com/lbl-srg/modelica-buildings/assets/91219266/560b1965-23e5-4398-aab5-957cf12e9d90">

I have opened a PR to add this reference to the chiller model documentation.
