### ISSUE TITLE
@GeorgeDawes : It looks like your Java Runtime Environment needs to be updated. Your system seems to use Java 8 and the jar file was compiled with Java 11. See also the explanation at https://www.baeldung.com/java-lang-unsupportedclassversion

### ISSUE THREAD

**Issue by rurubino1** [lbl-srg/modelica-buildings#3458]
@GeorgeDawes : It looks like your Java Runtime Environment needs to be updated. Your system seems to use Java 8 and the jar file was compiled with Java 11. See also the explanation at https://www.baeldung.com/java-lang-unsupportedclassversion

_Originally posted by @mwetter in https://github.com/lbl-srg/modelica-buildings/issues/3080#issuecomment-1207082271_

**Comment by rurubino1** [comment]
Hi, I would suggest recompiling "Buildings 9.1.0\Resources\bin\ConvertWeatherData.jar" with Java 8.
As the link provided in original issue #3080 suggests, this should be very easy.
https://www.baeldung.com/java-lang-unsupportedclassversion
> The above applies mainly to JDK 8 and lower. In JDK 9, the –release parameter was added to replace -source and -target. The –release option supports targets 6, 7, 8, 9, 10, and 11.
> 
> Let's use –release to target Java 8:
> 
> javac --release 8 com/baeldung/MajorMinorApp.java
> 
> Now we can run our code on a Java 8 or higher JRE.

Original issue #3080 solution (upgrade to Java 11) is not always practical, eg. company managed installation, Oracle changed license conditions, and latest suggested version with most permissive license is version 8, etc.
I suppose compiling for version 8 would be transparent for any user having Java >=8 and would make no difference for the code.

PS: also please consider converting the code from Java to python. It would seem much easier to use and maintain.

**Comment by mwetter** [comment]
Thanks for the hint with the compilation flag. This should be corrected with 
https://github.com/lbl-srg/modelica-buildings/pull/3460
