### ISSUE TITLE
Propagate m_flow_small in PartialFlowMachine

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/modelica-buildings#346]
Currently ```m_flow_small``` in ```Buildings.Fluid.Movers.BaseClasses.PartialFlowMachine``` is set to ```1E-4*abs(m_flow_nominal)```. I would expect that this parameter should be propagated to make it accessible for when using ``àllowFlowReversal = false```. I'll make a pull request for this change.

**Comment by mwetter** [comment]
Closed as this is now on the master branch.
