### ISSUE TITLE
VAVTemplate references an invalid parameter

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#3476]
@AntoineGautier : I think this reference to a non-existent parameter is not valid Modelica syntax. Can you please have a look into it. This is from the current master.

<img width="582" alt="image" src="https://github.com/lbl-srg/modelica-buildings/assets/1329080/81013782-eef7-4733-8f34-f7ccd98c7157">

**Comment by AntoineGautier** [comment]
This is weird: I don't have that on my system.
<img width="1563" alt="Capture d’écran 2023-08-21 à 10 38 18" src="https://github.com/lbl-srg/modelica-buildings/assets/10965994/59a07a8e-2c9b-4889-b99d-81a82b245b54">
I am with Dymola 2023x Refresh 1 on commit b153ffc957 where the bindings for `coiHeaPre` in`Buildings.Templates.AirHandlersFans.VAVMultiZone` are:
```
  inner replaceable Buildings.Templates.Components.Coils.WaterBasedHeating coiHeaPre(
    redeclare final package MediumHeaWat=MediumHeaWat,
    redeclare final Buildings.Templates.Components.Valves.TwoWayModulating val)
    constrainedby Buildings.Templates.Components.Interfaces.PartialCoil(
      final dat=dat.coiHeaPre,
      redeclare final package MediumAir=MediumAir,
      final energyDynamics=energyDynamics,
      final allowFlowReversalAir=allowFlowReversalAir,
      final allowFlowReversalLiq=allowFlowReversalLiq,
      final show_T=show_T)
```
I can't find the code snippet that generates this parameter dialog.
Can you double check on your end?

**Comment by mwetter** [comment]
@AntoineGautier : I reproduced it with commit b153ffc and Dymola 2023x, 2022-10-07, with these steps

1. Click on the model `VAVMultiZone`.
2. Click on the instance `coiHeaPre` and select "Parameters"
3. In the parameter window, click on the icon of `dat`.

**Comment by mwetter** [comment]
Submitted to Dassault,  SR01074419-01
