### ISSUE TITLE
Validate zone capacitance multiplier for Spawn

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#3481]
This issue is to correct a bug that causes EnergyPlus to always send a heat capacitance multiplier of 1 to Modelica.

On the master, commit, e2bc12fa48370c60033346abe476c7423b4940e9, adding the following snippet to 
`Resources/Data/ThermalZones/EnergyPlus_9_6_0/Examples/SingleFamilyHouse_TwoSpeed_ZoneAirBalance/SingleFamilyHouse_TwoSpeed_ZoneAirBalance.idf`
does not change the result of `Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.Unconditioned`:

```
ZoneCapacitanceMultiplier:ResearchSpecial,
    Living zone heat capacitance multiplier,  !- Name
    LIVING ZONE,                              !- Zone or ZoneList Name
    10,                                       !- Temperature Capacity Multiplier
     ,                                        !- Humidity Capacity Multiplier
     ,                                        !- Carbon Dioxide Capacity Multiplier
     ;                                        !- Generic Contaminant Capacity Multiplier
```
For this, a unit test should be added, and tested after https://github.com/lbl-srg/modelica-buildings/issues/3209 is addressed.

**Comment by hcasperfu** [comment]
@mwetter -

I have preliminary results testing this at f50d8117c9c56e28fe3ee80ddb5ae8b793005f57 that look like this problem is fixed with the new version (see screenshot below). Should I make a PR now or should I wait until `issue3209` is merged to master?

<img width="569" alt="Screenshot 2023-08-25 at 14 23 42" src="https://github.com/lbl-srg/modelica-buildings/assets/91219266/7ff65234-3d18-4aec-a0c3-5018a46c0a4f">

**Comment by mwetter** [comment]
@hcasperfu : I think best would be if you make a PR with the new examples, script and reference results, but not the binary files. Then, next week I can wrap up https://github.com/lbl-srg/modelica-buildings/issues/3209, merge it to the master and merge it to your PR, which then adds the latest binaries files for Spawn for Linux and Windows (the latter should be available next week).

**Comment by hcasperfu** [comment]
@mwetter -
Sounds good.
Then without the new binary files, do I use the results generated with the old version (no difference with the two outputs)?

**Comment by mwetter** [comment]
Either is fine, but if you use the new binaries for the Spawn binaries in `Resources/bin/Spawn-light-0.4.3....`, just don't commit them. 
The ones in `Resources/Library/linux64` are already updated on #3209 for Linux (but not Windows which I do next week)
