### ISSUE TITLE
An Update to the Contributor's List

### ISSUE THREAD

**Issue by khinkelman** [lbl-srg/modelica-buildings#3509]
Hi @mwetter, with the release of v10.0.0, new models by @SaranyaAnbarasu were added to the MBL. This includes the first implementation of `Buildings.Experimental.DHC.Loads.Steam.BaseClasses.ValveSelfActing`, as well as some other steam-related  improvements to other models. 

Is it possible to add her as a contributor to `Buildings/package.mo`? 
```
<li>Saranya Anbarasu, Pennsylvania State University, USA
</li>
```

**Comment by mwetter** [comment]
@khinkelman : Sure, I must have forgotten to add @SaranyaAnbarasu to the contributor list. I will make a PR to add here for future releases.

**Comment by khinkelman** [comment]
Many thanks @mwetter!
