### ISSUE TITLE
Compatibility of G36 VAV multiple-zone controller with ctrl-flow options

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#3526]
**Valve feedback position**

The controller `Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.Controller` uses the signals `uCooCoi_actual` and `uHeaCoi_actual` as inputs. (`uHeaCoi_actual` is only instantiated if `have_hotWatCoi` is `true`.)
This is not consistent with ASHRAE Guideline 36 (2021) which does not specify these signals as input points in Section 4.6.
The guideline rather specifies in Section 5.1.18 that, for modulating (analog) actuators,

> position may be assumed to be equal to ***analog signal to*** actuator.

The current implementation is therefore not compatible with the following equipment options from https://github.com/lbl-srg/ctrl-flow-dev/blob/main/server/scripts/sequence-doc/src/version/Current%20G36%20Decisions/Guideline%2036-2021%20(mappings).csv

- No cooling coil
- DX coil

The input signals `uCooCoi_actual` and `uHeaCoi_actual` should be removed from `Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.Controller` which should rather use the computed ***AO*** signal instead (with a `pre` operator if needed to avoid algebraic loops).

**Electric heating coil**

Within `Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.Controller`, the output connector `yHeaCoi` is instantiated with the condition `if have_hotWatCoi`, which makes the controller incompatible with the electric coil option from https://github.com/lbl-srg/ctrl-flow-dev/blob/main/server/scripts/sequence-doc/src/version/Current%20G36%20Decisions/Guideline%2036-2021%20(mappings).csv

**Two-position relief damper**

The controller `Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.Controller` only computes an AO signal to actuate the relief damper.
This is not compatible with configurations with a relief fan that require a two-position relief damper, i.e., a ***DO*** signal to be generated by the controller. See ASHRAE Guideline 36 (2021) Section 4.6.  

**Singular system when freezestat is hardwired to equipment**

The controller `Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.Controller` contains the following connect clause.
```
connect(frePro.yHotWatPlaReq, intSwi.u1)
```
Where `frePro` is an instance of `Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.SetPoints.FreezeProtection` which contains the following conditional declaration.
```
  Buildings.Controls.OBC.CDL.Interfaces.IntegerOutput yHotWatPlaReq
    if have_hotWatCoi and (not freSta == Buildings.Controls.OBC.ASHRAE.G36.Types.FreezeStat.Hardwired_to_equipment)
```
So, if `freSta == Buildings.Controls.OBC.ASHRAE.G36.Types.FreezeStat.Hardwired_to_equipment` the output signal `yHotWatPlaReq` is removed and the variable `intSwi.u1` lacks a connection with a non-input variable.

**Singular system when freezestat is hardwired to BAS**

Similarly, `Buildings.Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.Validation.Controller` yields a singular system error with the the following class modification.
```
conAHU(freSta=Buildings.Controls.OBC.ASHRAE.G36.Types.FreezeStat.Hardwired_to_BAS)
```

**Translation failing with `have_frePro=false`**

The translation of `Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.Validation.Controller` fails with OCT with the following class modification.
```
conAHU(have_frePro=false)
```
This can be reproduced with Dymola on closed-loop models only, e.g., when translating `Templates.AirHandlersFans.Validation.VAVMultiZone` with the following class modification.
```
VAV_1(ctl(have_frePro=false))
```

**Singular system when economizer high limit control uses differential dry bulb**

`Buildings.Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.Validation.Controller` yields a singular system error with the the following class modification (even after connecting `conAHU.TRet` with a non-input variable).
```
conAHU(ecoHigLimCon=Buildings.Controls.OBC.ASHRAE.G36.Types.ControlEconomizer.FixedDryBulbWithDifferentialDryBulb)
```
This is because, within `Buildings.Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.Economizers.Controller` we have:
```
  Buildings.Controls.OBC.CDL.Interfaces.RealInput TAirRet(...)
    if ecoHigLimCon == Buildings.Controls.OBC.ASHRAE.G36.Types.ControlEconomizer.DifferentialDryBulb
```
whereas within `Buildings.Controls.OBC.ASHRAE.G36.Generic.AirEconomizerHighLimits` we have:
```
  Buildings.Controls.OBC.CDL.Interfaces.RealInput TRet(...)
    if (ecoHigLimCon == Buildings.Controls.OBC.ASHRAE.G36.Types.ControlEconomizer.DifferentialDryBulb
     or ecoHigLimCon == Buildings.Controls.OBC.ASHRAE.G36.Types.ControlEconomizer.FixedDryBulbWithDifferentialDryBulb)
```

**Comment by AntoineGautier** [comment]
@JayHuLBL Can you look into that?

**Comment by JayHuLBL** [comment]
@AntoineGautier Thanks for the feedback. I will address them.
