### ISSUE TITLE
Unpropagated parameters in Buildings.Fluid.SolarCollectors.BaseClasses.PartialSolarCollector

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/modelica-buildings#357]
```Buildings.Fluid.SolarCollectors.BaseClasses.PartialSolarCollector``` is missing some propagations for parameters in ```LumpedVolumeDeclariations```. I'll make a pull request.

**Comment by mwetter** [comment]
Closed as this is now on the master. Thanks for the pull request.
