### ISSUE TITLE
FMU model with fmpy

### ISSUE THREAD

**Issue by burritotukituki** [lbl-srg/modelica-buildings#3574]
Hi,
I am learning and testing the examples of the Building package (big thanks to the developers for such amazing package).
I am importing the examples models as FMU and trying to simulate them with fmpy to latter on perform co-simulations. 

When I export 
Buildings.Examples.Tutorial.Boiler.System2
and run it with fmpy I get an error:

`fmu = 'fmu_test.fmu'
result = simulate_fmu(fmu)`

`The following assertion has been violated at time 400.000000
|                 | |       | ((noEvent(pumRad.vol.dynBal.medium.T <= 403.15))) --> "In fmu_test.pumRad.vol.dynBal.medium: Temperature T = 311048 K exceeded its maximum allowed value of 130 degC (403.15 Kelvin) as required from medium model "Buildings.Media.Water"."`

Can someone help me? 
Thanks

**Comment by mwetter** [comment]
That looks like fmpy makes too big a time step, then the water temperature raises over this large time step above 130 degC which the model properly reports, but fmpy does not attempt a smaller time step after this assertion. Please check with fmpy how to control the step size and/or react if the model triggers an assertion.
