### ISSUE TITLE
Move CDL blocks to obsolete

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#3595]
As suggested by ASHRAE 231p, this issue is to move following CDL elementary blocks to Obsolete:
- `CDL.Logical.Or3`
- `CDL.Logical.OnOffController`
- `CDL.Logical.ZeroCrossing`
- `CDL.Logical.TriggeredTrapezoid`

**Comment by mwetter** [comment]
@JayHuLBL : `CDL.Logical.TriggeredTrapezoid` still exists, in addition to the now obsolete version. The block `CDL.Logical.TriggeredTrapezoid` must be deleted.
