### ISSUE TITLE
Replaceable performance records in movers

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/modelica-buildings#360]
Performance records ```per``` in movers are currently not replaceable. This results in warnings when using for instance an ```Nrpm``` record for a ```y``` mover since ```N_nominal``` is not defined in ```y.per```. I therefore propose to make these records replaceable, which solves the problem for me.

**Comment by mwetter** [comment]
I am testing your changes on `issue360_replaceablePer`.

I believe the table in the user guide should be like that:
![image](https://cloud.githubusercontent.com/assets/1329080/6198055/b3a2e524-b3a6-11e4-9ece-0aa1e91ca44d.png)

Do you agree?

**Comment by Mathadon** [comment]
@mwetter I agree

**Comment by mwetter** [comment]
This is now on the master
