### ISSUE TITLE
Numerical issue with trace substances and mixing volumes

### ISSUE THREAD

**Issue by ohly87** [lbl-srg/modelica-buildings#3633]
Scaling the absolute value of trace component source terms by a constant factor leads to different integrator timesteps and overall simulation times with the mixing volume model. This can not be remedied by adjusting the nominal trace substance concentration in the mixing volume model. The problem occurs with the TraceSubstancesFlowSource but also with the use_C_flow attribute of the mixing volume.

1. Open model Airflow->Multizone->Examples->CO2TransportStep
2. Run Simulation with default value for pulse amplitude (8.18E-6): 1089 f-evaluations
3. Run Simulation with pulse amplitude of 8.18E-2: 4358 f-evaluations

**Expected behavior**
I expect that scaling the input by a constant factor should not have a significant impact on the simulation time as the resulting concentrations are scaled by the same factor. The input should be normalized by a nominal value. 

**Version**
 - Modelica Buildings Library 9.1.0
 - Modelica 4.0.0
 - Windows 11

**Comment by mwetter** [comment]
How this affects the solver really depends on how the solver is implemented. You could try to set the `C_nominal` parameter in the control volumes to tell the model the scale of `C`.
