### ISSUE TITLE
Support of fault triggering / simulation

### ISSUE THREAD

**Issue by TeoGoddet** [lbl-srg/modelica-buildings#3638]
Hello, 
It would be nice to be able to simulate fault on the various components.
I'm wondering if you would accept work in this direction ? 
For instance, this library could be implemented : https://github.com/DLR-SR/FaultTriggering/tree/master

**Comment by mwetter** [comment]
Thanks for sharing this interesting approach. Unfortunately we currently don't have worked lined up in this area, and it seems like it would be a significant redesign of the Buildings and IBPSA libraries to add faults. Also, the implementation of the functions appears to be Dymola specific.
