### ISSUE TITLE
Cannot connect weather bus to Buildings.Fluid.Sources.Outside weather bus port

### ISSUE THREAD

**Issue by AvisekNaug** [lbl-srg/modelica-buildings#3644]
I am trying to replicate the room heating example (page 29) shown in [this](https://simulationresearch.lbl.gov/modelica/downloads/workshops/2021-03-29-mit/IntroductionToModelicaModelingForBuildingSystems.pdf) tutorial by David Blum. In the process, when I try to connect the Buildings.BoundaryConditions.WeatherData.Bus with the Buildings.Fluid.Sources.Outside weather bus port, it does not connect. I also tried connecting Buildings.BoundaryConditions.WeatherData.ReaderTMY3 to the Buildings.Fluid.Sources.Outside weather bus port, but it does not connect either. There is not much instruction in the pdf on whether to do something specific to make the connection possible.

**Comment by AvisekNaug** [comment]
Specifically, I am talking about facing this issue in the screen record shown
![Capture](https://github.com/lbl-srg/modelica-buildings/assets/21328222/4508662e-0e5d-4a77-8d50-49d2a3e644b1)

Clicking ok does not make the connection

**Comment by ohly87** [comment]
I had the same issue in OpenModelica. Try connecting on the Modelica-text layer.

**Comment by AvisekNaug** [comment]
I just did that yesterday! But then the model view shows no connection. Is that something normal? Also, I am now getting a new translation error in the room component about binding C=fill... 

I am at a loss why there is so much issues when running a simple example from this tutorial.

**Comment by mwetter** [comment]
@AvisekNaug : That seems to be a limitation in OpenModelica's OMEdit. I suggest you submit a bug report and small test case at https://github.com/OpenModelica/OpenModelica/issues

**Comment by AvisekNaug** [comment]
Thank you.
