### ISSUE TITLE
Integrating motors in valves

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/modelica-buildings#365]
In some cases valve motors have a equal percentage opening characteristic as well. It would be nice if they could be integrated in the valve models. Ideally they would be replaceable since I can imagine that many types exist. Is this something we'd want to have a look at?

**Comment by mwetter** [comment]
Wouldn't it be sufficient to simply use an equal percentage valve in this case? I am afraid that this may lead to a complexity that would overwhelm the typical user?

**Comment by Mathadon** [comment]
I have a case where a linear-linear valve is controlled using an equal percentage characteristic motor. This cannot be represented by an equalpercentage-linear valve since I would an equalpercentage-equalpercentage valve. Also, the motors often have more settings. For instance some motors close the valve at 20% of the input signal instead of at 0%.

I agree that we should avoid making the valves too complicated. A possible solution would be to add a replaceable motor model in the valve with a trivial motor implementation y=u. The replaceable could then be ‘hidden’ in one of the advanced tabs so users don’t need to worry about it. However, advanced users are then able to redeclare the motor.

**Comment by Mathadon** [comment]
The pump equivalent of this option would be to integrate a frequency convertor into the pump models. The design could happen in a similar way.

**Comment by mwetter** [comment]
Wouldn't it be sufficient to simply put the motor into `Buildings.Fluid.Actuators.Motors`? This can then be used as in http://simulationresearch.lbl.gov/modelica/releases/latest/help/Buildings_Fluid_HeatExchangers_Examples.html#Buildings.Fluid.HeatExchangers.Examples.DryCoilDiscretizedPControl
The intention of the `Motor` package was to add motors for valves and dampers, although I have not had an application yet where this was needed.

**Comment by Mathadon** [comment]
Yes that would work as well. I'll do it that way if you think it would complicate things too much!
