### ISSUE TITLE
Translation Error in using Room Model for tutorial

### ISSUE THREAD

**Issue by AvisekNaug** [lbl-srg/modelica-buildings#3651]
I am trying to replicate the room heating example (page 29) shown in [this](https://simulationresearch.lbl.gov/modelica/downloads/workshops/2021-03-29-mit/IntroductionToModelicaModelingForBuildingSystems.pdf) tutorial by David Blum. However, when I try to validate/simulate the model in Open Modelica Connection Editor I get the following error:

[1] 15:46:17 Translation Notification
[Buildings.Air.Systems.SingleZone.VAV.Examples.BaseClasses.Room: 198:5-198:22]: [From here:](Buildings.Air.Systems.SingleZone.VAV.Examples.BaseClasses.Room?lineNumber=198)

[2] 15:46:17 Translation Error
[Buildings.Fluid.Sources.MassFlowSource_WeatherData: 15:3-18:67]: [Type mismatch in binding 'C = fill(0.0004, 1)', expected array dimensions [0], got [1].](Buildings.Fluid.Sources.MassFlowSource_WeatherData?lineNumber=15)

I created the following [System.mo](https://drive.google.com/file/d/1kHrWwEU9KeijeR9wmfUCe40H_xhlT3Vo/view?usp=sharing) model file.  

I am using Buildings 10.0.0 and OMEdit 
Connected to OpenModelica v1.22.0 (64-bit)
Connected to OMSimulator v2.1.1.post236-g634b019-mingw-notlm-debug

**Comment by ohly87** [comment]
BaseClasses are usually not meant to be simulated. if you look at the graphical interface, you will see that there are two fluidports in the model for supply and return air. these need to be connected to another model. there are several examples in the same folder that should work fine.

**Comment by AvisekNaug** [comment]
The fluid ports are connected to the two port temperature sensor and the outside blocks in the System.mo file I shared above.

![image](https://github.com/lbl-srg/modelica-buildings/assets/21328222/a3b36dec-fdbf-4fb4-88e5-c4382795e950)

The error happens with the given configuration in OpenModelica simulation.

**Comment by AvisekNaug** [comment]
Where do you see this declaration Buildings.Media.Air(extraPropertiesNames={"CO2"}) in the PartialOpenLoop example? I opened the mode in both Openmodelica editor and Dymola nad they just show redeclare package MediumA= MediumA

**Comment by ohly87** [comment]
![grafik](https://github.com/lbl-srg/modelica-buildings/assets/156214582/d2aefc2a-94fa-446d-a16c-44bbf456c799)

**Comment by ohly87** [comment]
The graphical interface is just a representation in support of the text layer. parameters of the main model can not be accessed from the graphical layer, so you need to access the text layer. 

the error tells you that a 0-dimension array is set equal to an array with 1 entry. this is because a medium is expected that has exactly 1 trace substance. meanwhile the air model itself has no trace substances. extraPropertiesNames adds a trace substance to the medium. My guess is that this functionality was changed somewhere between 2021 and now.
