### ISSUE TITLE
Connecting two PlugFlowPimpes to ohne Heat Port

### ISSUE THREAD

**Issue by RenaCon** [lbl-srg/modelica-buildings#3652]
Hi there :) 

my goal is to simplify my heating model. I want to put two plugflowpipes in one Model, one being for the hot water, and one for the return water. I noticed, that the results change, depending on how I connect my heatingport to a fixed ground temperature. 

The only thing i changed in my versions of the same Model is putting two pipes in one model and how they connect to the GroundTemp. 

Only the two single ports result in the same Q_flow and that only after about 10h. Is there a delay? Could there be another cause? I can't figure out, why they differ in the first place... Unfortunately it results in delays and different outputs in the rest of my model as well.

Thanks for the help!

Referenze:
![Referenze](https://github.com/lbl-srg/modelica-buildings/assets/158063239/88574f3a-f4f5-4b0c-bb2f-6c81b2762fd1)
One Port:
![One_Port](https://github.com/lbl-srg/modelica-buildings/assets/158063239/3d9a0b96-9888-416b-8fd0-8b345777febe)
Multiports:
![Multiport](https://github.com/lbl-srg/modelica-buildings/assets/158063239/96abf748-5a97-47f9-96d8-6dff3896cce3)
Two Ports:
![two_Ports](https://github.com/lbl-srg/modelica-buildings/assets/158063239/a78e4982-b79f-46e9-a2ef-1ea3045dac49)
Q_flow Plot
![Q_flow_Heat_Ports](https://github.com/lbl-srg/modelica-buildings/assets/158063239/53576512-4fa0-4dd7-8391-2118aa994d40)

**Comment by mwetter** [comment]
@RenaCon: I tried to reproduce it by editing `Buildings.Fluid.FixedResistances.Examples.PlugFlowPipe`, making a copy, changing `bou1` to be a scalar and adding the `Modelica.Fluid.Interfaces.HeatPorts_a` to create the model below:
![image](https://github.com/lbl-srg/modelica-buildings/assets/1329080/2f82c1ba-3cfe-49c8-81da-aa85ab5222ae)

However, `pip` and `pip1` have the same heat flow rates and also `senTemOut` and `senTemOut1` have the same temperature. If the problem persists, please reopen and send a minimalistic example model that reproduces the issue.
