### ISSUE TITLE
Incorrect assert statement in Fluid.HeatPumps.EquationFitReversible

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#3664]
**Describe the bug**

Inside the model `Fluid.HeatPumps.EquationFitReversible` the `Assert` block checks that the condition `uMod<0` is met for non-reversible heat pumps. 
The condition shall rather be `uMod>=0`, indicating off=0 or heating mode=+1 command.

**Comment by mwetter** [comment]
Thanks for catching this. This is indeed a bug that is not caught by the configuration of the unit tests.
This will need to be updated on 
[ ] `maint_9.1.x`
[ ] `maint_10.0.x`
[ ] `master`
