### ISSUE TITLE
During initial phase, the Temperature value of the system goes negative drastically

### ISSUE THREAD

**Issue by deepak19015** [lbl-srg/modelica-buildings#3681]
**Describe the bug**
After simulating the Buildings library model named `Buildings.Applications.DataCenters.ChillerCooled.Examples.IntegratedPrimaryLoadSideEconomizer`, in the plot of the protected variable `ahu.eleHea.hea.outCon.T`, we can see the initial value of the temperature at t=0+ sec, goes negative drastically and later comes back to positive value (Refer the screenshot for the plot).

**To Reproduce**
1. Load Buildings Library
2. Open the model file `Buildings.Applications.DataCenters.ChillerCooled.Examples.IntegratedPrimaryLoadSideEconomizer` 
3. In `Simulation Setup` options, go to `output` and tick the `Protected variables if not encrypted` option before simulating
4. Simulate the model
5. Plot variable, `ahu.eleHea.hea.outCon.T`

**Expected behavior**
The variable `ahu.eleHea.hea.outCon.T` value should not go negative at the initial time t=0+ sec. This initialization problem should be solved.

**Screenshots**
![Screenshot from 2024-03-05 16-55-57](https://github.com/lbl-srg/modelica-buildings/assets/139556265/db9a4be7-83f1-4050-8ef2-9af2c03693ff)

**Version**
   OpenModelica Version: OpenModelica 1.23.0~dev-358-g07765ef
        OS: Ubuntu 22.04.4 LTS
        Versions of used Modelica libraries:
        Modelica 4.0.0
        Buildings 11.0.0

**Comment by mwetter** [comment]
Thanks for reporting. I can reproduce it:

![image](https://github.com/lbl-srg/modelica-buildings/assets/1329080/5af811b0-4306-4d84-8ce6-d36c2f369db2)

The fault seems to be caused in `Buildings.Applications.DataCenters.ChillerCooled.Equipment.ElectricHeat` which sets `TSet` to -273.15 Kelvin (=-546.3 degC) which does not make sense:

![image](https://github.com/lbl-srg/modelica-buildings/assets/1329080/a3292c44-06ed-472a-8ce3-ee5e39de0327)

The likely work-around is to refactor `ElectricHeat` to use a P or PI controller, and a heater that takes `u` or `Q_flow` as input; or to replace `zer` with a measurement of the `hea` outlet temperature (and configure the heater with a dynamic balance to avoid an algebraic loop).

**Comment by mwetter** [comment]
Inspecting the inlet and outlet temperatures show that the model properly represents the physics.

![image](https://github.com/lbl-srg/modelica-buildings/assets/1329080/4db1d2b3-7dce-4aff-a9c8-fde299bf3aab)

When it obtains the set point of -546.3 degC, it correctly sets the heat added to the medium to 0. However, I think a more reasonable set point would avoid the confusion, which I can address in a revision of the model.
