### ISSUE TITLE
Remove CDL.Logical.OnOffController

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#3688]
The block `CDL.Logical.OnOffController` is rarely used, it is not in the ASHRAE Std 231P Public Review Draft 1, and can be removed. This is to move it to the `Obsolete` package and remove its use outside the `Obsolete` package.

**Comment by JayHuLBL** [comment]
@mwetter The `OnOffController` is already in the `Obsolete` package (`Buildings.Obsolete.Controls.OBC.CDL.Logical.OnOffController`) and it is not being used outside of the `Obsolete` package.

**Comment by mwetter** [comment]
@JayHuLBL : I see, it has been removed from the non-obsolete package. But you still need to update the documentation as the tutorial refers to it. Search for `Buildings.Controls.OBC.CDL.Logical.OnOffController` to see where it is used in the documentation, and this needs to be updated.
