### ISSUE TITLE
CDL review

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/modelica-buildings#3695]
@mwetter as promised some feedback on the `Buildings.Controls.OBC.CDL` package:

- `CDL.Constants.small`: the smalles ieee single precision float is about 1e-37 so `small=1E-60` may not be representable on machines with single precisions float implementations. I'm not sure whether this could pose a problem in practice for your use cases though.
- `Buildings.Controls.OBC.CDL.Types.ZeroTime` could be extended beyond the year 2020.
- I was wondering whether the CDL package was supposed to be self-contained? Since e.g. `Buildings.Controls.OBC.CDL.Discrete.UnitDelay` references `Buildings.Utilities.Math.Functions.round`.
- Other than that, most blocks are pretty basic, documentation and diagrams look good, so I don't have big comments.

Kind regards!

**Comment by mwetter** [comment]
@Mathadon : Thanks for the feedback.

I changed `small` to 1E-37 in f0b311ca2e

ZeroTime will be extended using Jelger's implementation (https://github.com/lbl-srg/modelica-buildings/pull/3701)

The implementation of the CDL blocks can reference other parts of the library (the parameters, inputs and outputs are standardized, and their behavior, but not the implementation). I will leave this reference to `round` to avoid having to copy the function as a `protected` function.
