### ISSUE TITLE
DHC.Loads.Combined.Examples.BuildingTimeSeriesWithETS do not comply with Modelica Language Definition

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#3697]
The model `Buildings.Experimental.DHC.Loads.Combined.Examples.BuildingTimeSeriesWithETS` fails to compile with the latest nightly build of OpenModelica as it violates the Modelica standard. The cause is that `datDes.mCon_flow_nominal` has no binding, and there should also be an inner declaration for `datDes`.
The message is
```
[2] 11:10:43 Translation Warning
[Buildings.Experimental.DHC.Loads.Combined.BaseClasses.PartialBuildingWithETS: 8:3-9:75]: [An inner declaration for outer component datDes could not be found and was automatically generated.](omeditmessagesbrowser:///Buildings.Experimental.DHC.Loads.Combined.BaseClasses.PartialBuildingWithETS?lineNumber=8)

[3] 11:10:43 Translation Error
[Buildings.Experimental.DHC.Examples.Combined.BaseClasses.DesignDataSeries: 11:3-12:53]: [Parameter datDes.mCon_flow_nominal has neither value nor start value, and is fixed during initialization (fixed=true).](omeditmessagesbrowser:///Buildings.Experimental.DHC.Examples.Combined.BaseClasses.DesignDataSeries?lineNumber=11)
```

The same applies to `Buildings.Experimental.DHC.Loads.Combined.Examples.BuildingTimeSeriesWithETSDHWTank`.

This should be corrected on the master and on `maint_10.0.x`.

(If the library release notes are updated on 10.0.x, they don't need to be updated for 11.)

**Comment by casella** [comment]
@mwetter this issue was fixed on the [10.0.x maintenance branch](https://libraries.openmodelica.org/branches/master/Buildings_10/files/Buildings_10_Buildings.Experimental.DHC.Loads.Combined.Examples.BuildingTimeSeriesWithETS.err) but it seems to me it wasn't on the [master branch](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Experimental.DHC.Loads.Combined.Examples.BuildingTimeSeriesWithETS.err).

Can you please check?

**Comment by dhblum** [comment]
@mwetter I think this PR which addresses this issue https://github.com/lbl-srg/modelica-buildings/pull/3708 was closed but not merged?

**Comment by mwetter** [comment]
@casella @dhblum : I double-checked and the files were merged through a batch PR to reduce the long backlog on PRs that are in the CI queue. The original (closed) PR has 0 file changes: https://github.com/lbl-srg/modelica-buildings/pull/3708:
![image](https://github.com/lbl-srg/modelica-buildings/assets/1329080/1656a4cb-4b60-42ff-95d1-aefc9f85a924)

**Comment by casella** [comment]
I confirm [Buildings.Experimental.DHC.Loads.Combined.Examples.BuildingTimeSeriesWithETS](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Experimental.DHC.Loads.Combined.Examples.BuildingTimeSeriesWithETS.err) now compiles again. It fails during simulation, but that's another issue.
