### ISSUE TITLE
Please remove time from reference file

### ISSUE THREAD

**Issue by casella** [lbl-srg/modelica-buildings#3718]
Model `Buildings.Examples.ScalableBenchmarks.BuildingVAV.Examples.OneFloor_OneZone` [fails verification](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Examples.ScalableBenchmarks.BuildingVAV.Examples.OneFloor_OneZone.diff.html) on signal "time" when tested with OpenModelica. All other signals are OK.

I really can't see the point of also including "time" in the reference signals, since different algorithms could take different time steps and that is perfectly legitimate.

Unless there are good reasons against this, I would suggest you to remove "time" from the reference signals of this model, for all supported versions (i.e. from Buildings 9.1.x onwards)

Thanks!

Francesco

**Comment by mwetter** [comment]
@casella : I don't understand what you mean or why OpenModelica verifies `time`, as `time` is not a signal for verification. The signals are here:
https://github.com/lbl-srg/modelica-buildings/blob/44d6494b3385fca27ef49c72f24548df64c75d31/Buildings/Resources/ReferenceResults/Dymola/Buildings_Examples_ScalableBenchmarks_BuildingVAV_Examples_OneFloor_OneZone.txt#L16
and below.
There is an entry for `time` but these are just the start and stop times, and all reference results have such an entry.

Also https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Examples.ScalableBenchmarks.BuildingVAV.Examples.OneFloor_OneZone.mos has no such entry.

Can you please explain what makes OpenModelica think that it should verify time.

**Comment by casella** [comment]
I'm sorry, that was a totally silly comment on my side - sleep deprivation, probably... 😅 

We need to check the script that imports your reference results, because there is probably something wrong with it. This may also explain the fairly large number of verification failures we still get.

BTW, now that I see the actual reference file, I guess the fact that only the start and stop time are reported means that the other variables must be sampled at regular intervals in-between those two values, with no exceptions for events that may take place at other points in time. Can you please confirm that? Thanks!

**Comment by mwetter** [comment]
@casella : Yes I confirm. We simply sample on an equidistant grid.
