### ISSUE TITLE
Should we bother about getting Obsolete models to simulate and pass verification in OpenModelica?

### ISSUE THREAD

**Issue by casella** [lbl-srg/modelica-buildings#3744]
If you check the [latest CI report](https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html) of OpenModelica with the development version of Buildings, there are 8 models failing to simulate and about a dozen having issues with verification or missing reference files.

The question is: should we bother about them at all, or shall we exclude them from the testing process?

**Comment by mwetter** [comment]
@casella : You can exclude `Obsolete` from the tests.
