### ISSUE TITLE
Buildings.Controls.DemandResponse.Client model contains may generate infinite event iterations

### ISSUE THREAD

**Issue by AndreaBartolini** [lbl-srg/modelica-buildings#3754]
**Describe the bug**
The model `Buildings.Controls.DemandResponse.Client` contains a shorted loop that may generate infinite event iterations depending on the implementation of the event iteration made by the Modelica compiler.
The details are discussed in the https://github.com/OpenModelica/OpenModelica/issues/10992.

**To Reproduce in OpenModelica**
1. Open and simulate the model `Buildings.Controls.DemandResponse.Examples.ClientLBNL90`

The simulation fails and the following message is shown:
`Simulation terminated due to too many, i.e. 20, event iterations. This could either indicate an inconsistent system or an undersized limit of event iterations. The limit of event iterations can be specified using the runtime flag '–mei=<value>'.`

The model simulates in Dymola because the implementation of the Event Iteration in Dymola is slightly different from that of OpenModelica.

A possible solution to break the shorted loop is to add a little delay (e.g. `tsample/1000`) in the transition `t1` of the `Buildings.Controls.DemandResponse.Client` model .

**Version**
 - Modelica Buildings Library:
Version: 11.0.0 - SHA cf73e6f1e127f27aca3aff658b6a18d59a550059

 - Modelica simulation environment:
 OpenModelica v1.23.0-dev-396-g9ae201ce92 (64-bit)

 - Operating system
win11 pro - 64 bit

Keep @casella in the loop...

**Comment by mwetter** [comment]
@AndreaBartolini : Thanks for reporting. This will be corrected through the above 3 pull requests.

**Comment by casella** [comment]
Confirmed fixed on [master](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Controls.DemandResponse.Examples.ClientLBNL90.sim), [10.0.x](https://libraries.openmodelica.org/branches/master/Buildings_10/files/Buildings_10_Buildings.Controls.DemandResponse.Examples.ClientLBNL90.sim), and [9.1.x](https://libraries.openmodelica.org/branches/master/Buildings_9/files/Buildings_9_Buildings.Controls.DemandResponse.Examples.ClientLBNL90.sim)
