### ISSUE TITLE
error: Modelica Spawn coupling is only supported for Windows and Linux 64 bit. Your operating system is not 64 bit

### ISSUE THREAD

**Issue by dearlu88** [lbl-srg/modelica-buildings#3760]
![微信截图_20240401162949](https://github.com/lbl-srg/modelica-buildings/assets/165647595/24560b6e-0c23-4073-8bd9-0a9db3afbbe0)

**Comment by mwetter** [comment]
Please see the dymola notes in https://simulationresearch.lbl.gov/modelica/releases/v10.0.0/help/Buildings_ThermalZones_EnergyPlus_9_6_0_UsersGuide.html#Buildings.ThermalZones.EnergyPlus_9_6_0.UsersGuide

**Comment by YangLu8787** [comment]
I followed the prompts to set up the environment, but still reported an error
![image](https://github.com/lbl-srg/modelica-buildings/assets/131147479/51234693-a378-4902-b4e9-5d58c78a772c)
![image](https://github.com/lbl-srg/modelica-buildings/assets/131147479/52942c49-0226-4481-9456-4b5a965fd171)

**Comment by YangLu8787** [comment]
Dymola2013 and Visual Studio 2019

**Comment by YangLu8787** [comment]
Dymola2013 and Visual Studio 2019

**Comment by hoxj180** [comment]
Hi Dr. Wetter, I am also having this issue and found the documentation in the Spawn User Guide. Where do I set the `Advanced.CompileWith64 = 2` flag? Is this accessible somewhere in the Dymola GUI? Thanks for the help.

**Comment by hcasperfu** [comment]
@hoxj180 - 

You can do so in the "Simulation" tab, look down, and find the "Commands" tab next to "Logs", and type in the command.
The screenshot is from Dymola 2024x Refresh 1 on Ubuntu.

<img width="318" alt="image" src="https://github.com/lbl-srg/modelica-buildings/assets/91219266/f1111c31-6749-4e6f-a897-6c1ebd67d688">

**Comment by hoxj180** [comment]
Thank you so much, @hcasperfu !
