### ISSUE TITLE
Buildings.Electrical.AC.ThreePhasesBalanced.Loads.Examples.ParallelLoads fails in OpenModelica due to structural singularity

### ISSUE THREAD

**Issue by AndreaBartolini** [lbl-srg/modelica-buildings#3776]
The model `Buildings.Electrical.AC.ThreePhasesBalanced.Loads.Examples.ParallelLoads` fails to simulate in OpenModelica because the derivative of the reactive power `Q=P*tan(acos(pf_internal))` in the submodel `RL_pf` approaches infinity when `pf_internal --> 1`, that is when the event at the end of the `pf_internal` ramp (from 0.8 to 1) is triggered.

Details are discussed in https://github.com/OpenModelica/OpenModelica/issues/11011#issuecomment-2035234375

A possible solution is indicated in https://github.com/OpenModelica/OpenModelica/issues/11011#issuecomment-2037312184

OpenModelica v1.23.0-dev-413-gfc210a9629 (64-bit)
Win 11 Pro (64-bit)
Buildings library Version: 11.0.0 - SHA1 c5fd934cf19f648017bcf9c97d1975b4042bc812 

Keep @casella in the loop

**Comment by mwetter** [comment]
@AndreaBartolini : Thanks for pointing to the root cause. I will do a PR for the 9.1.x, 10.0.x and master branch.
