### ISSUE TITLE
Unexpected output of Latch block when used in conjunction with TrueHold

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#3787]
When simulating the model `LatchWithHold` included below, the blocks `lat` and `lat1` have the same input values but different output values. 
<img width="123" alt="image" src="https://github.com/ibpsa/modelica-ibpsa/assets/10965994/c267529d-f85e-482e-b954-90453d250373">
The only difference is that `lat.clr` is computed using the block `TrueHold` whereas `lat1.clr` is not. 
The block `lat1` generates the expected output based on the documentation of `Latch`.
Both Dymola and OCT produce the same results.
Perhaps the implementation of `TrueHold` using a state graph is the cause although I can't find an explanation for this in the language specification.

On a side note, I wonder whether the implementation of `Latch` could not be simplified by removing the component `onDelay` and using `Modelica.StateGraph.Transition toInitial(enableTimer=duration > 0, waitTime=duration)`. 

```mo
model LatchWithHold
  Buildings.Controls.OBC.CDL.Logical.Latch lat
    annotation (Placement(transformation(extent={{40,-10},{60,10}})));
  Buildings.Controls.OBC.CDL.Logical.TrueHold truHol(duration=0.2)
    annotation (Placement(transformation(extent={{-30,-40},{-10,-20}})));
  Buildings.Controls.OBC.CDL.Logical.Sources.Pulse booPul(
    width=0.2,
    period=1,
    shift=0.5)
    annotation (Placement(transformation(extent={{-80,-10},{-60,10}})));
  Buildings.Controls.OBC.CDL.Logical.Not clr
    annotation (Placement(transformation(extent={{0,-40},{20,-20}})));
  Buildings.Controls.OBC.CDL.Logical.Latch lat1
    annotation (Placement(transformation(extent={{40,-70},{60,-50}})));
  Buildings.Controls.OBC.CDL.Logical.Not clr1
    annotation (Placement(transformation(extent={{0,-90},{20,-70}})));
equation
  connect(booPul.y, lat.u) annotation (Line(points={{-58,0},{38,0}},
               color={255,0,255}));
  connect(truHol.y, clr.u)
    annotation (Line(points={{-8,-30},{-2,-30}}, color={255,0,255}));
  connect(clr.y, lat.clr) annotation (Line(points={{22,-30},{30,-30},{30,-6},{38,
          -6}}, color={255,0,255}));
  connect(booPul.y, truHol.u) annotation (Line(points={{-58,0},{-40,0},{-40,-30},
          {-32,-30}}, color={255,0,255}));
  connect(booPul.y,clr1. u) annotation (Line(points={{-58,0},{-40,0},{-40,-80},{
          -2,-80}},  color={255,0,255}));
  connect(clr1.y, lat1.clr) annotation (Line(points={{22,-80},{30,-80},{30,-66},
          {38,-66}}, color={255,0,255}));
  connect(booPul.y, lat1.u) annotation (Line(points={{-58,0},{-40,0},{-40,-60},{
          38,-60}},  color={255,0,255}));
  annotation (
    experiment(
      StopTime=1.0,
      Tolerance=1e-06));
end LatchWithHold;
```

**Comment by mwetter** [comment]
The block `TrueHold` can indeed be simplified, which I started on `issue3787_trueHold_latch`

**Comment by mwetter** [comment]
I don't yet see why the difference in `lat.y` and `lat1.y` occurs. Could it be due to rounding errors?

**Comment by JayHuLBL** [comment]
@AntoineGautier I think the simplified `Latch` implementation `LatchSignal` can replace the current implementation. It indeed has the same results.

**Comment by AntoineGautier** [comment]
After discussing with Robin Andersson at Modelon, the results are as expected.
This is because two steps of a state machine that are connected with a transition cannot be active *simultaneously*. This leads to two distinct event iterations at the same time instant (0.5 s in the example). During the first one, the transition and the upstream state become active. During the second one only, the downstream state becomes active. So when the clause `elsewhen {clr, u}` is true, `not clr` is still false and `lat1.y` remains false.

I can see two ways moving forward with this issue and I suggest implementing the two.

1. In `Controls.OBC.CDL.Logical.Latch`: Change the clause `elsewhen {clr, u}` into `elsewhen {change(clr), u}`.

    - This changes the intent of the block as described in point 2) at https://github.com/lbl-srg/modelica-buildings/issues/3796#issuecomment-2051927205. 

    - However, if a Dirac pulse is used for the `clr` signal (see J[ianjun's comment](https://github.com/lbl-srg/modelica-buildings/issues/3796#issuecomment-2052215815)), then the output does switch to false when using `elsewhen {change(clr), u}` — which was not the case when using `elsewhen {clr, not clr, u}` as proposed in point 2) above.

2. In `Controls.OBC.CDL.Logical.TrueHold`: Conditionally remove all state graph components if `duration==0` and use a direct pass through of the input signal so that `y=u`.

@mwetter @JayHuLBL What do you think?

**Comment by mwetter** [comment]
I think these changes are fine. @JayHuLBL , do you agree?

**Comment by JayHuLBL** [comment]
The change looks good to me.

**Comment by AntoineGautier** [comment]
Updates after trying to implement the changes proposed in https://github.com/lbl-srg/modelica-buildings/issues/3787#issuecomment-2145291963:

1. In `Controls.OBC.CDL.Logical.Latch`: Changing the clause `elsewhen {clr, u}` into `elsewhen {change(clr), u}` yields a behavior that I eventually find very tedious to describe in English. The issue is that, in a scenario with a constant true input,
    - a Dirac pulse for the `clr` signal does clear the output which remains false until the input transitions back to true, but
    - a `clr` signal that transitions to true and then to false first clears the output then releases it back to true.
  
    So I find this even more counter-intuitive than what I described at https://github.com/lbl-srg/modelica-buildings/issues/3796#issuecomment-2051927205. And I tend to agree with Jianjun's initial comment suggesting that the clause `elsewhen {clr, u}` should remain as is.

2. In `Controls.OBC.CDL.Logical.TrueHold`: 
    - I was surprised to discover that the existing implementation does not strictly hold the input signal for the specified duration. Instead, it holds the signal for `i * duration` where `i` is the smallest integer such that `i * duration >= time(u switches to false) - time(hold started)`. This behavior aligns with the logic described in the documentation. However, this differs from the implementation of `Controls.OBC.CDL.Logical.TrueFalseHold` where the output is true for the longer of `trueHoldDuration` and the time during which the input signal is true. This latter logic matches the common pattern used in control sequences and aligns with the intuitive understanding of what "hold" means. 
    - Furthermore, to keep the output true for the required duration, the implementation of `Controls.OBC.CDL.Logical.TrueHold` loops over the state graph under the rationale that "the transitions are done in zero time" (as described in the documentation). This is brittle because the output is not strictly held constant, i.e., there is an event iteration during this "zero time" transition where it switches to false. This can be verified by simulating the model `TrueFalseHoldTrueHold` below. In this model, the instances `TrueHold` and `TrueFalseHold` appear to generate the same output that is constantly true between 0 and 1 s. But comparing the trajectory `lat.y` and `lat1.y` shows that `lat.y` does indeed transition to false at 0.5 s.
    - So I propose to modify `TrueHold` to adopt the same logic and use the same implementation as `TrueFalseHold`. Thus, the output will be held for the longer of `duration` and the time during which the input signal is true.

```mo
model TrueFalseHoldTrueHold
  Buildings.Controls.OBC.CDL.Logical.TrueHold truHol(duration=0.5)
    annotation (Placement(transformation(extent={{-40,-10},{-20,10}})));
  Buildings.Controls.OBC.CDL.Logical.Sources.Constant con(k=true)
    annotation (Placement(transformation(extent={{-90,-10},{-70,10}})));
  Buildings.Controls.OBC.CDL.Logical.Latch lat
    annotation (Placement(transformation(extent={{60,-10},{80,10}})));
  Buildings.Controls.OBC.CDL.Logical.Sources.Pulse booPul1(
    width=0.5,
    period=2,
    shift=0.1) annotation (Placement(transformation(extent={{0,30},{20,50}})));
  Buildings.Controls.OBC.CDL.Logical.Not not1
    annotation (Placement(transformation(extent={{0,-10},{20,10}})));
  Buildings.Controls.OBC.CDL.Logical.TrueFalseHold truFalHol(trueHoldDuration=0.5,
      falseHoldDuration=0)
    annotation (Placement(transformation(extent={{-40,-50},{-20,-30}})));
  Buildings.Controls.OBC.CDL.Logical.Not not2
    annotation (Placement(transformation(extent={{0,-50},{20,-30}})));
  Buildings.Controls.OBC.CDL.Logical.Latch lat1
    annotation (Placement(transformation(extent={{60,-50},{80,-30}})));
equation 
  connect(con.y, truHol.u)
    annotation (Line(points={{-68,0},{-42,0}}, color={255,0,255}));
  connect(booPul1.y, lat.u) annotation (Line(points={{22,40},{50,40},{50,0},{58,
          0}}, color={255,0,255}));
  connect(not1.y, lat.clr) annotation (Line(points={{22,0},{40,0},{40,-6},{58,-6}},
        color={255,0,255}));
  connect(truHol.y, not1.u)
    annotation (Line(points={{-18,0},{-2,0}}, color={255,0,255}));
  connect(con.y, truFalHol.u) annotation (Line(points={{-68,0},{-60,0},{-60,-40},
          {-42,-40}}, color={255,0,255}));
  connect(truFalHol.y, not2.u)
    annotation (Line(points={{-18,-40},{-2,-40}}, color={255,0,255}));
  connect(booPul1.y, lat1.u) annotation (Line(points={{22,40},{50,40},{50,-40},{
          58,-40}}, color={255,0,255}));
  connect(not2.y, lat1.clr) annotation (Line(points={{22,-40},{40,-40},{40,-46},
          {58,-46}}, color={255,0,255}));
  annotation (uses(Buildings(version="12.0.0")));
end TrueFalseHoldTrueHold;
```

**Comment by JayHuLBL** [comment]
@AntoineGautier Thanks for the detailed information.
For the `latch` block, keep `elsewhen {clr,u}` rather than `elsewhen{change(clr),u}`.

For the `TrueFalseHold`, I am actually updating the block as suggested: conditional remove the state graphical component when the duration is zero. Please see branch `issue3841_trueFalseHold`.

**Comment by AntoineGautier** [comment]
After discussing with @mwetter and @JayHuLBL the plan is now to:

- Replace each instance of `TrueHold` with `TrueFalseHold(trueHoldDuration=%duration%, falseHoldDuration=0)` and move `TrueHold` to `Obsolete`.
- Refactor `TrueFalseHold` to use direct pass-throughs if the duration is zero.

This is done in `issue3787_latchAndHold`.

**Comment by AntoineGautier** [comment]
Refactoring `TrueFalseHold` with direct pass-throughs if the duration is zero did not solve the initial issue. This is because the unexpected behavior — due to "hidden" event iterations — may not only occur when the duration is zero, but potentially at every instant when the variables `u` and `y` change simultaneously. 
This is illustrated in the example `TrueFalseHoldAndLatch` below where each instance of the `Latch` block is expected to produce the same output as the reference case `latRef`. I was not able to reach this objective by refactoring the current implementation with state graphs. I believe that it would significantly increase the block's complexity, which contradicts the initial purpose of using state graphs.
Therefore, I refactored the block using elementary synchronous language constructs. This is done in 6a1692b6de.

**Comment by AntoineGautier** [comment]
Closed with https://github.com/lbl-srg/modelica-buildings/pull/3863
