### ISSUE TITLE
A puzzle about library usage

### ISSUE THREAD

**Issue by shiyishiba** [lbl-srg/modelica-buildings#3822]
I am using openmodeica to run a case named airheating in modelica buildings library, but I don't know the function of the related component. I took a screenshot and hope that a professional can help me solve the confusion. In the screenshot I used a red box to frame the two modules, marked with the numbers 1 and 2. Based on my extrapolation, I think the number 1 refers to the volume of fresh air delivered, but what does the module of the number 2 represent?
![problem](https://github.com/lbl-srg/modelica-buildings/assets/125559199/91c8fdfd-dd78-40d0-a20f-27a3b7fa4cfa)

In addition, I have encountered many problems in the process of learning MBL, among which the biggest problem is that I do not understand the role of each module and the function of the interface. There are too few tutorials available on the Internet. I hope the development team can produce a set of pdf documents describing how to use each component, which is just a small suggestion.

**Comment by hcasperfu** [comment]
Greetings!
For general questions and comments that are not bug reports or feature requests please post here: https://github.com/lbl-srg/modelica-buildings/discussions.

In your screenshot, component 1 is a volume model that is used to impose the pressure boundary condition. You can think of it as the pressurisation point of the fluid loop.
I don't immediately recognise component 2. Please indicate the full path of this model in your post.

We have limited funding in terms of user support, but if there are specific models where you find the documentation is unclear, please post here and we will see if we can work on them.

Closing the issue.
