### ISSUE TITLE
the question about FMU

### ISSUE THREAD

**Issue by wuxu123** [lbl-srg/modelica-buildings#384]
One computer without lincense failed to deal with the fmu exported from  dymola in vs2013.And the vs2013 only supports the fmu exported in co-simulation way. When i changed an computer with lincense,it success. And i am considering how to export the fmu to solve the problem on the computer without lincense.

**Comment by mwetter** [comment]
Dymola requires a special license (binary model export I believe) in order to generate FMUs that can be simulated on a computer that has no Dymola license.
Closed issue as this is not a bug with the Buildings library.
