### ISSUE TITLE
Buildings.Examples.Tutorial.SimpleHouse.SimpleHouse2 not possible

### ISSUE THREAD

**Issue by n-marci** [lbl-srg/modelica-buildings#3843]
**Describe the bug**
When trying to connect "Modelica.Blocks.Math.Gain" to "Buildings.BoundaryConditions.WeatherData.Bus" as shown in the tutorial "Buildings.Examples.Tutorial.SimpleHouse.SimpleHouse2", there is an error: "Connectors gain.u and weaBus.HDirNor are not compatible."
Other connections like TDryBul are working with the gain block.
I am using OpenModelica 1.23

**To Reproduce**
1. Make a new model
2. Place Buildings.BoundaryConditions.WeatherData.Bus
3. Place Modelica.Blocks.Math.Gain
4. Connect the two and choose HDirNor for the connection
5. Get the error "Connectors gain.u and weaBus.HDirNor are not compatible."

**Expected behavior**
The tutorial should be reproducible in other models.

**Version**
 - Modelica Buildings Library: 11.0.0
 - Connected to OpenModelica 1.23.0~dev.beta.1-1-g379f714 built for Ubuntu 24.04 LTS.
 - The running OS is Ubuntu 24.04 LTS on x86_64.

**Additional context**

**Comment by hcasperfu** [comment]
Greetings and thanks for reporting!
I am able to reproduce this behaviour with slightly different steps.

1. Open `Buildings.Examples.Tutorial.SimpleHouse.SimpleHouse2` in OMEdit.
2. Select `connect(weaBus.HDirNor, gaiWin.u)` in the graphics view and delete it.
3. Reconnect `weaBus` and `gaiWin.u` in the graphics view and select `HDirNor` in the pop up.
4. Got the same error prompt.

Versions:
- Buildings 9411156ec2.
- OpenModelica 1.24.0~dev-16-gaa27cc1.
- Ubuntu 20.04.3.

Following exactly the same steps in Dymola 2024x would not result in an error message. Therefore I suspect this is a problem with OpenModelica, not the Buildings library.
I will open a ticket with OpenModelica and close this ticket.

**Comment by hcasperfu** [comment]
This is now reported to OpenModelica in https://github.com/OpenModelica/OpenModelica/issues/12471.
Closing the ticket.

**Comment by hcasperfu** [comment]
This bug is fixed in OpenModelica 1.24.0~dev-103-g1ef9b1b (nightly build).
