### ISSUE TITLE
Problems with 5GDHC Simulation Using Dragonfly from GeoJSON to Modelica Example in OpenModelica 1.22.3

### ISSUE THREAD

**Issue by bvidalEKT** [lbl-srg/modelica-buildings#3858]
**Issue Description**

I am new to OpenModelica and the use of the Modelica Building Libraries, so I apologize if this is not the appropriate place to raise these issues. I am using the MBL: Buildings-v10.0.0

I have created a 5GDHC district model from GeoJSON to Modelica using Dragonfly from Ladybug Tools. I managed to simulate several buildings (the example) and another one by modifying the loads. However, I am facing issues with my project, which includes 8 buildings. I had to adjust the distribution pump pressure and then manually include the peak loads in the terminal units of each building (terUniCoo and terUniHeat) to achieve a successful simulation.

The problem is that after multiple attempts, although I encounter errors like:

The following assertion has been violated at time 31459800.000000 ((noEvent(TimeSerLoa_630ef19b.ets.volMix_a.dynBal.medium.T >= 272.15))) --> "In DistrictEnergySystem.TimeSerLoa_630ef19b.ets.volMix_a.dynBal.medium: Temperature T = 271.51 K exceeded its minimum allowed value of -1 degC (272.15 Kelvin) as required from medium model "Buildings.Media.Water"."

I can get it to simulate 100%, but it has crashed several times at 99%, and I cannot determine the source of the error. I am completely new to OpenModelica, and starting with these fully configured models has been challenging.

Now, it seems to only consider the heating loads and not the cooling loads of the buildings.
Model Configuration

**Steps to Reproduce**

    Create the 5GDHC district model using Dragonfly. ( I attached the modelica model)
[des_modelica.zip](https://github.com/user-attachments/files/15661778/des_modelica.zip)

    Adjust the distribution pump pressure. ( put the "dp_nominal" from the Distribution pump in the DistrictEnergySystem to 600000)
    Manually include the peak loads in the terminal units. ( add the #Peak space cooling load  and #Peak space heating load  from the des_modelica\Loads\Resources\Data\B8161616DG7486S\modelica.mos of each building to the terUniCoo and terUniHeat elements in each TimeSeriesBuilding)
    Attempt to simulate the complete model.

Expected Behavior

The simulations should consider both the heating and cooling loads of the buildings.
Observed Behavior

Only the heating loads are considered. The cooling loads are not being properly accounted for.
The screenshot shows the Temperature Input and Output of the borehole between January and September
![image](https://github.com/lbl-srg/modelica-buildings/assets/128154169/4a6b06f4-d9be-41a2-86ee-ba5ec5f1452b)

**Comment by mwetter** [comment]
Closed as this is handled in https://github.com/urbanopt/geojson-modelica-translator/issues/637
