### ISSUE TITLE
Increase tolerance for CI testing for OptimalStart

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#3865]
This issue is to increase the tolerance for the CI testing for the optimal start examples.

See https://github.com/OpenModelica/OpenModelica/issues/12517 for details and what models are affected.

This should be applied to the `maint_10.0.x`, `maint_11.x` and `master` branch.

**Comment by casella** [comment]
I guess you mean "decrease" 😃

**Comment by mwetter** [comment]
This is corrected on all branches.
