### ISSUE TITLE
something about simulation result

### ISSUE THREAD

**Issue by wuxu123** [lbl-srg/modelica-buildings#387]
For example, in the air-conditioning system with heating coil, when i add a humidifier from the Building 1.6 in order to humidify the supply air,  the temperature of supply, heating load, the value of valve and the volume of the hot water change a lot. But the humidification amout is very little. what is wrong with my model,please!

**Comment by mwetter** [comment]
@wuxu123 : 
We would need more information to reproduce and understand what you intend to do. Please submit what is listed at http://simulationresearch.lbl.gov/modelica/userGuide/help.html

Please send the information to the mailing list at https://groups.google.com/group/modelica-buildings as this issue tracker is typically used to track bugs and model enhancements.
