### ISSUE TITLE
Can't use Buildings.BoundaryConditions.SolarIrradiation.DirectTiltedSurface in my models

### ISSUE THREAD

**Issue by n-marci** [lbl-srg/modelica-buildings#3872]
**Describe the bug**
When using `Buildings.BoundaryConditions.SolarIrradiation.DirectTiltedSurface` in my model and connecting the input to `Buildings.BoundaryConditions.WeatherData.Bus`, I get the errors:
```
[27] 13:43:20 Translation Error
[Buildings.BoundaryConditions.SolarIrradiation.DirectTiltedSurface: 15:3-18:73]: [Illegal access of protected element incAng.](omeditmessagesbrowser:///Buildings.BoundaryConditions.SolarIrradiation.DirectTiltedSurface?lineNumber=15)

[28] 13:43:20 Translation Error
[vertical_farm: 178:5-179:114]: [Variable plant1.HDirRoo.incAng.weaBus not found in scope airvolume.](omeditmessagesbrowser:///vertical_farm?lineNumber=178)
```

**To Reproduce**
1. Make new model `plant`
2. Place `Buildings.BoundaryConditions.SolarIrradiation.DirectTiltedSurface`
3. Place `Buildings.BoundaryConditions.WeatherData.Bus`
4. Connect the weaBus elements
5. Make a second model `airvolume`
6. Place `plant` inside `airvolume`
7. Observe Translation error

**Expected behavior**
You should be able to use the DirectTiltedSurface inside of a nested model.

**Version**
 - Modelica Buildings Library: 11.0.0
 - OpenModelica 1.23.0~dev.beta.1-1-g379f714
 - Ubuntu 24.04

**Additional context**

**Comment by mwetter** [comment]
That looks like a problem with the OpenModelica parser. Can you report it, and upload a test model, at https://github.com/OpenModelica/OpenModelica/issues
