### ISSUE TITLE
How to calculate the heat transfer of the envelope structure

### ISSUE THREAD

**Issue by shiyishiba** [lbl-srg/modelica-buildings#3882]
Hello professionals,

A question about the Modelica Buildings Library (MBL) has been bothering me for a long time. I know that the library can couple with EnergyPlus, and I want to use Spawn to calculate the heat transfer of a building's envelope. However, the Spawn description in the library is not very clear.

My specific question is: In the Buildings.ThermalZones.EnergyPlus_9_6_0.Building module, if the building is set up in the IDF file format, and is connected to the Buildings.ThermalZones.EnergyPlus_9_6_0.ThermalZone module, will Spawn automatically calculate the envelope's heat transfer? Or do I need to set up the envelope explicitly in the model and then calculate it through the thermal conductivity module?

Thank you all!
![buildings](https://github.com/lbl-srg/modelica-buildings/assets/125559199/ee79fb6d-958a-4571-87da-b4980c138c9e)

**Comment by mwetter** [comment]
EnergyPlus calculates the envelope heat transfer. See the UsersGuide of the Modelica Buildings Library (https://simulationresearch.lbl.gov/modelica/releases/v11.0.0/help/Buildings_ThermalZones_EnergyPlus_9_6_0_UsersGuide.html#Buildings.ThermalZones.EnergyPlus_9_6_0.UsersGuide) and the Spawn paper that is cited in the user guide.

**Comment by shiyishiba** [comment]
thanks，I am curious about whether it is necessary to manually set the envelope parameters in Modelica. Does Spawn automatically recognize the walls, windows, and other elements I have configured?

**Comment by mwetter** [comment]
These elements are automatically recognized by EnergyPlus if entered in the idf file.

**Comment by shiyishiba** [comment]
Thank you for your response. If I understand correctly, once the IDF file is imported into [building], the  spawn of EnergyPlus will automatically calculate the heat transfer of the envelope structure, including the heat from lamps and other sources. Could I use the Buildings.ThermalZones.EnergyPlus_9_6_0.OutputVariable module to read the heat transfer data that I am interested in?

**Comment by mwetter** [comment]
Please check the existing documentation that explains all of these points.
