### ISSUE TITLE
Impact of TrueFalseHold refactoring on TimeSuppression

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#3883]
With the refactoring from #3863:

- With Dymola, the reference results change for `Controls.OBC.ASHRAE.G36.Generic.Validation.TimeSuppressionNegativeStartTime` and `TimeSuppressionPositiveStartTime`.
- OCT fails to translate the models due to an algebraic loop with when clauses.

This is because the block `TimeSuppression` uses a hold to break the direct feedback of the Latch component's output to its `clr` input. 
I believe this should be changed as, fundamentally, holding a signal does not break a direct feedback loop — because when `truHol.u` switches to true, `truHol.y` should also immediately switch to true if there is no active hold, same when it switches to false if the holding time has elapsed. 
This went unnoticed before due to the "hidden" event iterations described in #3787. 

This issue is to refactor `TimeSuppression` using, e.g., a `pre` block instead of a hold to break the loop.

@JayHuLBL Can you look into that?

**Comment by AntoineGautier** [comment]
In `issue3883_timeSuppression` commit 242e5acb7e I replaced the instance of `TrueHold` with a pre block. The reference results for the models in `Controls.OBC.ASHRAE.G36.Generic.Validation` do not change.

@JayHuLBL Can you confirm that this change is valid to check if the suppression time has elapsed in `TimeSuppression`?

**Comment by JayHuLBL** [comment]
@AntoineGautier The change looks good. The results are valid.

**Comment by AntoineGautier** [comment]
Closed with https://github.com/lbl-srg/modelica-buildings/pull/3893
