### ISSUE TITLE
Which model can be used as moisture gain from occupant.

### ISSUE THREAD

**Issue by danggongfan** [lbl-srg/modelica-buildings#389]
I want to add moisture gain from occupant to the room model. But when I use  Buildings.Fluid.MassExchangers.HumidifierPrescribed like this, it doesn't work.
![qq 20150323223217](https://cloud.githubusercontent.com/assets/10896588/6782348/70aedd60-d1ae-11e4-90ba-77e446d9c842.png)
When I simulation the model, hum.vol.dynBal.medium.T drop sharply. Then the simulation is failed because T is less than 200K. In Buildings.Fluid.MassExchangers.Examples.HumidifierPrescribed, a MassFlowSource_T model is added, but I don't know the value of mass flow rate, so I only can use this model as picture showed. I want to learn which model can be used as moisture gain from occupant, and the right way to use it.
Thank you.

**Comment by mwetter** [comment]
@danggongfan 
Please repost to https://groups.google.com/group/modelica-buildings as this is a question, not a bug.
This issue tracker is meant to keep track of bugs and model enhancements and not as a discussion forum for user questions.

**Comment by danggongfan** [comment]
OK, thank you.
