### ISSUE TITLE
question about  the model of the room in building 1.6

### ISSUE THREAD

**Issue by wuxu123** [lbl-srg/modelica-buildings#391]
can the room be used in the VAV systerm? How much is the load of the room? Is it vevy little? 
 In my model , the air is supplied to the room and the volume of air is 6.5 m3/s. I have tried to change the number of window and the size of wall or window, but failed. The result is that the temperature of return air is equal to the supply.

**Comment by mwetter** [comment]
See your post at https://github.com/lbl-srg/modelica-buildings/issues/387 for where to submit general support questions. This issue tracker is to track bugs and enhancements, not for general questions.
