### ISSUE TITLE
Validate freeze protection logic

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#3917]
Currently on the master branch d95a645232, the validation model `Buildings.Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.SetPoints.Validation.FreezeProtection` gives results that seem to contradict the documentation of `Buildings.Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.SetPoints.FreezeProtection`:

> **2**. If the supply air temperature TAirSup drops below 3.3 °C (38 °F) for 5 minutes, fully close both the economizer damper and the minimum outdoor air damper for 1 hour and set a **Level 3 alarm** noting that minimum ventilation was interrupted. After 1 hour, the unit shall resume minimum outdoor air ventilation and enter the previous stage of freeze protection.

The condition on the SAT is met at 2730 s but the alarm level remains at 0 and the stage at 1.
In contrast, with the refactoring of the hold block in #3863, at 2730 s the alarm level transitions to 3 and the stage to 2. 

Same for `Buildings.Controls.OBC.ASHRAE.G36.AHUs.SingleZone.VAV.SetPoints.Validation.FreezeProtection` where the condition on the SAT is met at 3000 s but the alarm level remains at 0 and the stage at 1.
In contrast, with the refactoring of the hold block in #3863, at 3000 s the alarm level transitions to 3 and the stage to 2. 

@JayHuLBL Could you confirm that the results from #3863 are as expected and that the results currently on the master branch are incorrect? If so, no further action is needed for this ticket, as it will be addressed when #3863 is merged.

**Comment by JayHuLBL** [comment]
@AntoineGautier The results showing in #3863 are correct. It should sent a level 3 alarm when the condition is met.

I just pushed the updated results and confirmed that OpenModelica produces the same results (so it addressed the issue #3841). The updated results has been pushed to the branch issue3787_latchAndHold ([64ead7a](https://github.com/lbl-srg/modelica-buildings/pull/3863/commits/64ead7a3f18c97e674ca63400117b6f3224227c8)).

**Comment by AntoineGautier** [comment]
Closed with https://github.com/lbl-srg/modelica-buildings/pull/3863.
