### ISSUE TITLE
Another strange case of unmatching results vs reference file

### ISSUE THREAD

**Issue by AndreaBartolini** [lbl-srg/modelica-buildings#3918]
The variable `pumCHW.m_flow` of the model `Buildings.Examples.ChillerPlant.DataCenterDiscreteTimeControl` fails the verification vs the Dymola reference file but on my machine Dymola and OpenModelica produce the same results, and that results are according to the one produced by OpenModelica on the CI (see https://github.com/OpenModelica/OpenModelica/issues/12651 for further details).

Can you please cross check my Dymola result in the ticket above with the Dymola installation that has produced the reference result?  

Thanks a lot in advance.

Andrea

Keep @casella in the loop

**Comment by casella** [comment]
@AndreaBartolini please specify which versions of Dymola and OMC you are using 😃

**Comment by AndreaBartolini** [comment]
Is indicated in the https://github.com/OpenModelica/OpenModelica/issues/12651

**Comment by JayHuLBL** [comment]
@mwetter I will check the results as you [suggested](https://github.com/OpenModelica/OpenModelica/issues/12651#issuecomment-2197799543). It will be done today.

**Comment by JayHuLBL** [comment]
The issue has been address through issue #3939, PR #3940.

It can be closed.
