### ISSUE TITLE
undefined reference to `fmi2Instantiate'

### ISSUE THREAD

**Issue by lyw2024** [lbl-srg/modelica-buildings#3929]
Hello, all:
     I try to running FMU in Ubuntu with C code. first I have install FMILibrary-2.0a1. then I have wite a demo code to test whether we can run FMU in Ubuntu. but after I try to complie the code with  this command (gcc  CallFMU.c -o CallFMU  -L . -l fmilib -v). it tell me 
that can't find fmi2Instantiate and so on.
 the err discrription is follwiing: 
COLLECT_GCC_OPTIONS='-o' 'CallFMU' '-L.' '-v' '-mtune=generic' '-march=x86-64'
 as -v --64 -o /tmp/ccnJvgAX.o /tmp/ccXLpD6X.s
GNU assembler version 2.30 (x86_64-linux-gnu) using BFD version (GNU Binutils for Ubuntu) 2.30
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-o' 'CallFMU' '-L.' '-v' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/7/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/7/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper -plugin-opt=-fresolution=/tmp/ccRBIS5W.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o CallFMU /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o -L. -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. /tmp/ccnJvgAX.o -lfmilib -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o
/tmp/ccnJvgAX.o: In function `main':
CallFMU.c:(.text+0xa1): undefined reference to `fmi2Instantiate'
CallFMU.c:(.text+0xf1): undefined reference to `fmi2SetupExperiment'
CallFMU.c:(.text+0x112): undefined reference to `fmi2Terminate'
CallFMU.c:(.text+0x128): undefined reference to `fmi2EnterInitializationMode'
CallFMU.c:(.text+0x149): undefined reference to `fmi2Terminate'
CallFMU.c:(.text+0x15f): undefined reference to `fmi2ExitInitializationMode'
CallFMU.c:(.text+0x184): undefined reference to `fmi2Terminate'
CallFMU.c:(.text+0x1b5): undefined reference to `fmi2DoStep'
CallFMU.c:(.text+0x1f2): undefined reference to `fmi2GetReal'
CallFMU.c:(.text+0x24d): undefined reference to `fmi2Terminate'
collect2: error: ld returned 1 exit status

do you know how to solve this issue.?

 thank you.

**Comment by mwetter** [comment]
This is the wrong repository. You should contact the FMILibrary developers with this concern.
