### ISSUE TITLE
a bug with  humidifier in building ?

### ISSUE THREAD

**Issue by wuxu123** [lbl-srg/modelica-buildings#393]
there is no influence when i change the temperature of the water added into the humidifier.

**Comment by mwetter** [comment]
Closed as there is an influence, see
```
simulateModel("Buildings.Fluid.MassExchangers.Examples.Humidifier_u(humSte(T=273.15+50))", stopTime=1200, method="radau", tolerance=1e-06, resultFile="Humidifier_u");
```
produces different signals for the two controllers at steady-state.

We would need a test case that reproduces it.
