### ISSUE TITLE
Model Buildings.Fluid.Chillers.ModularReversible.Examples.Modular fails verification

### ISSUE THREAD

**Issue by AndreaBartolini** [lbl-srg/modelica-buildings#3930]
The following variables of the model `Buildings.Fluid.Chillers.ModularReversible.Examples.Modular` fails the verification vs the Dymola reference file:
- `chi.refCyc.sigBus.yMea`
- `chi.P`
- `chi.QEva_flow`
- `chi.QCon_flow`
- `chi.refCyc.sigBus.TEvaOutMea`
- `chi.refCyc.sigBus.TConOutMea`

The root cause of the all the failures is the variable `chi.refCyc.sigBus.yMea`:
![image](https://github.com/lbl-srg/modelica-buildings/assets/25974985/227b715b-8665-45f6-9846-378927583422)

That is produced by the safety logic `safCtr` in the following diagram and then propagated to the models of the process via the `sigBus` expandable bus:
![image](https://github.com/lbl-srg/modelica-buildings/assets/25974985/23605547-e616-4cff-b0dd-112e04767b0f)

the output of the `safCtr` logic depends (via the `sigBus` expandable bus) on the output of the threshold with hysteresis `hys`, that generates the problem:
![image](https://github.com/lbl-srg/modelica-buildings/assets/25974985/6849f693-1006-4aad-a655-0d13d7bcb211)

at time=1000s the threshold changes its state in Dymola but not in OpenModelica, note also that in the other cycles the threshold never change its state in both Dymola and OpenModelica.
The cause of this uniqe change of the state is the value of the lower limit of the hysteresis, that is set to 1e-15. This value is orders of magnitude lower than the tolerance of the solver, so the trigger of the threshold becomes unpredictable and depends on the numerical noise of the solution, this the reason because in the other cycles the threshold is not triggered.

The higher limit of the hysteresis is set to 0.01, so in some way the `hys` block is able to come back to the ON state.

The suggestion is to change the threshold limits in order to be better defined with respect to the tolerance of the solver.

Keep @casella in the loop

**Comment by mwetter** [comment]
@FWuellhorst: Could you please change this setting of the model in the `IBPSA` repository (and then LBL can download the changes to `Buildings`).

**Comment by FWuellhorst** [comment]
Yes, I can change that. Setting the lower bound to 0.001 as considering 0.1 % part load as "off" should be sufficient, what do you think? Also, 1e-3 should be higher than the tolerances, or? 
I would then add a min attribute to `ySet_small` to avoid values below 0.001, even though it is in the advanced tab.

**Comment by mwetter** [comment]
I think a lower bound of 0.001 should be good.

**Comment by mwetter** [comment]
@FWuellhorst : There are other models with this issue, also from the the `ModularReversible` package. Please see https://github.com/lbl-srg/modelica-buildings/issues/3943
Can you please address them in the same PR.
