### ISSUE TITLE
OBC CDL UnitDelay Block Doesn't Delay the Input Signal

### ISSUE THREAD

**Issue by wehuang16** [lbl-srg/modelica-buildings#3953]
**Describe the bug**
I found that the OBC CDL UnitDelay block (https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Controls/OBC/CDL/Discrete/UnitDelay.mo) doesn’t actually delay the input signal.

**To Reproduce**
1. Download my test file “UnitDelayAndSampleBlock.mo” here: https://drive.google.com/drive/folders/1mOC5agTgJYHSaId2KEcH7kBV83rd4zs2?usp=sharing 
2. Use a Modelica environment, such as Dymola or OpenModelica, to import the “UnitDelayAndSampleBlock.mo” file as well as the “modelica buildings library” (use the “master” branch).
3. Within the “UnitDelayAndSampleBlock.mo” file, I created a Sine Wave signal named “sin1” with a period of 1 second. I also pulled in a UnitDelay block named “unitDelay1” and a Sample block named “sam”. The output of the sine wave feeds to the inputs of the UnitDelay block and the Sample block. The UnitDelay block and the Sample block both have a “samplePeriod” of 0.05 seconds. I simulated the “UnitDelayAndSampleBlock.mo” file for 1 second, and plotted the parameters “sin1.y”, “unitDelay1.y”, and “sam.y”. I found that the both “unitDelay1.y" and "sam.y" signals have the same values (see the screenshot below).

**Expected behavior**
The Sample block was meant to sample the Sine Wave signal “sin1.y” every 0.05 seconds and output the sampled values. The screenshot below shows that the “sam.y” values behave as expected. However, by definition, the UnitDelay block should work like the Sample block by sampling the Sine Wave, but should output a delayed signal with a 0.05 seconds delay as compared to the Sample block. Thus, I expected that the “unitDelay1.y” signal should be 0.05 seconds delayed compared to the “sam.y” signal. 

However, we have seen that the “unitDelay1.y" and "sam.y" signals have the same values, which suggests that the UnitDelay block doesn’t delay the signal as expected, which is a problem. 

**Screenshots**
![Screenshot 2024-07-25 at 4 59 05 PM](https://github.com/user-attachments/assets/0bfa9263-2cb3-4c07-88df-4f98d6ae22a3)

**Version**
 - Modelica Buildings Library: use the most recent update in the “master” branch
 - Modelica simulation environment: Dymola 2023x in Ubuntu 20.0.4
 - Operating system: Mac + Ubuntu 20.0.4

**Additional context**
Any fixes to this issue will be greatly appreciated!

**Comment by JayHuLBL** [comment]
@wehuang16 Thanks for reporting this. I also tested the same block in Modeloca Standard Library `Modelica.Blocks.Discrete.UnitDelay` and it gives the same results as ours. However, I agree that the result is wrong. After the change in commit [750c2de](https://github.com/lbl-srg/modelica-buildings/commit/750c2de0df55145cbd6256afc5c2c62cb890a092), the result look as below.
![UnitDelayAndSampleBlock-2](https://github.com/user-attachments/assets/f019df58-6357-4145-9edf-e78128ddb042)

**Comment by mwetter** [comment]
@JayHuLBL : If the results from the `Modelica.Blocks.Discrete.UnitDelay` are wrong, please report to the Modelica github page.
