### ISSUE TITLE
Model Buildings.Fluid.CHPs.BaseClasses.EfficiencyCurve has double Icon annotations

### ISSUE THREAD

**Issue by NirmalaModelon** [lbl-srg/modelica-buildings#3954]
The model list Icon annotation twice:
`    Icon(coordinateSystem(extent={{-100,-100},{100,100}}), graphics={
        Line(points={{-90,-76},{68,-76}},
                                      color={192,192,192}),
        Line(points={{-80,-80},{-79.2,-50.6},{-78.4,-37},{-77.6,-28},{-76.8,-21.3},
              {-75.2,-11.4},{-72.8,-1.31},{-69.5,8.08},{-64.7,17.9},{-57.5,28},
              {-47,38.1},{-31.8,48.1},{-10.1,58},{22.1,68},{68.7,78.1},{80,80}}),
        Line(points={{-80,-80},{-80,68}}, color={192,192,192}),
        Polygon(
          points={{-80,90},{-88,68},{-72,68},{-80,90}},
          lineColor={192,192,192},
          fillColor={192,192,192},
          fillPattern=FillPattern.Solid)}),
    Icon(graphics={Text(
          extent={{-90,38},{90,-34}},
          textColor={160,160,164},
          textString="polynomial()")}));`

**Comment by JayHuLBL** [comment]
@NirmalaModelon Thanks! will fix it.

**Comment by NirmalaModelon** [comment]
thanks for the help! should i close this issue now?

**Comment by JayHuLBL** [comment]
It will be closed after the change has been merged to the master, through the PR #3956.
