### ISSUE TITLE
missing mos scripts

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#396]
`Buildings.Electrical.AC.OnePhase.Examples.GeneratorLoadGrid` and
`Buildings.Electrical.AC.OnePhase.Examples.GridDCLoad` both
reference a `.mos` script that does not exist.

These files were never part of any test because `Buildings/Electrical/AC/OnePhase/package.order` did not list `Examples`, and `Buildings/Electrical/AC/OnePhase/Examples` had no `package.mo`, which I now added.

This needed to be fixed because the generation of `package.order` will add this directory, and then OpenModelica can no longer load the `Buildings` library.

What remains to be done is to add `.mos` scripts, reference results and review the examples.

**Comment by mbonvini** [comment]
closed with 5d4a55701b09f31e8e636a4801670855f329d814
