### ISSUE TITLE
Error when selecting medium from the dropdown list

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#3970]
It is to address the issue reported in [IBPSA issue #1924](https://github.com/ibpsa/modelica-ibpsa/issues/1924).

In class `Buildings.Fluid.HeatExchangers.ConstantEffectiveness`, the choices given by the dropdown causes the code to try to redeclare `Medium` instead of `Medium1` or `Medium2`, and see following error:

<img width="739" alt="Screenshot 2024-08-27 at 12 14 20 PM" src="https://github.com/user-attachments/assets/682130d0-e5ba-4f04-af69-1ef87858ed9d">

------
The root cause is from the below code section in baseclass `Buildings.Fluid.Interfaces.PartialFourPort`:

```
 replaceable package Medium1 =
    Modelica.Media.Interfaces.PartialMedium "Medium 1 in the component"
      annotation (choices(
        choice(redeclare package Medium = Buildings.Media.Air "Moist air"),
        choice(redeclare package Medium = Buildings.Media.Water "Water"),
        choice(redeclare package Medium =
            Buildings.Media.Antifreeze.PropyleneGlycolWater (
          property_T=293.15,
          X_a=0.40)
          "Propylene glycol water, 40% mass fraction")));
  replaceable package Medium2 =
    Modelica.Media.Interfaces.PartialMedium "Medium 2 in the component"
      annotation (choices(
        choice(redeclare package Medium = Buildings.Media.Air "Moist air"),
        choice(redeclare package Medium = Buildings.Media.Water "Water"),
        choice(redeclare package Medium =
            Buildings.Media.Antifreeze.PropyleneGlycolWater (
          property_T=293.15,
          X_a=0.40)
          "Propylene glycol water, 40% mass fraction")));
```

The change will merge to the branches, master, the 11, 10 and 9 maintenance branches. And the error needs to done for the class `Buildings.Fluid.Interfaces.EightPort`.

**Comment by mwetter** [comment]
@JayHuLBL : Is this corrected?

**Comment by JayHuLBL** [comment]
Yes, it has been corrected. The issue can be closed.
