### ISSUE TITLE
VoltageLosses in PartialLine

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#398]
`PartialLine` declares
``` 
 Real VoltageLosses = 100*abs(PhaseSystem_p.systemVoltage(terminal_p.v) -
    PhaseSystem_n.systemVoltage(terminal_n.v))/
    Buildings.Utilities.Math.Functions.smoothMax(
      PhaseSystem_p.systemVoltage(terminal_p.v),
      PhaseSystem_n.systemVoltage(terminal_n.v),
      1.0) "Percentage of voltage losses across the line";
```
Wouldn't it be more consistent to use p.u.? In other parts of the `Buildings` library, we never use percentage.

**Comment by mbonvini** [comment]
I don't know if it's a stretch of the definition. Per unit are refers to a fixed unit (e.g., nominal power or nominal voltage). In this case the voltage losses are relative to the maximum voltage at one of the ends of the line.
I agree that the unit is present anywhere but on the other hand is not what one would expect from a per unit.

**Comment by mwetter** [comment]
Then it would be best to remove the factor 100, and add `unit="1"`

**Comment by mbonvini** [comment]
Done in c37768aa7b219d4eaea443a5ace7921284fb1943
