### ISSUE TITLE
Broken html links

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#3992]
There are various broken links in Modelica models, namely:

Error: Can not resolve link "Modelica://Buildings.Fluid.CHPs.OrganicRankine.BottomingCycle" in [Buildings.Fluid.CHPs.OrganicRankine.Data.Generic](modelica://Buildings.Fluid.CHPs.OrganicRankine.Data.Generic)
Error: Can not resolve link "modelica://Buildings.Fluid.Geothermal.ZonedBorefields.Template" in [Buildings.Fluid.Geothermal.ZonedBorefields.Data.Borefield.Validation](modelica://Buildings.Fluid.Geothermal.ZonedBorefields.Data.Borefield.Validation)
Error: Can not resolve link "modelica://Buildings.Fluid.Geothermal.ZonedBorefields.Data.Configuration.Example" in [Buildings.Fluid.Geothermal.ZonedBorefields.Data.Configuration.Template](modelica://Buildings.Fluid.Geothermal.ZonedBorefields.Data.Configuration.Template)
Error: Can not resolve link "modelica://Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.shiftAggregationCells" in [Buildings.Fluid.Geothermal.ZonedBorefields.BaseClasses.HeatTransfer.shiftAggregationCells](modelica://Buildings.Fluid.Geothermal.ZonedBorefields.BaseClasses.HeatTransfer.shiftAggregationCells)
Error: Can not resolve link "modelica://Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.temporalSuperposition" in [Buildings.Fluid.Geothermal.ZonedBorefields.BaseClasses.HeatTransfer.temporalSuperposition](modelica://Buildings.Fluid.Geothermal.ZonedBorefields.BaseClasses.HeatTransfer.temporalSuperposition)

@hcasperfu : Can you please address them on the master, then 10 and 11 maintenance branches (if they are there too) and also in the upstream Modelica library.

**Comment by hcasperfu** [comment]
I have created a PR for the master branch.
These models don't exist in maint 10 or IBPSA.
