### ISSUE TITLE
Using the radiative heat port of SPAWN thermal zones leads to the simulation failing midway.

### ISSUE THREAD

**Issue by Mov0** [lbl-srg/modelica-buildings#3994]
[dslog.txt](https://github.com/user-attachments/files/16955270/dslog.txt)
**Describe the bug**
When running Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.Radiator the simulation fails with the following error message: 

> ... Error message from dymosim
At time T = 1.260000e+04 and stepsize
H = 1.370330e-10 the code had repeated error test failures
on the last attempted step. A singularity in the solution may be
present. (For DAEs: Provide initial values of X and of XD which
are consistent). Integration will be terminated.

The simulation analysis indicates that there is a problem with the radiative heat port in Buildings.ThermalZones.EnergyPlus_9_6_0.ThermalZone. When the radiative heat port of the radiator is connected with the heat port of the air volume instead of the radiative heat port of the zone, the simulation terminates successfully.

**To Reproduce**
1. Download and unzip Buildings 11.0.0
2. Remove space from directory name (see #3993)
3. Run Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.Radiator

**Expected behavior**
The simulation of the example should terminate successfully.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/0693d8b8-de6f-49ff-b375-ac3ed14e18f0)

**Version**
 - Modelica Buildings Library: 11.0.0 (also tested with commit eadbd6c)
 - Modelica simulation environment: Dymola 2024x
 - Operating system: Windows: Windows 10 Education 22H2 64-bit

**Comment by mwetter** [comment]
This model works (as tested on Linux). It is possible that on Windows the numerics is slightly different due to a different compiler.

The fact that the model works if you connect the radiation port differently is because this changes the set of equations which can -- and here will -- make the model work.

I suggest you try to change the tolerance and/or the solver and if the problem persists, report it to the Dymola support. I don't see what could/should be changed in the library.

**Comment by Florayeon** [comment]
Changing the tolerance allows the model to run successfully. 
However, I don't know if changing the tolerance too much will have any other effects on the model.

**Comment by mwetter** [comment]
Usually there are no side effects. Some models need higher tolerances depending on the numerics of the equations that are being solved.
