### ISSUE TITLE
Issue with dimensions after updated actuator model

### ISSUE THREAD

**Issue by maltelenz** [lbl-srg/modelica-buildings#4004]
**Describe the bug**
There seems to be a problem with the dimensions in `Buildings.Applications.DataCenters.ChillerCooled.Equipment.BaseClasses.SignalFilter` after #4000 

Here is the report from System Modeler:

> Error: `Buildings.Applications.DataCenters.ChillerCooled.Equipment.BaseClasses.SignalFilter` [27:4-27:4] Incompatible number of dimensions. `actPos.y` has type `.Modelica.Blocks.Interfaces.RealOutput` but `y_actual` has type `(.Modelica.Blocks.Interfaces.RealOutput)[$dimension_8]`. 
> 
> Error: `Buildings.Applications.DataCenters.ChillerCooled.Equipment.BaseClasses.SignalFilter` [23:2-23:2] Incompatible number of dimensions. `actPos.y` has type `.Modelica.Blocks.Interfaces.RealOutput` but `y_filtered` has type `(.Modelica.Blocks.Interfaces.RealOutput)[$dimension_9]`. 
> 
> Error: `Buildings.Applications.DataCenters.ChillerCooled.Equipment.BaseClasses.SignalFilter` [12:5-12:5] Incompatible number of dimensions. `yValve_start` has type `(Real)[$dimension_7]` but the expected type is `Real`. 

**To Reproduce**
Validate `Buildings.Applications.DataCenters.ChillerCooled.Equipment.BaseClasses.SignalFilter`
or simulate one of these models using Wolfram System Modeler:
```
Buildings.Applications.BaseClasses.Equipment.Validation.ElectricChillerParallel
Buildings.Applications.DataCenters.ChillerCooled.Equipment.Validation.IntegratedPrimaryPlantSide
Buildings.Applications.DataCenters.ChillerCooled.Equipment.Validation.NonIntegrated
Buildings.Applications.DataCenters.ChillerCooled.Equipment.Validation.WatersideEconomizer
```

**Expected behavior**
Model builds and simulates.

**Version**
 - Modelica Buildings Library: 55203c6
 - Modelica simulation environment: Wolfram System Modeler
 - Operating system: All

**Comment by mwetter** [comment]
@maltelenz : Thanks, this is indeed a bug which will be corrected through #4005.
Please let me know if the problem persists (as other tools did not detect the issue).

**Comment by maltelenz** [comment]
I can confirm #4005 makes all the affected models work again in System Modeler.

**Comment by mwetter** [comment]
Thanks for the quick turn-around!
