### ISSUE TITLE
Difference in energyplus and buildinglib biquadratic formulation

### ISSUE THREAD

**Issue by TeoGoddet** [lbl-srg/modelica-buildings#4009]
Hi ! 
Regarding electricEIR chillers,
I noticed that energyplus formulation of capFunT is 
 `capFunT = a + b (Tcw,l) + c(Tcw,l)^2 + d (Tcond,e) + e(Tcond,e)^2 + f (Tcw,l) (Tcond,e) `

Where the energy plus biquadratic formulation is
`y := a[1] + x1*(a[2] + a[3]*x1) + x2*(a[4] + a[5]*x2) + a[6]*x1*x2;`

I checked the PLR record ElectricEIRChiller_McQuay_WSC_471kW_5_89COP_Vanes
`      capFunT =             {2.521130E-01,1.324053E-02,-8.637329E-03,8.581056E-02,-4.261176E-03,8.661899E-03}`
https://github.com/lbl-srg/modelica-buildings/blob/55203c63f0de6e1a2a77383ef66834736fdfb15f/Buildings/Fluid/Chillers/Data/ElectricEIR.mo#L64C30-L64C109

And the energy plus record : 
```
    -4.862465E-01,           !- Coefficient1 Constant
    -7.293218E-02,           !- Coefficient2 x
    -8.514849E-03,           !- Coefficient3 x**2
    1.463106E-01,            !- Coefficient4 y
    -4.474066E-03,           !- Coefficient5 y**2
    9.813408E-03,            !- Coefficient6 x*y
```
https://github.com/NREL/EnergyPlus/blob/80732bf0a8a545891d2b4a4fdc316bbccf658d28/datasets/Chillers.idf#L13678-L13686`

I find strange that those have the same coefficient while the biqudratic formulation is different. 

Can I use the curvefitTool from energyplus with this lib ? 

Thanks

**Comment by mwetter** [comment]
@TeoGoddet : The two polynomials `capFunT` and `y` are the same if you multiply the coefficients in `y`. Why do you think the biquadratic formulation is different?

**Comment by TeoGoddet** [comment]
Hi @mwetter !
I misread the equations
I'm very sorry for the noise !
