### ISSUE TITLE
problem Dymola with IDEAS-3.0/ReaderTMY3

### ISSUE THREAD

**Issue by jagica** [lbl-srg/modelica-buildings#4012]
**Describe the bug**
the reader failed to open weather file

**To Reproduce**
1. Open model  IDEAS/Fluid/example/SimpleHouse in Dymola 
2.  check model
3. See error : Not possible to open file "C:/Users/jacqu/Documents/Dymola/Library/IDEAS-3.0/IDEAS/modelica:/IDEAS/Resources/weatherdata/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.mos" for reading:
Invalid argument

**Expected behavior**
no problem to open and read the weather file

**Screenshots**

**Version**
 - Modelica Buildings Library: [version or commit] IDEAS-3.0
 - Modelica simulation environment  Modelica standard library 4.0
 - Operating system : win10

**Additional context**

**Comment by mwetter** [comment]
This issue is for a model from the IDEAS library. So please report to the IDEAS library team, not the Buildings library.

**Comment by jagica** [comment]
The issue is mainly with an example of the modelica library....the problem with IDEAS is simply reported because it is similar...
________________________________
