### ISSUE TITLE
allowFlowReversal in storageTanks

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/modelica-buildings#402]
Parameter ```allowFlowReversal``` is not propagated in the storageTank models.

**Comment by Mathadon** [comment]
An implementation is on https://github.com/Mathadon/modelica-buildings/tree/issue402_floRevStorTan

**Comment by mwetter** [comment]
@Mathadon The propagation is good. I was not aware of it. Will review in the next days. I made a new branch `issue402_floRevStorTan` to pull in your changes.

I have not seen your problem with the unit tests before. They worked for me yesterday. Do you have `.mos` files somewhere in your `Buildings` directory that are not part of the library and declare ` resultFile="Obsolete"`?

**Comment by Mathadon** [comment]
I removed the folder ```Rescources/Scripts/Dymola/Obsolete``` and then they run fine. In these folder there are a lot of scripts generating files with names ```Obsolete.modelName``` possibly the name gets interpreted wrong on my machine. Maybe because I'm running an older version of buildingspy?

**Comment by Mathadon** [comment]
I updated buildingspy, this fixed the issue.
