### ISSUE TITLE
a problem of room

### ISSUE THREAD

**Issue by wuxu123** [lbl-srg/modelica-buildings#405]
when i add a room into my model, everything is ok. However, when i set it true for shade of window, two errors come out. I modify the baseclass in the building and make it successful for shade. The same problem come when i add the baseclass into my model.

**Comment by mwetter** [comment]
See https://github.com/lbl-srg/modelica-buildings/issues/387 for instructions for how and where to pose questions in a way that others can help. This issue tracker is not a forum to answer questions.
