### ISSUE TITLE
Model Buildings.ThermalZones.EnergyPlus_24_2_0.Examples.SmallOffice.IdealHeatingCoolingSpring fails the simulation due to the coarse tolerance

### ISSUE THREAD

**Issue by AndreaBartolini** [lbl-srg/modelica-buildings#4063]
The model `Buildings.ThermalZones.EnergyPlus_24_2_0.Examples.SmallOffice.IdealHeatingCoolingSpring` fails the simulation in the CI because the default tolerance (`1e-6`) seems to be coarse in omc.

Detailed analysis is reported in https://github.com/OpenModelica/OpenModelica/issues/13281

Note that the transient of the temperature `flo.att.vol.medium.T` that triggers the assert that stop the simulation shows some high-frequency numerical oscillations at the beginning of the transient, also in Dymola.
These oscillations are not physical and could be originated by a not perfect initialization that should be investigated by the modeler.

**Comment by AndreaBartolini** [comment]
the same analysis is applicable to the model `Buildings.ThermalZones.EnergyPlus_24_2_0.Examples.SmallOffice.IdealHeatingCoolingSummer`

**Comment by AndreaBartolini** [comment]
keep @casella in the loop

**Comment by AndreaBartolini** [comment]
> what is a reasonable value of the tolerance that guarantees smooth solver behaviour? Would you mind opening a ticket on the Builings repo about that?

The value is 1e-7 (see https://github.com/OpenModelica/OpenModelica/issues/13281), this is the the building repo...

**Comment by mwetter** [comment]
@JayHuLBL : Can you please change the tolerance in the .mo file for
`Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.IdealHeating*` and for 
`Buildings.ThermalZones.EnergyPlus_24_2_0.Examples.SmallOffice.IdealHeating*` to 1E-7.

Also please back-port the changes on `Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.IdealHeating*`  to the `maint_11.x` and `maint_10.0.x`.

**Comment by JayHuLBL** [comment]
@mwetter Will do it
