### ISSUE TITLE
Modelica-Buildings Library (master): Simulation successful in both Ubuntu as well as Windows. Simulation terminated by initialization error displayed only in Log File

### ISSUE THREAD

**Issue by NehaSPatwardhan** [lbl-srg/modelica-buildings#4071]
### Description

Simulation is running successfully in both Ubuntu as well as Windows. Simulation terminated by initialization error is displayed only in Log File.
The given model is having this issue:
```
Buildings.DHC.ETS.Cooling.Examples.Indirect
```
The log report of the model is given below:
https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.DHC.ETS.Cooling.Examples.Indirect.sim
```
LOG_ASSERT        | error   | [/home/hudson/saved_omc/libraries/.openmodelica/libraries/Buildings 12.0.0-master/Media/Water.mo:66:5-67:122:writable]
|                 | |       | The following assertion has been violated during initialization at time 0.000000
|                 | |       | ((noEvent(loa.vol.dynBal.medium.T <= 403.15))) --> "In Indirect.loa.vol.dynBal.medium: Temperature T = 7156.93 K exceeded its maximum allowed value of 130 degC (403.15 Kelvin) as required from medium model "Buildings.Media.Water"."
LOG_ASSERT        | info    | simulation terminated by an assertion at initialization
```

The error report of the model is given below:
https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.DHC.ETS.Cooling.Examples.Indirect.err

### Steps to Reproduce

Load the Modelica-Buildings master library (Source: https://github.com/lbl-srg/modelica-buildings/)
Simulate the examples model present in  
Buildings.DHC.ETS.Cooling.Examples.Indirect

### Expected Behavior
Log Report should show successful simulation.

### Additional Context
Related tickets: #3416

### Version and OS

 - OpenModelica Version: OpenModelica 1.25.0~dev-152-g78d9a41
- OS: 11.1.0ubuntu4
- Windows 11 Version 23H2
 - Versions of used Modelica libraries:
Modelica 4.0.0
Buildings 12.0.0

**Comment by casella** [comment]
Wrong issue tracker, sorry 😅 

Please close this.
