### ISSUE TITLE
Error:export a  FMU from Dymola containing Spawn model      

### ISSUE THREAD

**Issue by sihuiren** [lbl-srg/modelica-buildings#4076]
**Describe the bug**
when i export a  FMU from Dymola containing Spawn model. 

~
i can simulate, but i can not export FMU
simulateModel("Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.AirHeating", stopTime=86400, tolerance=1e-06, resultFile="AirHeating");
 = true
translateModelFMU("Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.AirHeating annotation(experiment(StopTime=86400, Tolerance=1e-06, __Dymola_Algorithm=\"Dassl\"))", false, "", "2", "cs", false, 0, fill("",0));
 = ""
~

~
Error:
Compiler message:
Building FMU (Visual C++) 
64-bit mode activated. 
C:\Users\BIM\Documents\Dymola\DymosimDll64\ffd.dll
C:\Users\BIM\Documents\Dymola\DymosimDll64\fmilib_shared.dll
C:\Users\BIM\Documents\Dymola\DymosimDll64\ModelicaBuildingsEnergyPlus_9_6_0.dll
C:\Users\BIM\Documents\Dymola\DymosimDll64\ModelicaBuildingsPython3.6.dll
C:\Users\BIM\Documents\Dymola\DymosimDll64\ModelicaBuildingsPython_3_8.dll
C:\Users\BIM\Documents\Dymola\DymosimDll64\python3.6.dll
C:\Users\BIM\Documents\Dymola\DymosimDll64\python3.8.dll
C:\Users\BIM\Documents\Dymola\DymosimDll64\VCRUNTIME140.dll
ƶ 8 ļ
Compiling the model (Visual C++) with FMI. 

fmi2Functions.c
C:\Program Files\Dymola 2023x\source\FMI\fmi2TypesPlatform.h(1): warning C4819: ļڵǰҳ(936)бʾַ뽫ļΪ Unicode ʽԷֹݶʧ
C:\Program Files\Dymola 2023x\source\FMI\fmi2FunctionTypes.h(1): warning C4819: ļڵǰҳ(936)бʾַ뽫ļΪ Unicode ʽԷֹݶʧ
C:\Program Files\Dymola 2023x\source\FMI\fmi2Functions.h(1): warning C4819: ļڵǰҳ(936)бʾַ뽫ļΪ Unicode ʽԷֹݶʧ
dsmodel.c
dsmodel.c(4438): warning C4244: : ӡdoubleתintܶʧ
dsmodel.c(4901): warning C4244: : ӡdoubleתintܶʧ
ɴ...
ڴ ~FMUOutput\binaries\win64\Buildings_ThermalZones_EnergyPlus_09_06_00_Examples_SingleFamilyHouse_AirHeating.lib Ͷ ~FMUOutput\binaries\win64\Buildings_ThermalZones_EnergyPlus_09_06_00_Examples_SingleFamilyHouse_AirHeating.exp
LINK : warning LNK4199: Ѻ /DELAYLOAD:fmilib_shared.dllδҵ4 fmilib_shared.dll ĵ
Compiling the model (Visual C++) with FMI. 

fmi2Functions.c
C:\Program Files\Dymola 2023x\source\FMI\fmi2TypesPlatform.h(1): warning C4819: ļڵǰҳ(936)бʾַ뽫ļΪ Unicode ʽԷֹݶʧ
C:\Program Files\Dymola 2023x\source\FMI\fmi2FunctionTypes.h(1): warning C4819: ļڵǰҳ(936)бʾַ뽫ļΪ Unicode ʽԷֹݶʧ
C:\Program Files\Dymola 2023x\source\FMI\fmi2Functions.h(1): warning C4819: ļڵǰҳ(936)бʾַ뽫ļΪ Unicode ʽԷֹݶʧ
dsmodel.c
C:\Users\BIM\Documents\Dymola\Buildings-v11.0.0\Buildings 11.0.0\Resources\C-Sources\EnergyPlus_9_6_0_Wrapper.h(27): fatal error C1189: #error: Modelica Spawn coupling is only supported for Windows and Linux 64 bit. Your operating system is not 64 bit.
ɴ...
LINK : fatal error LNK1181: ޷ļModelicaBuildingsEnergyPlus_9_6_0.lib

Error creating FMU zip.
~

**Version**
 - Modelica Buildings Library: 11.0
 - Modelica simulation environment: dymola2023
- Modelica 4.0
 - Operating system：windows11

**Comment by mwetter** [comment]
The translation works on my installation on Windows.
The reason is this line:
https://github.com/lbl-srg/modelica-buildings/blob/471527a7fcd1597480149d2023de155fb0acb451/Buildings/Resources/C-Sources/EnergyPlus_9_6_0_Wrapper.h#L26
It seems like you either have a 32 bit compilation, or your compiler does not set `_WIN64`, which is used here:
https://github.com/lbl-srg/modelica-buildings/blob/471527a7fcd1597480149d2023de155fb0acb451/Buildings/Resources/C-Sources/EnergyPlus_9_6_0_Wrapper.h#L10

So there seems to be something wrong with your compiler installation as this flag should be present:
https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170

**Comment by sihuiren** [comment]
Thanks for the help, what I finally realized was that I had both 32bit and 64bit checked in dymola's FMI export, and should have unchecked 32bit!
