### ISSUE TITLE
WetCoilCounterFlow fails in OpenModelica

### ISSUE THREAD

**Issue by FReuss** [lbl-srg/modelica-buildings#418]
Hello everyone,
I was trying to simulate the Buildings.HeatExchangers.Examples.WetCoilCounterFlowMassFlow in OpenModelica (version 1.9.2) but got the Error: "Class Medium2.enthalpyOfCondensingGas not found in Buildings.Fluid.HeatExchangers.WetCoilCounterFlow$hex.$foriter loop scope$ (looking for a function or record)". Since Medium2 = Buildings.Media.Air and the function enthalpyOfCondensingGas is defined in this Medium package OpenModelica should acually find it. Since I'm relatively new to OpenModelica I can not explain why this appears.  Am I the only one who has this problem?

**Comment by mwetter** [comment]
OpenModelica does not yet fully support the Buildings library. The problem you mention is known and shows up in the OpenModelica regression tests. OpenModelica still sees to have problems with some `Media` functions. 
I will therefore close the issue as I don't think there is anything we can fix for the `Buildings` library to make this work.
