### ISSUE TITLE
Buildings.Electrical.AC.ThreePhasesUnbalanced.Sensors.GeneralizedSensor model fails in OpenModelica

### ISSUE THREAD

**Issue by s-and** [lbl-srg/modelica-buildings#421]
Hi,
The GeneralizedSensor and the GeneralizedSensor_n models under ThreePhasesUnbalanced package of the Electrical package give the following error when I do  'check model' in OpenModelica.

"Error: Class .Buildings.Electrical.PhaseSystems.OnePhase not found in scope PhaseSystem.
[C:/......./Buildings/Electrical/AC/OnePhase/Interfaces/Terminal_n.mo:4:27-5:51:writable] Error: Class .Buildings.Electrical.PhaseSystems.OnePhase not found in scope PhaseSystem.
.....
 Error: Variable terminal_n.phase[1].PhaseSystem.n not found in scope Buildings.Electrical.AC.ThreePhasesUnbalanced.Sensors.GeneralizedSensor.
Error: Error occurred while flattening model Buildings.Electrical.AC.ThreePhasesUnbalanced.Sensors.GeneralizedSensor"

I have also realized that the corresponding example (Buildings.Electrical.AC.ThreePhasesUnbalanced.Sensors.Examples.Sensors) is not listed on recursive build model test page here: https://test.openmodelica.org/libraries/Buildings/BuildModelRecursive.html

Thanks.

**Comment by mbonvini** [comment]
The first problem may be related to the ability of OpenModelica to handle multiple levels of inheritance, I need to have a deeper look into the model to see what causes this issue.

Regarding the missing example, that is probably due to the fact that the package containing that specific example is not part of a folder but is part of a single .mo file.

**Comment by mwetter** [comment]
`Buildings.Electrical.AC.ThreePhasesUnbalanced.Sensors.Examples.Sensors` now works with OpenModelica.

**Comment by mwetter** [comment]
Closed ticket as https://github.com/lbl-srg/modelica-buildings/issues/488 will be to change `Examples.mo` to single files.
