### ISSUE TITLE
Temperature bound for solar collectors

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/modelica-buildings#429]
```Buildings.Fluid.SolarCollectors.BaseClasses.EN12975SolarGain``` contains a temperature bound for avoiding media going above its maximum temperature. The current model contains equation:

```
QSol_flow[i] = A_c/nSeg*(y_intercept*(iamBea*HDirTil*(1.0 - shaCoe_internal) + iamDiff *
  HSkyDifTil))*Buildings.Utilities.Math.Functions.smoothHeaviside((Medium.T_max+1)-TFlu[i],1);
```

this should be

```
QSol_flow[i] = A_c/nSeg*(y_intercept*(iamBea*HDirTil*(1.0 - shaCoe_internal) + iamDiff *
  HSkyDifTil))*Buildings.Utilities.Math.Functions.smoothHeaviside((Medium.T_max-1)-TFlu[i],1);
```

(notice the minus).

I'll make a pull request.

**Comment by mwetter** [comment]
The suggested change is correct. I will run regression tests.

**Comment by mwetter** [comment]
This is now on the master
