### ISSUE TITLE
m_flow_nominal and dp_nominal are fixed at compile time

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#441]
A user reports that in `Buildings.Fluid.FixedResistances.Pipe`, when exported as an FMU, the pipe length and diameter cannot be changed anymore.

Similarly, for `FixedResistanceDpM`, the parameters `m_flow_nominal` and `dp_nominal` are fixed at compile time.

**Comment by mwetter** [comment]
In `FixedResistanceDpM`, `m_flow_nominal` and `dp_nominal` could be changed if they are not used to set the nominal attribute of the pressure and mass flow rate, and if `dp_nominal` is not used in the structural parameter `computeFlowResistance`. 
However, the latter is done for efficiency reason as it removes the pressure drop equations if a user sets `dp_nominal=0`.

For `Pipe`, the diameter and length cannot be changed because they are used to assign the parameter `vol.V` in `BaseClasses.Pipe`, which is then used in `ConservationEquation` in the assignment
```
  // Parameter for avoiding extra overhead calculations when CSen==0
  final parameter Boolean computeCSen = CSen > Modelica.Constants.eps
    annotation(Evaluate=true);
```
Again, for efficiency reason, we set `Evaluate=true` as this parameter affects the structure of the equations.

Also, the default assignment for `diameter` in the pipe model would need to be removed, or overwritten when exporting the model as an FMU, so that it can be changed later.

Therefore, allowing `m_flow_nominal`, `dp_nominal`, `diameter` and `length` to be changed after compilation likely affects the efficiency and also the solvers as they can no longer be used to set the nominal values.

**Comment by Habib-mezghani** [comment]
Thank you for this explanation. :+1:
