### ISSUE TITLE
Wrong assert statement check in Buildings.Fluid.FMI.FlowSplitter_u

### ISSUE THREAD

**Issue by tsnouidui** [lbl-srg/modelica-buildings#442]
Assert should check whether the flow difference is < not > than 1E-2 * mAve_flow_nominal
 assert(abs(inlet.m_flow-sum(outlet.m_flow)) > 1E-2 * mAve_flow_nominal,
    "Mass flow rate is not conserved.
  inlet.m_flow       = " + String(inlet.m_flow) + "
  sum(outlet.m_flow) = " + String(sum(outlet.m_flow)));

**Comment by mwetter** [comment]
This is now on the master.
