### ISSUE TITLE
Protected parameter in Storage

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/modelica-buildings#454]
`Buildings.Fluid.HeatExchangers.BaseClasses.HACoilInside` contains a parameter for disabling the temperature dependence of the correlation. This is useful since it allows breaking algebraic loops. However the component is protected in `Buildings.Fluid.Storage.BaseClasses.IndirectTankHeatExchanger` and the parameter is not propagated. Therefore I cannot change the parameter without generating a warning in Dymola.

Can we either propagate the parameter or make the component public?

**Comment by mwetter** [comment]
@Mathadon : I suggest you propagate the parameters `flowDependent` and `temperatureDependent`  and make a pull request

**Comment by mwetter** [comment]
@Mathadon : Is this still an issue or can this be closed?

**Comment by Mathadon** [comment]
thanks for reminding me!

**Comment by mwetter** [comment]
This is now on the master. Thanks for the changes!
