### ISSUE TITLE
DocumentationClass considered invalid?

### ISSUE THREAD

**Issue by tbeu** [lbl-srg/modelica-buildings#456]
Why does checkRelease.py consider DocumentationClass as invalid? It is standard conform as of MLS 3.2rev2.

**Comment by mwetter** [comment]
You are right that it conforms to Modelica 3.2rev2, but it is no longer present in Modelica 3.3. Hence, we updated the library to no longer use it in order to avoid future incompatibilities.

**Comment by tbeu** [comment]
Hm, I still can see it in MLS 3.3rev1 18.2.

**Comment by mwetter** [comment]
I now see that it has been removed in MLS 3.3, but added back to 3.3 revision 1.1. 

We could remove this check if you need it. The way classes with only documentation are handled in the Buildings library is shown in https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Fluid/package.mo

**Comment by tbeu** [comment]
I only noticed that checkRelease.py errors with DocumentationClass on many other libraries. If you consider it useful to not have DocumentationClass in your libs then just leave it as it is. Otherwise you also can remove it since it is standardized. Thus it is up to you.
