### ISSUE TITLE
pVSimple DC component and conACDC component don't work togheter. why?

### ISSUE THREAD

**Issue by nanoride** [lbl-srg/modelica-buildings#461]
model storage 
  Modelica.Blocks.Math.Abs abs1(generateEvent = false) annotation(Placement(transformation(extent = {{-10, -10}, {10, 10}}, rotation = -90, origin = {74, 6}))); 
  Modelica.Blocks.Sources.Sine sine(amplitude = 1000, freqHz = 0.000015704, phase = 0, offset = 0, startTime = 0) annotation(Placement(transformation(extent = {{38, 48}, {58, 68}}))); 
  Buildings.Electrical.DC.Sources.PVSimple pVSimple1(V_nominal = 400, A = 200, fAct = 0.9, eta = 0.12) annotation(Placement(visible = true, transformation(origin = {70, -64}, extent = {{-10, -10}, {10, 10}}, rotation = 0))); 
  Buildings.Electrical.AC.ThreePhasesBalanced.Sources.Grid gri(f = 50, V = 400, phiSou = 0.1) annotation(Placement(visible = true, transformation(origin = {-76, -16}, extent = {{-10, -10}, {10, 10}}, rotation = 0))); 
  Buildings.Electrical.AC.ThreePhasesBalanced.Conversion.ACDCConverter conACDC(conversionFactor = 1, eta = 0.9) annotation(Placement(visible = true, transformation(origin = {0, -54}, extent = {{-10, -10}, {10, 10}}, rotation = 0))); 
equation 
  connect(abs1.y, pVSimple1.G) annotation(Line(points = {{74, -5}, {70, -5}, {70, -52}, {70, -52}}, color = {0, 0, 127})); 
  connect(sine.y, abs1.u) annotation(Line(points = {{59, 58}, {74, 58}, {74, 20}, {74, 20}}, color = {0, 0, 127})); 
  connect(conACDC.terminal_n, gri.terminal) annotation(Line(points = {{-10, -54}, {-38, -54}, {-38, -78}, {-76, -78}, {-76, -26}}, color = {0, 120, 120})); 
  connect(conACDC.terminal_p, pVSimple1.terminal) annotation(Line(points = {{10, -54}, {36, -54}, {36, -64}, {60, -64}}, color = {0, 0, 255})); 
end storage; 

this model gives error: 

" Translation Error 
Error occurred while flattening model storage 

Translation Error 
[Buildings.Electrical.Interfaces.Terminal: 7:1-7:54]: Could not evaluate structural parameter (or constant): PhaseSystem.n which gives dimensions of array: v[PhaseSystem.n]. Array dimensions must be known at compile time. 

the error is in the line 7 (the last) of this script  : 

connector Terminal "Generalized electric terminal" 
  extends Buildings.Electrical.Interfaces.BaseTerminal; 
  replaceable package PhaseSystem = PhaseSystems.PartialPhaseSystem "Phase system" annotation(choicesAllMatching = true); 
  PhaseSystem.Voltage v[PhaseSystem.n] "Voltage vector"; 
  flow PhaseSystem.Current i[PhaseSystem.n] "Current vector"; 
  PhaseSystem.ReferenceAngle theta[PhaseSystem.m] "Optional vector of phase angles"; 

the model picture
![foto1](https://cloud.githubusercontent.com/assets/14937454/10241897/1c4ef7a6-68ed-11e5-856f-75aec80e5a83.JPG)

the link to the error line 7
![cattura](https://cloud.githubusercontent.com/assets/14937454/10241940/56644018-68ed-11e5-8b77-50f34d342d0f.JPG)

**Comment by mwetter** [comment]
@nanoride : Thanks for reporting. OpenModelica has problems with determining the array size of certain modeling constructs. This is also reported in the OpenModelica regression tests, for example at  https://test.openmodelica.org/libraries/Buildings/files/Buildings.Electrical.AC.ThreePhasesBalanced.Sources.Examples.PVPanels.err.
I don't think there is anything we can do in the `Buildings` library to avoid this problem and I therefore close the ticket.

**Comment by nanoride** [comment]
thank you Michael

**Comment by nanoride** [comment]
Hello Michael, there is a good news. I downloaded the 1.9.4 nightly build openmodelica version and this model work good! This model and other models that use PV panel and inverter
