### ISSUE TITLE
Changed extractor implementation for increased robustness in pumps

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/modelica-buildings#472]
I recently came across an issue where that the `extractor` block implementation seems to be malfunctioning:

![screen shot 2015-12-07 at 10 35 24](https://cloud.githubusercontent.com/assets/5970879/11651647/6caf1a00-9db8-11e5-8a14-6fbe4f8d62cc.png)

As you can see the `k[2]` value changes even though the `index` input does not change. Also the initialisation is wrong. It's difficult to get a simple example to reproduce this so in the meantime I'd like to propose a new implementation of `extractor` that does not rely on the `when change(index)` construct. Hopefully I can afterwards make a bug report a dymola or MSL.

I'll make a pull request.

**Comment by mwetter** [comment]
@Mathadon It probably is best to implement your work-around as a protected block inside the model that uses the extractor. This way, no other model can use it and hence we can remove it from the library when it is fixed in dymola without causing backward incompatibility.

**Comment by Mathadon** [comment]
Will fix this in A60
