### ISSUE TITLE
Temperature sensors in storage tank

### ISSUE THREAD

**Issue by rubenbaetens** [lbl-srg/modelica-buildings#478]
The current `Buildings.Fluid.Storage.Stratified` model (and its variants) for a storage tank contains enthalpy flow sensors but no temperature sensors, which are generalled used for control purposes.

The (only?) way to retrieve water temperatures from the current model is to connect a `Modelica.Thermal.HeatTransfer.Sensors.TemperatureSensor` to the `heaPorVol` of the tank model. Would it be benefitial to include a `Buildings.Fluid.Sensors.TemperatureTwoPort` or maybe even `Buildings.Fluid.Sensors.TemperatureTwoPort[nSeg]` in the tank model ?

**Comment by mwetter** [comment]
The most efficient way is to connect a temperature sensor to `heaPorVol` as this exposes directly the state variable.

Using `Buildings.Fluid.Sensors.TemperatureTwoPort[nSeg]` would be bad. If they are configured as steady state, then they trigger events when flow reverses. If they are configured as dynamic, then you get additional (fast) states. In either way, near flow reversal, their output changes quickly to the incoming fluid, which then rapidly changes the control signal. Hence, it is better to connect to the volume directly, as is done by using `heaPorVol`.

The enthalpy flow sensors are added as they are used in the stratification model (see `StratifiedEnhanced`).

Please close the ticket if this answers your question.

**Comment by rubenbaetens** [comment]
Ok, Thx Michael, i'll stick to the `heaPorVol` then.
