### ISSUE TITLE
verify 64 bit compatibility

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#485]
Verify that all C code is 64 bit compatible, in particular also `externalObjectStructure.h`, `exchangeValues.h` and the cfd interface.

**Comment by mwetter** [comment]
According to the Modelica Specification, 

> Unless an explicit function call is present in the external declaration, an array is passed by its address followed by n arguments of type size_t with the corresponding array dimension sizes, where n is the number of dimensions.

**Comment by mwetter** [comment]
@zuowangda 

Can you please verify the following:
- [ ] why is there in `Buildings/Resources/C-Sources/cfdCosimulation.h` a single line
```
#pragma comment(lib, "user32.lib")
```
Isn't there a similar statement missing for 64 bit? Does the code work if compiled on Windows on 64 bit?

- [ ] Can you please run for the branch `issue485_64bit` the regression tests for 32 and 64 bit on Windows and on Linux? On Linux, I get very different results when simulated with 64 bit, even before my changes (using the files from the `master` branch). The figure below shows the results for the `NaturalConvectionWithControl` test case with 32 and 64 bit on Linux. The reference results in `Resources/ReferenceResults` were generated with Linux 32 bit, and correspond to the results that you validated originally. So I think there is a bug in your 64 bit implementation. I suggest you make sure all array sizes use `size_t` consistently rather than `int`. You can switch to 64 bit using `Advanced.CompileWith64=2;` (and back to 32 bit with `Advanced.CompileWith64=1;`)

<img width="294" alt="naturalconvectionwithcontrol" src="https://cloud.githubusercontent.com/assets/1329080/13242937/e101d1b8-d9ae-11e5-92a4-a67f6d99fb6c.png">

**Comment by mwetter** [comment]
The package `Buildings.Fluid.HeatExchangers.Boreholes` works on Linux 32 and 64 bit.

**Comment by tianwei1989** [comment]
Hi Michael,

I am Wei Tian, Dr. Zuo's student. I am following up the issue.

**Comment by mwetter** [comment]
@tianwei1989 I am using Dymola 2016 FD01, but I think the problem should be visible also with Dymola 2016.

**Comment by tianwei1989** [comment]
@mwetter @zuowangda Hi Michael, thank you. I am upgrading my Dymola to 2016 version.

**Comment by tianwei1989** [comment]
@mwetter @zuowangda  Hi Michael I recompiled the 64 bit .so for FFD and they results are identical with 32 bit ones. Attached is my result. Since now I had some trouble with my buildingspy, I will run a unit test for all CFD examples to see if the results change or not after choose 64 bit. 
![results](https://cloud.githubusercontent.com/assets/5844451/13338835/0edea468-dbf2-11e5-9772-8771e6bb3d52.png)
