### ISSUE TITLE
add model to couple a Modelica HVAC system to the Spawn of EnergyPlus

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#505]
This issue is for adding a model that allows coupling a whole HVAC system to EnergyPlus for co-simulation in which both tools use FMI for model exchange and the time integration is done by a master algorithm.

**Comment by mwetter** [comment]
Todo:
- [ ] Add example of HVAC that serves multiple zones.
- [ ] Add a container `ThermalZonesConvective` which is similar to `ThermalZoneConvective` but allows for multiple thermal zones. Also add example for FMU export.

**Comment by tsnouidui** [comment]
I just added a more realistic HVAC and room model example. I also updated the reference result of the unit test.

**Comment by tsnouidui** [comment]
@mwetter: Actually, I think, we shouldn't have any `Convective` in the name of the ThermalZone export container right? The name should be `Buildings.Fluid.FMI.ExportContainers.Examples.FMUs.ThermalZone` not `Buildings.Fluid.FMI.ExportContainers.Examples.FMUs.ThermalZoneConvective`.
