### ISSUE TITLE
Potential issue with the Buildings.Examples.VAVReheat.Controls.Economizer.yOATFre object

### ISSUE THREAD

**Issue by wqp89324** [lbl-srg/modelica-buildings#511]
The output of Buildings.Examples.VAVReheat.Controls.Economizer asks the economizer to fully close when there is no freezing concern on a summer day, despite of minimum fresh air requirement. The issue may be caused by the Buildings.Examples.VAVReheat.Controls.Economizer.yOATFre object.

**Comment by mwetter** [comment]
@wqp89324 : Can you please state at what time in the simulation this occurs.

**Comment by wqp89324** [comment]
Try Atlanta weather with the following simulation parameters:
experiment(
      StartTime=1.56384e+007,
      StopTime=1.57248e+007,
      Interval=60,
      Tolerance=1e-006)

**Comment by mwetter** [comment]
@wqp89324 
The problem is that in the economizer control, the controller `yOATFre` changes its gain. I will replace this with a normal `PI` controller as the gain reversal is not needed for the freeze protection.
