### ISSUE TITLE
Unmatched dimensions in Buildings.Fluid.Storage.StratifiedEnhancedInternalHex

### ISSUE THREAD

**Issue by rubenbaetens** [lbl-srg/modelica-buildings#531]
When using `Buildings.Fluid.Storage.StratifiedEnhancedInternalHex` i constantly get errors for the connection of the internal hex to the tank. e.g.
```
  Buildings.Fluid.Storage.StratifiedEnhancedInternalHex tan(hTan=1.2, hHex_a=0.1, hHex_b=0.3, nSeg=12, hexSegMult=2)
```
gives
```
Unmatched dimension in connect(tan.indTanHex.port[5], tan.heaPorVol[13]);
Unmatched dimension in connect(tan.indTanHex.port[6], tan.heaPorVol[13]);
```
but at first sight i can't figure out the error.

**Comment by rubenbaetens** [comment]
Note, the error only occurs when `nSegHexTan > 1`.

**Comment by mwetter** [comment]
@rubenbaetens 
The problem occurs because the loop that connects the heat exchanger and the fluid volumes in incremented in the wrong direction if `hHex_a < hHex_b`.
I will correct it for the next release.
