### ISSUE TITLE
MSVCR100D.dll missing in Buildings.Rooms.CFD

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#537]
A user reports 

> I'm trying to run some of the examples, specifically ForcedConvection and ForcedConvectionWithControl.  The models compile without error or warning, but they fail to run.  I get an error that MSVCR100D.dll is missing when I try to simulate.  I'm using Dymola 2016, released 2015-04-15.  I get a warning when I first load the buildings library.  It says that the library uses Dymola  3.3.2 but I am running 3.3.1.  Not sure if this is a problem.  I tell it to use the version found.  I'm running Windows 7, 64 bit.  

@zuowangda : Do you know this problem, and are there dependencies that are not shipped?

**Comment by tianwei1989** [comment]
@mwetter @zuowangda Hi Dr. Wetter, I will look into this problem.

**Comment by tianwei1989** [comment]
@mwetter @zuowangda Hi Dr. Wetter, according to my investigation, the user's computer misses MSVCR100D.dll in the path: **_C:\Windows\SysWOW64_**. I think downloading one from online and put it in the designated path above can solve the problem. 
The reason that the missing file is needed is that we compiled the FFD codes in Debug mode. If  the FFD codes were compiled in Release mode, and his/her computer has MSVCR100.dll (note absence of "D" ) in the path , then the coupled simulation should run normally.

**Comment by tianwei1989** [comment]
@mwetter Since MSVCR100D.dll belongs to C run-time library (CRT), I personally think it shouldn't be shipped by us as the dependency.

**Comment by mwetter** [comment]
@tianwei1989 Thanks for diagnosing it. Could you please recompile the code without the debug option and issue a pull request against the branch `issue537_ffd_dll` so that we can ship the dll without dependencies on debug versions of MSVCR100?

**Comment by tianwei1989** [comment]
Hi Dr. Wetter,

 

I can do that. After I complete the work, I will send you a pull request. 

 

Best,

Wei Tian

**Comment by mwetter** [comment]
Closed as this is now on the master.
