### ISSUE TITLE
Refactor to export weather resource file as FMU

### ISSUE THREAD

**Issue by tsnouidui** [lbl-srg/modelica-buildings#539]
This issue should refactor the weather data reader to allow the export of models which contain weather file as FMUs.

Todo:
- [ ] Add an example which uses loadResource at the top level of the model and export the model as an FMU.

**Comment by mwetter** [comment]
@tsnouidui : Please work on a branch `issue489_weatherFMU ` of the Annex 60 library as this makes merging easier.

**Comment by mwetter** [comment]
Reopened to test FMU export
