### ISSUE TITLE
Parameter modifications contain variables

### ISSUE THREAD

**Issue by eshmoylova** [lbl-srg/modelica-buildings#543]
Buildings.Rooms.Validation.BESTEST.Case900 and Buildings.Rooms.Validation.BESTEST.Case900FF modify matExtWal and matFlo while extending from Case600 and Case600FF. matExtWal and matFlo are defined as parameters in Case600FF. Case 600 extends 600FF so they are parameters there as well. However, the modifications in Case900 and Case900FF are of the form matExtWal = extWalCase900 and  matFlo = floorCase900, where the names in the right hand-sides are declared as variables.

According to Modelica Specification 3.2 Rev.1, Section 3.8:
"For an assignment v:=expr or binding equation v=expr, v must be declared to be at least as variable as expr."

Clases Case900 and Case900FF as well as any classes that extend them (Case920, Case940, Case950, Case950FF) are illegal.

**Comment by mwetter** [comment]
@eshmoylova 
Thanks for reporting. I agree that this violates the Modelica Language and will fix it.
