### ISSUE TITLE
Incompatible inherited class in Buildings.Fluid.Storage.Stratified

### ISSUE THREAD

**Issue by eshmoylova** [lbl-srg/modelica-buildings#544]
Model Buildings.Fluid.Storage.Stratified declares package Medium declares as:
  replaceable package Medium =
      Modelica.Media.Interfaces.PartialSimpleMedium;
The model extends  Buildings.Fluid.Interfaces.PartialTwoPortInterface, which also contains package Medium declared as:
  replaceable package Medium =
      Modelica.Media.Interfaces.PartialMedium....

Modelica.Media.Interfaces.PartialMedium has smaller number of components than       Modelica.Media.Interfaces.PartialSimpleMedium, which violates the requirement in Modelica Specification 3.2 Rev. 1, section 7.1:

  The declaration elements of the flattened base class shall either
* Not already exist in the partially flattened enclosing class [i.e., have different names] .
* The new element is a long form of redeclare or uses the ‘class extends A’ syntax, see Section 7.3.
* Be exactly identical to any element of the flattened enclosing class with the same name and the same level of protection (public or protected) and same contents. In this case, the first element in order (can be either inherited or local) is kept. It is recommended to give a warning for this case; unless it can be guaranteed that the identical contents will behave in the same way.

Any class that extends from Buildings.Fluid.Storage.Stratified (StratifiedEnhanced and StratifiedEnhancedInternalHex) is also illegal.

**Comment by mwetter** [comment]
@eshmoylova Thanks for reporting. I will correct it.
