### ISSUE TITLE
Incorrect Description for Generic Data Record

### ISSUE THREAD

**Issue by BradleyTran** [lbl-srg/modelica-buildings#545]
The descriptions for the nEIRFunT and nEIRFunPLR fields within the generic data record for the electric reformulatedEIR chiller appear to be incorrect. 
![screen shot 2016-07-21 at 16 26 26](https://cloud.githubusercontent.com/assets/19754187/17042111/eaeb5c5e-4f5f-11e6-93ba-016ad77db92e.png)

**Comment by mwetter** [comment]
@BradleyTran Thanks for reporting. I corrected it on the master branch.
