### ISSUE TITLE
Error in Buildings.Fluid.HeatExchangers.WetCoilCounterFlow

### ISSUE THREAD

**Issue by eshmoylova** [lbl-srg/modelica-buildings#547]
Buildings.Fluid.HeatExchangers.WetCoilCounterFlow uses Medium2.enthalpyOfCondensingGas. Medium2 is defined as Modelica.Media.Interfaces.PartialMedium, which does not contain enthalpyOfCondensingGas. To use enthalpyOfCondensingGas one needs to use (at least) Modelica.Media.Interfaces.PartialCondensingGases.

**Comment by mwetter** [comment]
@eshmoylova 
Thanks, I will fix 
```
Fluid/HeatExchangers/WetCoilCounterFlow.mo
Fluid/HeatExchangers/WetCoilDiscretized.mo
```
which both require `Medium2` to subclass `Modelica.Media.Interfaces.PartialCondensingGases`.
