### ISSUE TITLE
Small stylistic/convention issue in Controls.SetPoints.Table

### ISSUE THREAD

**Issue by eshmoylova** [lbl-srg/modelica-buildings#555]
In Controls.SetPoints.Table there is a parameter nCol, commented as "Number of columns."  It is used as the first dimension of the two-dimensional array offsetVector, which in itself is a confusing name. A two-dimensional array in Modelica is equivalent to a matrix. In a matrix the first dimension refers to the number of rows, and the second dimension refers to a number of columns. So it would be more correct to refer to nCol as nRow, number of rows.

**Comment by mwetter** [comment]
@eshmoylova 
Thanks for reporting. I will look at it next week when I am back in the office again.

**Comment by mwetter** [comment]
@eshmoylova . Thanks for the issue. This is now on the `master`
