### ISSUE TITLE
Orifice information update

### ISSUE THREAD

**Issue by tianwei1989** [lbl-srg/modelica-buildings#562]
Hi Michael,

I found that the documentation information of the Buildings.Airflow.Multizone.Orifice may need update. The value of m and k specified in the documentation is based on IP unit. If using SI unit, an coefficient of 2119/249^m needs be multiplied. By adding this information it may help avoid confusion.

Thanks,
Wei Tian

**Comment by mwetter** [comment]
Thanks for reporting. I will close this issue and instead open the issue https://github.com/iea-annex60/modelica-annex60/issues/546 so that we can address this upstream in the Annex 60 library.
