### ISSUE TITLE
In building model, add capacity at surface

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#565]
Adding the capacity at the surface rather than inside the material may lead to smaller systems of equations. This issue is to test this configuration.

**Comment by tsnouidui** [comment]
Todo:
- [ ] Remove fixme in `Buildings.HeatTransfer.Conduction.SingleLayer` model for production code.
- [ ] Review simulation results of models that have constructions. Setting states at surfaces of constructions is the default. This leads to a change in most of the reference results.
- [ ] Set the options to add states at surfaces of FLEXLAB models to false so the models can translate.
- [ ] Overwrite reference results and mos script of `Buildings.HeatTransfer.Conduction.Examples.ConductorInitialization`. The example was modified by Michael and is now different from the one on the master. 
- [ ] Add an example similar to `Buildings.ThermalZones.Detailed.Validation.TestConditionalConstructions.OnlyConstructionBoundary ` but with the states being set at the surfaces of the construction.

**Comment by tsnouidui** [comment]
Adding states at constructions' surfaces leads to smaller number of non-linear system of equations and faster simulation.

|  Test Cases                                                                                        |  Runtime Improvement [%]|  
|------------------------------------------------------------------------------------------|------------------------------------|
| Buildings.ThermalZones.Detailed.Validation.BESTEST.Case600FF | 40% faster                        |   
| Buildings.ThermalZones.Detailed.Validation.BESTEST.Case600     | 40                                      |   
| Buildings.Examples.VAVReheat.ClosedLoop                                    | 30                                      |   
| Buildings.Examples.HydronicHeating.TwoRoomsWithStorage         | 20                                      |  
| Buildings.Examples.DualFanDualDuct.ClosedLoop                          | 20                                      |
