### ISSUE TITLE
tow.FRWat0 not within bounds in Buildings.Fluid.HeatExchangers.CoolingTowers.Examples.YorkCalc

### ISSUE THREAD

**Issue by agnesramle** [lbl-srg/modelica-buildings#567]
There is no solution within the bounds (0,1) for tow.FRWat0 to the following system with the current values of tow.TApp_nominal, tow.TRan_nominal and tow.TAirInWB_nominal:

tow.TApp_nominal = Buildings.Fluid.HeatExchangers.CoolingTowers.Correlations.yorkCalc(tow.TRan_nominal, tow.TAirInWB_nominal, tow.FRWat0, 1)
  Computed variables: tow.FRWat0

tow.FRWat0}}} takes a value of 1.0093894 which is greater than 1.

**Comment by mwetter** [comment]
@agnesramle Thanks for reporting. The type was wrong as the variable should be allowed to take on values bigger than 1. The fix is now on the `master` branch.
