### ISSUE TITLE
tra.ada_n.terminals[j].i[k] missing start values in  Buildings.Electrical.AC.ThreePhasesUnbalanced.Conversion.Examples.TransformerDD

### ISSUE THREAD

**Issue by agnesramle** [lbl-srg/modelica-buildings#568]
All of these are iteration variables of the initialization problem when compiled with Jmodelica and as such need to get start values:

  tra.ada_n.terminals[1].i[1] ()
  tra.ada_n.terminals[1].i[2] ()
  tra.ada_n.terminals[2].i[1] ()
  tra.ada_n.terminals[2].i[2] ()
  tra.ada_n.terminals[3].i[1] ()
  tra.ada_n.terminals[3].i[2] ()

It concerns the model Buildings.Electrical.AC.ThreePhasesUnbalanced.Conversion.Examples.TransformerDD.

**Comment by agnesramle** [comment]
The same goes for

  sou.ada.terminals[2].i[1] ()
  sou.ada.terminals[2].i[2] ()
  sou.ada.terminals[3].i[1] ()
  sou.ada.terminals[3].i[2] ()
  sou.ada.terminals[1].i[1] ()
  sou.ada.terminals[1].i[2] ()

in the model Buildings.Electrical.AC.ThreePhasesUnbalanced.Conversion.Examples.TransformerStepUpYD.

**Comment by mwetter** [comment]
This has been fixed and is now on the `master` branch.
