### ISSUE TITLE
[JModelica.org] Illegal class access

### ISSUE THREAD

**Issue by jonathankampemodelon** [lbl-srg/modelica-buildings#570]
When compiling Buildings.Electrical.AC.ThreePhasesUnbalanced.Loads.Examples.Impedances, JModelica.org detects two illegal class accesses:

```
Error at line 27, column 65, in file '...\Buildings\Electrical\AC\ThreePhasesUnbalanced\Sensors\GeneralizedSensor.mo',
In component sen:
  Cannot find class or component declaration for PhaseSystem
Error at line 29, column 65, in file '...\Buildings\Electrical\AC\ThreePhasesUnbalanced\Sensors\GeneralizedSensor_N.mo',
In component sen_N:
  Cannot find class or component declaration for PhaseSystem
```

According to the modelica specification [MLS 3.3, 5.3.2 Composite Name Lookup], classes can not be accessed in components, with the exception of function calls. It seems ThreePhasesBalanced.GeneralizedSensor has a correct access:
`Modelica.Blocks.Interfaces.RealOutput S[PhaseSystems.OnePhase.n]` while ThreePhasesUnbalanced.GeneralizedSensor (and GeneralizedSensor_N)has not:
`Modelica.Blocks.Interfaces.RealOutput S[3,terminal_n.phase[1].PhaseSystem.n]`

Could you please fix this?

**Comment by mwetter** [comment]
Thanks for reporting. This is now fixed.
