### ISSUE TITLE
[JModelica.org] Modified component not in constraining class

### ISSUE THREAD

**Issue by jonathankampemodelon** [lbl-srg/modelica-buildings#571]
JModelica.org gives the following error when compiling `Buildings.Electrical.AC.OnePhase.Lines.Examples.ACLine`

```
Error: in file '...\Buildings\Electrical\AC\OnePhase\Lines\Line.mo':
Semantic error at line 14, column 5:
  Cannot find component declaration for mode
```

In the source file:
```
  replaceable TwoPortRL line(R=R/3,L=L/3) constrainedby
    Buildings.Electrical.Transmission.BaseClasses.PartialTwoPortRLC(
    useHeatPort=true,
    mode=modelMode,
    M=M,
    T_ref=T_ref) "Model of the line"
    annotation (Placement(transformation(extent={{-10,-10},{10,10}})));
```

It seems mode is a component in `TwoPortRL`  but not in the constraining class `PartialTwoPortRLC`. To be able to modify a component it needs to be in the constraining class.

Can you please fix this?

**Comment by mwetter** [comment]
Thanks for reporting. This is now fixed.
