### ISSUE TITLE
Asserts depedning on the state variables causes problem in Buildings.HeatTransfer.Examples.ConductorSingleLayerPCM

### ISSUE THREAD

**Issue by agnesramle** [lbl-srg/modelica-buildings#576]
There is a similar issue for Buildings.HeatTransfer.Examples.ConductorSingleLayerPCM  as reported in [​https://github.com/iea-annex60/modelica-annex60/issues/564] with a too tight assert that depends on the state variables. The assert makes the simulation in JModelica.org to fail.

**Comment by mwetter** [comment]
Thanks for reporting. This issue is now fixed.
