### ISSUE TITLE
[JModelica.org] Missing connections

### ISSUE THREAD

**Issue by jonathankampemodelon** [lbl-srg/modelica-buildings#577]
When compiling `Buildings.Fluid.MixingVolumes.Validation.BaseClasses.MoistureMixingConservation` in JModelica.org i get the following error message:

```
Error in flattened model:
  The system is structurally singular. The following varible(s) could not be matched to any equation:
     cheMasFra.u2
     cheMasFlo.u2
     cheSpeEnt.u2
```

When i look in the class definition for `MoistureMixingConservation` i see that the `Modelica.Blocks.Math.Add` components `cheMasFra`, `cheMasFlo`, and `cheSpeEnt` are all only connected to one component. The `Add` block have three components and one equation. It seems to me there is one connect or equation missing to make the model balanced.

Can you please fix this?

**Comment by mwetter** [comment]
@jonathankampemodelon Thanks for reporting.The model should have been declared `partial` and not contain an `experiment` annotation.  This is now fixed.
