### ISSUE TITLE
[JModelica.org] Overdetermined initial system in Buildings.Examples.ChillerPlant

### ISSUE THREAD

**Issue by jonsten** [lbl-srg/modelica-buildings#578]
I'm investigating an error in JModelica.org where we get errors that the initial system for the following models is overdetermined:
* Buildings.Examples.ChillerPlant.BaseClasses.Controls.Examples.BatteryControl
* Buildings.Examples.ChillerPlant.DataCenterRenewables
Digging further into the model I find that we have the following chain of equations:
```
pre(con.multiSwitch1.u[1:3]) = fill(false, 3); // Modelica\Blocks\Math.mo:810
con.off.active = true; // Modelica\StateGraph.mo:2197
pre(con.off.newActive) = pre(con.off.localActive); Modelica\StateGraph.mo:1998
con.off.active = con.off.localActive; // Modelica\StateGraph.mo:2199
con.off.localActive = pre(con.off.newActive); // Modelica\StateGraph.mo:2017
con.multiSwitch1.u[1] = con.off.active; // Buildings\Examples\ChillerPlant\BaseClasses\Controls\BatteryControl.mo:134
```
If we combine all the equations together we get the following:
```
true = con.off.active = con.off.localActive = pre(con.off.newActive) = pre(con.off.localActive) = pre(con.off.active) = pre(con.multiSwitch1.u[1]) = false
```
I'm guessing that it is the last equation that is the problem. Any thoughts?

**Comment by mwetter** [comment]
@jonsten : Thanks. The `con.off.active` connection needs to be removed. I fixed this in f137ddd1dc0de4acc8833c73f3fa3dbcd102721d

Both examples simulate now.
