### ISSUE TITLE
[JModelica.org] Overdetermined initial system in Buildings.ThermalZones.Detailed.Examples.FFD

### ISSUE THREAD

**Issue by jonsten** [lbl-srg/modelica-buildings#579]
I'm investigating a series of Models which all have similar errors related to overdetermined initial systems. The models in question are:
Buildings.ThermalZones.Detailed.Examples.FFD.ForcedConvection
Buildings.ThermalZones.Detailed.Examples.FFD.NaturalConvectionWithControl
Buildings.ThermalZones.Detailed.Examples.FFD.RoomOnlyConstructionBoundary
Buildings.ThermalZones.Detailed.Examples.FFD.RoomOnlyExteriorWallNoWindow
Buildings.ThermalZones.Detailed.Examples.FFD.RoomOnlySurfaceBoundary
Buildings.ThermalZones.Detailed.Examples.FFD.Tutorial.MixedConvection
Buildings.ThermalZones.Detailed.Examples.FFD.Tutorial.NaturalConvection
Buildings.ThermalZones.Detailed.Examples.FFD.WindowWithoutShade
Buildings.ThermalZones.Detailed.Examples.FFD.WindowWithShade

All of these models have one or more superfluous equation. Now it is really hard to tell whether this is an error in JModelica.org or if it is an modeling error, so I was hoping for some input from you.

Let's take Buildings.ThermalZones.Detailed.Examples.FFD.ForcedConvection for example. This model has one extra equation:
```
roo.air.cfd.u[11] = roo.air.cfd._uStart[11]
```
This equation is inserted due to roo.air.cfd.u beeing a continuous real equation with fixed set to true. According to the specification the variable should be equal to its start value in the initial system.

By following the variable/equation matchings from that equation I can gather the following related equations (based on the transformed Modelica model, e.g. alias elimination and other transformations has been done to the system):
```
Right hand side of origin equation:
    roo.air.cfd._uStart[11] = if roo.air.cfd.flaWri[11] <= 1 then roo.air.cfd.uStart[11] else roo.air.cfd.uStart[11] * roo.air.cfd.samplePeriod
        parameter Integer roo.air.cfd.flaWri[11] = 1
        roo.air.cfd.uStart[11] = roo.air.uStart[11]
            roo.air.uStart[11] = 0
Left hand side of origin equation:
    0.0 = roo.air.fluInt.p_start * (roo.air.cfd.u[10] + roo.air.cfd.u[11]) / roo.air.fluInt.m_start
    Solving for roo.air.cfd.u[11] gives us:
    roo.air.cfd.u[11] = - roo.air.cfd.u[10]
        roo.air.cfd.u[10] = bounIn.m_flow;
            parameter Modelica.SIunits.MassFlowRate bounIn.m_flow = 0.01
```
So as you see we get the following:
```
0 = roo.air.uStart[11] = roo.air.cfd.uStart[11] = roo.air.cfd._uStart[11] = roo.air.cfd.u[11] = - roo.air.cfd.u[10] = - bounIn.m_flow = - 0.01
```
The only conclusion that I can draw is that something is wrong. And it is similar for the other models (although in some cases we can conclude that some of the superfluous equations can be removed since the right- and left-hand sides are equal).

So my best guess is that roo.air.cfd.u should have fixed equal to false so that no extra equations are added. I made that change locally, it solves the problem for all models that I've tried. However, I have limited insights into the physics of these models and it is hard for me to determine how this affect the models. So what is your thoughts on this?

Oh, and since I've already done the work of back-solving to the original equations, here they are. It is on the same format as the big block above, but with all the alias equations and origin included:
```
Modelica.Blocks.Interfaces.RealInput roo.air.cfd.u[15](start = roo.air.cfd._uStart[1:15],each fixed = true) // binding exp Buildings/ThermalZones/Detailed/BaseClasses/CFDExchange.mo:40
Right:
    initial parameter Real roo.air.cfd._uStart[15] = {..., if roo.air.cfd.flaWri[11] <= 1 then roo.air.cfd.uStart[11] else roo.air.cfd.uStart[11] * roo.air.cfd.samplePeriod, ...} // binding exp Buildings/ThermalZones/Detailed/BaseClasses/CFDExchange.mo:55
        parameter Integer roo.air.cfd.flaWri[15] = ones(15) // binding exp Buildings/ThermalZones/Detailed/BaseClasses/CFDExchange.mo:19
        initial parameter Real roo.air.cfd.uStart[15] = roo.air.uStart[1:15] // binding exp Buildings/ThermalZones/Detailed/BaseClasses/CFDAirHeatMassBalance.mo:43
            roo.air.uStart[9 + 2] = 0 // equ in for equ Buildings/ThermalZones/Detailed/BaseClasses/CFDAirHeatMassBalance.mo:420
Left:
    roo.air.cfd.u[11] = roo.air.fluInt.m_flow[2]; // connect in for equ Buildings/ThermalZones/Detailed/BaseClasses/CFDAirHeatMassBalance.mo:744
    roo.air.fluInt.m_flow[2] = roo.air.fluInt.ports[2].m_flow // equ in for equ Buildings/ThermalZones/Detailed/BaseClasses/CFDFluidInterface.mo:170
    der(roo.air.fluInt.p) = roo.air.fluInt.p_start * sum(roo.air.fluInt.ports[1:2].m_flow) / roo.air.fluInt.m_start // equ in if equ Buildings/ThermalZones/Detailed/BaseClasses/CFDFluidInterface.mo:150
    roo.air.fluInt.m_flow[1] = roo.air.fluInt.ports[1].m_flow // equ in for equ Buildings/ThermalZones/Detailed/BaseClasses/CFDFluidInterface.mo:170
    roo.air.cfd.u[10] = roo.air.fluInt.m_flow[1]; // connect in for equ Buildings/ThermalZones/Detailed/BaseClasses/CFDAirHeatMassBalance.mo:744
        roo.air.cfd.u[10] = roo.air.fluInt.m_flow[1]; // connect in for equ Buildings/ThermalZones/Detailed/BaseClasses/CFDAirHeatMassBalance.mo:744
        roo.air.fluInt.m_flow[1] = roo.air.fluInt.ports[1].m_flow // equ in for equ Buildings/ThermalZones/Detailed/BaseClasses/CFDFluidInterface.mo:170
        roo.air.fluInt.ports[1].m_flow - roo.air.ports[1].m_flow = 0; // connect Buildings/ThermalZones/Detailed/BaseClasses/CFDAirHeatMassBalance.mo:731
        roo.air.ports[1].m_flow - roo.ports[1].m_flow = 0; // connect in for equ Buildings/ThermalZones/Detailed/BaseClasses/RoomHeatMassBalance.mo:671
        bounIn.ports[1].m_flow + roo.ports[1].m_flow = 0; // connect Buildings/ThermalZones/Detailed/Examples/FFD/ForcedConvection.mo:45
        sum(bounIn.ports[1:1].m_flow) = - bounIn.m_flow_in_internal // equ Buildings/Fluid/Sources/MassFlowSource_T.mo:83
        bounIn.m_flow_in_internal = bounIn.m_flow // equ in if Buildings/Fluid/Sources/MassFlowSource_T.mo:72
            parameter Modelica.SIunits.MassFlowRate bounIn.m_flow = 0.01 // Buildings/Fluid/Sources/MassFlowSource_T.mo:17
```

**Comment by mwetter** [comment]
@jonsten : Thanks for analyzing this problem. The initial conditions were indeed overdetermined. I corrected the model. Now, JModelica translates the model, but fails during compilation of the C code. I am not sure if this is because the C code that this model uses is not C89. This may be related to https://github.com/lbl-srg/modelica-buildings/issues/569

**Comment by jonsten** [comment]
Thank you for the quick response @mwetter . Indeed there seems to be some additionally problems with these models. Besides #569, there also seems to be some models which fail to a bug in [JModelica.org](https://trac.jmodelica.org/ticket/5224), we will resolve that one as soon as possible since it affects a lot of models.
