### ISSUE TITLE
[JModelica.org] GetAbsolutePath file URI

### ISSUE THREAD

**Issue by jonathankampemodelon** [lbl-srg/modelica-buildings#581]
In `Buildings.BoundaryConditions.WeatherData.BaseClasses.Examples.GetAbsolutePath` there is an indirect call (trough `Buildings.BoundaryConditions.WeatherData.BaseClasses.getAbsolutePath`) to loadResource(). The inputs are
```
   {"file://package.mo",
    "modelica://Buildings/package.mo",
    "package.mo"}
```

The second one seems fine to me. The third could work, if your current working directory contains a "package.mo". I don't think it is safe to assume that (me and our test servers don't).

The file URI seems a bit off. The format for file URIs is `file://<host>/<path>`. Where we omit the <host> part to get the localhost (file:///<path>. <path> should be an absolute path. Even if we did allow only two slashes and relative paths here we would still have the same issues as with the relative path described above.

I think the only safe input for a model/test like this is the modelica URI and that the others should be removed. What do you think?

**Comment by mwetter** [comment]
@jonathankampemodelon : I agree that the first and last test should be removed.

**Comment by mwetter** [comment]
@jonathankampemodelon : I removed the first and last test.
