### ISSUE TITLE
Wrong name in the Infiltration block in ElectroChromicWindow example

### ISSUE THREAD

**Issue by eshmoylova** [lbl-srg/modelica-buildings#582]
In the equations for Buildings.ThermalZones.Detailed.Examples.ElectroChromicWindow.Infiltration there is a variable x_pTphi. The variable is not declared in the declaration for the component. There is a declared variable x_pTphiValidation that is not used anywhere. Perhaps it was renamed but the equations were not updated.

**Comment by mwetter** [comment]
Thanks for reporting. We will remove the `Infiltration` block which is not needed and indeed has an error in one of the implementation. The error was not detected as the block is not instantiated by any model.

**Comment by mwetter** [comment]
@eshmoylova Thanks for reporting. This is now fixed on the `master` branch.
