### ISSUE TITLE
Missing start values transformer.ada3to3_p.terminals[1].i[1:2] in JModelica 

### ISSUE THREAD

**Issue by agnesramle** [lbl-srg/modelica-buildings#584]
In JModelica transformer.ada3to3_p.terminals[1].i[2] and transformer.ada3to3_p.terminals[2].i[1] are iteration varaibles of the initialization system. They are, however, not provided with any start values which makes JModelica end up with another solution. Could you please set start values on these?

This concerns the models:
Buildings.Electrical.AC.ThreePhasesUnbalanced.Validation.IEEETests.Test4NodesFeeder.BalancedStepDown.YD
Buildings.Electrical.AC.ThreePhasesUnbalanced.Validation.IEEETests.Test4NodesFeeder.BalancedStepUp.YD
Buildings.Electrical.AC.ThreePhasesUnbalanced.Validation.IEEETests.Test4NodesFeeder.UnbalancedStepDown.YD

**Comment by mwetter** [comment]
@agnesramle : It turns out that Dymola 2016 found the correct solution, but Dymola 2017, and hence the reference results, are at the wrong solution. I will set start values (and remove start values that were set to 0 as this is the default anyway).

**Comment by mwetter** [comment]
@agnesramle : I pushed a fix to the branch `issue574_jmodelica_verification` (and also to `issue510_refactorJModelica`). Please reopen the issue if there are still differences in some of the results.
