### ISSUE TITLE
[JModelica.org] Runtime evaluations of loadResource()

### ISSUE THREAD

**Issue by jonathankampemodelon** [lbl-srg/modelica-buildings#585]
When compiling `Buildings.Experimental.DistrictHeatingCooling.SubStations.VaporCompression.BaseClasses.Validation.GetPeakLoad` in JModelica.org we get the error 
```
Error: in file 'null':
Semantic error at line 0, column 0:
  Cannot generate code for loadResource() in function
```

Currently we have limited support for calling loadResource() from functions. It would be very hard to support this for modelica URIs. Would it be possible to update the getPeakLoad function to get the full path as an input?

In calls to getPeakLoad:
```
  parameter Modelica.SIunits.HeatFlowRate QCoo_flow=
    Buildings.Experimental.DistrictHeatingCooling.SubStations.VaporCompression.BaseClasses.getPeakLoad(
      string="#Peak space cooling load",
      filNam="modelica://Buildings/Resources/Data/Experimental/DistrictHeatingCooling/SubStations/VaporCompression/RefBldgLargeOfficeNew2004_7.1_5.0_3C_USA_CA_SAN_FRANCISCO.mos")
    "Peak heat flow rate";
```

The filNam argument could be altered:
```
filNam=Modelica.Utilities.Files.loadResource("modelica://Buildings/Resources/Data/Experimental/DistrictHeatingCooling/SubStations/VaporCompression/RefBldgLargeOfficeNew2004_7.1_5.0_3C_USA_CA_SAN_FRANCISCO.mos")
```
And the getAbsolutePath() in getPeakLoad() could be removed.

**Comment by mwetter** [comment]
@jonathankampemodelon : I refactored the models. They are not available on `issue574_jmodelica_verification` and on `issue510_refactorJModelica`.
