### ISSUE TITLE
Missing start values in Buildings.Electrical.AC.ThreePhasesUnbalanced.Validation.IEEETests.Test4NodesFeeder.UnbalancedStepDown.YY for JModelica

### ISSUE THREAD

**Issue by agnesramle** [lbl-srg/modelica-buildings#590]
With the fix to #584 there are now missing start values in Buildings.Electrical.AC.ThreePhasesUnbalanced.Validation.IEEETests.Test4NodesFeeder.UnbalancedStepDown.YY. 
Could start values be added to
  Iteration variable "line1.i1[1]" is missing start value!
  Iteration variable "line1.i1[2]" is missing start value!
  Iteration variable "line1.i2[1]" is missing start value!
  Iteration variable "line1.i2[2]" is missing start value!
  Iteration variable "line1.i3[1]" is missing start value!
  Iteration variable "line1.i3[2]" is missing start value!
  Iteration variable "line2.i2[1]" is missing start value!
  Iteration variable "line2.i2[2]" is missing start value!
  Iteration variable "line2.i3[1]" is missing start value!
  Iteration variable "line2.i3[2]" is missing start value!

This leads to problem with the initialization of the model.

**Comment by mwetter** [comment]
@agnesramle Thanks, the model now simulates with JModelica. I pushed the changes to `issue574_jmodelica_verification`.
