### ISSUE TITLE
add block h_TDryBulPhi

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#591]
A block that computes the enthalpy for given dry bulb temperature and relative humidity will be needed for the Control Description Language. It should be similar to the existing blocks `TDewPoi_pW` or `TWetBul_TDryBulPhi`.

**Comment by milicag** [comment]
@mwetter Did this get resolved or is there still a need for me to address it?

**Comment by mwetter** [comment]
@milicag : These are available already in `CDL.Psychrometics`.
