### ISSUE TITLE
Tolerance for Buildings.Fluid.FMI.ExportContainers.Validation.RoomHVAC

### ISSUE THREAD

**Issue by agnesramle** [lbl-srg/modelica-buildings#597]
JModelica needs a tolerance of 1e-7 to be able to simulate Buildings.Fluid.FMI.ExportContainers.Validation.RoomHVAC (current use is 1e-6). Would it be possible to add this as the tolerance in the experiment annotation of the model?

**Comment by mwetter** [comment]
Sure. @tsnouidui Can you please update this test as part of your refactoring. Please also fix it in the Annex60 repository.

**Comment by tsnouidui** [comment]
Sure.

**Comment by tsnouidui** [comment]
@agnesramle I just looked at the mo/mos file and saw that the tolerance was not specified. The model was using a tolerance of 1e-4 which is the default. I am not sure how you knew that it was 1e-6? I will change the model to use 1e-7 which seems to work with JModelica.

**Comment by tsnouidui** [comment]
@agnesramle I pushed the changes to `issue574_jmodelica_verification `and will close this issue.

**Comment by agnesramle** [comment]
@tsnouidui On the Jenkins for JModelica the tolerance 1e-6 was used. I think this is the default tolerance of the test environment there.
