### ISSUE TITLE
undefined reference to sleep on MinGW

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#600]
The JModelica compilation of the FFD models fail with
```
cfdReceiveFeedback.o:cfdReceiveFeedback.c:(.text+0x72): undefined reference to `sleep'
```

**Comment by tianwei1989** [comment]
@mwetter @tsnouidui I looked at the problems over the weekends. As far as I can see, the `sleep` function is necessary in the codes. Currently I am still working on this issue. Please allow me some more time and I will keep you posted. @zuowangda

**Comment by tsnouidui** [comment]
@tianwei1989 @zuowangda You should hold on to that as I believe to have found a solution to the issue. I will keep you posted if you need to change the code.

Thanks!

**Comment by tianwei1989** [comment]
@tsnouidui @mwetter implemented the `Sleep` in MinGW and I assumed that the implementation did not work well. I found another implementation online which is worthy being considered. I haven't tested yet. I will wait until being updated.
`void sleep(unsigned int mseconds)
{
    clock_t goal = mseconds + clock();
    while (goal > clock());
}`
