### ISSUE TITLE
[JModelica.org] Integer/Enum array index

### ISSUE THREAD

**Issue by jonathankampemodelon** [lbl-srg/modelica-buildings#602]
When declaring an array size as an integer any indices in uses need to be of the same integer type. When using an enumeration in the declaration the array can only be sliced using enumeration indices. In some models there are arrays declared with integer sizes that have uses using enumeration indices. The locations can be found in the error messages for 

[Buildings.Examples.DualFanDualDuct.ClosedLoop](https://jenkins.jmodelica.org/job/Buildings-Compliance-Simulate/lastSuccessfulBuild/artifact/diag/21136cf4_compile.html ) and [Buildings.Examples.VAVReheat.ClosedLoop](https://jenkins.jmodelica.org/job/Buildings-Compliance-Simulate/lastSuccessfulBuild/artifact/diag/807c3127_compile.html)

Could you please use the Integer operator to convert the enumeration values to Integers, or change the declaration to use the enumeration type?

**Comment by mwetter** [comment]
@jonathankampemodelon 
This is now fixed on the verification test branch and on the `master`.
