### ISSUE TITLE
[JModelica.org] Extra initial condition in validation test

### ISSUE THREAD

**Issue by jonsten** [lbl-srg/modelica-buildings#605]
We are seeing an error in the model Buildings.ThermalZones.Detailed.Validation.LBNL_71T.RoomB.ElectroChromicWindow that the initial system is over-determined. The problem seems to be related to the following initial equation:
roo.air.vol.dynBal.medium.T = roo.air.vol.dynBal.T_start
which is defined in Buildings.Fluid.Interfaces.ConservationEquation.mo line 178. I'm guessing that everything should work fine if roo.air.vol.dynBal.medium.T is selected as state, however it is not, at-least not in JModelica.org. Should it be? Currently, in roo.air.vol.dynBal we select two states, roo.air.vol.dynBal.m and a dynamic state set consisting of roo.air.vol.dynBal.medium.Xi[1], roo.air.vol.dynBal.hOut. The later seems incorrect. So what is good states for this model?

**Comment by mwetter** [comment]
@jonsten 
I fixed this problem and it now simulates with JModelica. It will be processed in https://github.com/lbl-srg/modelica-buildings/pull/607

The states should be `roo.air.vol.dynBal.{m, mXi[1], U}` and statically selected.
