### ISSUE TITLE
Comma separated csv file problemtic with indexed variables

### ISSUE THREAD

**Issue by agnesramle** [lbl-srg/modelica-buildings#613]
In order for the verification tool on the JModelica.org Jenkins to work for variables like winAbs.QAbsGlaUns_flow[1, 2], i.e. variables with indices included (due to the comma), the generated csv file cannot be comma separated. 

Could you change to use ';' instead?

**Comment by tsnouidui** [comment]
I changed the separator from  "," to ";". The converted .csv file will look like this

time; limPID.u_m; limPIDRev.y; limPID.y; limPID.u_s
0.0; 0.5; 1.; -1.; 1.
0.01; 0.5;  1.;  -1.;  1.
0.02; 0.5;  1.;  -1.;  1.
0.03; 0.5;  1.;  -1.;  1.
0.04; 0.5;  1.;  -1.;  1.
0.05; 0.5;  1.;  -1.;  1.

I push the changes on the verifification branch. I will do the same for the Annex60 branch. Please update csv compare accordingly.

**Comment by tsnouidui** [comment]
@agnesramle All Annex60 tests are failing verification https://jenkins.jmodelica.org/job/Annex60-Compliance-Simulate/lastSuccessfulBuild/artifact/diag/index.html. Did you set `csv-compare` to use `;` as delimiter?

**Comment by agnesramle** [comment]
@tsnouidui The JModelica Jenkins configuration is now updated. Thanks for the update!

**Comment by tsnouidui** [comment]
Thanks!
