### ISSUE TITLE
[JModelica.org] Incorrect stop time in experiment annotations

### ISSUE THREAD

**Issue by jonsten** [lbl-srg/modelica-buildings#619]
There are several models where the stop time in the experiment annotation contains an expression. This is not allowed according to the Modelica Specification  (Section 17.4), it may only be a literal value. Models in the question are:
* Buildings.BoundaryConditions.WeatherData.BaseClasses.Examples.ConvertTime
* Buildings.Fluid.Chillers.Examples.ElectricEIR
* Buildings.Fluid.Chillers.Examples.ElectricReformulatedEIR
* Buildings.Fluid.HeatExchangers.Ground.Boreholes.BaseClasses.Examples.BoreholeSegment
* Buildings.Fluid.HeatExchangers.Ground.Boreholes.Examples.UTube

**Comment by tsnouidui** [comment]
will look into those.

**Comment by tsnouidui** [comment]
These are now fixed and should be reflected in the next JModelica run.

**Comment by agnesramle** [comment]
Buildings.Fluid.Chillers.Examples.ElectricReformulatedEIR was only updated in the .mos script.

**Comment by tsnouidui** [comment]
I fixed it in in .mo as well.

**Comment by tsnouidui** [comment]
These are all fixed and on the master.
