### ISSUE TITLE
Issue with the LimPID block

### ISSUE THREAD

**Issue by wthomare** [lbl-srg/modelica-buildings#639]
Hello

For a few days I have this problem (see image) that appears when I use the LimPID block of the Buildings library. I replace them with the model of the library Modelica and everything works.
Does anyone know why?

![capture du 2017-01-27 09-43-50](https://cloud.githubusercontent.com/assets/18418835/22364960/4009e23c-e475-11e6-9516-a371130e245e.png)

**Comment by mwetter** [comment]
@wthomare I run `LimPID` in a test model as a P, PI and PID controller and don't see any issues. Could you isolate the problem?

**Comment by wthomare** [comment]
@mwetter No, I obtain the same result with different models and from different repositories of the buildings librairy.

**Comment by mwetter** [comment]
@wthomare No sure what you mean by "same results with different models". Is there a test case that you can share that reproduces the error (ideally a small model), or is the error caused by your system model?

**Comment by wthomare** [comment]
@mwetter By "same results" I mean same issue ^^. My models are available on https://github.com/locie/comis and the FBM.ElementaryBlocs.MixingCircuit_Tset should be a good example. Others in the AHUSystems sub-package are available too.

ps: just need to load a Buildings librairy with this librairy

**Comment by mwetter** [comment]
@wthomare 
`FBM.ElementaryBlocs.MixingCircuit_Tset ` has no boundary conditions set, this is not an executable model.
`FBM.AHUSystems.Examples.VAVReheat` simulates. I therefore don't think there is an issue. If you have a model that does not work, then please send instructions for how to reproduce it, ideally based on a small test case, and reopen this issue.
