### ISSUE TITLE
add parameters for control point and tagging

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#647]
In CDL, we should be able to generate a list of control points, and also tag control blocks. This issue is to design and provide an implementation for control points and tags.

**Comment by ChristianTremblay** [comment]
I don't know if it's relevant for your project directly but regarding control point tagging, you should have a look to www.project-haystack.org
It is an open source project driven by a community of building specialists trying to build a common dictionnary of tags for building controls.

There are actually different implementation available : 

- Haystack Java Toolkit: light weight J2ME compliant client and server implementation
- NHaystack: Niagara module to add Haystack tagging and REST API
- Haystack CPP: C++ Haystack client and server implementation
- Haystack Dart: client library for Dart programming language
- NodeHaystack: node.js client/server implemtnation
- PyHaystack: Python toolkit

(I'm core contributor to pyhaystack (https://github.com/ChristianTremblay/pyhaystack))

It would allow your project  to connect directly to live equipment running haystack server (Tridium Niagara, SkySpark, WideSky...) for the commissionning part.

Finding consensual for control points tagging is a long and hard task that project-haystack has done for years now. I'm pretty sure it could help you, starting with something widely accepted among hvac integrator, contractor, etc.

**Comment by mwetter** [comment]
@ChristianTremblay : Thanks for your input. We certainly look at Project Haystack as a source to populate the tags in our control sequence representations (and don't intent to come up with another tagging scheme).
