### ISSUE TITLE
[Question] Using modelica-building models in a python app

### ISSUE THREAD

**Issue by ChristianTremblay** [lbl-srg/modelica-buildings#648]
I'm actually working on a project allowing DDC programmers to test their sequence.
Project targets BACnet controllers actually and is developed using Python 3.

> Context : 
> I'm using a proprietary tool to program a DDC controller (JCI BACnet device). 
> Using the Python app I created, I connect to the device and I can read/write to variable to test what has been programmed. No need to connect any sensor as every IO can be simulated writing to them via Python. 

I'm wondering if in some way, it would be possible to use the models of this project to "simulate" temperature variation based on heating or cooling for example.

Actually, when testing a heating sequence I can, write to the room temperature and create a need for heating. but if I want to validate the discharge air temperature PID loop, I must manually change the discharge air temperature... Having access to some kind of model I could simulate a realistic reaction of discharge air temperature based on the output to a heater, or any other equipment.

Goal of my project is to provide a tool to DDC programmer so they can test their sequence in their office... not when connected to client's equipment. I think there is some link to this project.

Thanks

**Comment by mwetter** [comment]
@ChristianTremblay : Testing of control sequences is a key use case for this library. We have various models that can be used for HVAC and room simulations and who take as an input for example a control signal for a valve or damper, and output a measure temperature, pressure, flow rate etc. See also the example in http://www.tandfonline.com/doi/full/10.1080/19401493.2015.1062557 (which uses CFD for the room air, but we also have a computationally much faster mixed room air model).

The tutorial http://simulationresearch.lbl.gov/modelica/releases/latest/help/Buildings_Examples_Tutorial_Boiler.html#Buildings.Examples.Tutorial.Boiler.System6 
shows how to test a control sequence with a simple HVAC system in the loop. You can also package the HVAC system as an input/output block, compile it with JModelica (or Dymola) as a Functional Mockup Unit, and then set control signals as inputs and retrieve sensor values as output from Python using PyFMI.
