### ISSUE TITLE
CFD with FFD

### ISSUE THREAD

**Issue by yfuerst** [lbl-srg/modelica-buildings#656]
I recently stumbled across the CFD cosimulation in the ThermalZones package. I compiled the library according to the instruction in UsersGuide and tried to simulate the models MixedConvection and NaturalConvection. Sadly, the simulation won't work and I am confronted with the following log:

```
Log-file of program ./dymosim
(generated: Thu Feb 16 12:49:56 2017)

dymosim started
... "dsin.txt" loading (dymosim input file)
... loading "tab1" from "/home/yannick/Dokumente/git/modelica-buildings/Buildings/Resources/weatherdata/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.mos"
Start cosimulation
The following error was detected at time: 0
Error: Could not find dll handle.

The stack of functions is:
Buildings.ThermalZones.Detailed.BaseClasses.cfdStartCosimulation
Buildings.ThermalZones.Detailed.BaseClasses.CFDExchange.sendParameters
Buildings.ThermalZones.Detailed.BaseClasses.CFDExchange.sendParameters("/home/yannick/Dokumente/git/modelica-buildings/Buildings/Resources/Data/Rooms/FFD/Tutorial/MixedConvection.ffd", {"East Wall", "West Wall", "North Wall", "South Wall", "Ceiling", "Floor"}, {0.9, 0.9, 1.0, 1.0, 1.0, 1.0}, {1.5707963267948966, 1.5707963267948966, 1.5707963267948966, 1.5707963267948966, 0.0, 3.141592653589793}...
Error: Failed to start model.
```
I am using a 64 Bit distribution of Linux. Any help is appreciated.

**Comment by mwetter** [comment]
@yfuerst : Which version of the Buildings library do you use? The official release or a development version? If it is a development version, it may be broken as the FFD implementation is currently refactored in https://github.com/lbl-srg/modelica-buildings/issues/612

**Comment by yfuerst** [comment]
I am using the latest version from the master branch, but a switch to the official release 3.0.0 didn't change anything. The error remains the same. I also tried to simulate the examples on a Windows machine and I am getting the same error `Could not find dll handle.`. Maybe I am doing something completely wrong?

**Comment by mwetter** [comment]
Strange that it works on none of these operating systems. The master works for me on Ubuntu 64 bit, and we have Windows users as well. Is there an issue with the file permissions or the checkout?

@tianwei1989 Do you know what could be the problem?

**Comment by tianwei1989** [comment]
@mwetter I simulated the case using development version (master) on Windows 7 using Dymola 2016.  The simulation is a success. @yfuerst what is the work path for your dymila? Is it referred to the Buildings folder? You may want to check it by clicking "File->Change Directory". If it is not, you may need to change to "Buildings" folder and try it.

**Comment by tianwei1989** [comment]
@mwetter @yfuerst a followup of last message: I just simulated the case in Ubuntu 64 bit using Dymola 2016. The simulation is a success, too. Please let me know if my suggestion works for you. CC: @zuowangda

**Comment by yfuerst** [comment]
"Change directory" did the job. I just simulated in Arch Linux with the development version and Dymola 2017. I don't have access to a windows machine at home, but I suspect it to work as well. Thank you very much for the support. I guess the issue is closed.

**Comment by tianwei1989** [comment]
@yfuerst Glad it helps. Let us know if you have any question regarding this issue. 
CC: @mwetter @zuowangda
