### ISSUE TITLE
nominal mass flow rate needs to be corrected

### ISSUE THREAD

**Issue by zuowangda** [lbl-srg/modelica-buildings#673]
the nominal mass flow rate in `Buildings.Examples.Tutorial.Boiler.System1` @is calculated as

`parameter Modelica.SIunits.MassFlowRate mA_flow_nominal = V*6/3600`

However, it does not include the air density 1.2 kg/m3. Thus, the correct way should be 

`parameter Modelica.SIunits.MassFlowRate mA_flow_nominal = V*1.2*6/3600`

**Comment by mwetter** [comment]
@zuowangda : Thanks for reporting. I will correct the model.
