### ISSUE TITLE
Sequences ask for these basic blocks

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#700]
Add the following blocks and tests, since a need for them got identified while modeling the economizer sequence:
- CDL.Conversions.BooleanToReal
- Or3
- Add3

**Comment by JayHuLBL** [comment]
@milicag I can add them to my branch.

**Comment by milicag** [comment]
@JayHuLBL closing this issue since you've handled it on ```issue610_cdl_extra_basic_blocks``` branch, issue ```Issue610 cdl extra basic blocks```. I'll add any further comments directly to that branch.

**Comment by milicag** [comment]
I've encountered a need for the following additional basic blocks:

- real to boolean converter
- logical: equivalence (or an equation block with boolean inputs)

**Comment by mwetter** [comment]
@milicag : Real to boolean can be done with the `Logical.Greater` or `GreaterThreshold` block.

What is "logical equivalence"? Isn't this `Logical.And`?

**Comment by milicag** [comment]
It would be convenient to have a ```real to boolean```, since we also have ```boolean to real``` in the ```Converters```.

Logical equivalence is ```not(xor)```. It returns the same output as ```=```. ```And``` is only true if all inputs are true. Equivalence is true if all inputs are false as well.

**Comment by mwetter** [comment]
@milicag OK, we could integrate into CDL `Modelica.Blocks.Math.RealToBoolean`

**Comment by milicag** [comment]
I added this to ```issue763_delay_blocks``` for convenience, since it's a single block. This closes the thread for now.
