### ISSUE TITLE
add tolerance to damper example

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/modelica-buildings#703]
Must add tolerance of 1e-6 to damper example experiment annotation, as found in IBPSA library.

**Comment by dhblum** [comment]
@mwetter I tried to push a new branch to fix this and got an error that I don't have permission.  Can you check if I have push access to this repository?

**Comment by mwetter** [comment]
@dhblum You were not on the access list, please try again.

**Comment by dhblum** [comment]
Per discussion with Michael and Thierry, this should not be done manually.
