### ISSUE TITLE
Wrong unit in CDL.Sources.DutyCycle

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#714]
In `CDL.Sources.DutyCycle`, the input
```modelica
  Interfaces.RealInput u "Percentage of the cycle time the output should be on: [0, 100]"
```
should be
```modelica
  Interfaces.RealInput u(
    final min=0,
    final max=1,
    final unit="1")
    "Fraction of the cycle time the output should be on"
```
as we don't want to use percentage to avoid confusion, but rather normalize all signals to be between 0 and 1.

**Comment by JayHuLBL** [comment]
- [x] changed the wrong unit in `CDL.Sources.DutyCycle`
- [x] updated other validation blocks that using `DutyCycle` as source input
- [x] re-run the unit test, however, it didn't generate new result.
