### ISSUE TITLE
Error in the DayType block

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#729]
Error gets thown if the user selects a ```days``` parameter from a fall down menu when running simulation for ```Buildings.Experimental.OpenBuildingControl.CDL.Discrete.DayType``` block (same goes for ```DayType``` block in the modelica library). 

```
The left hand side of the following equation is a vector
and the right hand side is a scalar, i.e. it has non-compatible parts;
dayTyp.days = Buildings.Experimental.OpenBuildingControl.CDL.Types.Day. Holiday;
```

It would be good bundle this issue with the remaining table/scheduling issues, since I haven't added validation blocks in ```Buildings.Experimental.OpenBuildingControl.CDL.SetPoints``` after I've copied the blocks over from the buildings library.

**Comment by milicag** [comment]
Jianjun and I just met to look at this issue. The issue with the ```DayType``` block is basically a Dymola GUI issue, where one should not be permitted to select from a drop down menu in the parameter field directly if the parameter is defined as a vector, but should only use drop downs in the table view. Selecting directly from the drop down can only yield a scalar value and should be used if the parameter is expected to be a scalar.

```Buildings.Experimental.OpenBuildingControl.CDL.SetPoints``` need validation blocks, but are working fine.

**Comment by mwetter** [comment]
@milicag Can you please close this unless it needs work (which it doesn't sound).
