### ISSUE TITLE
Modularize Python 2.7 I/O?

### ISSUE THREAD

**Issue by tbeu** [lbl-srg/modelica-buildings#748]
The Python 2.7 I/O in package Utilities is nice and also of use for other Modelica projects. Can you imagine to modularize it and release it as stand-alone package instead of part of the Buildings library?

**Comment by mwetter** [comment]
@tbeu : If there are other users, in particular outside of Buildings users, that can benefit, I'd be happy to see how we can best release this as a stand-alone package or contribute it to another library. In the bigger picture, it would be nice to have a Modelica package to interface to other languages, web services etc, of which the Python 2.7 package would just be a single package. This also shows the need again for a package manager such as impact, which would go a long way in avoiding having to put too much into a domain-specific library just for ease of use/installation.

**Comment by tbeu** [comment]
Do you think you could create a new repository https://github.com/lbl-srg/Modelica_Python27IO where we can move the Python 2.7 I/O from package Utilities to a new generic and domain-independent library?

**Comment by mwetter** [comment]
@tbeu As we are discussing changing the license to MIT or BSD, I prefer to do this after the license is changed to avoid going through this process multiple times.

**Comment by tbeu** [comment]
Will it move to BSD-3-Clause then?

**Comment by mwetter** [comment]
@tbeu We plan to use 3-clause BSD when the MSL is changed

**Comment by tbeu** [comment]
> We plan to use 3-clause BSD when the MSL is changed

Which you can follow here: modelica/Modelica#2320.

**Comment by tbeu** [comment]
> We plan to use 3-clause BSD when the MSL is changed

Can you quickly summarize what the main differences between the previously considered 3-clause BSD and the current Modelica Buildings License are?

**Comment by mwetter** [comment]
@tbeu : I am not sure what you mean by "previously considered 3-clause BSD", but the Buildings library now has a 3 clause BSD license with a paragraph added at the end. This paragraph allows us to accept and distribute bug fixes, upgrades etc should users decide the share them with us, without having to sign additional paperwork or licenses. See http://simulationresearch.lbl.gov/modelica/releases/v5.1.0/help/Buildings_UsersGuide.html#Buildings.UsersGuide.License

**Comment by tbeu** [comment]
I just was wondering why you would mix software license with contributor's license agreeement, because this ammendment turns an official OSI license into a custom, non-catalog BSD-style license.

**Comment by mwetter** [comment]
@tbeu That is the suggested approach from our tech transfer department to make clear that we can accept contributions.

**Comment by tbeu** [comment]
> @tbeu As we are discussing changing the license to MIT or BSD, I prefer to do this after the license is changed to avoid going through this process multiple times.

MSL v3.2.3 is now released under the 3 Clause BSD License.

**Comment by mwetter** [comment]
@tbeu Buildings 5.1.0 already uses BSD.

**Comment by tbeu** [comment]
Hm. I was waiting to have a new MSL unter BSD license releases all the time. 😕 

Back to the main proposal then:

> Do you think you could create a new repository https://github.com/lbl-srg/Modelica_Python27IO where we can move the Python 2.7 I/O from package Utilities to a new generic and domain-independent library?

Thanks.

**Comment by tbeu** [comment]
OK, no more pressure to modularize Python I/O.
