### ISSUE TITLE
Documentation mistake for HexElement

### ISSUE THREAD

**Issue by damienpicard** [lbl-srg/modelica-buildings#749]
I believe that there is a mistake in the documentation of `Buildings.Fluid.HeatExchangers.BaseClasses.HexElementLatent` and of 
`Buildings.Fluid.HeatExchangers.BaseClasses.HexElementSensible`. The latter mentions in its head comment
_Element of a heat exchanger with humidity condensation of fluid 2_  while no condensation is included while the former has as head comment _Element of a heat exchanger_.

**Comment by mwetter** [comment]
Good catch, I will fix it.
