### ISSUE TITLE
optionally avoid events in LimPID controller

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#75]
Add option to
{{{
Buildings.Controls.Continuous.LimPID
}}}
which avoids the state events that are introduced by the output limiter. This can decrease computing time significantly (about a factor of two for the hub building).

**Comment by Mathadon** [comment]
This option already exists, no? In the ```Advanced``` tab, just set ```strict=true```. I would enable this by default since the output of a min/max function is continuous.

**Comment by mwetter** [comment]
You are right,  I will therefore close this ticket.
