### ISSUE TITLE
Triggered sampler needs no samplePeriod

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#762]
Unlike ```Sampler```, the ```TriggeredSampler``` doesn't need ```samplePeriod``` parameter, since the trigger input defines the sampling period. This is how these blocks look in the Modelica library, but as they got copied over to CDL, the ```samplePeriod``` parameter has sneaked in the ```Buildings.Experimental.OpenBuildingControl.CDL.Discrete.TriggeredSampler``` block.

@mwetter @JayHuLBL Should I fix this?

**Comment by mwetter** [comment]
Yes, please fix this.

**Comment by mwetter** [comment]
This has been merged
