### ISSUE TITLE
heat pump model data record generation 

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/modelica-buildings#767]
@MassimoCimmino I tried to generate some performance records for Viessmann BW301 series heat pumps. I.e. I used following input in `somePerformanceData.txt`:

```
268.15	308.15	1.16	0.71	18.79	14.58	4.52
273.15	308.15	1.16	0.71	21.20	17.0	4.48
275.15	308.15	1.16	0.71	22.58	18.34	4.53
283.15	308.15	1.16	0.71	28.10	23.7	4.73
288.15	308.15	1.16	0.71	32.19	28.0	4.57
268.15	318.15	1.16	0.71	17.73	12.57	5.55
273.15	318.15	1.16	0.71	20.39	15.2	5.58
275.15	318.15	1.16	0.71	21.64	16.45	5.58
283.15	318.15	1.16	0.71	26.64	21.44	5.58
288.15	318.15	1.16	0.71	30.19	25.03	5.55
273.15	328.15	1.16	0.71	19.28	12.94	6.82
275.15	328.15	1.16	0.71	20.41	14.07	6.82
283.15	328.15	1.16	0.71	24.92	18.59	6.8
288.15	328.15	1.16	0.71	28.32	21.97	6.83
275.15	333.15	1.16	0.71	19.59	12.59	7.52
283.15	333.15	1.16	0.71	24.10	17.16	7.5
288.15	333.15	1.16	0.71	27.36	20.37	7.52

```

As you can see, I don't have data for different flow rates.

The python script gives output like:

```
Invalid : EWT_Source = 275.15 EWT_Load =  333.15 flowSource =  1.16 flowLoad =  0.71
Invalid : EWT_Source = 283.15 EWT_Load =  333.15 flowSource =  1.16 flowLoad =  0.71
Invalid : EWT_Source = 288.15 EWT_Load =  333.15 flowSource =  1.16 flowLoad =  0.71
```
multiple times.

Moreover at the end of the script I get:

```
timeWarning: divide by zero encountered in double_scalars
  SE = ((refData.Power[i]-data.Power[i])/refData.Power[i])**2 \
/media/psf/Home/Documents/Software/Buildings-git/Buildings/Resources/src/fluid/heatpumps/calibration/PythonModel/calibrate.py:90: RuntimeWarning: divide by zero encountered in double_scalars
  + ((refData.Capacity[i]-data.Capacity[i])/refData.Capacity[i])**2
```

Dymola returns following output
```
Sum of square errors (dymola) : 0.160769124211
```
This is hard to interpret: is this a small or a large error? What are the units of this?
Edit: I did not specify `tableFileName` correctly so that probably causes the large error relative to the example file of 0.000677114980592. However, I did not get an error message either?

Also, the output file I get is called ```Viessmann_BW301.A21_84kW_4_0COP_R410A.mo```, which is indicative of a 84kW heat pump whereas in fact it is a 21 kW heat pump. Multiplying the COP of 4 with 21 yields 84, so maybe I did something wrong that's related to that.

If you can provide some more insights on this I can adjust the scripts accordingly and make a pull request!

**Comment by Mathadon** [comment]
I had another look at EN14511-2 that defines the testing conditions of the heat pumps. I should have used a temperature difference of 5K for condenser and 3K for evaporator. From that I should have computed flow relates. Moreover the manufacturer data species the condenser _outlet_ temperature.

Taking that into account I should have used following performance data:

```
268.15	303.15	1.162679426	0.899043062	18.79	14.58	4.52
273.15	303.15	1.355661882	1.014354067	21.2	17	4.48
275.15	303.15	1.462519936	1.080382775	22.58	18.34	4.53
283.15	303.15	1.889952153	1.344497608	28.1	23.7	4.73
288.15	303.15	2.232854864	1.540191388	32.19	28	4.57
268.15	313.15	1.002392344	0.848325359	17.73	12.57	5.55
273.15	313.15	1.212121212	0.975598086	20.39	15.2	5.58
275.15	313.15	1.311802233	1.035406699	21.64	16.45	5.58
283.15	313.15	1.709728868	1.274641148	26.64	21.44	5.58
288.15	313.15	1.996012759	1.444497608	30.19	25.03	5.55
273.15	323.15	1.031897927	0.922488038	19.28	12.94	6.82
275.15	323.15	1.122009569	0.976555024	20.41	14.07	6.82
283.15	323.15	1.48245614	1.192344498	24.92	18.59	6.8
288.15	323.15	1.75199362	1.355023923	28.32	21.97	6.83
275.15	328.15	1.003987241	0.937320574	19.59	12.59	7.52
283.15	328.15	1.368421053	1.153110048	24.1	17.16	7.5
288.15	328.15	1.624401914	1.309090909	27.36	20.37	7.52
```

Now I get no invalid points and a (suspiciously ?) low `Sum of square errors : 1.63131474841e-08`.

The filename is still unexpected though -> 84 kW. Any thoughts on this?

**Comment by Mathadon** [comment]
I did misinterpret the script.. I thought the script asked for Q_nominal but instead it asked for P_nominal.

**Comment by MassimoCimmino** [comment]
@Mathadon I was just writing my reply. It looks like you figured it out.

Q_nominal and P_nominal are used to calculate the first guesses for the heat pump model. If overestimated, this leads to invalid points (the model fails to converge to a working state).

Since you have very few data points, it could be worthwhile to use all of the data for the calibration:
At line 57: `calData = data`
