### ISSUE TITLE
Error in NaturalConvectionWithControl Example in OpenModelica

### ISSUE THREAD

**Issue by billstav** [lbl-srg/modelica-buildings#768]
Hello everyone !

I am trying to run the NaturalConvectionWithControl Example in OpenModelica (v1.11.0), however, i get these errors:
[1] 21:44:35 Translation Error
[Modelica.Blocks.Tables: 335:5-341:46]: Variable weaDat.absFilNam not found in scope Modelica.Blocks.Tables.CombiTable1Ds$weaDat$datRea.

[2] 21:44:35 Symbolic Warning
[Modelica.Blocks.Tables: 390:7-391:66]: Unused input variable tableAvailable in function .Modelica.Blocks.Tables.CombiTable1Ds$weaDat$datRea.getDerTableValue.

[3] 21:44:35 Symbolic Warning
[Modelica.Blocks.Tables: 363:7-364:66]: Unused input variable tableAvailable in function .Modelica.Blocks.Tables.CombiTable1Ds$weaDat$datRea.getTableValue.

[4] 21:44:35 Translation Error
[Modelica.Blocks.Tables: 335:5-341:46]: Variable weaDat.absFilNam not found in scope Modelica.Blocks.Tables.CombiTable1Ds$weaDat$datRea1.

[5] 21:44:35 Symbolic Warning
[Modelica.Blocks.Tables: 390:7-391:66]: Unused input variable tableAvailable in function .Modelica.Blocks.Tables.CombiTable1Ds$weaDat$datRea1.getDerTableValue.

[6] 21:44:35 Symbolic Warning
[Modelica.Blocks.Tables: 363:7-364:66]: Unused input variable tableAvailable in function .Modelica.Blocks.Tables.CombiTable1Ds$weaDat$datRea1.getTableValue.

[7] 21:44:35 Translation Error
[Buildings.ThermalZones.Detailed.BaseClasses.RoomHeatMassBalance: 248:11-248:38]: Type mismatch in binding ove = Buildings.ThermalZones.Detailed.BaseClasses.Overhang$roo$datConExtWin$ove(0, 0, 0, 0, false), expected subtype of record Buildings.ThermalZones.Detailed.BaseClasses.Overhang
  Real(min = 0.0, quantity = "Length", unit = "m") wL;
  Real(min = 0.0, quantity = "Length", unit = "m") wR;
  Real(min = 0.0, quantity = "Length", unit = "m") dep;
  Real(min = 0.0, quantity = "Length", unit = "m") gap;
  Boolean haveOverhang;
end Buildings.ThermalZones.Detailed.BaseClasses.Overhang;, got type record .Buildings.ThermalZones.Detailed.BaseClasses.Overhang$roo$datConExtWin$ove.

[8] 21:44:35 Translation Error
Error occurred while flattening model Buildings.ThermalZones.Detailed.Examples.FFD.NaturalConvectionWithControl

Same problem with JModelica. any ideas?
Generally, I have observed that most of the models do not get compiled in the OpenModelica environment... (almost all if the times I get the Translation Error: Error occurred while flattening model)
:(
Do you think that purchasing a Dymola license is the best solution?

Any help is much appreciated as I am really struggling with my Ph.D. right now.

Thank you in advance for your time!

Best regards.

**Comment by mwetter** [comment]
I suggest you get a Dymola license which currently has the best support and also has a graphical editor.

**Comment by billstav** [comment]
Thank you very much for your prompt response!
