### ISSUE TITLE
Infeasible solution in ScrollWaterToWater

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/modelica-buildings#769]
I'm using the `ScrollWaterToWater` model. When the condensor reaches relatively high temperatures (45 C) non-physical solutions seem to exist for the algebraic loop that computes the heat flow rate of the heat pumps since I get following error:

```
Solving nonlinear system of equations number = 7
Tag: simulation.nonlinear[5]
        iteratively at Time = 1.42658E+09
  Solution: Infinity-norm of residue = 4.36557E-10
            Acc. number of residue     calc.: 160742
            Acc. number of symbolic Jacobian calc.: 54521
heatPumps.heaPum29b.eva.port_ref.T = 278.924
heatPumps.heaPum29b.con.port_ref.T = 8931.68
Residual:
{ -3.12866E-10, -1.23691E-10 }
heatPumps.heaPum29b.con.port_ref.T > 173.15 and heatPumps.heaPum29b.con.port_ref.T < 345.25
The following error was detected at time: 1426579274
Condensing temperature must be above the minimum refrigerant temperature
    and below the critical temperature.

```

I.e. the residual equations are satisfied but the resulting temperature (8900K) is non-physical. 
The evaporator temperature solution is reasonable since the evaporator state temperature is 279.867 K. The supply temperature is still within a reasonable range so this looks like a bug?

edit: problem occurs when switching heat pump on, both when using an integer input or a real input control signal.

edit2: This solution may be caused by polynomial extrapolation of `Buildings.Media.Refrigerants.R410A.pressureSatVap_T`? I'm wondering though whether the 'real' solution does in fact exist.

**Comment by Mathadon** [comment]
The problem seems to be that there is no mass flow rate to 'cool' the heat pump, due to which it simple gets too hot. I.e. there's a control error such that the pump is off while the heat pump is on.

Similar to
```
  pressure_error = (pre(pressure_error) and PR <= 1.01) or (not pre(pressure_error) and PR <= 1.0);
```
it would make sense to have
```
  pressure_error2 = (pre(pressure_error2) and PR >= 3.5) or (not pre(pressure_error2) and PR >= 3.55);
```
although we could argue about what the upper bound of `PR` should be of course. That however doesn't have the desired effect.

**Comment by Mathadon** [comment]
Some preliminary validation results that you may be interested in:

![screen shot 2017-05-19 at 15 53 44](https://cloud.githubusercontent.com/assets/5970879/26269712/633d63f8-3cab-11e7-9d17-a7f42cd451b6.png)

this figure shows electrical power and thermal power results for 4 parallel on/off heat pumps. Their control signals are at the bottom.

**Comment by Mathadon** [comment]
I'm also getting error like: 

```
Model error - power: (Buildings.Utilities.Math.Functions.smoothMax(1-T/TCri, 0.0001, 0.005)) ^ (0.3333333333333333) = (-2.50166e-16) ^ (0.333333)

The stack of functions is:
Buildings.Media.Refrigerants.R410A.enthalpySatLiq_T
Buildings.Media.Refrigerants.R410A.enthalpySatLiq_T(basement.heatPumps.heaPum29a.con.port_ref.T)
Non-linear solver will attempt to handle this problem.
```

**Comment by Mathadon** [comment]
The problem seems to be related to how the condenser is modelled. Its thermal conductance equals `G=eps*cp_default*abs(port_a.m_flow)/(1 - eps)` so when `m_flow=0` then `G=0`. This apparently leads to solutions for the algebraic loop where high temperatures are encountered. 

I changed this to
`G=max(UA, eps*cp_default*abs(port_a.m_flow)/(1 - eps))`, which solved the problem when also using the `pressure_error2` variable.  Without `pressure_error2 the temperature keeps climbing until the triple point and then the model fails. 

An additional problem that occurs is that `pressure_error2` (and `pressure_error`) are computed from a mixed system of equations. Therefore repeated switchings between iterations may occur, even when using a hysteresis-type definition. Hysteresis has no effect in this case since all equations are algebraic and therefore there is no time delay. For completeness sake, the errors that I got are of this type: 

```
  Variable heatPumps.heaPum29b.com.pressure_error2 = 1 at time 1.42658e+09
Expression heatPumps.heaPum29b.com.PR >= 3.51 became false ( (heatPumps.heaPum29b.com.PR)-(3.51) = -0.13245 )
  Variable heatPumps.heaPum29b.com.pressure_error2 = 0 at time 1.42658e+09
Shorter attempt for mixed equation system 0.00376772502590911
Expression heatPumps.heaPum29b.com.PR >= 3.51 became true ( (heatPumps.heaPum29b.com.PR)-(3.51) = 0.000367602 )
  Variable heatPumps.heaPum29b.com.pressure_error2 = 1 at time 1.42658e+09
Shorter attempt for mixed equation system 0.2664121500702994
Expression heatPumps.heaPum29b.com.PR >= 3.51 became false ( (heatPumps.heaPum29b.com.PR)-(3.51) = -0.13245 )
  Variable heatPumps.heaPum29b.com.pressure_error2 = 0 at time 1.42658e+09
Shorter attempt for mixed equation system 0.001003778167719708
Expression heatPumps.heaPum29b.com.PR >= 3.51 became true ( (heatPumps.heaPum29b.com.PR)-(3.51) = 0.000367602 )
  Variable heatPumps.heaPum29b.com.pressure_error2 = 1 at time 1.42658e+09
Shorter attempt for mixed equation system 0.2658728697392277
Expression heatPumps.heaPum29b.com.PR >= 3.51 became false ( (heatPumps.heaPum29b.com.PR)-(3.51) = -0.13245 )
  Variable heatPumps.heaPum29b.com.pressure_error2 = 0 at time 1.42658e+09
Shorter attempt for mixed equation system 0.001003775396111921
```

It would be better to evaluate `pressure_error` and `pressure_error2` based on the state variables in the compressor and evaporator instead of based on the algebraic refrigerant temperatures. Or it could even make sense to add a state variable for the refrigerant temperatures. This way the (costly) algebraic loop can also be avoided.

Feedback welcome!

**Comment by mwetter** [comment]
@Mathadon : The change in `G`, but with regularization, should be fine, as is computing the pressure error based on the states rather than the refrigerant temperatures.

**Comment by Mathadon** [comment]
I'm not sure how to implement this best. I see three options:
 - 1 Add temperature sensors inputs to the compressor for the evaporator and condenser temperature and compute the pressure ratio in the compressor. This would require two new inputs for the compressor.
 - 2 Create a 'pressure protection' block outside of the compressor that uses the temperature measurements and the refrigerant to compute the corresponding pressures and use these to compute the pressure ratio. I would move the existing `pressure_error` computation into this block. This controller block overrides the compressor control signal if any of the checks fails.
- 3 The same as 2) but without the refrigerant. I.e. absolute temperatures are used to determine whether T>Tmax or T<Tmin. This is less physical but does not require a refrigerant medium to be declared and used.

I'm not sure how these checks happen in practice, but I guess that 3) is the most physically correct choice?

**Comment by Mathadon** [comment]
@mwetter the heat pump example models such as `Buildings.Fluid.HeatPumps.Validation.ScrollWaterToWater_Dynamic` have an inlet temperature difference of only 2K, which causes the temperature error to trigger.  I assume this boundary condition can be changed.

**Comment by mwetter** [comment]
This is on the master (https://github.com/lbl-srg/modelica-buildings/pull/780)
