### ISSUE TITLE
avoid dip in energy at shallow incidence angle for solar collector

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#785]
The solar collector model has a dip at shallow incidence angles due to the incidence angle modifier, see figure below.

![image](https://cloud.githubusercontent.com/assets/1329080/26656906/ded94978-4615-11e7-883c-2f668ca4c47d.png)

**Comment by mwetter** [comment]
The above commit should solve this issue. What remains before merging it is to verify that the validation above is now correct.

**Comment by Mathadon** [comment]
![screen shot 2017-05-31 at 16 59 03](https://cloud.githubusercontent.com/assets/5970879/26659001/7aafbc40-4622-11e7-81ef-218bbbaabaaa.png)
Results are clearly better :)

**Comment by mwetter** [comment]
@Mathadon : Every morning there is a large spike, presumably when there is no flow rate. Is this because the pump switches on too late in your model?
Evening hours look good now.

**Comment by Mathadon** [comment]
The pump only turns on when a certain temperature threshold is obtained. This control loop is not modelled and therefore the pump turns on too early/late. This causes the water to heat up more/less than in the measurements.
