### ISSUE TITLE
revise CDL.Logical.{OnHold, OnOffHold}

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#789]
Revise `CDL.Logical.{OnHold, OnOffHold}` and check if the implementation can be simplified.

Also, these blocks have quite different behavior and hence we may want to rename one of them to better distinguish their different functionalities.

**Comment by milicag** [comment]
@mwetter I've created [a new branch](https://github.com/lbl-srg/modelica-buildings/tree/issue789_improve_hold_blocks) for this issue. The test that is currently in place for the ```OnHold``` tests both the behavior if the input signal is ```on``` and ```off``` as the user defined time period expires. In the following plot the first instance when the timed period expires the input signal is on, so the timer gets started again. After the second period expires, the input signal is off and the output stays off until the next occurrence of the rising edge in the input signal. 

<img width="579" alt="screen shot 2017-06-13 at 9 36 32 pm" src="https://user-images.githubusercontent.com/5322943/27115578-7db4074e-5080-11e7-9dcc-60a1c364323e.png">

**Comment by mwetter** [comment]
@milicag : Yes, this is the purpose of the additional test. I will work on it today and make a pull request when I am done. It is important that we are clear what the expected behavior is so that others can implement the same behavior and we won't see any differences during cross comparison among implementations.

**Comment by mwetter** [comment]
@milicag Can you please delete `issue789_improve_hold_blocks` (assuming you did not do any work yet) as I already created the branch `issue789_OnHold` with some commits.

**Comment by milicag** [comment]
@mwetter Yes, it's deleted, sorry about that.

**Comment by mwetter** [comment]
- [ ] Move `OnHold` out of `Composite` package
