### ISSUE TITLE
ThreeWay valves' documentation and code need to be corrected

### ISSUE THREAD

**Issue by YangyangFu** [lbl-srg/modelica-buildings#795]
@mwetter I found several errors in the existing Valve package:

1. In the documentation of `Buildings.Fluid.Actuators.Valves.ThreeWayEqualPercentageLinear`, the linear characteristic is used between `port_1` and `port_3`, rather than `port_1` and `port_2`.
2. In the `Buildings.Fluid.Actuators.BaseClasses.PartialThreeWayValve`, the top-level parameter `CvData` is not propagated to the bottom model `res1` and `res3`. Maybe you can delete  `CvData` in the top-level model if you want to use fixed `CvTypes `.

**Comment by mwetter** [comment]
This has been closes through https://github.com/ibpsa/modelica-ibpsa/issues/800
