### ISSUE TITLE
Unit test: `HysteresisWithDelay`

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#818]
- [x] Conduct unit test on model `Buildings.Air.Systems.SingleZone.VAV.BaseClasses.HysteresisWithDelay`

**Comment by JayHuLBL** [comment]
- [x] Replaced the `BaseClasses.HysteresisWithDelay` with `BaseClasses.HysteresisWithHold`: the `TrueFalseHold` model used in OBC was modified with real input and hysteresis.

**Comment by mwetter** [comment]
@JayHuLBL : I believe this can be closed? Please go ahead and close the ticket if all code is on the `issue609_cdl` branch.

**Comment by JayHuLBL** [comment]
All code is on branch `issue609_cdl`. This closes the issue.
