### ISSUE TITLE
Minimum mass fraction violation in WetCoilCounterFlow

### ISSUE THREAD

**Issue by rubenbaetens** [lbl-srg/modelica-buildings#821]
I'm using `Buildings.Fluid.HeatExchangers.WetCoilCounterFlow.mo` with `Media.Air` to model a air-to-air heat exchanger including condensation of saturated air to include the latent heat exchange. However, during the simulation, `port_b2.Xi_outflow[1]` of the `WetCoilCounterFlow` drops below the the minimum mass fraction X[1] of -1e-005 of substance water.

I noticed the latent heat exchange was overestimated in the previous version of the model, but now it seems also the amount of condensation is overestimated (?).

**Comment by mwetter** [comment]
@rubenbaetens 
Do you have a small test case that reproduces the problem? It should suffice to have a case with a coil with constant mass flow rates, temperature and humidify to reproduce what you see. Then we can see where the issue arises.

**Comment by rubenbaetens** [comment]
It seems it's a problem of solver tolerance, if i make it more strict the error disappears. I'll check if i can deduce it to a MWE.

**Comment by mwetter** [comment]
@rubenbaetens : I will close the issue, but can reopen if you have a small test case.
