### ISSUE TITLE
Add block for sunrise and sunset to CDL

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#829]
Add a block that outputs the next sunrise and sunset time. The block should be updated for the sunset at each sunset, and for the sunrise at each sunrise. This will give the building automation system sufficient time to schedule controls in the corner-case of the sun only setting for a few seconds (e.g., at or above the polar circle).

The outputs should be the next sunrise and sunset in units of the model time.

See the `BoundaryConditions` package for a block that could be used.

**Comment by mwetter** [comment]
@kuzha : Please address the following:
- [ ] Remove the input nDay, and instead use the built-in variable `time`.
- [ ] Change the info section in the model and the test to remove the leading spaces.
- [ ] The first values are wrong: The output should not be zero as this would lead to a wrong controller. Think about a lighting control that would switch off if the `time >= sunSet` and on if `time >= sunRise`. For example, the behavior would not be correct (or even defined) for the first few hours of San Francisco.
- [ ] Add an entry under the ReleaseNotes to inform users about the new model.

**Comment by milicag** [comment]
Would an optional time offset parameter be useful for lighting control? Since it gets darker before sunset and stays darker after sunrise example.

**Comment by mwetter** [comment]
@milicag : Let's leave it for now to see if there is a need. Some commercial lighting control simply use the sunrise/sunset time and don't give this option either.

**Comment by mwetter** [comment]
@kuzha : Please also do the following:
- [ ] Add an example that simulates from t=-0.5 day to t=+0.5 day.
- [ ] Add an example that simulates from t=+0.5 day to t=+1.5 day.
These will validate that the model behaves correctly if the simulation starts in the middle of a day.
