### ISSUE TITLE
Multizone VAV AHU supply air temperature setpoint

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#838]
Create an atomic sequence that calculates the outdoor air temperature setpoint as a function of the outdoor air temperature, based on ASHRAE G36.

**Comment by milicag** [comment]
@JayHuLBL I see I've assigned this one to myself. Would you like to finish it up, since you've started working on it, or would it be more convenient that I take it over? Either is fine by me.

**Comment by JayHuLBL** [comment]
@milicag I have been taken care of it. I will check into it today and tomorrow.

**Comment by mwetter** [comment]
This is now on the master
