### ISSUE TITLE
Freeze Protection

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#864]
Implement freeze protection.

**Comment by mwetter** [comment]
@milicag : what is the status on this?

**Comment by milicag** [comment]
@mwetter After I last discussion we've decided to not implement the exact G36 version of the freeze protection, since it does not reliably protect the coil from freezing in cold climates (it looks at TSup and not TMix). You've added your own version of freeze protection to the case study. 

If we were to go forward on this, I would suggest an approach similar to the one in the guideline (a separate block able to generate freeze protection level signal which can be passed to any dependent sequence), but assuming a mixed air temperature sensor is present. Essentially, we could keep the G36 response to different freeze protection levels, but use TMix instead of TSup. That implementation can be ready in 2 days.

**Comment by mwetter** [comment]
Let's wait with such an implementation for after the review. We may have more pressing items to work on. I will close it for now.

**Comment by milicag** [comment]
@mwetter Let me know how I can help.
