### ISSUE TITLE
LimPID: add reverse acting and fix parameter inconsistency

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#871]
Reverse acting feature:

In CDL there is a need to reverse the controller signal (e.g. cooling control signal that maintains ```TRoo``` at ```TRooCooSet```, see #839). This is in line with the feedback we got on CDL from Larry, ALC:

```
LimPID – There should be an added feature to make the block either direct acting or reverse acting for the output.
```

The model implemented on that branch, ```HeatingCoolingControlLoops```, contains a group of blocks that add this feature. Should we incorporate it in ```LimPID```?

Parameter inconsistency fix:

If one is not using a differential controller, parameter ```Td``` should not appear in the list of parameters at instantiation, equivalent to parameter ```Nd```. Currently this is not the case.

**Comment by mwetter** [comment]
@milicag The PID controller from `Buildings.Controls.Continuous` has an option for reverse action that could be used here.

I don't understand what you mean by the parameter inconsistency as they are greyed out in `LimPID` if configured as a P or PI controller.

**Comment by milicag** [comment]
@mwetter While implementing the cooling and heating loop I realized that we might need to add a reverse acting feature to LimPID. Please let me know weather you prefer to keep it as is, in which case we have a bunch of blocks to reverse the signal, see ```HeatingCoolingControlLoops``` on  [```issue839_uhea_ucoo_loop```](https://github.com/lbl-srg/modelica-buildings/tree/issue839_uhea_ucoo_loop).

**Comment by milicag** [comment]
Right, deactivated on the GUI, but one still needs to keep the default value in the code itself, unlike Nd.

**Comment by milicag** [comment]
@mwetter: both of those issues resolved if we use the controller you suggested. Why don't we replace our controller with that one? What is the difference?

**Comment by milicag** [comment]
@mwetter It looks like the problem with the parameter is that CDL version of the controller does not assign a default value in the model itself (see line 14 in ```Buildings.Experimental.OpenBuildingControl.CDL.Continuous.LimPID```). That is an easy fix. Should I add the reverse action to our controller and go with that?

**Comment by milicag** [comment]
This issue is on hold till the meeting next week, where we'll determine whether a reverse action function is something we'd like to implement within the controller or as a separate composite block.

I'm adding the default for ```Td``` parameter with the cooling and heating loop model.
