### ISSUE TITLE
NaturalConvectionWithControl: Compilation failed in Dymola

### ISSUE THREAD

**Issue by billstav** [lbl-srg/modelica-buildings#942]
Hello, everyone.

I am new in the Dymola environment and i am trying to develop some first models for my Ph.D. using the "buildings" library. In particular, i am trying to simulate the NaturalConvectionWithControl FFD example but i get the error: "Process Setting up default experiment stopped without any error indication". Any thoughts or suggestions?

Thank you in advance for your time.

**Comment by mwetter** [comment]
@billstav : We need more information to reproduce as I have not seen this error before. What operating system, dymola version, library version (master or official release) are you using? Are you compiling 32 or 64 bit? Are other examples that don't use FFD working? Did you do any changes to the installation or the model?

**Comment by billstav** [comment]
@mwetter : OS: Windows 10, dymola version: Dymola 2018 , library version: 4.0.0 (released: 2017-03-29), compiler: Visual Studio 2015/Visual C++ 2015 Express Edition (14.0) 32 bit.
Actually, no model is getting compiled. I have also tried some simple modelica models (i.e. the bouncing ball, etc.) and i am getting the same error. No i didn't do any changes to neither the installation nor the model.

**Comment by thorade** [comment]
Please see this screenshot how to test your compiler setup:

![dymola2018_compilertest](https://user-images.githubusercontent.com/314571/30533457-b12766aa-9c59-11e7-820f-03ed3b31a0bc.png)

Does that pass successfully?

One possible reason for failure could be that Visual Studio is installed in modules and the C++ module is not installed by default. See this SO answer how to fix that:
https://stackoverflow.com/questions/45185108/microsoft-visual-c-compiler-for-dymola/45185508#45185508

**Comment by billstav** [comment]
@thorade: Thank you very much for your prompt response. I have found the issue. In the compiler settings i had to check the DDE server box.
