### ISSUE TITLE
Re-order package DataCenters.ChillerCooled.Equipment

### ISSUE THREAD

**Issue by YangyangFu** [lbl-srg/modelica-buildings#951]
@mwetter Two partial models (`AHUParameters` and  `PartialCoolingCoilHumidifyingHeating` in `Buildings.Applications.DataCenters.ChillerCooled.Equipment` ) that should be placed in` BaseClasses` are mistakenly placed at top level.

**Comment by mwetter** [comment]
@YangyangFu : Thanks for pointing this out. I will rename the models.
