### ISSUE TITLE
Revise and add to G36_PR1 documentation

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#974]
Add structure and contents summary for the ```Buildings.Controls.OBC.ASHRAE.G36_PR1``` package and revise  sub-package info sections.

**Comment by milicag** [comment]
@mwetter I've noticed that http://gpc36.savemyenergy.com/public-files/ and the committee members speak of G36_PPR1 rather than PR1, where PPR stands for Publication Public Review. Maybe something worth considering.

**Comment by milicag** [comment]
Some of the commits are pertaining to #975 and not this issue. The development on this issue starts after this comment.

**Comment by mwetter** [comment]
Closed at this is now on the master
